### ISSUE TITLE
RTMP sources

### ISSUE THREAD

**Issue by quenthal** [AlexxIT/go2rtc#1]
I tried to add Frigate RTMP -cameras, however this doesn't work:
18:13:49.125 INF [streams] create new stream url=rtmp://192.168.1.142/live/Etuovi
2022/08/21 21:14:19 http: panic serving 172.30.32.2:51410: not implemented
goroutine 193 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1825 +0xbf
panic({0x960640, 0xaf73a0})
	runtime/panic.go:844 +0x258
github.com/AlexxIT/go2rtc/pkg/rtmp.(*Client).Dial(0xc0000ca8c0)
	github.com/AlexxIT/go2rtc/pkg/rtmp/client.go:73 +0x5ec
github.com/AlexxIT/go2rtc/cmd/rtmp.handle({0xc00043a095, 0x20})
	github.com/AlexxIT/go2rtc/cmd/rtmp/rtmp.go:15 +0x65
github.com/AlexxIT/go2rtc/cmd/streams.GetProducer({0xc00043a095, 0x20})
	github.com/AlexxIT/go2rtc/cmd/streams/handlers.go:31 +0x87
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc000066480)
	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:31 +0x85
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc000556300, {0xafbfa0?, 0xc0000cb9d0})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:52 +0x305
github.com/AlexxIT/go2rtc/cmd/webrtc.offerHandler(0xc0000e1080, 0xc000642040)
	github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:109 +0x428
github.com/AlexxIT/go2rtc/cmd/api.apiWS({0xafcc30, 0xc000512000}, 0xc000144600)
	github.com/AlexxIT/go2rtc/cmd/api/api.go:129 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x7fe63d2cefb8?, {0xafcc30?, 0xc000512000?}, 0x40d2c5?)
	net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00043a0cc?, {0xafcc30, 0xc000512000}, 0xc000144600)
	net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000556150?}, {0xafcc30, 0xc000512000}, 0xc000144600)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001920a0, {0xafcfe8, 0xc00001e150})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db

I also tried directly to one of my cameras using RTSP, this was fine. This was tested by using HASS, generic camera, webrtc.

**Comment by quenthal** [comment]
0.1 alpha 5

**Comment by quenthal** [comment]
same error with alpha 6, as I tried with docker-version. RTSP works fine, but RTMP (Frigate) sources do not work.

**Comment by benedikt-bartscher** [comment]
same here with frigate and go2rtc latest versions

**Comment by AlexxIT** [comment]
This is RTMP with audio. Not problem, will be fixed in next version. But still without audio support for RTMP.

**Comment by AlexxIT** [comment]
Check `alpha.7`

**Comment by quenthal** [comment]
This now mostly works. I have 7 cameras behind Frigate, 6 Reolinks and one Dahua. Reolinks thru Frigate as RTMP-sources have been stable for hour or two now. With Dahua it has been more complex; it works now, but at the beginning gave error and didn't load at all.. Panic serving, runtime error: slice bounds out of range [:-1] etc. in addition to lines consisting of ERR [api.ws] readJSON error="websocket: close 1000 (normal)".

**Comment by AlexxIT** [comment]
You need to provide a full error log

**Comment by quenthal** [comment]
> You need to provide a full error log

Will do, as soon as it breaks again. It has now worked just fine :).
