### ISSUE TITLE
Q: More Details on 2 Way Audio

### ISSUE THREAD

**Issue by gniknalu** [AlexxIT/go2rtc#10]
> Default Home Assistant lovelace cards don't support 2-way audio. You can use 2-way audio from [Add-on Web UI](https://my.home-assistant.io/redirect/supervisor_addon/?addon=a889bffc_go2rtc&repository_url=https%3A%2F%2Fgithub.com%2FAlexxIT%2Fhassio-addons). But you need use HTTPS to access the microphone. This is a browser restriction and cannot be avoided.

Can you please provide a configuration example of using 2 way audio in Home Assistant? Also clarification on the statement about needing https to access the microphone please?

I have several cameras that are 2 way audio capable but have not been able to use this feature. Looking forward to experimenting!

Thank you!

**Comment by AlexxIT** [comment]
There is no advanced config. You just need to meet the conditions:

- camera support ONVIF Profile T
- you open stream from go2rtc web interface
- you use HTTPS to access to go2rtc web interface via Hass add-on or Ngrok or Nginx, etc

PS. You may run go2rtc on your PC and open web interface via http://localhost:1984/. This is also will work

**Comment by gniknalu** [comment]
I will give it a try following the comments you made. **THANK YOU**
