### ISSUE TITLE
Help & Wiki

### ISSUE THREAD

**Issue by Sheredeka** [AlexxIT/go2rtc#1004]
Greetings to all!

The Wiki lacks examples of adding threads as well as solving common problems - it would be nice to collect them.

I can't cope with the task - I ask for help:
There is a public stream with [camera](http://camera.lipetsk.ru/ms-25.camera.lipetsk.ru/live/6a3efc18-3651-43a4-b164-d07543151c3b/playlist.m3u8 ) - and I want to record it on my own DVR, which only understands ONVIF or RTSP. I would also like to reduce the number of frames per second to 10.

If I add this stream to the config
```
streams:
  cam: http://camera.lipetsk.ru/ms-25.camera.lipetsk.ru/live/6a3efc18-3651-43a4-b164-d07543151c3b/playlist.m3u8
```
then view it through `http://192.168.50.3:1984/stream.html?src=cam `it's just not possible, it plays at high speed, then freezes and breaks, while in vlc-player, the link http://camera.lipetsk.ru/ms-25.camera.lipetsk.ru/live/6a3efc18-3651-43a4-b164-d07543151c3b/playlist.m3u8 above works fine.

Please help me solve my problem, and think about creating a knowledge base in the Wiki

**Comment by skrashevich** [comment]
```yaml
streams:
  - "exec: ffmpeg -i 'https://camera.lipetsk.ru/ms-25.camera.lipetsk.ru/live/6a3efc18-3651-43a4-b164-d07543151c3b/playlist.m3u8' -c:v libx264 -pix_fmt yuv420p -b:v 2368512 -f rtsp {output}"
```
