### ISSUE TITLE
Recording video with two-way audio using the MP4 API

### ISSUE THREAD

**Issue by jjorosa** [AlexxIT/go2rtc#1007]
Hi guys,

First, congratulations. This is a wonderful piece of software.

I'm using a Hikvision camera with two-way audio and it works great.

However, now I want to record a mp4 file the video with the two-way audio.

The scenario is this:

I have a running session in a browser with the camera and the two-way audio and it works OK.
Then, using the mp4 api:

`curl "http://192.168.86.119:1984/api/stream.mp4?src=PTZ&duration=20&mp4=all&audio=all" -o video.mp4`

But the video file generated only contains the audio originated from the camera, not the audio originated from the browser (the microphone from the computer).

I've tried some combinations with the audio option, but the result is the same.

Is there any way that you know to achieve this?

The stream configuration that I'm using is this:

```
streams:
        PTZ:
            - rtsp://admin:xxxxxxx@192.168.86.64:554/Streaming/Channels/101
```

Thanks in advance

**Comment by AlexxIT** [comment]
It's very strange request. I'll save it for the far future

**Comment by jjorosa** [comment]
Thanks @AlexxIT 

Don't worry. It's really an uncommon request because my goal was to avoid a central server (like Janus) to achieve the recording. Finally I was forced to go in the Janus direction.

Let me close the issue.
