### ISSUE TITLE
MSE Stream Getting Stuck in the web

### ISSUE THREAD

**Issue by markspo** [AlexxIT/go2rtc#1011]
I am having a similar issue as seen in [https://github.com/AlexxIT/go2rtc/issues/644](url)

System info:
- Ubuntu 20.04.6 VM on vCenter host
`Intel Xeon Gold 6248R 4 vCores, 8GB RAM, 40GB drive` 
- Axis P3245-V via RTSP sream
- go2rtc running in Docker version 24.0.7
- go2rtc.yaml
>streams:
>>1080p: rtsp://UN:PW@10.X.X.X/axis-media/media.amp
480p: rtsp://UN:PW@10.X.X.X/axis-media/media.amp?videocodec=h264&resolution=640x480
720p: rtsp://UN:PW@10.X.X.X/axis-media/media.amp?videocodec=h264&resolution=1280x720&audio=0&fps=29

- Browser streams tried
`stream.html?src=[streams]
stream.html?src=[streams]&mode=mse`

The stream is freezing in Chrome on Windows, as well as a kiosk Chromebook (the main reason for using go2rtc), but refreshing the page, or just a "Save & Restart" via the web portal will refresh, and revive the stream.  Also to note, it doesn't freeze on the devices at the same time, so it doesn't seem like the stream, but more like the stream.html player.

Since I am running it in Docker, I do not see a way to change the stream.html page to add a JS to refresh the page after X minutes.  Or is this possible to add to the config?

**Comment by AlexxIT** [comment]
It's known issue if you have "bad" stream source #543

You can change WebUI even in docker if you want
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-api
