### ISSUE TITLE
output http ??

### ISSUE THREAD

**Issue by bellad17** [AlexxIT/go2rtc#1020]
hi , it's possible intput http://ip:8080/ instead of device ?
because my camera ( esp32-cam ) is http://192.168.1.230:8080/ that I want stream out http://192.168.1.51:8080/
on debian buster
thank

**Comment by AlexxIT** [comment]
HTML is not streaming protocol. It's a text protocol.
I think there is a MJPEG picture on your page that is supported as a source. You need to find a link to it.
