### ISSUE TITLE
A way to specify the default video codec supplied  when use mp4 output?

### ISSUE THREAD

**Issue by edensit** [AlexxIT/go2rtc#1023]
For example, let's say I have:
```
streams:
  dahua_camera1:
    - rtsp://user:password@192.168.1.110/cam/realmonitor?channel=1&subtype=1
```
And I want to get MP4 stream at H.264 (http://localhost:1984/api/stream.mp4?src=dahua_camera1&mp4=all)
Is there any way to force it to stream at  H.264?

Thanks!

**Comment by NickM-27** [comment]
video-h264

**Comment by AlexxIT** [comment]
If your camera output H265 - you should use transcoding and `?video=h264` option, like @NickM-27 said.
`mp4` param affects only to default MP4 audio codecs
