### ISSUE TITLE
MDVR

### ISSUE THREAD

**Issue by devorerl** [AlexxIT/go2rtc#1024]
Looking for a way to stream from an MDVR (Mobile Digital Video Recorder).  Joinlgo Model V80-WSX, 4 channel.  Using a QNAP NAS which as go2rtc app installed.  Very novice on programming or configuring to communicate with.  Device is on the same internal network.

**Comment by AlexxIT** [comment]
I don't know how to help you. You need to either figure out the documentation yourself. Or hire someone to do it for you.
