### ISSUE TITLE
2-way audio with Reolink doorbell

### ISSUE THREAD

**Issue by jerry34ha** [AlexxIT/go2rtc#1025]
Hi,
I'm trying to setup 2-way audio with my doorbell.
I tried the Frigate 0.13.2 + Frigate Card way, and the Go2rtc + WebRTC card way.

I think I solved the SSL issue (using NGINX add-on) as the browser asks for permission to use the microphone.

I see the camera image and hear the sound, but cannot talk to it.

Doorbell firmware is: v3.0.0.3215_2401262241
go2rtc is 1.8.5

Can someone take a look at the go2rtc info and tell me if it provides any useful info to help me troubleshoot ?

Here is my go2rtc config (sorry for the formatting, I tried...):

`streams:

  camera.reolink_doorbell:
    - "ffmpeg:https://192.168.1.106/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=myuser&password=mypassword#video=copy#audio=copy#audio=pcm"
    - rtsp://myuser:mypassword@192.168.1.106:554/h264Preview_01_sub`

And here is the go2rtc info:
[go2rtc.txt](https://github.com/AlexxIT/go2rtc/files/14812713/go2rtc.txt)

`{
  "producers": [
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/0cb15c93f81883996baa12cb46b61c3c",
      "remote_addr": "127.0.0.1:38094",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat 60.16.100\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:128\r\na=rtpmap:98 L16/8000/1\r\na=control:streamid=2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, recvonly, L16/8000"
      ],
      "receivers": [
        "96 H264, bytes=96370866, senders=1",
        "97 MPEG4-GENERIC/16000, bytes=726634, senders=0",
        "98 L16/8000, bytes=2963424, senders=1"
      ],
      "recv": 100920280
    },
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.1.106/Preview_01_sub/",
      "remote_addr": "192.168.1.106:554",
      "user_agent": "go2rtc/1.8.5",
      "sdp": "v=0\r\no=- 1711296547438431 1 IN IP4 192.168.1.106\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "senders": [
        "0 PCMU/8000, bytes=0, receivers=2"
      ],
      "recv": 392
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15",
      "medias": [
        "video, sendonly, H264, RTX, VP8, VP9, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, PCML"
      ],
      "senders": [
        "96 H264, bytes=91238611, receivers=1",
        "8 PCMA/8000, bytes=2780160, receivers=1"
      ],
      "send": 93635435
    }
  ]
}`

**Comment by jerry34ha** [comment]
And here is the log:
```
17:45:19.871 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.152:36708->192.168.1.106:554: read: connection reset by peer" url=rtsp://myuser:myadmin@192.168.1.106:554/h264Preview_01_sub
17:47:26.855 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.152:56494->192.168.1.106:554: i/o timeout" url=rtsp://myuser:myadmin@192.168.1.106:554/h264Preview_01_sub
```

The camera is PoE, not Wifi.
All the while this error happens, I can still see the video stream and hear sound.

**Comment by marcosimeone** [comment]
2-way audio Is broken with latest firmware. Reolink Is aware of It. You can open a ticket with them and they will provide you and older and working firmware. Check [](https://github.com/AlexxIT/go2rtc/issues/987) for more info.
