### ISSUE TITLE
Go2RTC is not compatible with ffmpeg4.4.2 version on Ubuntu，although it can be resolved by overloading the fmmpeg parameter

### ISSUE THREAD

**Issue by tanpopoycz** [AlexxIT/go2rtc#1027]
ffmpeg version 4.4.2-0 ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)

`root@ssy:ffmpeg_test$ ffmpeg -hide_banner -v debug -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout [5000000](tel:5000000) -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://172.20.142.188:32554/199 -c:v copy -c:a pcm_mulaw -ar:a 8000 -ac:a 1 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -c copy test.ts
Splitting the commandline.
Reading option '-hide_banner' ... matched as option 'hide_banner' (do not show program banner) with argument '1'.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'debug'.
Reading option '-allowed_media_types' ... matched as AVOption 'allowed_media_types' with argument 'video+audio'.
Reading option '-fflags' ... matched as AVOption 'fflags' with argument 'nobuffer'.
Reading option '-flags' ... matched as AVOption 'flags' with argument 'low_delay'.
Reading option '-timeout' ... matched as AVOption 'timeout' with argument '[5000000](tel:5000000)'.
Reading option '-user_agent' ... matched as AVOption 'user_agent' with argument 'go2rtc/ffmpeg'.
Reading option '-rtsp_flags' ... matched as AVOption 'rtsp_flags' with argument 'prefer_tcp'.
Reading option '-i' ... matched as input url with argument 'rtsp://172.20.142.188:32554/199'.
Reading option '-c:v' ... matched as option 'c' (codec name) with argument 'copy'.
Reading option '-c:a' ... matched as option 'c' (codec name) with argument 'pcm_mulaw'.
Reading option '-ar:a' ... matched as option 'ar' (set audio sampling rate (in Hz)) with argument '8000'.
Reading option '-ac:a' ... matched as option 'ac' (set number of audio channels) with argument '1'.
Reading option '-user_agent' ... matched as AVOption 'user_agent' with argument 'ffmpeg/go2rtc'.
Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'tcp'.
Reading option '-c' ... matched as option 'c' (codec name) with argument 'copy'.
Reading option 'test.ts' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option hide_banner (do not show program banner) with argument 1.
Applying option v (set logging level) with argument debug.
Successfully parsed a group of options.
Parsing a group of options: input url rtsp://172.20.142.188:32554/199.
Successfully parsed a group of options.
Opening an input file: rtsp://172.20.142.188:32554/199.
[RTSP demuxer @ 0x559d8e7be580] The "timeout" option is deprecated: set maximum timeout (in seconds) to wait for incoming connections (-1 is infinite, imply flag listen) (deprecated, use listen_timeout)
[tcp @ 0x559d8e7c0d00] No default whitelist set
[rtsp @ 0x559d8e7bda40] Unable to open RTSP for listening
rtsp://172.20.142.188:32554/199: Cannot assign requested address`

**Comment by tanpopoycz** [comment]
Actually, I'm not sure if I can overload the global parameters of ffmpeg

**Comment by tanpopoycz** [comment]
I'm not sure if it's possible to replace the lower version of ffmpeg as a better solution

**Comment by tanpopoycz** [comment]
![image](https://github.com/AlexxIT/go2rtc/assets/107358453/19242d62-e6b3-45b3-9038-785ac806aea1)
![image](https://github.com/AlexxIT/go2rtc/assets/107358453/249e761b-67de-43ca-955f-a8324c6c9d06)
    After removing the timeout parameter, although RTSP negotiation can be successfully carried out, the TS bare stream can only reach ffmpeg。I pulled 111 streams，The configuration file is as follows：
`streams:
  demo2-mp4-h264: ffmpeg:/home/nas/ycz/go2rtc_work_dir/demo2.mp4#video=h264#audio=pcmu
  demo2-mp4-h265: ffmpeg:/home/nas/ycz/go2rtc_work_dir/demo2.mp4#video=h265#audio=pcmu
  demo2-ts-h264: ffmpeg:/home/nas/ycz/go2rtc_work_dir/demo2.ts#video=h264#audio=pcmu
  demo2-ts-h265: ffmpeg:/home/nas/ycz/go2rtc_work_dir/demo2.ts#video=h265#audio=pcmu
  "111": ffmpeg:rtsp://172.20.142.188:32554/226#input=myinput_tcp#video=mycodec
 
api:
  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  #username: "admin"  # default "", Basic auth for WebUI
  #password: "pass"   # default "", Basic auth for WebUI
  #base_path: "/rtc"  # default "", API prefix for serve on suburl (/api => /rtc/api)
  #static_dir: "/usr/local/www"  # default "", folder for static files (custom web interface)
  #origin: "*"        # default "", allow CORS requests (only * supported)
  #tls_listen: ":443" # default "", enable HTTPS server
  #tls_cert: |        # default "", PEM-encoded fullchain certificate for HTTPS
  #  -----BEGIN CERTIFICATE-----
  #  ...
  #  -----END CERTIFICATE-----
  #tls_key: |         # default "", PEM-encoded private key for HTTPS
  #  -----BEGIN PRIVATE KEY-----
  #  ...
  #  -----END PRIVATE KEY-----
  #unix_listen: "/tmp/go2rtc.sock"  # default "", unix socket listener for API

ffmpeg:
  #bin: "/asdf/asdf"

  myinput_tcp: " -fflags nobuffer -flags low_delay -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i {input}"
  myinput_udp: " -fflags nobuffer -flags low_delay -user_agent go2rtc/ffmpeg -i {input}"
  myoutput: "-user_agent ffmpeg/go2rtc -rtsp_transport udp -f rtsp {output}"
  mycodec: "-c:v copy"

rtsp:
  listen: ":8554"    # RTSP Server TCP port, default - 8554
  #username: "admin"  # optional, default - disabled
  #password: "admin_123"   # optional, default - disabled
  default_query: "video&audio"  # optional, default codecs filters


webrtc:
  listen: ":8555"  # address of your local server and port (TCP/UDP)

  #candidates:
  #  - [216.58.210.174:8555](http://216.58.210.174:8555/)  # if you have static public IP-address
  #  - stun:8555  # if you have dynamic public IP-address`

**Comment by AlexxIT** [comment]
Yes. It's known fact. And no any plans to support so very old version.
