### ISSUE TITLE
Possible to protect only web gui?

### ISSUE THREAD

**Issue by Barabba11** [AlexxIT/go2rtc#1028]
Hi, I'm using this program to broadcast into RTC an RTSP stream of a camera for guests (they can see their kids playing safely by their phones), I want to protect the config from malicious accesses, I've implemented the user+password but this become requested also for access the stream http://192.168.1.10/stream.html?src=Baby-room, can I protect instead only the web gui editor?
Thanks

**Comment by AlexxIT** [comment]
You should use Nginx or any other reverse proxy with custom config. For now there is no other options.

**Comment by Barabba11** [comment]
Than you for answering, may you please add this feature on todo? I hope you consider it important, thank you

**Comment by AlexxIT** [comment]
This is a big task and a part of authorisation rework.
