### ISSUE TITLE
Producers sometimes remain after all consumers removed

### ISSUE THREAD

**Issue by bdoiron74** [AlexxIT/go2rtc#1033]
I'm finding that over time I end up with left over producers that continue to stream data from my cameras even if no consumers are connected. Is there any way to prevent this? Any way I can help debug the situation?

In this case I had 10 steams running and when I closed the page they all clean up properly except this one producer:

Zombie producer:
```json
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://10.187.214.15:553/stream/",
      "remote_addr": "10.187.214.15:553",
      "user_agent": "go2rtc/1.8.5",
      "sdp": "v=0\r\no=- 1546300803632188 1 IN IP4 10.187.214.15\r\ns=RTSP/RTP stream from IPNC\r\ni=stream\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2015.08.07\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:RTSP/RTP stream from IPNC\r\na=x-qt-text-inf:stream\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:12000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=64002A;sprop-parameter-sets=Z2QAKq2EAQwgCGEAQwgCGEAQwgCEO1A8ARPyzcBAQECA,aO48sA==\r\na=control:track1\r\n",
      "medias": [
        "video, recvonly, H.264 High 4.2"
      ],
      "receivers": [
        "96 H264, bytes=22726211904, senders=1"
      ],
      "recv": 22932482124
    }
  ],
  "consumers": []
}
```

expected:
```json
{
  "producers": [
    {
      "url": "rtsp://10.187.214.27:553/stream"
    }
  ],
  "consumers": []
}
```

edit: Using go2rtc docker image on Docker 26.0.0/Debian 11

**Comment by IliasEagle** [comment]
I think that's the same issue AlexxIT identified here [issue-904](https://github.com/AlexxIT/go2rtc/issues/904)

**Comment by bdoiron74** [comment]
Slightly different maybe? - I'm finding dead _producers_ which maintain an rtsp connection to the camera when all consumers have gone away. Then when a new consumer connection is made, you end up with a 2nd producer. I'm monitoring bandwidth over a wireless link and can see that both producers in this scenario are pulling data from the camera.

**Comment by sachinss123** [comment]
I concur with this. I am seeing the exact same thing but for only specific cameras. This is a different issue than 904.

One of the producers where this issue happens is a python script running on an Rpi 3b+ that streams a MJPEG video using libcamera2. Even after all consumers have stopped, the ffmpeg process from go2rtc still keeps running indefinitely. Another is an ESP32Cam flashed with Tasmota that is consuming ~10GB data on my network every day due to this issue!

**Comment by sachinss123** [comment]
Btw, this issue is not present in v1.8.4 - I just tested that out. I'm staying on that version till this gets fixed.

**Comment by AlexxIT** [comment]
The reconnection problem in version 1.8.5 is a known issue. Solution or use version 1.8.4. Or use the master version. Or wait for the next release.

**Comment by bdoiron74** [comment]
1.9.0 is much worse for this than 1.8.5. I have a monitor running that looks for producers with no consumers the deletes/re-adds to fix it. It seems that now with 1.9.0 consumers remain as well. Disappointing - I really like the new dark mode :)
