### ISSUE TITLE
Stopped working after update to Unifi Protect 3.x.x

### ISSUE THREAD

**Issue by madAndroid** [AlexxIT/go2rtc#1034]
Following on from: https://github.com/AlexxIT/WebRTC/issues/674

Camera streams started failing directly after upgrade to Unifi Protect version: 3.0.22 from 2.x.x

Camera stream in Home Assistant shows EOF:

<img width="508" alt="2024-03-28_08-05-57" src="https://github.com/AlexxIT/WebRTC/assets/1321437/1dc83752-28a2-42bd-bc96-5346572c5f0b">

I've enabled debug logging, but not much to go on there:

<img width="893" alt="2024-03-28_08-08-50" src="https://github.com/AlexxIT/WebRTC/assets/1321437/889bf948-e275-43b3-9d50-beaf8bf65e48">

**Comment by kungfuice** [comment]
Having a similar issue with 3.0.22 and 3.0.26, all cameras non functional showing the EOF error and same exception from init.go

**Comment by songochain** [comment]
Same here:

11:47:03.306 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: wrong login"

**Comment by kungfuice** [comment]
FYI for those having this issue, this worked to fix it for me:

SSH to your UDM console and run the following:
`rm /data/unifi-core/config/unifi-core.key`
`rm /data/unifi-core/config/unifi-core.crt`
`systemctl restart unifi-core unifi-protect`

I also ensured I put the cameras back to using RTSP on port 7447 rather then RTSPS or RTSPX on 7441

Community post regarding the issue:
https://community.ui.com/questions/RTSPS-stream-issue/f6b7c59a-4cff-4ff9-b305-dea0e38a4be5

**Comment by AlexxIT** [comment]
Solution: https://github.com/AlexxIT/go2rtc/issues/1034#issuecomment-2063744621

**Comment by madAndroid** [comment]
Thank you, I can confirm that using `rtsp` urls on port `7447` instead of `rtspx` on port `7441`, works - I didn't have to remove the certs though, I was already managing those with https://github.com/alxwolf/ubios-cert
