### ISSUE TITLE
[Question] What is the best practice: 1) rtsp->go2rtc->frigate 2) rtsp->friagte->go2rtc

### ISSUE THREAD

**Issue by Idan37S** [AlexxIT/go2rtc#104]
Hi,

What is the best practice usage of go2rtc and why?
1) rtsp->go2rtc->frigate 
2) rtsp->friagte->go2rtc

Thanks.

**Comment by AlexxIT** [comment]
go2rtc will be built into frigate from the next release
https://github.com/blakeblackshear/frigate/pull/4082

**Comment by Idan37S** [comment]
Wow that would be amazing,
Thanks for all of your hard work!
