### ISSUE TITLE
Raspberry Pi camera only works with mjpeg not h264

### ISSUE THREAD

**Issue by JustinS-B** [AlexxIT/go2rtc#1041]
Raspberry Pi 5 with freshly installed & fully updated full version of the Raspberry Pi OS 64bit desktop and a Raspberry Pi Camera 3 using 64bit go2rtc downloaded binary. Following the examples in the go2rtc documentation here, I have edited go2rtc.yaml to include the following lines.

```
streams:
  picam_h264: exec:libcamera-vid -t 0 --codec h264 -o -
  picam_mjpeg: exec:libcamera-vid -t 0 --codec mjpeg -o -
```
go2rtc starts normally from CLI and if I use the WebUI on port 1984, I can click on the **picam_mjpeg** stream link and streams to the webpage, exactly as expected.
```
justin@Pi5:$  ./go2rtc_linux_arm64 
11:27:35.601 INF go2rtc version 1.8.5 linux/arm64
11:27:35.602 INF [api] listen addr=:1984
11:27:35.602 INF [rtsp] listen addr=:8554
11:27:35.602 INF [webrtc] listen addr=:8555
```

However, if I click on the **picam_h264** stream link, the web page is blank grey only displaying the text **mse: streams: EOF**

The CLI gives the following error:

`11:32:31.187 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: EOF"`

If I click on the stream.html link, I get a grey video page with the following text:

```
webrtc/offer: streams: codecs not matched: JPEG => VP8, RTX, VP9, H264, ULPFEC, RED, OPUS, G722, PCMU, PCMA, TELEPHONE-EVENT, S16B, S16L
error
```

**FIXED**
However, if I edit go2rtc.yaml to add the switch **--libav-format h264** to the picam_h264 stream entry, as below, everything seems to work exactly as it should. 

```
streams:
  picam_h264: exec:libcamera-vid -t 0 --libav-format h264 -o -
  picam_mjpeg: exec:libcamera-vid -t 0 --codec mjpeg -o -
```

**Comment by AlexxIT** [comment]
Probably libcamera developers have changed default params

**Comment by marcob79** [comment]
Probably it is something related to pi5 in particoluar

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/881

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.2

**Comment by marcob79** [comment]
@JustinS-B how about performance of picamera in h264 mode on pi5 ?
if the stream running smooth even with at least FHD resolution?

**Comment by andi34** [comment]
@AlexxIT the jfyi: `--libav-format h264` isn't needed on go2rtc v1.9.2

**Comment by Tcoton** [comment]
I confirm that mjpeg codec works with format mpegts on rpi 5

`exec:rpicam-vid -t 0 --camera 1 --mode 2592:1944 --codec mjpeg --libav-video-codec-opts "profile=baseline" --libav-format mpegts -o -`

It also works with h264 but you must use the option `--libav-video-codec-opts "profile=baseline" ` otherwise the image is horrible.

I know have to find why the video resets (freezes for a few seconds, screen goes black and video comes back) randomly with no error visible.
