### ISSUE TITLE
No video in Home Assistant companion app for Mac

### ISSUE THREAD

**Issue by mbrevda** [AlexxIT/go2rtc#1044]
In the Mac companion app video streams refuse to play. In Safari/Chrome they play just fine. Any idea?

<img width="370" alt="Screenshot 2024-04-15 at 10 46 29 AM" src="https://github.com/AlexxIT/go2rtc/assets/293004/6f58f4d8-99b5-49a4-a272-fb3c58948924">

```
type: custom:webrtc-camera
url: camera.reolink
mode: mse,webrtc,webrtc/tcp
style: '.mode {display: none};'
muted: true
```
anything other configs needed?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#codecs-madness

**Comment by mbrevda** [comment]
sorry I missed that. Added `hls`, works great. Thanks!!!
