### ISSUE TITLE
RTSP Link include &param= parametr

### ISSUE THREAD

**Issue by pgswow** [AlexxIT/go2rtc#1055]
Hello!
I have rtsp link includes parametr '&subtype=0', full link as: rtsp://videouser:password@127.0.0.1:31003/cam/realmonitor?channel=1&subtype=0

If i'm add this link over [PUT] /api/streams?src=rtsp://videouser:password@127.0.0.1:31003/cam/realmonitor?channel=1&subtype=0 - programm trimm '&subtype=0' and save only rtsp://videouser:password@127.0.0.1:31003/cam/realmonitor?channel=1

**Comment by AlexxIT** [comment]
You should use some URL query encoding function.
