### ISSUE TITLE
restream m3u8 HLS segment size

### ISSUE THREAD

**Issue by ChrisPices** [AlexxIT/go2rtc#1058]
Hey,

I'd like to know is there a way to resize the m3u8's segments created when we use hls api to restream.
Actually it's 0.5sec each segment, but i'd like to resize it (-hls_time), and create a buffer to synchronize multiples cameras together on multiple hls player on a web page.

I search a lot about it, can input ffmpeg options to the rtsp streams created in the config.yml, but i can't change anything about the m3u8 streams created?

Either, sorry for my english.

Have a good day, and I hope find a way to change this.

Chris

**Comment by AlexxIT** [comment]
The current implementation of HLS differs from the standard. Chunks don't have a specific size. The data simply stores up until the customer requests it. This is different from the standard, but it works on many clients. And allows you to achieve good latency. Unlike standard HLS.

**Comment by ChrisPices** [comment]
but it is possible to create a buffer with that? i mean, if the segments are sended only when customer requests it, that means it's never stocked somewhere? In case i watch 2/3 cameras simultaneous on 3 hls player, if i have a tiny lag, cpu load or anything else, a desync is creating and that means cameras are not sync anymore, i have to reload them..

That's why i want, at least, change the time size of the chunks. They are at 0.5sec actually, would like to extand them to 1/2 sec.

But if you tell me it's impossible, i'll try to find another way to do it !

**Comment by AlexxIT** [comment]
Every HLS stream has ID and personal buffer. They NOT 0.5 sec in general. It's just personal case for your camera/viewer.
The current implementation does not assume a fixed chunk size.
