### ISSUE TITLE
Set `-user_agent` in `ffmpeg` calls

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#106]
So that I can easily distinct between consumers:

![image](https://user-images.githubusercontent.com/29582865/201231901-b6ae2f7f-699d-450f-b77e-2ab98880a686.png)

This can be set with the `-user_agent` ffmpeg flag. In order of usefulness but also in order of difficulty to implement:

1. `-user_agent 'go2rtc'` already much better than now
2. `-user_agent 'go2rtc/0.1-rc.1'`
3. `-user_agent 'go2rtc/0.1-rc.1 FFmpeg'`
4. `-user_agent 'go2rtc/0.1-rc.1 FFmpeg/3.1.2'`

I guess that, with the FFmpeg version in the string we don't need the `Lavf59.27.100` either. But it wouldn't hurt, I guess.

**Comment by AlexxIT** [comment]
I don't want generate ugly exec commands for ffmpeg. So it would be:
- for ffmpeg input: `go2rtc/ffmpeg`
- for ffmpeg output: `ffmpeg/go2rtc`
- for go2rtc client: `go2rtc/version`

**Comment by felipecrs** [comment]
This is awesome, thanks a lot!
