### ISSUE TITLE
ffmpeg source stop working RTC after update 1.9.0

### ISSUE THREAD

**Issue by DieMetRik** [AlexxIT/go2rtc#1073]
After update go2rtc from 1.8.5 to 1.9.0 stop workink RTC-stream  in frigate liveview (WebRTC) and in WebRTC card.

After some inspections:
If source streams RTSP -> OK
If source streams FFMPEG -> Only show MSE in frigate and WebRTC cards

Back to 1.8.5 all streams in RTC

My config:
Proxmox -> LXC -> Docker -> Frigate

```My go2rtc config in frigate
go2rtc:
  log:
    level: debug  # default level    
  rtsp:
    listen: :8554
    username: admin
    password: GKV
  streams:
#***********************************************   MAIN FLOW
    livingroom_camera_main: 
      ffmpeg:rtsp://admin:pass@192.168.1.35/cam/realmonitor?channel=1&subtype=0#video=copy#audio=copy#audio=opus
 #***********************************************   SUB FLOW
    livingroom_camera_sub: rtsp://admin:pass@192.168.1.35/cam/realmonitor?channel=1&subtype=1
  webrtc:
    listen: :8555
    candidates:
    - 192.168.1.130:8555
    - 192.168.1.44:8555
    - 127.0.0.1:8555
    - 192.168.1.1:8555
    - 192.168.1.50:8555
    - stun:8555
```
i tried this one but no sound in Chrome
```this
      rtsp://admin:pass@192.168.1.35/cam/realmonitor?channel=1&subtype=0
      ffmpeg:livingroom_camera_main#video=copy#audio=copy#audio=opus
```

updated:
If add webrtc/tcp to WebRTC card. All streams again in RTC
![image](https://github.com/AlexxIT/go2rtc/assets/31734768/dfb69872-eb26-4277-8feb-ea174243c145)
but a lot of streams
In go2rtc log:
![image](https://github.com/AlexxIT/go2rtc/assets/31734768/7434558e-585d-41cd-9104-1b31de93d658)

**Comment by AlexxIT** [comment]
I can't reproduce or confirm issue. Needs more specific info

**Comment by DieMetRik** [comment]
go2rtc is used as binary.
go2rty binary forwarded from host to frigate via docker-compose

I can share any log, if needed

**Comment by AlexxIT** [comment]
Frigate also uses built-in go2rtc. Are you sure they don't interfere with each other?

**Comment by DieMetRik** [comment]
![image](https://github.com/AlexxIT/go2rtc/assets/31734768/1804a966-3e73-468f-a476-0de757b53099)
![image](https://github.com/AlexxIT/go2rtc/assets/31734768/3495f2ee-021b-4dc5-961a-9b67f76f267e)

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/go2rtc/issues/1072#issuecomment-2096601667
