### ISSUE TITLE
Using piped backchannel without consumers leads to nil 

### ISSUE THREAD

**Issue by slyoldfox** [AlexxIT/go2rtc#1080]
Using the following from the example config:

```
streams:
    play_pcm48k: exec:ffplay -fflags nobuffer -f s16be -ar 48000 -i -#backchannel=1
```
And visiting https://localhost/stream.html?src=play_pcm48k will return in a nil pointer exception on `c.cmd.Process.Kill`

https://github.com/AlexxIT/go2rtc/blob/9c98f5e769bd3ecdf9eb0fec20a82630b0b77c35/pkg/stdin/pipe.go#L25

`c.cmd.Process` is `nil` in my case.

I am guessing this is caused by the producers being closed down before the command has spawn.
The producers are shut down because there are no consumers triggered by:

https://github.com/AlexxIT/go2rtc/blob/master/internal/streams/add_consumer.go#L86

**Comment by slyoldfox** [comment]
This is on 1.9.0 on macos (intel)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.1
