### ISSUE TITLE
Incoming MJPEG stream not work

### ISSUE THREAD

**Issue by jiekechoo** [AlexxIT/go2rtc#1087]
Version: 1.8.5

I create an empty stream like this:
```
streams:
  in:
```

using the example command to send mjpeg to `mjpeg dst`
```
ffmpeg -re -i BigBuckBunny.mp4 -c mjpeg -f mpjpeg http://localhost:1984/api/stream.mjpeg?dst=in
```

some error:
```
media_server  | 11:27:11.794 DBG [streams] can't stop external producer
media_server  | 11:27:11.794 DBG [mp4] add consumer error="streams: codecs not matched: JPEG => H264, AAC, PCMA, PCMU, S16B, S16L, OPUS"
media_server  | 11:27:11.797 DBG [webrtc] new consumer src=in
media_server  | 11:27:11.798 DBG [streams] can't stop external producer
media_server  | 11:27:11.798 DBG [webrtc] add consumer error="streams: codecs not matched: JPEG => VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03, OPUS, G722, PCMU, PCMA, CN, TELEPHONE-EVENT, S16B, S16L"
media_server  | 11:27:11.798 DBG [streams] can't stop external producer
```

And, I don't want to use ffmpeg to send 'mjpeg' to the go2rtc, I have a golang app using `gocv` mod, I tried to send image([]byte) with content-type: image/jpeg  , I got EOF. 
What should I do? Is there any missing? 

Thanks.

**Comment by AlexxIT** [comment]
There is no any errors in your logs. mp4 and webrtc doesn't support JPEG codec

**Comment by jiekechoo** [comment]
I have a MJPEG stream with url: http://192.168.1.1/hello , I can play in web browser. How to use go2rtc transfer to stream for clients?

**Comment by jiekechoo** [comment]
media_server  | 11:46:16.351 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="multipart: wrong boundary: ����[�\x7f�\x1fg_\\/�����k��,���\x0f��\x00ڕم���yG�_��X�=���q[���\x00��W��_���/�\v���W���~-��^��\x03W���..-�������?�_�\x7f�W��\x00� ���\x17~\r�l�m\x1f��/��\\[��\x00\n" url=http://[192.168.1.1/hello](http://192.168.1.1/hello)

**Comment by jiekechoo** [comment]
I upgrade `go2rtc` to  v1.9.0, the MJPEG source could read, but got WRN:
```
media_server  | 12:20:45.889 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="multipart: wrong boundary: /���\x00�o....."
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#source-http

**Comment by AlexxIT** [comment]
I think your http mjpeg stream not respect web standards

**Comment by jiekechoo** [comment]
thanks for your help

**Comment by AlexxIT** [comment]
You shouldn't set `content-type: image/jpeg` for mjpeg stream

https://github.com/AlexxIT/go2rtc/blob/4c3de3bbf426a4e975f1dc7204feb8afdf6d3ff5/internal/http/http.go#L69-L70

You can remove it, so magic source will try to guess type

https://github.com/AlexxIT/go2rtc/blob/4c3de3bbf426a4e975f1dc7204feb8afdf6d3ff5/pkg/magic/producer.go#L31-L32
