### ISSUE TITLE
stun/turn webrtc config not respected

### ISSUE THREAD

**Issue by tsulatsitamim** [AlexxIT/go2rtc#1088]
I'm sorry if i wrong about the config.
I config yml to be like this
![Screenshot 2024-05-05 at 11 48 07](https://github.com/AlexxIT/go2rtc/assets/5946791/d08bded3-364c-4a2d-b51d-d9619006580d)
but i still get google as stun server not metered.ca and it seems the turn also ignored.
![Screenshot 2024-05-05 at 11 49 09](https://github.com/AlexxIT/go2rtc/assets/5946791/cc7ac40c-7bd6-42f9-a7db-9bba87d6a98b)

did i made a mistake?

**Comment by AlexxIT** [comment]
Client boy using this settings. They only for server.

**Comment by tsulatsitamim** [comment]
the first screenshoot is setting for the server, where i put `metered.ca` as stun/turn

the second screenshoot is from debug in `chrome://webrtc-internals` when i visit
`xxx.com/stream.html?src=mycctv&mode=webrtc`
It show the usage of `google stun`, instead of `metered.ca` i configured in the server

**Comment by AlexxIT** [comment]
Client boy using this settings. They only for server.

**Comment by AlexxIT** [comment]
Client not using this settings. They only for server.

**Comment by tsulatsitamim** [comment]
yes, it's on server not client. the yml config is on server. sorry for my english.

**Comment by AlexxIT** [comment]
I know. There is no any mistake here.

**Comment by tsulatsitamim** [comment]
why there is google stun when i debug with chrome://webrtc-internals ?

**Comment by AlexxIT** [comment]
Client not using this settings. They only for server.

**Comment by tsulatsitamim** [comment]
i think the client use turn/stun to connect with server behind nat

**Comment by AlexxIT** [comment]
Server also can be behind NAT. This setting solve this situation.

**Comment by tsulatsitamim** [comment]
i use taht setting but not solve the solution, the clients seems not know the turn or stun to used

**Comment by AlexxIT** [comment]
I've already said three times that these settings are not for the client.
In my tests, the client does not need to change the default settings. If you need it - you need to write your own client.

**Comment by tsulatsitamim** [comment]
I find that in client js script there is also setting for turn and stun. thank you.
