### ISSUE TITLE
WebRTC stream freezes 

### ISSUE THREAD

**Issue by vuminhkh** [AlexxIT/go2rtc#1091]
Hello,

I'm writing a react native app using react-native-webrtc to communicate with go2rtc via frigate and home assistant. It works great in webrtc mode on my Tapo C210, Hikvision doorbell, but on my Annke FCD600 cameras with high resolution 3632 x 1632 in H264, the video stream freezes every seconds or even don't start at all (in debug log the stream receive mute event frequently and takes really long time to establish the connection, the bi directional audio stream is ok). If I reduces the bit rate drastically, then it works a little bit better but it still freezes from time to time, in night mode it freezes less than day mode. In the same time on all other cameras, it works great, if you guys have an idea how to debug this, I'll be very thankful. Basically, if i'm not mistaken Annke is just Hikvision rebranded, so I'm not sure what can be different between my Annke stream and Hikvision doorbell streams. I'm using go2rtc 1.8.5. Thank you in advance for your help.

**Comment by vuminhkh** [comment]
The hikvision doorbell's video in 1920x1080 also freezes from time to time.

**Comment by AlexxIT** [comment]
It depends if you using WebRTC inside or outside your network.

**Comment by vuminhkh** [comment]
I have the same problem inside or outside my network. I checked the stream configuration when i'm inside my network, it's IP v6 UDP which is used. Anyway with Tapo C210 (2304 x 1296), I have the best streaming experience, never freezes inside or outside. For the moment, for my Annke cameras, I get the video stream from home assistant  in HLS mode (with 3, 4 seconds lag but no freezing) and audio + microphone stream via WebRTC as a work around. I really wish to be able to use WebRTC though but I don't know how to optimize to avoid freezing.

**Comment by AlexxIT** [comment]
Have you read recommendations?
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-rtsp

**Comment by vuminhkh** [comment]
Thanks, I prefix the rtsp stream with ffmpeg, it's still 'glitchy'
`glichy_camera: ffmpeg:rtsp://username:password@192.168.1.123/live/ch00_1 `

**Comment by vuminhkh** [comment]
I don't know how yet, but frigate on safari on my phone works better than react-native-webrtc. It's perhaps the library which has issues, but I still don't know why the tapo stream works well with react-native-webrtc but not the annke streams.

**Comment by vuminhkh** [comment]
but in the same time, it's glitchy both on ios and android.

**Comment by AlexxIT** [comment]
Have you tried very glitchy version?

**Comment by vuminhkh** [comment]
I think about buying more robuste matos like ubiquiti wifi but the perf tests make me wonder, because the difference is not at all significant between wifi and ethernet for 358 Mbytes in 30 seconds.

**Comment by AlexxIT** [comment]
You can disable UDP for WebRTC in latest go2rtc
https://github.com/AlexxIT/go2rtc/blob/master/internal/webrtc/README.md

**Comment by vuminhkh** [comment]
yes, I confirm that no lag when it's tcp. Do you have an explanation ? My stress test seems to show that I don't have any issue in UDP with my Wifi but perhaps packets arrive a little bit more in disorder over Wifi and it makes react native webrtc too much effort to reorder packets ? In the same time TCP does not work when i'm not in my network as I block everything except for the port 80 and 443 for home assistant. I'll try from react native side to choose exclusively TCP when Home Assistant (and so Frigate) is in the same network as my cellphone. But when i'm outside of my network, do you have a solution ? Thanks.

**Comment by vuminhkh** [comment]
Anyway the glitchy problem also applied to frigate from chrome on mac os, so it seems to be not related uniquely to react native webrtc.

**Comment by AlexxIT** [comment]
A lot of people complain about WebRTC UDP for high bitrates on external access.
If the bitrate is very high and the channel is bad enough - you won't get a picture at all.
But I haven't heard of any complaints on the local network.

Better solution is to use UDP for local and TCP for external.
```yaml
webrtc:
  listen: :8555/tcp  # this is default
  ice_servers: []  # this is disable STUN/UDP external access (enabled by default)
  candidates:
    - stun:8555  # this is add external TCP candidate for your public IP
```

Also you need to port forward 8555 TCP port you your router if you has public IP-address.
