### ISSUE TITLE
building  custom ui

### ISSUE THREAD

**Issue by roycw** [AlexxIT/go2rtc#1094]
Hi we set up docker container and all working properly.
I want to build my own ui. how do i consume the feed via MSE ? do i need to open my own socket ?
If u can guid me toward the docs that would be great.

**Comment by AlexxIT** [comment]
You can read this docs:
https://github.com/AlexxIT/go2rtc/blob/master/api/README.md

And research this code:
https://github.com/AlexxIT/go2rtc/tree/master/www
