### ISSUE TITLE
[QUESTION]: Are homekit connected cameras kept after restart?

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#110]
I'm curious on how the homekit cameras work, if a user adds the camera is that connection kept after go2rtc is restarted? Does it not require any changes to the config.yaml?

**Comment by AlexxIT** [comment]
1. Camera can be imported from Hass. So Hass storage remember HomeKit credentials.
2. Camera can be paired to go2rtc. Credentials will be stored in go2rtc.json file in `cwd`. That should be `/config` folder in case of Docker container. Or Hass config folder for Hass users.

I think this should be added to the readme for Docker users that not using Hass.

**Comment by AlexxIT** [comment]
Also credentials could be converted to source link and used in yaml. They always will be same after pairing. But I think this is way only for geeks and developers. IP-address and port will be automatically updated on each connection via mDNS.

```
homekit://192.168.1.123:12345?client_id=xxx&client_private=xxx&device_id=xxx&device_public=xxx
```

**Comment by NickM-27** [comment]
> Also credentials could be converted to source link and used in yaml. They always will be same after pairing. But I think this is way only for geeks and developers. IP-address and port will be automatically updated on each connection via mDNS.
> 
> ```
> homekit://192.168.1.123:12345?client_id=xxx&client_private=xxx&device_id=xxx&device_public=xxx
> ```

Agreed, thinking about the frigate case of supporting homekit video cameras we would either need the user to map `go2rtc/config/` to their host so the config is saved, or we would need to save that URL for future use. Will be a while until that is considered / added to frigate though.
