### ISSUE TITLE
Streaming h265 / hevc from Unifi Protect doesn't work

### ISSUE THREAD

**Issue by RaHehl** [AlexxIT/go2rtc#1116]
If i try to stream a rtsp stream from Unifi Protect from a camera with h265 / hevc enabled it freezes and looks like this:

![image](https://github.com/AlexxIT/go2rtc/assets/7577984/5bcc1490-8074-4524-a569-dae682ef4a2e)

The same source RTSP url in VLC Works

![image](https://github.com/AlexxIT/go2rtc/assets/7577984/9869b659-e52f-4793-b801-b8c5b9ea22d9)

![image](https://github.com/AlexxIT/go2rtc/assets/7577984/df430c02-33fc-42a1-a6d5-38044377e67e)

Here's a log from the docker container with trace enabled:
[h265.log](https://github.com/AlexxIT/go2rtc/files/15324896/h265.log)

**Comment by RaHehl** [comment]
Frame.jpeg:
![image](https://github.com/AlexxIT/go2rtc/assets/7577984/fedcd796-b8ac-4ae8-aeac-f930f99a7510)


rtsp://192.168.7.10:8554/rtspx://192.168.7.8:7441/*********
Works in VLC

**Comment by AlexxIT** [comment]
#1102

**Comment by RaHehl** [comment]
@AlexxIT regarding https://github.com/AlexxIT/go2rtc/issues/1102#issuecomment-2118845248 my last comment was with 1.9.2 are u sure this is duplicate? This isn't fixed

**Comment by RaHehl** [comment]
@AlexxIT 

Without knowing what I was doing, I noticed the following:
I have a G5 Bullet that doesn't cause any problems, and several G4s that have this problem.
I have " log.Printf("[HEVC] %v, len: %d", Types(buf), len(buf))" activated in the h265 rtp.go.

The broken stream from the G4 looks like this:

2024/05/19 00:28:51 [HEVC] [1], len: 158
2024/05/19 00:28:51 [HEVC] [1], len: 88
2024/05/19 00:28:51 [HEVC] [1], len: 141
2024/05/19 00:28:51 [HEVC] [1], len: 137
2024/05/19 00:28:51 [HEVC] [1], len: 72
2024/05/19 00:28:51 [HEVC] [1], len: 132
2024/05/19 00:28:51 [HEVC] [32 33 34 19], len: 5568
2024/05/19 00:28:51 [HEVC] [19], len: 4502

And with the functioning G5 like this:
2024/05/19 00:29:47 [HEVC] [1], len: 6354
2024/05/19 00:29:47 [HEVC] [32 33 34 19], len: 249579

I suspect it may be more of a problem with the source stream that comes from protect than a go2rtc problem, but vlc works, how could I describe the problem when I approach the UI? Unfortunately I have no idea about the HEVC internals

**Comment by AlexxIT** [comment]
This is duplicate about frizes from broken stream. Why it's broken - we don't know.
You can use transcoding via ffmpeg. Probably it will fix broken stream.
