### ISSUE TITLE
Question: go2rtc and a large number of cameras (150-200)

### ISSUE THREAD

**Issue by pgswow** [AlexxIT/go2rtc#1120]
First I would like to thank everyone involved in the development of this wonderful program.
The question is: given a sufficiently powerful server, has anyone tested such a number of cameras, and were there any problems? Also, what kind of server is needed for this number of cameras (amount of CPU and memory)? 
Sorry for my bad English
UPD: all cameras HD

**Comment by AlexxIT** [comment]
There's no such calculations. I know setups with 6500 cameras in the config.
Each protocol has a different workload.
Every protocol is not free. Simple RTSP 4K proxying can load 3% of CPU. It's just a network load.
The most expensive is WebRTC.

**Comment by pgswow** [comment]
> There's no such calculations. I know setups with 6500 cameras in the config. Each protocol has a different workload. Every protocol is not free. Simple RTSP 4K proxying can load 3% of CPU. It's just a network load. The most expensive is WebRTC.

Thanks for the answer =) The question is closed.
