### ISSUE TITLE
Does the roborock s8 maxv work?

### ISSUE THREAD

**Issue by borgqueenx** [AlexxIT/go2rtc#1125]
I want to buy the roborock s8 maxv to use with go2rtc, but only if it works...
So im curious if anyone has the experience with this?
Same protocols as the s7 maxv?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/853

S8 doesn't has this feature in the firmware.

**Comment by borgqueenx** [comment]
@AlexxIT im not talking about the S8, the S8 plus or ultra. im talking about the S8 Maxv, it is the model with a camera. the other s8's do not have a camera.

**Comment by AlexxIT** [comment]
You can't watch S8 camera from original app. They disabled this feature.

**Comment by borgqueenx** [comment]
you CAN watch the camera in the roborock app, i dont know what you mean with "original" app. But ONLY on the s8 maxv model.

**Comment by AlexxIT** [comment]
Oh. I didn't know about this. Anyway there is no known users with approved support for S8 model.

**Comment by borgqueenx** [comment]
> Oh. I didn't know about this. Anyway there is no known users with approved support for S8 model.

so we need some official support from roborock? there is no chance this newer model works the same as the s7 maxv?

I would be willing to test it in the time i can still return the device...

**Comment by AlexxIT** [comment]
Is S8 uses same API like S7 - it should work.

**Comment by borgqueenx** [comment]
it works technically, but i have trouble getting it working trouble-free.
First today, it was working while docked, yet i got many times the robot saying "remote viewing active, remote viewing disabled, video call active, etc" it was spamming it, and in frigate it reported no frames received. as soon as i opened the stream through the go2rtc dashboard, it stopped spamming me voice messages and kept working, also in frigate.

I restarted the robot and now its constantly spamming me the message "remote viewing active", but none of the streams are working. errors in vlc when trying to play, errors in frigate. media player in browser through go2rtc dashboard not working either.
