### ISSUE TITLE
webRTC Stream does not run on Fully Kiosk Browser

### ISSUE THREAD

**Issue by UeT-Fire** [AlexxIT/go2rtc#1127]
Hello,

I don't know if it belongs here, but maybe someone has had the same problem.

I integrated go2rtc using the latest Frigate version. The latest Frigate version runs go2rtc version 1.8.4

I have a Fire Tab HD 10. It's the newest one from last year. I have this hanging in the hallway so that, among other things, I can display a live stream of the Reolink video doorbell. I copied the link to open the webRTC stream via the go2rtc interface in the browser. I have this opened automatically via HA automation via the Fully Kiosk Browser when the doorbell rings.

I have integrated both streams from the camera into go2rtc. So once the sub stream and once the main stream. The sub stream runs without any problems via webRTC, but the mainstream is not loaded. I don't have this problem with mse. The main and substream run there without any problems. The webRTC stream doesn't really run smoothly on the PC in the browser (Chrome). There are no problems accessing the stream on my iPhone in either Safari or Chrome.

The mainstream bit rate is 4096Kbps by default. I have already set this down to 1024Kbps. That didn't help either.

I think it has more to do with the device or the browser, right?

Thanks in advance for your solutions.

**Comment by felipecrs** [comment]
Sorry, I did not read the entire text. I just wanted to say webrtc over go2rtc works very well in my Fully Kiosk tablet since years.

My guess is that you are running a too old Webview.

**Comment by felipecrs** [comment]
Oh sorry. I also use only substreams with my tablet, 720P. I didn't really test higher than that.

But upgrading Webview if possible or even the Android version may help with that, I think.

**Comment by UeT-Fire** [comment]
I've already read about this problem with the web viewer. I thought that since the tablet is fairly current, it should fit without me having to do anything.

Do you have instructions for me on how I can update the web viewer?

**Comment by felipecrs** [comment]
If you are lucky, you can update it through Play Store. Check in Developer Options the current version you're using.

**Comment by UeT-Fire** [comment]
I have already tried to install the Android web viewer. However, you can still only select the Amazon WebView implementation.
![IMG_4253](https://github.com/AlexxIT/go2rtc/assets/139175521/fa7503c8-467b-44f7-bd2d-204acf3e9f80)

**Comment by UeT-Fire** [comment]
When I display the main stream in HA in the form of a card, it also stutters quite a bit on the Fire Tab. I think the tablet's performance simply won't be sufficient to display the high resolution cleanly. The stream runs almost smoothly on the PC in the browser.

**Comment by felipecrs** [comment]
122 is not too old. It's this year's. But maybe because of this amazon on it... Maybe amazon crapped it somehow?

No idea.

Anyway. The only way I know to change webview is to use a magisk module.

But don't trust me, do your own research if you want to tinker with it.

**Comment by UeT-Fire** [comment]
That´s my stream info.

```json
{
  "producers": [
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/9d825245db472df29adce50a23237ca0",
      "remote_addr": "127.0.0.1:36960",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=No Name\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat LIBAVFORMAT_VERSION\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000/1\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:streamid=1\r\nm=audio 0 RTP/AVP 98\r\nb=AS:64\r\na=rtpmap:98 opus/48000/2\r\na=control:streamid=2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, recvonly, OPUS/48000/2"
      ],
      "receivers": [
        "96 H264, bytes=69838803038, senders=1",
        "97 MPEG4-GENERIC/16000, bytes=522462810, senders=1",
        "98 OPUS/48000/2, bytes=1202635072, senders=0"
      ],
      "recv": 72240646072
    }
  ],
  "consumers": [
    {
      "type": "RTSP passive consumer",
      "url": "rtsp://127.0.0.1:8554/doorbell_main?video=copy\u0026audio=aac",
      "remote_addr": "127.0.0.1:36954",
      "user_agent": "FFmpeg Frigate/0.13.2-6476f8a",
      "sdp": "v=0\r\no=- 1 1 IN IP4 0.0.0.0\r\ns=go2rtc/1.8.4\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:trackID=0\r\nm=audio 0 RTP/AVP 97\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408\r\na=control:trackID=1\r\n",
      "medias": [
        "video, sendonly, ANY",
        "audio, sendonly, MPEG4-GENERIC"
      ],
      "senders": [
        "96 H264, bytes=69838803038, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=522462810, receivers=1"
      ],
      "send": 71154227464
    }
  ]
```

**Comment by AlexxIT** [comment]
Like I said. `H.264 High 5.1` case of problems with many low end mobile devices.

**Comment by UeT-Fire** [comment]
Ah okay, thanks for the answer.

I still only have this problem with the RTC stream and not with the MSE stream. Is there a way to transcode it or something similar?

**Comment by AlexxIT** [comment]
Transcoding should help. Upgrading WebView may help or may broke even more.

**Comment by UeT-Fire** [comment]
I've now tried transcoding. It only works with webRTC if I transcode the resolution down far enough. The sub stream only runs at a resolution of 640x 480 pixels and 256 Kbps. I don't think the Fire HD 10 can handle the high resolution paired with a bit rate that's too high.

I haven't managed to change the WebView version yet. With a decent Android tablet with better hardware, this problem probably won't occur.

But the MSE stream is completely sufficient for me and I'm happy with it.

Thanks for the help!

**Comment by sircoynie** [comment]
Did you stick with MSE or with the recent HA integrated Webrtc find a solution that works with the fire hd10? Thanks
