### ISSUE TITLE
Improvement suggestion: In docker log entries, add the date and show the time in the local timezone

### ISSUE THREAD

**Issue by mcsquared88** [AlexxIT/go2rtc#113]
I'm running go2rtc version 0.1-rc.3 in a Docker container on UnRAID. The timestamp for each entry in the log only shows the time and I think the time is in UTC, not my local timezone. This makes figuring out what's going on (and if the most-recent log entry actually happened recently) a lot harder than it needs to be.

Here's an example line from the go2rtc log:

01:06:16.970 INF go2rtc version 0.1-rc.3 linux/amd64

Here's an example line from the frigate log, which has the date and then the time adjusted for the local timezone:

[2022-11-18 17:57:00] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39360]

**Comment by AlexxIT** [comment]
Fixed in latest versions
