### ISSUE TITLE
[Feature Request] Add support to authenticate RTSP clients

### ISSUE THREAD

**Issue by tsightler** [AlexxIT/go2rtc#114]
I've been testing go2rtc as a replacement for rtsp-simple-server due to the fact that it handles streams more smoothly, however, the lack of support for username/password auth for the RTSP streams is a little bit of an issue for my project.  Curious if this is something on your roadmap.

**Comment by AlexxIT** [comment]
Supported in [v0.1-rc.5](https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.5)
