### ISSUE TITLE
rtsp sink playback issues, while webrtc stream works flawlessly

### ISSUE THREAD

**Issue by FrankyBoy** [AlexxIT/go2rtc#1144]
In the web view (i.e. /stream.html?src=cam1) things work perfectly well, however when trying to connect to rtsp I often cannot connect or only get a frame every few seconds (in contrast to once every second). There is no significant CPU or memory usage when connecting either way. 

In the logs I see the following warning:
`undefined error=read tcp 10.0.2.100:8554->10.0.2.100:55730: i/o timeout caller=github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:225` which looks like go2rtc is trying to open some internal connection to itself but fails. 

My config is as follows:
```
streams:
  cam1: rtsp://[censored]/Streaming/channels/101

rtsp:
  listen: ":8554"
  user: "[someuser]"
  pass: "[somepass]"
```
and rtsp runs inside podman. with command `podman run --name go2rtc-cams --init --rm --detach -p 8554:8554 -p 8080:1984 -v $DATA_DIR:/config docker.io/alexxit/go2rtc:latest`, which is then proxied by nginx to ports 80 and 554. However the same behaviour can also be observed when connecting to port 8554 directly, so I don't think that part is relevant. 

Also not entirely sure where that IP comes from as podmans network supposedly is 10.88.0.0/16, but I'm not a container expert.

**Comment by AlexxIT** [comment]
I don't know. Maybe it's podman's issue about proxy ports.
Go2rtc not "trying to open some internal connection to itself".
This is incoming RTSP connection to 8554 port.

**Comment by FrankyBoy** [comment]
Hi, 

Yeah I read that wrong. The network stuff just looks strange due to containerization. 
We figured out now that it was the damn load ballancer doing something weird. Taking that out of the picture resolved our issues.
