### ISSUE TITLE
Issues loading in Octoprint

### ISSUE THREAD

**Issue by aegjoyce** [AlexxIT/go2rtc#115]
Not sure if this is an octoprint issue or a go2rtc issue but perhaps you might be able to point me in the right direction!

Trying to use go2rtc to convert an rtsp stream from a tapo camera into an mjpeg stream that octoprint can use in its web interface. I've previously used rtsp2mjpg with success but had problems with it crashing frequently so thought I would give go2rtc a try.

No problems with setup - I used "ffmpeg:[my stream url]#video=mjpeg" and when I click on the mjpeg link I get a video output. However when I put the mjpeg link into octoprint I get the question-mark box and no stream shows. No errors in the logs.

I note that with rtsp2mjpg the address used was much shorter than the go2rtc address - "http://[IP address]/live.mjpg".

Could the problem be to do with the format of the link or the absence of '.mjpg' at the end?

Many thanks for an otherwise amazing bit of software.

**Comment by AlexxIT** [comment]
Maybe you forgot to add `?src=` to your stream link. I have checked in octoprint, everything works.

```yaml
streams:
  camera1: ffmpeg:c:/media/bbb_720p.mp4#video=mjpeg
```

Link: http://192.168.1.123:1984/api/stream.mjpeg?src=camera1

**Comment by aegjoyce** [comment]
Unfortunately not, it's all there - I'm just copying and pasting the url after clicking on the mjpeg stream:

http://192.168.1.244:1984/api/stream.mjpeg?src=ffmpeg%3Artsp%3A%2F%2F[username]%3A[password]%40192.168.1.101%3A554%2Fstream1%23video%3Dmjpeg

**Comment by NickM-27** [comment]
Are you adding the camera via the UI? I think this would be a lot simpler if you used a config file

**Comment by aegjoyce** [comment]
Bingo! Deleted the docker container and reinstalled having set up the stream in a config file first. My mjpeg address is now http://192.168.1.244:1984/api/stream.mjpeg?src=test and it works with octoprint perfectly! Many thanks
