### ISSUE TITLE
Question: create and update stream from API

### ISSUE THREAD

**Issue by pgswow** [AlexxIT/go2rtc#1151]
Hello!
im use Postman and javascript fetch:
1. create stream: [PUT] /api/streams?src=rtsp://rtsp:1234@192.168.1.1/av_stream/ch_0&name=camera01
stream succsess created and streaming.
2. update stream (change ch_0 to ch_1): [PATCH] /api/streams?src=rtsp://rtsp:1234@192.168.1.1/av_stream/ch_1&name=camera01
stream succsess updated and streaming updated channel

in config file go2rtc.yaml i not see my changes, and after restart go2rtc i see in stream my old channel.
Is this a bug or am I doing something wrong? (I also tried to update the config via [PATCH] /api/config)

EDIT: go2rtc Version: 1.9.2

**Comment by AlexxIT** [comment]
PUT should change the yaml file. Depends on what parameters you run go2rtc with. And if it is docker - if its parameters correct.

**Comment by pgswow** [comment]
> PUT should change the yaml file. Depends on what parameters you run go2rtc with. And if it is docker - if its parameters correct.

Clean install of debian 11 without docker. I run ./go2rtc & (without -c parameter)

**Comment by pgswow** [comment]
> PUT should change the yaml file. Depends on what parameters you run go2rtc with. And if it is docker - if its parameters correct.

im checked on my local windows 10 and go2rtc.exe (1.9.2) - PATCH not changed go2rtc.yaml file =(

**Comment by pgswow** [comment]
> PUT should change the yaml file. Depends on what parameters you run go2rtc with. And if it is docker - if its parameters correct.

I realized what I was doing wrong, I'm trying to update both the stream and the config file via PATCH, but this doesn't happen, however, everything works fine if I change the stream via PUT. Thank you!

**Comment by clyra-deep** [comment]
is it possible to dynamically delete
