### ISSUE TITLE
Wrong documentation about default ffmpeg file arguments

### ISSUE THREAD

**Issue by mike2307** [AlexxIT/go2rtc#1159]
The wiki page https://github.com/AlexxIT/go2rtc/wiki/Configuration#defaults states, that the default arguments for the ffmpeg file is `-re -stream_loop -1 -i {input}`.

It is also mentioned in a code comment https://github.com/AlexxIT/go2rtc/blob/bd73b07ed809d40ee75632f2ff06069976c2d321/pkg/ffmpeg/ffmpeg.go#L21

The `-stream_loop -1` was actually removed in https://github.com/AlexxIT/go2rtc/commit/a8612fca4399e503324fc3cddb09a1905bfef3d5.

Please synchronize the documentation with the code.
Thanks :+1:

**Comment by AlexxIT** [comment]
Thanks. I removed the mention of presets from the documentation. There are a lot of presets and they change all the time.
