### ISSUE TITLE
go2rtc to onvif id name madness 

### ISSUE THREAD

**Issue by robert-sz-76** [AlexxIT/go2rtc#1160]
Hi Alex.
In my _go2rtc_ I have several input:

-   rtcAsus
-   rtcImouHd
-   rtcImouSd
-   rtcIngresso
-   rtcSamsung
-   rtcSoggiorno
-   rtcTapoHD
-   rtcTapoSD

I add to _Onvif integration go2rtc_ as source (127.0.0.1:1984) and I call it "**go2onvif**"
The problem is that the **ID entity do not respect the source name**. For example:

- Onvif Name   ->   ID Name
___________________________________________
- go2onvif rtcTapoSD   ->   camera.go2onvif_rtcasus
- go2onvif rtcImouHd   ->   camera.go2onvif_rtcsoggiorno
- go2onvif rtcSoggiorno   ->   camera.go2onvif_rtcsamsung
- and so on

I have to mention that the stream is correct, go2onvif rtcTapoSD stream from rtcTapoSD, only the id (camera.go2onvif_rtcasus) is wrong. Same for the others.

Thank you.
Robert

**Comment by AlexxIT** [comment]
Hi. I can't confirm your words. Just made same test. I hope your talking about Home Assisstant onvif integration. All streams shows as they should.
You can increase log level to trace and check something useful there.

**Comment by robert-sz-76** [comment]
I delete the go2rtc source from onvif integration, re-add it and everything looks that should be. Maybe it was an onvif integration issue.

Thank you.
