### ISSUE TITLE
Tapo Camera Microphone Issue

### ISSUE THREAD

**Issue by dkahn93** [AlexxIT/go2rtc#1163]
Hi, I can't for the life of me figure out how to get the microphone working on HA. I'm using a Tapo C210 camera. This is in my go2rtc.yaml config:

```
streams:

  camera.livingroom:
    - rtsp://username:password@192.168.x.xxx:554/stream2
    - tapo://admin:md5hashcloudpassword@192.168.x.xxx
```

It works perfectly with audio and video, a seamless stream, no delay at all, but when I go to "links", select the option "video+audio+microphone = two way audio from camera" and click "webrtc.html" I only get video and audio. I did get the mic request and do see that the mic is  on, on my computer, but nothing comes out of the camera speaker.

I have Tailscale set up with their https enable feature, which is how i can get the computer mic on in the first place.

The weird thing is, setting the log to debug, I only see "[streams] start producer url: rtsp://username:password@192.168.x.xxx:554/stream2" and then a "stop producer url rtsp://..." line. I'm new to this, but it's almost as if go2rtc is ignoring the tapo:// line in the config altogether.

I even added this in the HA config yaml:

```
media_player:
  - platform: webrtc
    name: camera.livingroom
    stream: camera.livingroom
    audio: pcma
```

Not sure if that is necessary, but I saw someone use that somewhere to fix a similar issue for a Tapo Camera. It doesn't work for me.

I'm using Home Assistant Core , and I've tried this on both Safari and Chrome, and neither work.

What am I doing wrong?

**Comment by dkahn93** [comment]
Oh, and the computer is a Macbook 2021.

I also tried on the Android app, which I actually have a different set up on, using cloudflare with a regular domain name, again https enabled. Again, phone shows the mic is on, but nothing is coming out of the camera.

**Comment by AlexxIT** [comment]
Have you read docs? https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#two-way-audio

**Comment by AlexxIT** [comment]
With `video+audio+microphone` link on HTTPS site you SHOULD be asked about access mic. Even in case if camera doesn't support two way. Maybe you have manually blocked mic access for this site or for whole browser.

**Comment by dkahn93** [comment]
I'm saying that EVEN though I WAS asked and the icon that says the computer's mic is on DOES show on both the browser and the computer, it does not work. This Tapo camera does support 2-way.

**Comment by AlexxIT** [comment]
Are you sure tapo proto works for you? You can remove rtsp proto and leave only tapo.
Some users has problems with new firmwares on their cameras.

**Comment by dkahn93** [comment]
Nevermind, I looked back at the docs and tried changing the encryption of
the cloud password from the md5 hash to sha-256, and it started working
perfectly.

**Comment by bmwgurkan** [comment]
Hi @AlexxIT, 
I have the same configuration. I was very happy with it until 5 days ago. However, both two-way talk and media player no longer work. I think this has to do with Tapo himself. The problem persists even when I try again after deleting and resetting the camera from the Tapo application. Additionally, when using cameras on the homekit with the Scrypted plugin, two-way conversation no longer works. I use 3 Tapo c225 and 1 Tapo c320ws.

**Comment by AlexxIT** [comment]
@bmwgurkan you can search discussion about new tapo firmwares in other issues.

**Comment by bmwgurkan** [comment]
Hi again @AlexxIT,
The 2-way audio problem persists on 1 Tapo C320SW and 3 C225 cameras. When I want to test with Webrtc magic and the Webrtc special card in the Home Assistant mobile application, I see that the microphone is used, but the speech sound does not come from the camera speaker. I changed the Tapo cloud password, tried with md5, sda passwords, reset and reinstalled the cameras, but the problem persists. Although I have used it before without any problems, now I am having a hard time understanding why there is a problem. Should I start a new topic here for this problem?

**Comment by AlexxIT** [comment]
You should check existing issues

**Comment by bmwgurkan** [comment]
I couldn't find any solution in the other problems section :(

**Comment by AlexxIT** [comment]
If you have latest firmware with broken auth - there is no solution

**Comment by ppfeister** [comment]
@AlexxIT A lil late here but does the issue you mention impact ALL tapo:// functionality now or just the mic request? Experiencing some issues with some TC85s and want to know if that's related

**Comment by AlexxIT** [comment]
Current tapo protocol doesn't support auth for new cameras firmware. Works just fine for old firmwares. You can use RTSP protocol for tapo cameras, but without two way.

**Comment by ppfeister** [comment]
Thanks for confirming @AlexxIT 

I had a feeling that was the case, but I was _hoping_ to be wrong. Glad that I found this before spending all day diagnosing.

Cheers
