### ISSUE TITLE
daemonization causes process to constantly restart with new pid

### ISSUE THREAD

**Issue by puterboy** [AlexxIT/go2rtc#1165]
Running go2rtc on a RPi5.
Works if I just run `go2rtc_linux_arm64`
However if I run `go2rtc_linux_arm64 -d`, then the process continually restarts with a new pid, making the stream useless.
Note this happens whether I run as root or as unprivileged user.

**Comment by AlexxIT** [comment]
You can use `-daemon` flag as temporary solution

**Comment by puterboy** [comment]
Is that '-daemon' or '--daemon'?
Also, is there a way to get log output in daemon mode?
Would be good to have a flag to redirect stdout/stderr when in daemon mode to catch errors

**Comment by skrashevich** [comment]
> Is that '-daemon' or '--daemon'?

Both will work (#1168).

> Also, is there a way to get log output in daemon mode?
> Would be good to have a flag to redirect stdout/stderr when in daemon mode to catch errors

Apologies for the oversight. This feature will been implemented in #1167.

**Comment by puterboy** [comment]
Any idea when this will all be pulled into 'master' and official release number will be bumped?
Thanks :)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.4
