### ISSUE TITLE
Any way to default stream display to MSE?

### ISSUE THREAD

**Issue by tbrausch** [AlexxIT/go2rtc#117]
I am using Wyze Bridge to get RTSP streams for my 4 Wyze cameras.   When displaying the cameras in Home Assistant, I get occasional stuttering in the display.  Checking the go2rtc Web UI, I do not get the stuttering in MSE, only in WebRTC.  Is there anyway to configure go2rtc to display video streams as MSE by default?  I am willing to sacrifice the extra 1 second delay between MSE and WebRTC.

**Comment by AlexxIT** [comment]
Wait for #13. Or use iframe

Also you can share your stream, so I can check it
https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet

**Comment by tbrausch** [comment]
> Wait for #13. Or use iframe

Not quite sure I understand.  Will the new card you are referring to in #13 or an iframe card support the display of MSE instead of WebRTC?  I am not having issues with my current card (I am currently using the  Frigate Lovelace Card).  I simply want the card to display a MSE stream instead of a WebRTC stream (since the WebRTC display frequently stops for a second or two, then jumps back to realtime) .  My testing of the MSE stream in the go2rtc UI seems to work fine, whereas the WebRTC stream stutters.

> Also you can share your stream, so I can check it https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet

I will look at this and see if I can figure out how to share the stream with you.  If I get it working, how should I send the link to you.

**Comment by NickM-27** [comment]
The card has to support displaying mse, it's not as simple as the card just showing something else. 

I'd like to see the frigate card support mse and WebRTC directly since frigate will have go2rtc built in in the next version.

**Comment by tbrausch** [comment]
> The card has to support displaying mse, it's not as simple as the card just showing something else.
> 
> I'd like to see the frigate card support mse and WebRTC directly since frigate will have go2rtc built in in the next version.

Thanks, I think I understand a little better now.

**Comment by AlexxIT** [comment]
Supported in WebRTC Camera v3
https://github.com/AlexxIT/WebRTC/releases
