### ISSUE TITLE
api.ws] upgrade error="websocket: request origin not allowed by Upgrader.CheckOrigin"

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#118]
After updating to rc4 I am getting this error regardless of if `api -> origin` is set to `"*"` or `""` when it was previously working. I am not sure if this is a go2rtc issue or something that needs to be adapted to

**Comment by AlexxIT** [comment]
api > origin should disable this check. Don't know why it doesn't work. This problem could be happened because wrong port forwarding via docker #28 
I have removed dummy fix for this issue because origin settings now exist.

**Comment by NickM-27** [comment]
Interesting, we are using an nginx proxy with a web socket from :5000 -> :1984 and like I said the origin option hasn't had any affect.

Is there a specific value that is needed or any other value than * should disable that?

**Comment by AlexxIT** [comment]
Origin settings should work in any way. Are you sure you use quotes as in example? `origin: "*"`

https://github.com/AlexxIT/go2rtc/blob/fae59c799233180b8cfd7abacc73f1d6e050c590/cmd/api/ws.go#L16-L20

**Comment by AlexxIT** [comment]
This happens when the Host and Origin headers are different:
- OK: `host=192.168.1.123:1984 origin=http://192.168.1.123:1984` (no nginx)
- OK: `host=myhome.duckdns.org origin=https://myhome.duckdns.org` (nginx docker port 433:433)
- ERROR: `host=myhome.duckdns.org origin=https://myhome.duckdns.org:4430` (nginx docker port 4330:433)

I'll return dummy fix. It seems that strange nginx configuration in Docker is a common situation.

**Comment by NickM-27** [comment]
@AlexxIT This is my bad actually, I had assumed that "*" was the default value. Now that I have set that, it is working just fine

**Comment by AlexxIT** [comment]
Using CORS * in all cases is not a good idea from a security reason. You will be able to remove this setting in the next version.

**Comment by AlexxIT** [comment]
Fixed in [v0.1-rc.5](https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.5)

**Comment by markfrancisonly** [comment]
unfortunately this issue was resolved for me but the error message as returned in my go2rtc version 1.5 logs: 
```11:58:39.317 ERR github.com/AlexxIT/go2rtc/internal/api/ws/ws.go:96 > host=go2rtc-dns-entry origin=https://homeassistant-dns-entry error="websocket: request origin not allowed by Upgrader.CheckOrigin"```

go2rtc.yaml:
```
api:
  listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  origin: "*"        # default "", allow CORS requests (only * supported)
```

any suggestions?

**Comment by AlexxIT** [comment]
You has some strange config. Maybe self signed certificate. I don't know what means xxx-dns-entry.

**Comment by docdawning** [comment]
I'm having this issue as well, but it seems like reports of this have been fairly sparce. Feels like a subtle config issue that users can resolve, if they know what the appropriate course of action is. Kind of a bigger IF there.
