### ISSUE TITLE
Install 1.9.3 error in china 

### ISSUE THREAD

**Issue by yuhuanfan** [AlexxIT/go2rtc#1182]
![IMG_9179](https://github.com/AlexxIT/go2rtc/assets/90470314/224fc713-ca24-4ae4-b665-58288afa684b)
![IMG_9180](https://github.com/AlexxIT/go2rtc/assets/90470314/349e0c5c-98ef-4258-89c4-0d0ae34d36c1)

**Comment by yuhuanfan** [comment]
$ docker pull ghcr.io/alexxit/go2rtc:latest 
it`s working! thanks!

**Comment by AlexxIT** [comment]
Default images (including Hass addon linked to Docker Hub).
But go2rtc also hosting docker images on GitHub.

**Comment by yuhuanfan** [comment]
thanks
