### ISSUE TITLE
Please make a restart button for the stream.

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#1187]
Please make a restart button for the stream. With the ability to use it in automation. Please. After several returns from two-way communication on hikvision, the sound becomes intermittent and quiet. Only rebooting Go2rtc helps. Thank you.

**Comment by AlexxIT** [comment]
It's the wrong way out of this situation. If there is a bug in the protocol - it should be fixed. But I don't have such cameras that I can personally study this problem.

**Comment by TokarevSergey** [comment]
> Это неправильный выход из этой ситуации. Если в протоколе есть ошибка – ее следует исправить. Но у меня нет таких камер, чтобы я мог лично изучить эту проблему.

Thank you for trying to help. But this problem is real. It’s just that if you connect several times to a stream with two-way audio “video, audio, microphone”, it freezes and does not exit it, and therefore after connecting “video, audio” the sound becomes quiet and is constantly interrupted. I thought if I added some command that stopped (interrupted) the stream with “video, audio, microphone”, then this would correct the situation using automation.
