### ISSUE TITLE
Snapshot URL

### ISSUE THREAD

**Issue by aegjoyce** [AlexxIT/go2rtc#119]
Sorry if I'm missing something obvious - how can I generate a snapshot URL from a stream? I note the MP4 component mentions snapshot generation but I'm unclear on how to access this...

> Module: MP4
> 
> Provides several features:
> 
> MSE stream (fMP4 over WebSocket)
> **Camera snapshots in MP4 format (single frame), can be sent to [Telegram](https://www.telegram.org/)**
> Progressive MP4 stream - bad format for streaming because of high latency, doesn't work in Safari

**Comment by AlexxIT** [comment]
You can find it in Web UI. It is called **frame**.

**Comment by aegjoyce** [comment]
Thanks. Unfortunately I'm not getting any image appear when I click on Frame, just a blank screen.

URL is http://192.168.1.244:1984/api/frame.mp4?src=3d_printer

Config:
```
streams:
  3d_printer:
    - ffmpeg:rtsp://username:password@192.168.1.101:554/stream1#video=mjpeg
```

**Comment by aegjoyce** [comment]
Figured it out, changed my config to:
```
streams:
  3d_printer:
    - rtsp://username:password@192.168.1.101:554/stream1
    - ffmpeg:rtsp://username:password@192.168.1.101:554/stream1#video=mjpeg
```
Frame and MP4 links are now working. Unfortunately the Frame link is incompatible with the octoprint Timelapse feature, I think it requires a static link to an image file rather than a still mp4 frame. Is this something I could achieve in go2rtc using ffmpeg and the -ss flag?

**Comment by AlexxIT** [comment]
You need to understand
- H264 codec > mp4 stream and mp4 snapshot
- MJPEG codec > MJPEG stream and jpeg snapshot

**Comment by aegjoyce** [comment]
Got it. Went back to the first config and tested `http://192.168.1.244:1984/api/frame.jpeg?src=3d_printer` - it works! Many thanks again

**Comment by maxi1134** [comment]
> You need to understand
> 
> * H264 codec > MP4 stream and MP4 snapshot
> * MJPEG codec > MJPEG stream and JPEG snapshot

Is this a hard limit? Or could we obtain a jpg still from a h264 stream in some fashion?

**Comment by AlexxIT** [comment]
@maxi1134 https://github.com/AlexxIT/go2rtc#module-mjpeg

**Comment by maxi1134** [comment]
![image](https://user-images.githubusercontent.com/1342643/204331641-1995cf30-43be-4fef-9cc4-9e2f7b721e74.png)
This is what I obtain doing that, the image seems broken

**Comment by AlexxIT** [comment]
@maxi1134 https://github.com/AlexxIT/go2rtc/issues/83#issuecomment-1286704116

**Comment by maxi1134** [comment]
@AlexxIT I've set the resolution to "2560x1920" but now get `04:05:01.216 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:114 > stream.AddConsumer error="couldn't find the matching tracks"`

With the  `- ffmpeg:rtsp://u:p@192.168.0.210/h264Preview_01_main#video=mjpeg` input.
While the following one works; `- ffmpeg:rtsp://u:p@192.168.0.210/h264Preview_01_main#video=h264`

**Comment by AlexxIT** [comment]
JPEG is a codec. It is not supported in WebRTC.
H264 is also a codec. It is not supported in MJPEG.
You need to choose the right codecs for the technologies you want to use.

You can also tell me what was your original resolution. I'll add a fix for it for MJPEG.
