### ISSUE TITLE
Tapo tapo:// method via internet?

### ISSUE THREAD

**Issue by Lockie85** [AlexxIT/go2rtc#1192]
Hey,

I wanted to check my understand which seems obvious now I think about it but I not at the time.

I assume if you use the tapo:// method, it needs to make calls to the internet and if these calls fail your entire system of Tapo cameras will go offline. I ask as it appears this is what happened to me last night.

I quickly shifted them to  rtsp:// and they instantly began to work. Has anyone else had this issue, especially in the last 24 hours?

**Comment by AlexxIT** [comment]
tapo not using Internet.
https://github.com/AlexxIT/go2rtc/issues/849

**Comment by Lockie85** [comment]
Ar ok, the internet note was just an assumption as I couldn't make sense of why the method would randomly stop working after being fine for weeks. Then when switching to rtsp:// it instantly worked.

**Comment by AlexxIT** [comment]
Answer in linked issue
