### ISSUE TITLE
unable to parse rtsp stream with special characters, invalid URL escape

### ISSUE THREAD

**Issue by si458** [AlexxIT/go2rtc#1208]
i cannot stream from my DVR using because the password has special characters in,
however it works no questions asked with VLC
`streams: parse "rtsp://admin:Dt4ICz%0X6sgvVG1@MYIPADDRESS:12345/cam/realmonitor?channel=5&subtype=0": invalid URL escape "%0X"`

**Comment by AlexxIT** [comment]
#1032
