### ISSUE TITLE
Multiple Streams?

### ISSUE THREAD

**Issue by eblieb** [AlexxIT/go2rtc#1209]
Using go2rtc with my YI-Hack cameras and Octoprint. Works well but if I open a stream on another device, it breaks the stream on the device i was watching on. Is there a way to have multiple streams of the same camera open at the same time? Not sure if I am missing something.

**Comment by AlexxIT** [comment]
This is main app feature - one input to multiple output. You need to provide more info about setup.

**Comment by eblieb** [comment]
http://192.168.100.10:1984/api/stream.m3u8?src=printer&mp4

This is the stream I am using to access the camera via octoprint.
