### ISSUE TITLE
Is there a correct way or possibly adding Logitech Circle View into go2rtc?

### ISSUE THREAD

**Issue by artoodetoo3301** [AlexxIT/go2rtc#1210]
Am I supposed to remove the cam from Homekit app, then pair it into Home Assistant?

I tried using the Homekit link shown in the go2rtc page, but it keeps giving total black screen, yet it show image in Home Assistant.
Since I cannot route it back into Homekit from Home Assistant, I cannot get it work.

**Comment by AlexxIT** [comment]
#1180

**Comment by artoodetoo3301** [comment]
> #1180

Hello, 
"You can change bitrate manually, but it works only for homekit source, not work for hass source."

Sorry I don't really understand this.
Should I pair it with Home Assistant Homekit Device integration or Pair it with some way in go2rtc?

**Comment by AlexxIT** [comment]
Doesn't matter. You always can get homekit source (pair to go2rtc) from hass source (pair to Hass).
