### ISSUE TITLE
Tuya HLS

### ISSUE THREAD

**Issue by Bsector** [AlexxIT/go2rtc#1216]
Hello everyone, one of my biggest frustrations is not being able to display images from my Tuya cameras directly in the home assistant. 

The only way I can do it is through onvif (but unfortunately not all cameras support it). 

I would like to know if this is possible using go2rtc or if someone has already managed to do this.

**Comment by AlexxIT** [comment]
Tuya is hundreds (maybe thousands) of cheap noname cameras. It is impossible to answer your question in a general way.
