### ISSUE TITLE
Problems playing local audio file on Dahua camera

### ISSUE THREAD

**Issue by diadehoy** [AlexxIT/go2rtc#1218]
Hello everyone, 

I'm trying to play locally stored audio files through my Dahua Cam's speaker but **I can't come up with the correct HTTP api command.** I'd appreciate if anyone can provide the correct syntax.  At the moment I am able to stream the camera's audio and video through Home Assistant/go2rtc.  

I'm also able to play a locally stored .wav file through the camera's speaker **ONLY** when I use go2rtc's "links" option in the browser interface.  Here's the log for this - 

```
17:12:16.678 DBG [ffmpeg] bin libavformat="60. 16.100" version=6.1.1
17:12:16.697 DBG [exec] run rtsp args=["ffmpeg","-hide_banner","-v","error","-readrate_initial_burst","0.001","-re","-i","/media/sounds/2.wav","-c:a","pcm_s16be","-ar:a","16000","-ac:a","1","-vn","-user_agent","ffmpeg/go2rtc","-rtsp_transport","tcp","-f","rtsp","rtsp://127.0.0.1:8554/d6456833f8b9c5bf0a2b097970fdf585"]
17:12:16.794 DBG [exec] run rtsp launch=96.702354ms
```

I've tried different commands through HA's terminal but with no success:
 `curl -X POST http://localhost:1984/api/streams\?dst\=porch_camera\&src\=ffmpeg:/media/sounds/2.wav%23audio\=pcma%23input\=file`

Here's my Config

```
streams:

  camera_porch:
    - rtsp://admin:password@172.16.0.5:554/cam/realmonitor?channel=1&subtype=0
    
log:
  level: debug
  exec: debug
```

when I activate the camera's stream through go2rtc, here's the log info

```
{
  "producers": [
    {
      "id": 2,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "172.16.0.5:554",
      "url": "rtsp://admin:password@172.16.0.5:554/cam/realmonitor?channel=1\u0026subtype=0",
      "sdp": "v=0\r\no=- 2251984979 2251984979 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:15.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0032;sprop-parameter-sets=Z00AMukAYAGzQgAAB9IAAOqcCAA=,aOqPIAA=\r\na=recvonly\r\nm=audio 0 RTP/AVP 97\r\na=control:trackID=1\r\na=rtpmap:97 MPEG4-GENERIC/64000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1108\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=5\r\na=rtpmap:8 PCMA/8000\r\na=sendonly\r\n",
      "user_agent": "go2rtc/1.9.4",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, MPEG4-GENERIC/64000",
        "audio, sendonly, PCMA/8000"
      ],
      "receivers": [
        {
          "id": 4,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 50,
            "profile": "Main"
          },
          "childs": [
            6,
            5
          ],
          "bytes": 3775285,
          "packets": 2659
        },
        {
          "id": 7,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 64000
          },
          "childs": [
            8
          ],
          "bytes": 68410,
          "packets": 297
        }
      ],
      "bytes_recv": 3879263
    }
  ],
  "consumers": [
    {
      "id": 1,
      "format_name": "mse/fmp4",
      "protocol": "ws",
      "remote_addr": "172.30.32.2:56186 forwarded 192.168.1.45, 172.30.32.1",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
      ],
      "senders": [
        {
          "id": 6,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 50,
            "profile": "Main"
          },
          "parent": 4,
          "bytes": 3775285,
          "packets": 2659
        },
        {
          "id": 8,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 64000
          },
          "parent": 7,
          "bytes": 68410,
          "packets": 297
        }
      ],
      "bytes_send": 3874983
    },
    {
      "id": 3,
      "format_name": "webrtc",
      "protocol": "ws+udp",
      "remote_addr": "192.168.1.45:56497 prflx",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, VP9, H264, AV1",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, L16, PCML"
      ],
      "senders": [
        {
          "id": 5,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video"
          },
          "parent": 4,
          "bytes": 3775285,
          "packets": 2659
        }
      ],
      "bytes_send": 3815068
    }
  ]
}
```

**Comment by diadehoy** [comment]
**Fixed the issue**, ridiculous mistake.

The http command - `curl -X POST http://172.16.1.2:1984/api/streams\?dst\=camera_porch\&src\=ffmpeg:/media/sounds/2.wav%23audio\=pcma%23input\=file`

Instead of using "camera_porch" I had written "porch_camera", now the command plays the audio file through the speaker just fine.

One last issue that I'm having is that I must specify the exact IP address instead of localhost.  The terminal returns a **curl: (7) Failed to connect to localhost....**

Is there an easy fix? As of now I'm just happy I solved the other issue.

**Comment by dagleaves** [comment]
Curl failing to connect to localhost is a network routing issue on your machine, not anything with go2rtc. 

* Ensure you are on the same server as go2rtc (localhost will point to whatever machine you're running the command on)
* Consider any weird network set up you may have
  * Running inside WSL2 (Windows), inside a Docker container / VM, etc

**Comment by diadehoy** [comment]
> Curl failing to connect to localhost is a network routing issue on your machine, not anything with go2rtc.
> 
> * Ensure you are on the same server as go2rtc (localhost will point to whatever machine you're running the command on)
> * Consider any weird network set up you may have
>   
>   * Running inside WSL2 (Windows), inside a Docker container / VM, etc

Thank you for the reply, I'm running Home Assistant on a VM inside of Proxmox.  I'm using HA's built in terminal add-on when I write "localhost" in the http address.

**Comment by Skyline643** [comment]
Interesting topic. I'm looking to get the right API or URL to play stored audioclips on the Dahua camera's (TiOC 2.0), but I'm not able to find the right one. Maybe you can help me.

I found this, but this only plays the default siren, not an uploaded audio clip?

Play sound (siren)
ON:
http://ipaddress/cgi-bin/coaxialControlIO.cgi?action=control&channel=1&info[0].Type=2&info[0].IO=1
OFF:
http://ipaddress/cgi-bin/coaxialControlIO.cgi?action=control&channel=1&info[0].Type=2&info[0].IO=2
