### ISSUE TITLE
[Question] Can 2 way talk be supported along with transcoding h.265 -> h.264

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#123]
I have a camera which supports Onvif Profile T but only supports h.265 for the main stream. Is there a way to transcode the stream while also keeping the 2 way talk ability?

**Comment by AlexxIT** [comment]
Yes. It can be player with MSE for video/audio and WebRTC only for mic.

**Comment by NickM-27** [comment]
confirmed this setup is already working by just adding an h264 stream
