### ISSUE TITLE
How to update on a raspberry pi 4

### ISSUE THREAD

**Issue by rmp63526** [AlexxIT/go2rtc#1242]
Hi, how do I perform an update 1.9.5 version on a Raspberry Pi 4?
I have installed the 1.8.5 version

**Comment by andi34** [comment]
v1.9.5 is not even available.
In general: stop go2rtc if it's running and replace the binary. Now start go2rtc again.
There might be variations, for example I am starting it via a service which I would need to stop.

**Comment by AlexxIT** [comment]
1.9.5 does not exist at the moment. The update depends on the selected installation method.

**Comment by rmp63526** [comment]
Thanks for trying to help. I meant the v 1.9.4.
Unfortunately it is a bit too complicated for me how to update it. I installed it through a video on youtube. I am not familiar with the Linux system and need a step by step guide.

**Comment by andi34** [comment]
What's your output of `which go2rtc ` via terminal?

**Comment by rmp63526** [comment]
@andi34 sorry, i'm a noob.
What do you want me to type in the terminal

**Comment by andi34** [comment]
`which go2rtc`

**Comment by rmp63526** [comment]
I installed everything new. To much for me.
