### ISSUE TITLE
Fix mjpeg source for Foscam G2 camera

### ISSUE THREAD

**Issue by gambalaya** [AlexxIT/go2rtc#1258]
I have a Foscam G2 camera configured to supply an mjpeg secondary stream from url http://x.x.x.x/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=xxx&pwd=xxx  , which works directly in Chrome browser and VLC. When attempting to use as a go2rtc source there is continuous logging of malformed MIME header: missing colon messages (and no output). The camera is indeed producing a malformed MIME header as seen with curl -i response:
```
HTTP/1.1 200 OK
Content-type:multipart/x-mixed-replace;boundary=ThisString

--ThisString
--ThisString
Content-type:image/jpeg
Content-Length:32514
```
Since other apps like Chrome and VLC can handle the camera stream, any chance go2rtc can ignore malformed lines? I can see the error is coming from "mustHaveFieldNameColon" function in golang source - https://github.com/golang/go/blob/master/src/net/textproto/reader.go per RFC 7230.
Thanks.

**Comment by AlexxIT** [comment]
I don't know if it's difficult to give you access to the stream. It would make it a lot easier to fix.

**Comment by gambalaya** [comment]
Thanks, I have made the stream available, will DM the url to you via discord.

**Comment by gambalaya** [comment]
I rebuilt from the latest master and can confirm the camera fix works from my end - thanks for such an amazing quick response! Closing the issue as fixed in v1.9.5.

**Comment by AlexxIT** [comment]
You don't needs to rebuild anything manually
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#go2rtc-dev-version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.5

**Comment by gsainsbury86** [comment]
I think I'm having a similar error with the same model of camera. The MSE stream works for the first couple of seconds (and will again after a refresh) and then freezes. This is the error I see in the go2rtc log.


`undefined error=read tcp 10.90.0.79:48030->129.127.38.55:88: i/o timeout url=rtsp://user:pass!@129.127.38.55:88/videoSub caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:170`
