### ISSUE TITLE
HTML Coding using go2rtc Links: Examples?

### ISSUE THREAD

**Issue by darethehair** [AlexxIT/go2rtc#126]
I am totally impressed by go2rtc, and have started to use it at our non-profit thrift store to display a web page showing at outside view from one of our Swann security cameras -- which I then Chromecast to a remote TV/monitor.  Next step: creating some HTML to display a 'mosaic' of thumbnail images from each of our 16 Swann cameras on a single page, which can then be clicked on to display the desired full-screen stream.

To get started, I thought of using the 'frame' option of go2rtc to get still-image snaps, put into some HTML table containing the links to the various cameras.  Seems simple, but I am not getting any images so far.  Maybe somebody has some starter HTML for me to start with?  Thanks!

**Comment by AlexxIT** [comment]
Page with mosaic will be in next version. I'm working on it.

**Comment by AlexxIT** [comment]
Supported in [v0.1-rc.5](https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.5)
Support width URL param with pixels `&width=320px` (default) or percents `&width=25%`.
