### ISSUE TITLE
ngrok client deprecated for HAOS

### ISSUE THREAD

**Issue by syntesys87** [AlexxIT/go2rtc#1260]
Hello all,

is there anyone that configured recently ngrok in HAOS? I see that the plugin in the repository is deprecated, but I would configure it because sometimes I use my mobile connection at home. Can someone give me a guide to configure it or an alternative method to use?
I have HAOS configured with Nabu Casa.

Thank you!

**Comment by AlexxIT** [comment]
This project is not related to your question
