### ISSUE TITLE
Reolink E1 Zoom and Video Doorbell (POE) - no audio in WebRTC mode, only MSE mode. go2rtc v1.9.4

### ISSUE THREAD

**Issue by ASAujla** [AlexxIT/go2rtc#1267]
Reolink E1 Zoom and Video Doorbell (POE) - no audio in WebRTC mode, only MSE mode. go2rtc v1.9.4

I have seen issues where lack of audio has been reported for go2rtc version v1.2.0 I believe. I have been using the Frigate Home Assitant add-on for a while with go2rtc v1.5.0, but I've noticed that me E1 Zooms do no have any audio in WebRTC mode, only in MSE mode. I am not tlking about 2-way audio here, which I understand will not work as Reolink's implemention is proprietary. I am talking about camera audio.

This issue only came to light today as I recently purchased a Reolink Video Doorbell (POE) and I've been messing around trying to get it to work with the WebRTC card. The same issue exists. Camera audio only works in MSE mode, not WebRTC mode. Talkback, however, works but only in WebRTC mode and not MSE mode.

I am using a Conditional Card linked to a toggle helper to control mic access. When the toggle is on, the mic is enabled by setting "media: video, audio, microphone" as follows in the WebRTC card:
`type: custom:webrtc-camera`
`url: rtsp://admin:pass@192.168.X.X:554/h264Preview_01_sub`
`media: video, audio, microphone`
`mode: webrtc`
`muted: false`

When the toggle is off, the mic is disabled by setting "media: video, audio" as follows in the WebRTC card:
`type: custom:webrtc-camera`
`url: rtsp://admin:pass@192.168.X.X:554/h264Preview_01_sub`
`media: video, audio`
`mode: webrtc`
`muted: false`

I updated to go2rtc v1.9.4 but I still have the same issues.

I prefer to use direct URLs for each camera in my dashboard rather than HA or Frigate cameras as the latency is amost instantaneous this way.

Any ideas if there is a go2rtc issue or whether I need to do things differently?

**Comment by dagleaves** [comment]
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#codecs-madness

Ensure that you add an ffmpeg stream to transcode the audio to OPUS for WebRTC to play it. Most cameras will use AAC, which cannot be played through WebRTC.

```
Camera:
  - http://........
  - ffmpeg:Camera#audio=opus
 ```

**Comment by AlexxIT** [comment]
@dagleaves thanks. Codecs madness is a right link for this issue.

All Reolink cameras uses AAC sound by default without any setting to change it on camera side. You should use transcoding.
