### ISSUE TITLE
[Feature] Add option to add timestamp to feed

### ISSUE THREAD

**Issue by algoz098** [AlexxIT/go2rtc#127]
Would be good for a some type of cameras which do not have it, to be able to add timestamp to the feed.

Some research indicate it would be easy to do it with ffmpeg, most of the cases i imagine would be in using ffmpeg too.

Is this possible and reasonable?

Would love to see it.

**Comment by NickM-27** [comment]
In case you're not aware this would involve decoding the stream, adding the timestamp, and reencoding the stream (via ffmpeg) which is a lot of work for your cpu and will add latency. 

Also worth noting is that go2rtc already supports ffmpeg commands so you can do this yourself today.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/402#issuecomment-1606026909

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
