### ISSUE TITLE
Stream lags behind on slow connection

### ISSUE THREAD

**Issue by franconoronha** [AlexxIT/go2rtc#1277]
Hello, I have noticed that my MSE streams start to lag behind when I use chrome's network throttling. I would like to know if that's intended behavior, or if it can be configured so that streams use only latest data.

**Comment by AlexxIT** [comment]
This is a known behavior and a major disadvantage of MSE streams. It is very channel sensitive and only works well if the data channel is larger than the bitrate of the video. This is a TCP connection and it is not capable of losing data.

**Comment by dagleaves** [comment]
@franconoronha See https://github.com/AlexxIT/go2rtc/issues/1308#issuecomment-2469527200
