### ISSUE TITLE
SDP: invalid value vana

### ISSUE THREAD

**Issue by doosarinikhil** [AlexxIT/go2rtc#1278]
Hi,
I am trying to convert the RTSP stream to WebRTC.
But I am getting errors.   streams: SDP: invalid value `vana`
I tried the RTSP URL in the VLC player it is working fine, but with go2rtc, I am getting an error

I added the stream URL using the web interface in the temporary stream option.
and went to the streams tab and clicked on the stream link redirected to the WebRTC player page but got the above error 

![log](https://github.com/user-attachments/assets/b0e95db6-c59b-4dc1-8c0f-f77179c255ac)

![log](https://github.com/user-attachments/assets/dbc1910f-3323-48a1-ab5d-d96b18ec80c0)

**Comment by AlexxIT** [comment]
Can you provide text, not screens?

**Comment by doosarinikhil** [comment]
Trace log file.
[log.txt](https://github.com/user-attachments/files/16387068/log.txt)

**Comment by AlexxIT** [comment]
Interesting. What is your camera model?

**Comment by doosarinikhil** [comment]
Hello Alex,

Thank you for your quick reply. Please find the camera models below:
VICON-V2005D-W28IR
VICON-V2005B-W313MIR

If you need any other information, please let me know. Thank you.
Best Regards,
Nikhil

**Comment by AlexxIT** [comment]
Fixed in latest master version

**Comment by doosarinikhil** [comment]
Hello Alex,
Good evening thank you for fixing the issue, I will test it and about you.

Thank you,
Best Regards,
Nikhil

**Comment by doosarinikhil** [comment]
Hello Alex,

Good morning. We cloned the latest code and tested it, and it is working fine now. If we notice any issues, we will update you again. Thank you, once again for the quick fix and help. Have a good day.

Best Regards,
Nikhil.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.5
