### ISSUE TITLE
Remote webRTC connection doesn't worth with Reolink

### ISSUE THREAD

**Issue by mgoh99** [AlexxIT/go2rtc#1281]
- I can get a webrtc remote feed from my Unifi cameras but not from my Reolink POE Doorbell.  
- Reolink webrtc works locally 
- Reolink only work MSE remotely 
- Even with a wireguard local tunnel, I can't get the reolink webRTC to work.  

Here's my config 
```
streams:
	Front_door:
	#reolink POE doorbell
           - rtsp://admin:90kitties@192.168.1.xx:554/h264Preview_01_main
           - "ffmpeg:Front_door#audio=opus"
        Unfi: rtspx://192.168.1.1:7441/xxxxxxxxxx
	#unifi g3 instant
``` 

What would cause that difference?  I'd understand if webRTC didn't work for any cameras but it seems odd that it's only for the Reolink it's broken.

**Comment by AlexxIT** [comment]
Well. If "Reolink webrtc works locally" + "Unifi webrtc works remote" = probably Reolink bitrate too high for WebRTC UDP connection. It's known problem for 2K+ and 4K+ streams. WebRTC TCP should work fine, but you needs to setup it properly. It can be not easy task.

**Comment by mgoh99** [comment]
Thanks. You were right. Switching to lower res sub stream fixed it. Still periodically choppy on RTC vs MSE but it’s a start!  Thanks for your amazing work on this software

—
Mark Goh
________________________________
