### ISSUE TITLE
Combine multiple streams

### ISSUE THREAD

**Issue by utya** [AlexxIT/go2rtc#1286]
Добрый день. Спасибо за продукт.
Есть два вопроса
Можно сделать что-то типа такого
https://stackoverflow.com/questions/15391368/how-to-combine-multiple-ffmpeg-streams-into-a-single-4x4-collage
Взять несколько потоков и соединить в один колаж

И второй вопрос, есть кастоманая камера которая умеет отдавать jpeg
можно ли средствами go2rtc заходить на неё раз в секунду, забирать с неё jpeg и делать такой стрим? 1 кадр/c

_________________
Hello. Thank you for the product.

I have two questions:

1. Can we do something like this: [StackOverflow Link](https://stackoverflow.com/questions/15391368/how-to-combine-multiple-ffmpeg-streams-into-a-single-4x4-collage)? Take several streams and combine them into a single collage.

2. I have a custom camera that can output JPEG. Is it possible to use go2rtc to access it once per second, retrieve the JPEG, and create such a stream? 1 frame/second.

**Comment by AlexxIT** [comment]
1. https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-exec
2. https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-http

**Comment by utya** [comment]
sample for combine collage
  mosaic:  exec:ffmpeg -i rtsp://strem1 -i rtsp://stmre2 -i rtsp://strem3 -i rtsp://strem4 -filter_complex "[0:v] setpts=PTS-STARTPTS, scale=320x240 [a]; [1:v] setpts=PTS-STARTPTS, scale=320x240 [b]; [2:v] setpts=PTS-STARTPTS, scale=320x240 [c]; [3:v] setpts=PTS-STARTPTS, scale=320x240 [d]; [a][b][c][d]xstack=inputs=4:layout=0_0|320_0|0_240|320_240[out]" -map "[out]" -c:v libx264 -f rtsp {output}

**Comment by AlexxIT** [comment]
There is also hardware version for xstack. But I haven't time to research it yet.
https://github.com/AlexxIT/go2rtc/issues/823
