### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Chandramouli-P** [AlexxIT/go2rtc#1287]
Hello Alex,

Good morning. I am sending this issue with continuation to the issue #1278 

1) When I am trying to render H265 stream on Chrome browser in Windows OS, getting this below warning message couple of times:

```
warn: undefined error=read tcp 192.168.1.42:49887->172.20.0.215:554: wsarecv: An existing connection was forcibly closed by the remote host. url=rtsp://ADMIN:Admin123@172.20.0.215:554/stream1 caller=C:/Users/go/go2rtc-app/go2rtc/internal/streams/producer.go:170
```

After sometime, the stream is rendering successfully. If I load the same stream again in the same browser in new tab, it is loading immediately. 

2) Also, I noticed that the stream is getting hang-up (strucked)  after sometime. I am not sure whether it is camera issue or framework issue. 

Any help would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by AlexxIT** [comment]
"An existing connection was forcibly closed by the remote host". Remote host is RTSP camera. Go2rtc can't do anything with that.

**Comment by Chandramouli-P** [comment]
Thank you Alex for your reply.
