### ISSUE TITLE
New Multiple Stream on Page Option: Questions

### ISSUE THREAD

**Issue by darethehair** [AlexxIT/go2rtc#129]
Regarding the new enhancement "New stream page with support multiple stream on page with automatic or manual technology selection": like it a lot, but confused on a few issues:

1) When I multi-select on some cameras, and click the top 'stream' button for all, I get a URL that looks like this (sample):

http://192.168.100.60:1984/stream.html?src=deck&src=garage&mode=webrtc,mse,mp4,mjpeg

Since I really only need the 'webrtc' option, I click off the others and resubmit my request:

http://192.168.100.60:1984/stream.html?src=deck&src=garage&mode=webrtc

However, this presents non-functioning video playback windows.  Instead, this is what actually works as I intend:

http://192.168.100.60:1984/stream.html?src=deck&src=garage&stream=webrtc

Note the change from 'mode=' to 'stream='.  Am I misunderstanding what is expected?

2) The 'width' options have been tricky for me to get working.  Should this (sample) URL force the (two) video streams to be only 100 pixels wide?

http://192.168.100.60:1984/stream.html?src=deck&src=garage&stream=webrtc&width=100px

Thanks!

**Comment by AlexxIT** [comment]
Maybe webrtc doesn't works for you. `stream=webrtc` means nothing. Default settings will be used (webrtc,mse,mp4,mjpeg).

100px means:
- when you have page 200px - it will show 2 columns
- when you have page 300px - 3 columns
- when you have page 199px - 1 column with 199px width
- when you have page 299px - 2 columns with 149px width each

**Comment by darethehair** [comment]
Why I believed that 'webrtc' was working for me is that the previous version of go2rtc had a 'webrtc' option which worked fine:

http://localhost:1984/webrtc.html?src=deck

I assumed that this would carry over (in meaning/purpose) to the new interface.  Clicking the 'info' button (on the older version) when using the 'webrtc' option produces this:

```
[
  {
    "media:0": "video, sendonly, 96 H264/90000",
    "media:1": "audio, sendonly, 8 PCMA/8000",
    "receive": 6882313,
    "remote_addr": "192.168.100.73:554",
    "send": 0,
    "track:0": "8 PCMA/8000, sinks=1",
    "type": "RTSP client producer",
    "url": "rtsp://192.168.100.73/stream1/",
    "user_agent": "go2rtc/0.1-rc.4"
  },
  {
    "remote_addr": "udp4 host 172.17.0.1:44226",
    "send": 6939891,
    "type": "WebRTC server consumer",
    "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0"
  }
]
```

**Comment by AlexxIT** [comment]
Because you using FF #120

**Comment by darethehair** [comment]
> Because you using FF #120

You are correct!  Thanks for pointing this out to me.  This works in Chrome but not Firefox (for example):

http://localhost:1984/stream.html?src=deck&mode=webrtc
