### ISSUE TITLE
MSE player streaming slow

### ISSUE THREAD

**Issue by techsupportsardonyx** [AlexxIT/go2rtc#1308]
**System info:**

1. OS version : Windows 11 pro - 64 bit
2. Processer : Intel(R) Core (TM) i7-8809G CPU @ 3.10 GHZ (8 CPUs)
3. Ram : 32 RAM

- Dahua Camera via RTSP Stream
- go2rtc running in Golang
- go2rtc.yaml

```
streams:
        test: rtsp://admin:admin123@172.25.10.34:554/cam/realmonitor?channel=1&subtype=0
```

Browser streams tried
`http://172.25.10.28:1984/stream.html?src=test&mode=webrtc,mse`

When adding the same camera using WebRTC and MSE, the live view in the MSE player streaming speed slows down after running for a long duration

**Comment by techsupportsardonyx** [comment]
AlexxIT, Could you check the bug ? May i know the status of the bug

**Comment by techsupportsardonyx** [comment]
AlexxIT, Could you check the bug ? May i know the status of the bug

**Comment by AlexxIT** [comment]
It's a feature of the MSE technology.

**Comment by dagleaves** [comment]
@techsupportsardonyx Noticed the same thing. Resolved it by forcing the player to jump to current time if it got over a second behind. 

https://github.com/EscapeOracle/go2rtc/blob/554f9147a050a05a967836f25b11e02acc790354/www/stream.html#L58-L76
