### ISSUE TITLE
WHIP endpoint fails on CORS preflight requests

### ISSUE THREAD

**Issue by krokosik** [AlexxIT/go2rtc#1311]
I would like to develop an app allowing for ingesting the data from the user camera into my go2rtc server. I find the software amazing and extremely useful and I have managed to set it up for uploading my camera feed from OBS using WHIP.

However, the WHIP endpoint does not seem to work in the browser, which is IMO the primary purpose of using it. In particular, the POST request that sends the SDP offer is never sent, because the server does not properly respond to the preflight OPTIONS request, yielding the following error in the console:

> Access to fetch at 'http://localhost:1984/api/webrtc?dst=camera1' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

For testing, I tried the Allow CORS extension, but it just produces another error:

> Access to fetch at 'http://localhost:1984/api/webrtc?dst=camera1' from origin 'https://web.whip.eyevinn.technology' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

What I tried is two example WHIP client implementations, available in a release [here](https://github.com/Softvelum/webrtcjs) as well as [another one](https://www.npmjs.com/package/@eyevinn/whip-web-client) available also as an online [demo](https://web.whip.eyevinn.technology/).

According to the linked WHIP/WISH [spec](https://datatracker.ietf.org/doc/draft-ietf-wish-whip/) (last paragraph of sesction 4.2):

> The WHIP endpoints MUST support OPTIONS requests for Cross-Origin
   Resource Sharing (CORS) as defined in [FETCH].  The "200 OK" response
   to any OPTIONS request SHOULD include an "Accept-Post" header with a
   media type value of "application/sdp" as per [W3C.REC-ldp-20150226].

### My config

Pretty simple, no matter what I set in the `cors` option, the error stays the same:
```yml
api:
  listen: ":1984"
  cors: "*"

streams:
  camera1:

webrtc:
  listen: ":8555"
  candidates:
    - stun:8555
```

### Minimal working example

I guess if the [demo](https://web.whip.eyevinn.technology/) is able to work properly, then it will be fine. I would like to help, but have zero knowledge of Go unfortunately.

**Comment by AlexxIT** [comment]
Check docs about API module
https://github.com/AlexxIT/go2rtc#module-api

**Comment by krokosik** [comment]
I've read it several times, did not find anything CORS related apart from the setting that I already have. Could you please be more specific?

**Comment by AlexxIT** [comment]
```yaml
origin: "*"        # default "", allow CORS requests (only * supported)
```

**Comment by krokosik** [comment]
As I said and can be seen in the included config, I already have this setting. Both the asterisk and default option do not work as they do not change the fact that the backend doesnt handle CORS preflight requests, i.e. HTTP requests of type OPTIONS

**Comment by krokosik** [comment]
The WHIP standard requires dispatching a POST request, while your CORS solution only works for GET requests. Other types require preflight handling with additional headers, implementing the functionality that I quoted in my original comment.

Perhaps this package might be of help?
https://github.com/rs/cors

**Comment by AlexxIT** [comment]
You don't have this option in your config.

**Comment by krokosik** [comment]
Oh damn. You're right sorry for the confusion. It seems to work now.
