### ISSUE TITLE
Option to remove watermarks

### ISSUE THREAD

**Issue by HVR88** [AlexxIT/go2rtc#1312]
Offer an option to remove any watermarks added by go2rtc, such as "MSE" on the top right. The watermarks are suitable for debug purposes, but not for production.

Reference: https://github.com/blakeblackshear/frigate/discussions/6656

**Comment by AlexxIT** [comment]
The go2rtc interface is focused at administrative and debugging functions.
Other projects deal with front-end - Frigate, Hass custom cards and others.

**Comment by HVR88** [comment]
Ok...

So are you saying go2rtc is not adding any watermark or text?

If so, then in Home Assistant, is the MSE text added instead by the Web2rtc HAC integration? If so, I can redirect this issue to the appropriate place.

**Comment by HVR88** [comment]
I just played the stream directly from the go2rtc webUI and the "MSE" text appears on the video. So it looks like that's added by go2rtc. Making it impossible for any front end to remove it unless there's a parameter to disable it or provide a stream without it.

![Screenshot 2024-08-17 at 1 37 10 PM](https://github.com/user-attachments/assets/0a97fd74-6772-4f70-a5a8-1ee81c4eb80a)

**Comment by HVR88** [comment]
I'll attribute this to a language barrier.

`Hide mode label

style: '.mode {display: none}'`

**Comment by AlexxIT** [comment]
`stream.html` is part of go2rtc WebUI. It has mode label (ex. MSE). And don't has easy options for remove this label. 

WebRTC Camera integration also has this label. And has options for remove this label.
