### ISSUE TITLE
websocket: request origin not allowed by Upgrader.CheckOrigin

### ISSUE THREAD

**Issue by toptensoftware** [AlexxIT/go2rtc#1314]
I'm trying to pull a webrtc feed from go2rtc into a page hosted on a different local host server, but getting cross origin errors:

```
16:26:17.739 ERR github.com/AlexxIT/go2rtc/internal/api/ws/ws.go:105 > host=localhost:1984 origin=http://localhost:3000
 error="websocket: request origin not allowed by Upgrader.CheckOrigin"
```

For the moment, I'm just testing with a copy of the webrtc feed page from go2rtc re-hosted in another server and I've hardcoded the websocket URL like so:

```
new WebSocket("ws://localhost:1984/api/ws?src=stream_1&media=video");
```

In this particular example it's all localhost but different ports.  Down the track I was hoping to get this working for different ip addresses too.  In case it matters I only need this to work on the local network.

Is there any workaround for this?

(fwiw: very new to RTC, I hope this isn't a stupid question :)

**Comment by ausfas** [comment]
> Please ignore, found solution was to add to go2rtc.yaml
> 
> ```
> api:
>     origin: "*"
> ```

Thanks after two days of struggle found this link.
