### ISSUE TITLE
Setting up UDP RTSP stream

### ISSUE THREAD

**Issue by rodenj1** [AlexxIT/go2rtc#132]
This is probably more of an issue with my understanding how to set up streams with parameters.  I am trying to get grab a stream from the nest-rtsp project that keeps a persistent video stream for Nest cameras.  However, it only supports UDP output.  So I am trying to get go2rtc to pull the stream.  Here is the config.  Note: the options came from the nest-rtsp project as frigate recommendations.

```
streams:
  doorbell: ffmpeg:rtsp://x.x.x.x:554/doorbell#raw=-rtsp_transport udp -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
```  

Here is the debug output
```
go2rtc     | 22:01:11.289 WRN github.com/AlexxIT/go2rtc/cmd/mp4/ws.go:41 > error="sources unavailable: 1"
go2rtc     | 22:01:11.289 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:115 > error="sources unavailable: 1"
go2rtc     | 22:01:11.294 DBG [streams] probe producer url=ffmpeg:rtsp://x.x.x.x:554/doorbell#raw=-rtsp_transport udp -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1
```

Here is the error from nest-rtsp
```
nest-rtsp  | 2022-12-11T22:01:11.397Z rtsp-streaming-server:ClientServer ::ffff:x.x.x.x:32938 - we dont support tcp, sending 504: 'rtsp://192.168.0.180:554/doorbell/streamid=0'
```
So even though I think I am passing the UDP flag, it looks like it is still trying TCP.  Any help would be greatly appreciated!

**Comment by AlexxIT** [comment]
You need to use `exec` source and write full ffmpeg command manually.

**Comment by rodenj1** [comment]
Perfect!  I got it working, but I was wondering if you could output part of this.  I essentially was looking at the debug output for exec and figured out the {output}.  Is there a more correct way of doing this, or am I on the right track here?

```
doorbell: exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -fflags +genpts+discardcorrupt -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport udp -use_wallclock_as_timestamps 1  -strict experimental -i rtsp://localhost:554/doorbell -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}
```

**Comment by AlexxIT** [comment]
Maybe I will add rtsp_transport as ffmpeg param in the future. But you did everything right.

**Comment by poblabs** [comment]
@rodenj1 I'm trying to figure this out now and it's not working for me. I think maybe I have {output} wrong? Do I have to actually put something there like `rtsp://192.168.0.123:8554/doorbell` ?

**Comment by rodenj1** [comment]
Sorry, I have been on the road.  Here is what I used...
`streams:
  nest_doorbell: exec:ffmpeg -avoid_negative_ts make_zero -hide_banner -v error -fflags nobuffer -flags low_delay -fflags +genpts+discardcorrupt -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport udp -use_wallclock_as_timestamps 1  -strict experimental -i rtsp://localhost:554/doorbell -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}
  nest_front_driveway: exec:ffmpeg -avoid_negative_ts make_zero -hide_banner -v error -fflags nobuffer -flags low_delay -fflags +genpts+discardcorrupt -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport udp -use_wallclock_as_timestamps 1  -strict experimental -i rtsp://localhost:554/front_driveway -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}`

I had the same problem with the RTSP stream continuing to work.  I finally gave up and started replacing all my cameras so I could have local streams.
