### ISSUE TITLE
【solved】Homeassistant Add-on can not install go2rtc

### ISSUE THREAD

**Issue by ssgy1312** [AlexxIT/go2rtc#1320]
日志: homeassistant.components.hassio
来源: components/hassio/websocket_api.py:134
集成: Home Assistant Supervisor (文档, 问题)
首次发生: 14:22:12 (1 全部发生)
上次记录: 14:22:12

Failed to to call /addons/a889bffc_go2rtc/install - Can't install alexxit/go2rtc:1.9.4: 404 Client Error for http+docker://localhost/v1.43/images/alexxit/go2rtc:1.9.4/json: Not Found ("No such image: alexxit/go2rtc:1.9.4")

**Comment by AlexxIT** [comment]
Probably you have problems with connection to Docker Hub in your country. 
Images also available on GitHub. But you should to install them manually.

**Comment by felipecrs** [comment]
Yeah, try the following in Terminal add-on with Protection disabled:

```
docker pull alexxit/go2rtc:1.9.4
```

**Comment by AlexxIT** [comment]
Or this
https://github.com/AlexxIT/go2rtc/pkgs/container/go2rtc

**Comment by felipecrs** [comment]
Yes, but to use that with the add-on he would need to clone https://github.com/AlexxIT/hassio-addons in /addons/ and patch config.yaml to point to the ghcr.io image.

**Comment by AlexxIT** [comment]
I know. Don't want to change it from docker to github in hass-addons. Docker pulls counter now more than 1M.

**Comment by felipecrs** [comment]
Yes yes. Also, someday some countries may impose restrictions on ghcr.io as well (or the opposite). Who knows.

I think it would make more sense to have a docker hub mirror configured in your HAOS.

It's on /etc/docker/daemon.json. If it's proven useful, I could build an add-on that automatically sets it on system initialization.

**Comment by skrashevich** [comment]
> I think it would make more sense to have a docker hub mirror configured in your HAOS.
> 
> It's on /etc/docker/daemon.json. If it's proven useful, I could build an add-on that automatically sets it on system initialization.

I've already had to do that :)
https://t.me/homassistant/764791: for HAOS < 13.0

**Comment by ssgy1312** [comment]
> Yeah, try the following in Terminal add-on with Protection disabled:
> 
> ```
> docker pull alexxit/go2rtc:1.9.4
> ```

yes，it works。after pull manul ，it succeed
