### ISSUE TITLE
Tapo protocol alone results in 200 error

### ISSUE THREAD

**Issue by gabriel403** [AlexxIT/go2rtc#1325]
When trying to use the tapo protocol 
```
streams:
  bedroom_hd:
  - tapo://cloudpassword@192.168.0.252
```

and using the steam from go2rtc I have a strange error

```
mse: streams: Expected StatusCode to be 401, received 200
```

**Comment by dgibbs64** [comment]
I think its related to the cloud password issue that's detailed in this thread. https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551
