### ISSUE TITLE
Question: Conversion of RTSP or RPSPS to ONVIF

### ISSUE THREAD

**Issue by prokopp80** [AlexxIT/go2rtc#1329]
Hi team, 
sorry , I am not an expert on this topic but I wonder if I can somehow use go2rtc to convert RTSP to ONVIF ?  
I have Unifi cameras and I need to convert one cam to ONVIF since Unifi doesn't support this protocol.

Thank you,
Br. Petr

It this doesnt work - are you aware how to achieve this?

**Comment by xlucasfelix** [comment]
Hello! Did you manage to get around this issue? I'm looking to do something like this for a project!

**Comment by AlexxIT** [comment]
#1036
