### ISSUE TITLE
Two way audio cameras

### ISSUE THREAD

**Issue by adrienfrugier** [AlexxIT/go2rtc#1333]
Hello, 

First of all thanks for all the work ! 

Also, I have reolink CX410, do you confirm the two way audio doesn't work ? 
And do you have a list of working cameras with two way audio ? Or something to watch in the caracteristics of the camera ? 

Thanks again

**Comment by AlexxIT** [comment]
There are, tens and even hundreds of thousands of camera models in the world. Plus there are countless unnamed cameras from China. Plus depending on the firmware of the camera, its functionality may vary. Including Reolink cameras. I think it's impossible to collect a reliable list.

You can view the functionality of your camera in the go2rtc WebUI (info/probe).
