### ISSUE TITLE
Tapo tc85 firmware 1.2.21 401 Unauthorized

### ISSUE THREAD

**Issue by ppfeister** [AlexxIT/go2rtc#1340]
TP-Link is slowly rolling out 1.2.21 for certain Tapo cameras, the tc85 included. While the tapo:// protocol works on our cameras running the prior version, cameras that have received this automatic update don't seem to function. These cameras are receiving the typical `streams: 401 Unauthorized" stream=streamxyz`.

Note that both the md5 and sha256 methods were attempted.

Curious if anyone else has experienced this, and assuming it's reproducible, if there's anything that can be done to help get a fixed merged.

**Comment by dgibbs64** [comment]
You are not the only one https://github.com/AlexxIT/go2rtc/issues/849

**Comment by ppfeister** [comment]
@dgibbs64 Interesting. I must've missed that issue since it's with another model number.

I am noticing that the discussed models and the discussed firmware versions are all different. Also, tapo:// worked wonderfully on this model up until this specific firmware version. Should probably still close thing one as a duplicate and keep them together.
