### ISSUE TITLE
Invalid memory "streamer.(*Track).GetSink"

### ISSUE THREAD

**Issue by darethehair** [AlexxIT/go2rtc#135]
Out of curiosity, I clicked on the '2-way-aud' option on the generated web page for go2rtc, and it crashed my session.  No big deal, since it was just an experiment, but here is the crash output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x60281e]

goroutine 1882 [running]:
[github.com/AlexxIT/go2rtc/pkg/streamer.(*Track).GetSink(0x0](http://github.com/AlexxIT/go2rtc/pkg/streamer.(*Track).GetSink(0x0), 0xc000a9aba0)
        [github.com/AlexxIT/go2rtc/pkg/streamer/track.go:62](http://github.com/AlexxIT/go2rtc/pkg/streamer/track.go:62) +0x1e
[github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).reconnect(0xc0000b9d80)](http://github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).reconnect(0xc0000b9d80))
        [github.com/AlexxIT/go2rtc/cmd/streams/producer.go:144](http://github.com/AlexxIT/go2rtc/cmd/streams/producer.go:144) +0x597
[github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start.func1()](http://github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start.func1())
        [github.com/AlexxIT/go2rtc/cmd/streams/producer.go:107](http://github.com/AlexxIT/go2rtc/cmd/streams/producer.go:107) +0x89
created by [github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start](http://github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start)
        [github.com/AlexxIT/go2rtc/cmd/streams/producer.go:102](http://github.com/AlexxIT/go2rtc/cmd/streams/producer.go:102) +0x14b

```
I was wondering how easy it would be to add some flags in the 'go2rtc.yaml' file to eliminate options that won't be used (or are too dangerous to use) -- or (vice versa) to request the ones to add?  I am thinking specifically of the situation where I make go2rtc available to other volunteers, and I want to control what they can click on.

Something that I also noticed was that the 'frame' (single image with no stream) option is gone now.  I found it useful, so I am curious to know if it will be coming back?

Thanks!

**Comment by NickM-27** [comment]
That's a known bug, there's nothing inherently dangerous about it and under normal circumstances would either work or not without issue: https://github.com/AlexxIT/go2rtc/issues/111

**Comment by darethehair** [comment]
> That's a known bug, there's nothing inherently dangerous about it and under normal circumstances would either work or not without issue: #111

Thanks!  That may be true, but I think it might still be useful -- in general -- to have control over what options are available, to help avoid confusion for not-so-technical folks using it (in a workplace situation).

**Comment by NickM-27** [comment]
Right, I wasn't refuting the idea, just clarifying

**Comment by AlexxIT** [comment]
@NickM-27 this is another bug.
@darethehair you can host your own Web UI (`static_dir` option)
https://github.com/AlexxIT/go2rtc#module-api

Link to frame gone, but API still in place. `/api/frame.mp4?src=camera1`

**Comment by AlexxIT** [comment]
Is problem still actual? I haven't seen it for a while.
