### ISSUE TITLE
Using 'static_dir' for self-hosted HTML: Examples?

### ISSUE THREAD

**Issue by darethehair** [AlexxIT/go2rtc#136]
I appreciate the suggestions to create my own HTML to modify the look & feel of go2rtc, but my attempts have not been successful.  Here is what start of my 'go2rtc.yaml' looks like at the moment:

```
api:
  #listen: ":1984"    # default ":1984", HTTP API port ("" - disabled)
  #base_path: ""  # default "", API prefix for serve on suburl (/api => /rtc/api)
  static_dir: "/home/darren/www"  # default "", folder for static files (custom web interface)
  #origin: "*"        # default "", allow CORS requests (only * supported)
```

What is the minimum HTML that I need to place into my personal 'www' directory (from the go2rtc github code repository) to start off my customization?  'index.html'?  'stream.html'?  Since go2rtc is relatively new, Google does not find many hits of people doing this sort of thing :)

**Comment by AlexxIT** [comment]
You can place the contents of this folder there:
https://github.com/AlexxIT/go2rtc/tree/master/www

And change any files for your needs. There is no any "important" files.
The only rule that `index.html` file opens by default, if the file name is not specified.
