### ISSUE TITLE
FFMPEG necessary to convert RTSP to fragemented mp4

### ISSUE THREAD

**Issue by roycw** [AlexxIT/go2rtc#1360]
Hello, when pulling raw RTSP stream, do u used ffmpeg under the hood to convert to mp4 or does to library does that independently.
If so is there a place in the code i could be refered to and potentially use it in a custom solution?

**Comment by AlexxIT** [comment]
FFmpe is not used
https://github.com/AlexxIT/go2rtc/tree/master/internal/mp4
https://github.com/AlexxIT/go2rtc/tree/master/pkg/mp4
https://github.com/AlexxIT/go2rtc/tree/master/pkg/iso
