### ISSUE TITLE
TTS With HIKVISION Camera Speaker, Terrible Sound with pcmu/8000

### ISSUE THREAD

**Issue by Coketrd** [AlexxIT/go2rtc#1367]
Hello Guys,
i hope someone can help me, because i am to stupid to solve my problem. I have a HIKVISON CAMERA DS-2CD2387G2-LSU/SL.
I reached to connect the Speaker and i can send TTS to it. Thats already fine. But the sound is totally bad.
The mp3 files from HomeAssistant are 32bit with 24000hz. But so far I have only managed to control the pcmu with 8000hz..

But the camera has several more codecs like MP2L2, G.726, AAC, PCM and MP3. But i dont know how to integrate this codecs... everytime i got a error. Do you have any idea?

This i have in go2rtc
```
streams:
  hikvision_tuere:
    - rtsp://User:Password@Youre-IP:554/ISAPI/Streaming/Channels/101
    - isapi://User:Password@Youre-IP:80/
```
and this in the configuration
```
media_player:
  - platform: webrtc
    name: HIKVISION_Tuere
    stream: hikvision_tuere
    audio: pcmu/8000
```
![460356467_27247954061469573_513478506223213275_n](https://github.com/user-attachments/assets/f6925d0c-b2f1-4a71-a207-ab7f746c35f4)

thanks for youre help

**Comment by AlexxIT** [comment]
Show stream probe info from go2rtc WebUI

**Comment by Coketrd** [comment]
> Show stream probe info from go2rtc WebUI

You mean this? This is with the profile pcmu Profile. 

{
  "producers": [
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/Channels/102?transportmode=unicast\u0026profile=Profile_2"
    }
  ],
  "consumers": []
}

**Comment by Coketrd** [comment]
> Show stream probe info from go2rtc WebUI

This is with aac

{
  "producers": [
    {
      "url": "rtsp://admin:45840312!TK@192.168.178.17:554/ISAPI/Streaming/Channels/101"
    },
    {
      "url": "isapi://user:pw@IP:80/"
    },
    {
      "url": "rtsp://user:pw@IP:554/Streaming/Channels/101?audioCodecType=AAC\u0026audio=1"
    },
    {
      "url": "rtsp://user:pw@IP:554/Streaming/ISAPI/Channels/101?audioCodecType=AAC\u0026audio=1"
    }
  ],
  "consumers": null
}

**Comment by Coketrd** [comment]
> Show stream probe info from go2rtc WebUI

This is with aac

{
"producers": [
{
"url": "rtsp://user:pw@IP:554/ISAPI/Streaming/Channels/101"
},
{
"url": "isapi://user:pw@IP:80/"
},
{
"url": "rtsp://user:pw@IP:554/Streaming/Channels/101?audioCodecType=AAC\u0026audio=1"
},
{
"url": "rtsp://user:pw@IP:554/Streaming/ISAPI/Channels/101?audioCodecType=AAC\u0026audio=1"
}
],
"consumers": null
}



Add a

**Comment by Coketrd** [comment]
i test a few other links in internet. now i got this replay:

{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/",
      "remote_addr": "IP-Adress:554",
      "user_agent": "go2rtc/1.8.4",
      "sdp": "v=0\r\no=- 1726996184316491 1726996184316491 IN IP4 IP-Adress\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5150\r\nt=0 0\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:3840,2160\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AM4qKUB4AIff+AAIAAtkAAAMD6AAAw1AE,aO48gA==\r\nm=audio 0 RTP/AVP 104\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=2\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\nm=application 0 RTP/AVP 107\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=3\r\na=rtpmap:107 isapi.metadata/90000\r\nm=audio 0 RTP/AVP 0 102 104\r\na=rtpmap:0 PCMU/8000/1\r\na=rtpmap:102 G726/8000/1\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=sendonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=4\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\na=Media_header:MEDIAINFO=494D4B48010300000400000101200110803E0000007D000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "application, recvonly, ISAPI.METADATA",
        "audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        "96 H264, bytes=37762926, senders=1",
        "104 MPEG4-GENERIC/16000, bytes=134007, senders=0"
      ],
      "recv": 38231652
    },
    {
      "url": "isapi://user:pw@IP-Adress:80/"
    },
    {
      "url": "rtsp://user:pw@IP-Adress:554/Streaming/Channels/101?audioCodecType=AAC\u0026audio=1"
    },
    {
      "url": "rtsp://user:pw@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=AAC\u0026audio=1"
    },
    {
      "url": "rtsp://user:pw@IP-Adress:554/Streaming/Channels/101?audioCodecType=ACC"
    },
    {
      "url": "rtsp://user:pw@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=ACC"
    },
    {
      "url": "rtsp://user:pw@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=audio=1"
    },
    {
      "url": "http://IP-Adress/ISAPI/System/TwoWayAudio/channels/1/stream"
    },
    {
      "url": "http://IP-Adress/ISAPI/System/TwoWayAudio/channels/101/stream"
    },
    {
      "url": "http://user:pw@IP-Adress/ISAPI/System/TwoWayAudio/channels/1/stream"
    },
    {
      "url": "http://user:pw@IP-Adress/ISAPI/System/TwoWayAudio/channels/101/stream"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.178.187:55608 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, ULPFEC, RED",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "126 H264, bytes=37762926, receivers=1"
      ],
      "send": 37773936
    }

**Comment by Coketrd** [comment]
and this is the replay when i have a steam open, and audio set to mp3 in camera:

{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/",
      "remote_addr": "IP-Adress:554",
      "user_agent": "go2rtc/1.8.4",
      "sdp": "v=0\r\no=- 1726997999284128 1726997999284128 IN IP4 IP-Adress\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5150\r\nt=0 0\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:3840,2160\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AM4qKUB4AIff+AAIAAtkAAAMD6AAAw1AE,aO48gA==\r\nm=audio 0 RTP/AVP 14\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=2\r\na=rtpmap:14 MPA/90000\r\nm=application 0 RTP/AVP 107\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=3\r\na=rtpmap:107 isapi.metadata/90000\r\nm=audio 0 RTP/AVP 0 102 104\r\na=rtpmap:0 PCMU/8000/1\r\na=rtpmap:102 G726/8000/1\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=sendonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=4\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\na=Media_header:MEDIAINFO=494D4B48010300000400000100200110803E000000FA000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, MPA",
        "application, recvonly, ISAPI.METADATA",
        "audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        "96 H264, bytes=159312417, senders=1"
      ],
      "recv": 160691944
    },
    {
      "url": "isapi://user:password@IP-Adress:80/"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/Channels/101?audioCodecType=AAC\u0026audio=1"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=AAC\u0026audio=1"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/Channels/101?audioCodecType=ACC"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=ACC"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=audio=1"
    },
    {
      "url": "http://IP-Adress/ISAPI/System/TwoWayAudio/channels/1/stream"
    },
    {
      "url": "http://IP-Adress/ISAPI/System/TwoWayAudio/channels/101/stream"
    },
    {
      "url": "http://user:password@IP-Adress/ISAPI/System/TwoWayAudio/channels/1/stream"
    },
    {
      "url": "http://user:password@IP-Adress/ISAPI/System/TwoWayAudio/channels/101/stream"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "tcp4 prflx 192.168.178.187:60613 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, ULPFEC, RED",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "126 H264, bytes=144516977, receivers=1"
      ],
      "send": 146047582
    }
  ]
}

**Comment by Coketrd** [comment]
and this is the replay when i have a steam open, and audio set to aac in camera:

{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/",
      "remote_addr": "IP-Adress:554",
      "user_agent": "go2rtc/1.8.4",
      "sdp": "v=0\r\no=- 1726998312224229 1726998312224229 IN IP4 IP-Adress\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5100\r\nt=0 0\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:3840,2160\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AM4qKUB4AIff+AAIAAtkAAAMD6AAAw1AE,aO48gA==\r\nm=audio 0 RTP/AVP 104\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=2\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\nm=application 0 RTP/AVP 107\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=3\r\na=rtpmap:107 isapi.metadata/90000\r\na=Media_header:MEDIAINFO=494D4B48010300000400000101200110803E0000007D000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "application, recvonly, ISAPI.METADATA"
      ],
      "receivers": [
        "96 H264, bytes=104780382, senders=1",
        "104 MPEG4-GENERIC/16000, bytes=317901, senders=0"
      ],
      "recv": 106020028
    },
    {
      "url": "isapi://user:password@IP-Adress:80/"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/Channels/101?audioCodecType=AAC\u0026audio=1"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=AAC\u0026audio=1"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/Channels/101?audioCodecType=ACC"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=ACC"
    },
    {
      "url": "rtsp://user:password@IP-Adress:554/Streaming/ISAPI/Channels/101?audioCodecType=audio=1"
    },
    {
      "url": "http://IP-Adress/ISAPI/System/TwoWayAudio/channels/1/stream"
    },
    {
      "url": "http://IP-Adress/ISAPI/System/TwoWayAudio/channels/101/stream"
    },
    {
      "url": "http://user:password@IP-Adress/ISAPI/System/TwoWayAudio/channels/1/stream"
    },
    {
      "url": "http://user:password@IP-Adress/ISAPI/System/TwoWayAudio/channels/101/stream"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.178.187:64652 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, ULPFEC, RED",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "126 H264, bytes=101634042, receivers=1"
      ],
      "send": 102708652
    }
  ]
}

**Comment by Coketrd** [comment]
here is the probe with AAC

{
  "producers": [
    {
      "id": 430,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "IP-Adress:554",
      "url": "rtsp://user:password@IP-Adress:554/ISAPI/Streaming/Channels/101",
      "sdp": "v=0\r\no=- 1727214543677869 1727214543677869 IN IP4 IP-Adress\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5150\r\nt=0 0\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:3840,2160\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AM4qKUB4AIff+AAIAAtkAAAMD6AAAw1AE,aO48gA==\r\nm=audio 0 RTP/AVP 104\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=2\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\nm=application 0 RTP/AVP 107\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=3\r\na=rtpmap:107 isapi.metadata/90000\r\nm=audio 0 RTP/AVP 0 102 104\r\na=rtpmap:0 PCMU/8000/1\r\na=rtpmap:102 G726/8000/1\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=sendonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=4\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\na=Media_header:MEDIAINFO=494D4B48010300000400000101200110803E0000007D000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
      "user_agent": "go2rtc/1.9.4",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "application, recvonly, ISAPI.METADATA",
        "audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        {
          "id": 431,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "Main"
          },
          "childs": [
            432
          ]
        },
        {
          "id": 433,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "childs": [
            434
          ]
        }
      ],
      "senders": [
        {
          "id": 436,
          "codec": {
            "codec_name": "pcm_mulaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 435
        }
      ]
    },
    {
      "url": "isapi://user:password@IP-Adress:80/"
    }
  ],
  "consumers": [
    {
      "id": 429,
      "format_name": "probe",
      "protocol": "http",
      "remote_addr": "172.30.32.2:46356 forwarded 192.168.178.187, 172.30.32.1",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        {
          "id": 435,
          "codec": {
            "codec_name": "ANY",
            "codec_type": ""
          },
          "childs": [
            436
          ]
        }
      ],
      "senders": [
        {
          "id": 432,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "Main"
          },
          "parent": 431
        },
        {
          "id": 434,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "parent": 433
        }
      ]
    }
  ]
}

**Comment by Coketrd** [comment]
here is the probe with aac

`{
  "producers": [
    {
      "id": 430,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "IP-Adress:554",
      "url": "rtsp://user:password@IP-Adress:554/ISAPI/Streaming/Channels/101",
      "sdp": "v=0\r\no=- 1727214543677869 1727214543677869 IN IP4 IP-Adress\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5150\r\nt=0 0\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:3840,2160\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AM4qKUB4AIff+AAIAAtkAAAMD6AAAw1AE,aO48gA==\r\nm=audio 0 RTP/AVP 104\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=2\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\nm=application 0 RTP/AVP 107\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=3\r\na=rtpmap:107 isapi.metadata/90000\r\nm=audio 0 RTP/AVP 0 102 104\r\na=rtpmap:0 PCMU/8000/1\r\na=rtpmap:102 G726/8000/1\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=sendonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=4\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\na=Media_header:MEDIAINFO=494D4B48010300000400000101200110803E0000007D000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
      "user_agent": "go2rtc/1.9.4",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "application, recvonly, ISAPI.METADATA",
        "audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        {
          "id": 431,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "Main"
          },
          "childs": [
            432
          ]
        },
        {
          "id": 433,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "childs": [
            434
          ]
        }
      ],
      "senders": [
        {
          "id": 436,
          "codec": {
            "codec_name": "pcm_mulaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 435
        }
      ]
    },
    {
      "url": "isapi://user:password@IP-Adress:80/"
    }
  ],
  "consumers": [
    {
      "id": 429,
      "format_name": "probe",
      "protocol": "http",
      "remote_addr": "172.30.32.2:46356 forwarded 192.168.178.187, 172.30.32.1",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        {
          "id": 435,
          "codec": {
            "codec_name": "ANY",
            "codec_type": ""
          },
          "childs": [
            436
          ]
        }
      ],
      "senders": [
        {
          "id": 432,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "Main"
          },
          "parent": 431
        },
        {
          "id": 434,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "parent": 433
        }
      ]
    }
  ]
}
`

**Comment by Coketrd** [comment]
here the aac probe

```python
{
  "producers": [
    {
      "id": 430,
      "format_name": "rtsp",
      "protocol": "rtsp+tcp",
      "remote_addr": "IP-Adress:554",
      "url": "rtsp://user:password@IP-Adress:554/ISAPI/Streaming/Channels/101",
      "sdp": "v=0\r\no=- 1727214543677869 1727214543677869 IN IP4 IP-Adress\r\ns=Media Presentation\r\ne=NONE\r\nb=AS:5150\r\nt=0 0\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=recvonly\r\na=x-dimensions:3840,2160\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z00AM4qKUB4AIff+AAIAAtkAAAMD6AAAw1AE,aO48gA==\r\nm=audio 0 RTP/AVP 104\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=2\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\nm=application 0 RTP/AVP 107\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=recvonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=3\r\na=rtpmap:107 isapi.metadata/90000\r\nm=audio 0 RTP/AVP 0 102 104\r\na=rtpmap:0 PCMU/8000/1\r\na=rtpmap:102 G726/8000/1\r\nc=IN IP4 0.0.0.0\r\nb=AS:50\r\na=sendonly\r\na=control:rtsp://IP-Adress:554/ISAPI/Streaming/Channels/101/trackID=4\r\na=rtpmap:104 mpeg4-generic/16000/1\r\na=fmtp:104 profile-level-id=15; streamtype=5; mode=AAC-hbr; config=1408;SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;\r\na=Media_header:MEDIAINFO=494D4B48010300000400000101200110803E0000007D000000000000000000000000000000000000;\r\na=appversion:1.0\r\n",
      "user_agent": "go2rtc/1.9.4",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "application, recvonly, ISAPI.METADATA",
        "audio, sendonly, PCMU/8000, G726/8000, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        {
          "id": 431,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "Main"
          },
          "childs": [
            432
          ]
        },
        {
          "id": 433,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "childs": [
            434
          ]
        }
      ],
      "senders": [
        {
          "id": 436,
          "codec": {
            "codec_name": "pcm_mulaw",
            "codec_type": "audio",
            "sample_rate": 8000
          },
          "parent": 435
        }
      ]
    },
    {
      "url": "isapi://user:password@IP-Adress:80/"
    }
  ],
  "consumers": [
    {
      "id": 429,
      "format_name": "probe",
      "protocol": "http",
      "remote_addr": "172.30.32.2:46356 forwarded 192.168.178.187, 172.30.32.1",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
      "medias": [
        "video, sendonly, ALL",
        "audio, sendonly, ALL",
        "audio, recvonly, ANY"
      ],
      "receivers": [
        {
          "id": 435,
          "codec": {
            "codec_name": "ANY",
            "codec_type": ""
          },
          "childs": [
            436
          ]
        }
      ],
      "senders": [
        {
          "id": 432,
          "codec": {
            "codec_name": "h264",
            "codec_type": "video",
            "level": 51,
            "profile": "Main"
          },
          "parent": 431
        },
        {
          "id": 434,
          "codec": {
            "codec_name": "aac",
            "codec_type": "audio",
            "sample_rate": 16000
          },
          "parent": 433
        }
      ]
    }
  ]
}

```

**Comment by Coketrd** [comment]
this is the ACC log from net 

![grafik](https://github.com/user-attachments/assets/c5148b69-2c2f-478e-9956-5d3280ff94a2)

**Comment by jeeftor** [comment]
What is the final configuration I need to set to get this to work? :)

**Comment by jeeftor** [comment]
Well I got mine working -> at least with wav files... not with TTS unfortunately

**Comment by Coketrd** [comment]
> Well I got mine working -> at least with wav files... not with TTS unfortunately

Hi, i send the TTS for example in an automation like this
```
action: tts.cloud_say
data:
  cache: false
  entity_id: media_player.hikvision_tuere
  message: "{{ states('input_text.gpt_response') }}"
  language: de-DE
  options:
    voice: ChristophNeural
```

in the go2rtc yaml i have this integrated
```
streams:
  hikvision_tuere:
    - rtsp://admin:PASSWORD@192.168.178.17:554/ISAPI/Streaming/Channels/101
    - isapi://admin:PASSWORD@192.168.178.17:80/
```
and in the configuration.yaml
```
media_player:
  - platform: webrtc
    name: HIKVISION_Tuere
    stream: hikvision_tuere
    audio: pcmu/8000
```
