### ISSUE TITLE
Ability to define a "push" RTSP stream?

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#137]
In frigate we have a feed called "birdseye" which is where we take individual frames of cameras and composite them based on certain rules (like if that camera currently sees an object). We currently expose this stream as a jsmpeg stream over websocket to our frontend, but we would like to also expose this as an rtsp stream. 

You can see the current ffmpeg command https://github.com/blakeblackshear/frigate/blob/dev/frigate/output.py#L32

I don't believe ffmpeg can use the jsmpeg over websocket as an input, so I'm trying to think about other ways this could be done. I believe we could run ffmpeg to push rtsp to go2rtc (for example, rtsp-simple-server supports this). Please correct me if I am wrong and there is a better option.

**Comment by AlexxIT** [comment]
This is an undocumented feature. go2rtc can accept external RTSP at any time. But only for a previously configured stream. I  have already answered here: https://github.com/AlexxIT/go2rtc/issues/134#issuecomment-1358820212

You can create stream with empty source and push RTSP to it. go2rtc won't stop it when there is no viewers.

You can also push RTSP to stream with sources. But remember, if there are several identical codecs in the stream, the first of them will be selected when viewing. Most likely the pre-existing.

**Comment by NickM-27** [comment]
Oh perfect, I think that will work great.

**Comment by AlexxIT** [comment]
Also I can create new stream on the fly. Don't know if it is a good idea :)

**Comment by NickM-27** [comment]
We ended up having some other issues and the easiest way to accomplish this was to have ffmpeg create a rtsp_mpegts stream locally and then have go2rtc consume that and encode as h264 whenever someone connects to the stream which is working great.
