### ISSUE TITLE
Stream address parsing error: net/url invalid userinfo

### ISSUE THREAD

**Issue by footswitch** [AlexxIT/go2rtc#1370]
Certain combinations of user/password can't be parsed because of special characters such as { }
The stream address returns the following message:
**mse: streams: parse "rtsp://username:p{assword@ip_address:554/Streaming/Channels/101": net/url: invalid userinfo**

Current workaround: change user/password combination to avoid certain special characters
This was the search result that led me to try changing the password:
https://stackoverflow.com/questions/48671938/go-url-parsestring-fails-with-certain-user-names-or-passwords

**Comment by AlexxIT** [comment]
#1032
