### ISSUE TITLE
add consumer error=streams: EOF

### ISSUE THREAD

**Issue by latel** [AlexxIT/go2rtc#1371]
I'm adding TP-Link cameras to go2rtc（not tapo)，i'm sure the [rtsp address](https://security.tp-link.com.cn/service/detail_article_4432.html) and credentials are correct, go2rtc can also find it as well.
![image](https://github.com/user-attachments/assets/ce26b87b-962d-4243-814c-ec4d46d3e922)

but streaming is always failing, deug logs here
```
11:59:44.609 | debug | [webrtc] new consumer src=TP_Link_TL_IPC14CH
-- | -- | --
11:59:44.640 | debug | [mp4] add consumer error=streams: EOF
11:59:44.671 | debug | [webrtc] add consumer error=streams: EOF
11:59:45.017 | debug | [mjpeg] add consumer error=streams: EOF
12:00:26.143 | debug | [webrtc] new consumer src=Hikvision

```

config
```
log:
  level: debug

streams:
  TP_Link_TL_IPC14CH:
    - rtsp://admin:cafnu-jytku*******@10.*.10.25:554/stream1
```

**Comment by latel** [comment]
wired, I removed the '-' in my password, and it's ok now. 
for example, origin password is "111-222-333", changed to "111222333" solved the problem

**Comment by AlexxIT** [comment]
Perhaps these characters should be url escaped. I'm not sure.

**Comment by 3clypse** [comment]
> Perhaps these characters should be url escaped. I'm not sure.

Yes, this issue happen to me too.
I had to only use a-z and numeric chars as user and password. It fail as the OP, with "-" and "_" as part of the password and username.

I could make a PR, but I'm not sure what's the issue, to be honest.

Thank you.
