### ISSUE TITLE
How to make stream drop faster after client disconnects

### ISSUE THREAD

**Issue by Erithax** [AlexxIT/go2rtc#1375]
With a simple stream
```yaml
ffmpeg:device?video=/dev/video0&input_format=h264&video_size=1280x720
```
and using the included web page (stream.html). When the client disconnects, the stream takes 7-9s to shutdown as indicated
- usb led
- go2rtc web page showing '1' online
- error when opening another camera quickly after closing the first, because usb hub can't handle both at the same time

How do I make sure the stream shuts down quickly?

Adding `#raw=-timeout 1 -rw_timeout 1` did not work.

**Comment by Erithax** [comment]
I think I found the offending code by following a trace message up the stack:
```
/internal/streams/producer.go : func stop
/internal/streams/stream.go : func stopProducers
/internal/streams/stream.go : func RemoveConsumer
/internal/streams/publish.go : func Publish
```
Which does
```go
go func() {
  run()
  s.RemoveConsumer(cons)

  // TODO: more smart retry
  time.Sleep(5 * time.Second)
  _ = s.Publish(url)
}()
```
But the sleep happens after s.RemoveConsumer()? Not sure if this is the issue...

**Comment by Erithax** [comment]
Another potential culprit is `pkg/roborock/client.go` which has a 5s sleep in 2 places (line 84 and 160).

**Comment by Erithax** [comment]
I found how to control the timeout durations:

```go
// /pkg/webrtc/api.go
func NewServerAPI(network, address string, filters *Filters) (*webrtc.API, error) {
    // ...
    s := webrtc.SettingEngine{}
    s.SetICETimeouts(1000*time.Millisecond, 25*time.Second, 2*time.Second) // add this line
    // ...
}
```
Where the first arg is the timeout duration. That answers my question, altough it requires a code change.

However, 1000ms even on intranet sometimes makes the stream drop out, especially just after opening the stream (on device with RaspberryPi-class perf). So this is not an option, I will need to disconnect it manually when closing a stream, for which I'm looking into `/www/stream.html`, `/www/video-stream.js` and `/www/video-rtc.js`

**Comment by AlexxIT** [comment]
You're right, in this and the other issue. WebRTC needs time to break the connection. Up to 30 seconds.
