### ISSUE TITLE
Error opening RTSP stream from Lollipop baby camera

### ISSUE THREAD

**Issue by WazzA1987** [AlexxIT/go2rtc#1399]
Thanks for your efforts with this integration, it’s awesome for me as an IT novice.

My Lollipop RTSP stream works live with VLC  but I seem to only get a black screen in webrtc/go2rtc. Probably my config but see error message log below, could this be the reason?

14:10:45.813 DBG [webrtc] add consumer error="streams: wrong response on DESCRIBE"

Webrtc card—:
```
type: custom:webrtc-camera
url: rtsp://192.168.0.13:554/live/<id>/ch00_0
```
config.yaml—:
```
streams:
lollipop:  rtsp://192.168.0.13:554/live/<id>/ch00_0

log:
level: info
api: debug
rtsp: debug
streams: debug
webrtc: debug
```

(sorry not sure how to copy YAML or do indentation in github to copy/paste properly.

appreciate any help.

**Comment by AlexxIT** [comment]
Have you tried all recommendations?
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-rtsp

**Comment by WazzA1987** [comment]
Hi @AlexxIT i managed to trial and error get it working.

`url: >-
  ffmpeg:rtsp://192.168.0.13:554/live/4f3df37f86fb2a8df0de3e9df18ab189/ch00_0#video=h264
`

**Comment by AlexxIT** [comment]
Looks like you got to the item - use transcoding with ffmpeg source.

**Comment by JerryVDP** [comment]
@WazzA1987 Hey, a completely unrelated question: how do I get the <id> part of the url?

**Comment by WazzA1987** [comment]
> @WazzA1987 Hey, a completely unrelated question: how do I get the "id" part of the url?

Hey mate,
I sold the Lollipo, kids are old now :( from memory, dont update the FW or it gets tricky (depending what version you are already running) 

Try:

https://dparv.dev/2023/08/16/reverse-engineering-lollipop-camera.html

https://www.lafois.com/2022/02/04/lollipop-camera-reverse-engineering/

Hope this helps.
