### ISSUE TITLE
sometimes 1 of my cmaeras didn't show related stream on HASS card

### ISSUE THREAD

**Issue by marcob79** [AlexxIT/go2rtc#14]
Hi,
thank you for this great successor pluign that seems already working cmoothly even if in alpha stage.
I'm running it as HASS Add-on

I currently have 4 IP cameras:
2 Hikvision
1 ezviz
1 reolink

I putted all my camera on same HASS card.
Sometimes it happened that the stream related to the Reolink camera (that is the latest one) didn't show up on the page.

in BDG log i can just see the following

```
15:35:00.223 DBG [streams] probe producer url=rtsp://admin:xxxxxxx@192.168.1.240:1240
15:35:00.234 DBG [streams] start producer url=rtsp://admin:xxxxxxx@192.168.1.240:1240
15:35:00.269 DBG [streams] probe producer url=rtsp://admin:xxxxxxx@192.168.1.241:1241
15:35:00.270 DBG [streams] probe producer url=rtsp://admin:xxxxxxx@192.168.1.242:554
15:35:00.271 DBG [streams] probe producer url=rtsp://admin:xxxxxxx%21@192.168.1.243:554/h264Preview_01_sub
15:35:00.289 DBG [streams] start producer url=rtsp://admin:xxxxxxx@192.168.1.241:1241
15:35:00.296 DBG [webrtc] stun public address addr=79.54.208.253:8555
15:35:00.314 DBG [streams] start producer url=rtsp://admin:xxxxxxx%21@192.168.1.243:554/h264Preview_01_sub
15:35:00.336 DBG [webrtc] stun public address addr=79.54.208.253:8555
15:35:00.338 DBG [streams] start producer url=rtsp://admin:xxxxxxx@192.168.1.242:554
15:35:00.369 DBG [webrtc] stun public address addr=79.54.208.253:8555
15:35:00.394 DBG [webrtc] stun public address addr=79.54.208.253:8555
15:35:28.602 DBG [streams] stop producer url=rtsp://admin:xxxxxxx@192.168.1.241:1241
15:35:28.607 DBG [streams] stop producer url=rtsp://admin:xxxxxxx@192.168.1.240:1240
15:35:28.720 DBG [streams] stop producer url=rtsp://admin:xxxxxxx%21@192.168.1.243:554/h264Preview_01_sub
15:35:28.748 DBG [streams] stop producer url=rtsp://admin:xxxxxxx@192.168.1.242:554
```

I can only highlight three things looking at the logs but not really helpful.... 

- timestamp seems UTC and not my local timezone
- the Reolink password is diplayed in log ending with %21 instead of !
- i see log with probe producer and start producer, but not any logs related to webrtc module

praobably i need to enhance the log level of one of the module and collect new logs. if so, can you suggest me which module and which level i should configure in order to have intersting logs?
thanks

**Comment by AlexxIT** [comment]
So you can see all your cameras on single Hass page and they all works fine. But sometimes you can't see picture from reolink?

**Comment by marcob79** [comment]
You're right. Sometimes i can see all of them.  Sometimes not all of them.  Usually if not all of them, it is the reolink (the last one of the page) that is missing.

**Comment by AlexxIT** [comment]
Well. Open add-on UI and check active sessions. Then check info link for problem camera. Reload it few times. If you can see changes in send and receive fields.

**Comment by marcob79** [comment]
if i open the page i can see 2 online for each camera (even if i cannot see the reolink one, that is the longer URL)

![image](https://user-images.githubusercontent.com/66200214/186472198-01867c13-1b36-438c-9ba8-b8352f0fdbc8.png)

clicking on info at first i was not able to see anything (but that is just because i have dark theme and it was black over black)

`[{"media:0":"video, sendonly, 96 H264/90000","media:1":"audio, sendonly, 97 MPEG4-GENERIC/16000","receive":1330510,"remote_addr":"192.168.1.243:554","send":0,"track:0":"96 H264/90000, sinks=1","type":"RTSP client producer","url":"rtsp://192.168.1.243/h264Preview_01_sub/"},{"remote_addr":"udp4 prflx 192.168.1.79:36478 related :0","send":1339719,"type":"WebRTC server consumer","user_agent":"HomeAssistant/2022.8.6 aiohttp/3.8.1 Python/3.10"}]`

after some time
`[{"media:0":"video, sendonly, 96 H264/90000","media:1":"audio, sendonly, 97 MPEG4-GENERIC/16000","receive":1566907,"remote_addr":"192.168.1.243:554","send":0,"track:0":"96 H264/90000, sinks=1","type":"RTSP client producer","url":"rtsp://192.168.1.243/h264Preview_01_sub/"},{"remote_addr":"udp4 prflx 192.168.1.79:36478 related :0","send":1577763,"type":"WebRTC server consumer","user_agent":"HomeAssistant/2022.8.6 aiohttp/3.8.1 Python/3.10"}]`

here blow what i can see from HASS APP
![Screenshot_20220824-182958_Home Assistant](https://user-images.githubusercontent.com/66200214/186473151-35829c5a-17cc-4d9e-b280-a056865a80a1.jpg)

**Comment by AlexxIT** [comment]
Try to config Lovelace card with only one problem camera.  Is there still a problem?

**Comment by marcob79** [comment]
According to the few tests i did up to now, I have 100% success rate with 1 single camera on the lovelace tab.

according to my previous snap of addon UI, is my configuration correct?
i have 4 rows never online with the content of the camera included in the go2rtc.yaml, and then the other URL camera generated (I guess) during the 1st vision attempt after HASS restart

**Comment by AlexxIT** [comment]
`go2rtc` support zero-config feature. So Hass create stream link on the fly on first stream start (`rtsp://` links on your scree).

Streams with name are streams from you `go2rts.yaml`. You may add them to Hass using `rtsp://127.0.0.1:8554/balcone_sala` links. You add them to Frigate. Or view them in VLC (but change IP to your Hass server).

With first config - camera will have multiple connections. Some from Hass directly and one from go2rtc.

With second config - camera will have one connection from `go2rtc`. And `go2rtc` will have multiple connection - some from Hass via RTSP protocol, some from your browser via WebRTC protocol.

Use any config what you like.

**Comment by marcob79** [comment]
thank again for your feedback. So I'm going to remove static yaml configuration keeping only HASS streams created on the fly (that are practically used.
Why if i open my page i hot "2" Online instead of "1" ?

On a RPi4 with 4 camera, can we say that 10% CPU usage is reasonable (all my stream should be H264 and no need to be trascoded, if I correctly got from your readme

regarding my original problem, can be something related to the concurrent stream requests?
do you think that my visulization problem could be some "HASS generic issue" rather than some problem with your addon?

with a lovale page with only that camera currently i got 100% success rate
I tried to switch among high/low resolution streams, but it seems no difference from that point of view

**Comment by AlexxIT** [comment]
1. Online counts Producers and Consumers of Media content.
2. Handling network traffic also takes time. I know about problem, don't know if I can fix it.

**Comment by marcob79** [comment]
Currently i moved one of the 4 cameras on a different card and now seems better. 
All my pucture camera has live settings (instead of auto).
On my samsung and on my laptop with chrome now i have almost 100% successful view.

While i just noticed that my wife with nokia 6 never see the 2 hikvision camera's.... that's so strange. If she can see one of them that is webrtc h.264 in principle should be able to see all of them....
