### ISSUE TITLE
How to use multiple streams?

### ISSUE THREAD

**Issue by andreymukha** [AlexxIT/go2rtc#140]
If I specify two streams for one camera, how can I choose them in the future?

```
streams:
  dahua_camera:
    - rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=1
```

**Comment by AlexxIT** [comment]
This is not multiple streams. This is multiple sources of one stream. If you want to use specific source - create separate stream with only this source.

go2rtc automatically selects tracks from your sources based on the codecs your current client supports.

**Comment by maxi1134** [comment]
> go2rtc automatically selects tracks from your sources based on the codecs your current client supports.

Could there be a way for the stream to be selected upon performance? Per instance if a stream is lagging it automatically reverts to a lower res stream in the same stream but as a different source

**Comment by marcocunha** [comment]
I have the same question as @maxi1134

**Comment by AlexxIT** [comment]
Someone should write a JS client that will switch to another thread in case of lags.
