### ISSUE TITLE
2-way Audio on Amcrest AD110

### ISSUE THREAD

**Issue by aeozyalcin** [AlexxIT/go2rtc#141]
Has anyone been able to get 2-way audio working on the Amcrest AD110 doorbell camera? I see that people have had success with AD410's, but I have not seen any reports of success with 2-way audio working on the AD110's.

I have tried the recommended solution for the AD410 on my AD110, but could not get 2-way audio working. Here is what I have tried:
I changed the audio codec to G.711Mu, G711.A and PCM via both "Amcrest Surveillance Pro", as well as using the HTTP commands. It became pretty clear pretty quickly how buggy the firmware is with audio encoding.

Changing the audio codec on the camera appears to do nothing. Unless I change the sample rate to 8000, the audio encoding stays as 32-bit 16khz AAC (despite being set to G.711Mu/G711.A/PCM). Changing bit depth does not appear to do anything either. The only semi-success I had was with changing the sample rate to 8000. This appears to set the audio to 16-bit 8khz Mono PCM, which gets audio from the camera working when streaming. However, when I switch to 2-way audio, not only does my voice not get to the camera, but the audio from the camera also stops working. I believe the desired codec is _8-bit_ 8khz Mono PCM, but 16-bit was the closest I could get.

I should also note that I was able to get TinyCam Pro to work with 2-way audio, but my end goal is of course to get 2-way audio working also in Home Assistant.

Here is the debug info:
```
[
  {
    "media:0": "video, sendonly, 96 H264/90000",
    "media:1": "audio, sendonly, 97 MPEG4-GENERIC/8000",
    "media:2": "application, sendonly, 107 VND.ONVIF.METADATA/90000",
    "media:3": "audio, recvonly, 97 MPEG4-GENERIC/8000",
    "receive": 2005621,
    "remote_addr": "192.168.0.191:554",
    "send": 0,
    "track:0": "97 MPEG4-GENERIC/8000, sinks=0",
    "type": "RTSP client producer",
    "url": "rtsp://192.168.0.191:554/cam/realmonitor?channel=1\u0026subtype=0\u0026unicast=true\u0026proto=Onvif/",
    "user_agent": "go2rtc/0.1-rc.5"
  },
  {
    "remote_addr": "udp4 prflx 192.168.0.160:58466 related :0",
    "send": 1061346,
    "type": "WebRTC server consumer",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
  }
]
```

Looking forward to hints to get this working on the AD110! Thanks!

**Comment by maglat** [comment]
> Has anyone been able to get 2-way audio working on the Amcrest AD110 doorbell camera? I see that people have had success with AD410's, but I have not seen any reports of success with 2-way audio working on the AD110's.
> 
> I have tried the recommended solution for the AD410 on my AD110, but could not get 2-way audio working. Here is what I have tried: I changed the audio codec to G.711Mu, G711.A and PCM via both "Amcrest Surveillance Pro", as well as using the HTTP commands. It became pretty clear pretty quickly how buggy the firmware is with audio encoding.
> 
> Changing the audio codec on the camera appears to do nothing. Unless I change the sample rate to 8000, the audio encoding stays as 32-bit 16khz AAC (despite being set to G.711Mu/G711.A/PCM). Changing bit depth does not appear to do anything either. The only semi-success I had was with changing the sample rate to 8000. This appears to set the audio to 16-bit 8khz Mono PCM, which gets audio from the camera working when streaming. However, when I switch to 2-way audio, not only does my voice not get to the camera, but the audio from the camera also stops working. I believe the desired codec is _8-bit_ 8khz Mono PCM, but 16-bit was the closest I could get.
> 
> I should also note that I was able to get TinyCam Pro to work with 2-way audio, but my end goal is of course to get 2-way audio working also in Home Assistant.
> 
> Here is the debug info:
> 
> ```
> [
>   {
>     "media:0": "video, sendonly, 96 H264/90000",
>     "media:1": "audio, sendonly, 97 MPEG4-GENERIC/8000",
>     "media:2": "application, sendonly, 107 VND.ONVIF.METADATA/90000",
>     "media:3": "audio, recvonly, 97 MPEG4-GENERIC/8000",
>     "receive": 2005621,
>     "remote_addr": "192.168.0.191:554",
>     "send": 0,
>     "track:0": "97 MPEG4-GENERIC/8000, sinks=0",
>     "type": "RTSP client producer",
>     "url": "rtsp://192.168.0.191:554/cam/realmonitor?channel=1\u0026subtype=0\u0026unicast=true\u0026proto=Onvif/",
>     "user_agent": "go2rtc/0.1-rc.5"
>   },
>   {
>     "remote_addr": "udp4 prflx 192.168.0.160:58466 related :0",
>     "send": 1061346,
>     "type": "WebRTC server consumer",
>     "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54"
>   }
> ]
> ```
> 
> Looking forward to hints to get this working on the AD110! Thanks!

Could you pls. provide your snippet of your config? I would like to try myself with my AD110

**Comment by aeozyalcin** [comment]
I ended up switching to an AD410, and it works.

**Comment by dejongmarten** [comment]
> I ended up switching to an AD410, and it works.

did you manage to setup 2-way audio?

**Comment by dhtguru** [comment]
Greetings, sorry for a dumb question.  But how would I change my AD410 codec to the OPUS/48000/2?

Can I see an example of what this would look like in the yaml?
