### ISSUE TITLE
ffmpeg transcoding not working after updating to v1.9.5

### ISSUE THREAD

**Issue by RPGWiZ4RD** [AlexxIT/go2rtc#1414]
I couldn't for some reason get ffmpeg transcoding to work in v1.9.5 using following line:

type: custom:webrtc-camera
url: ffmpeg:cam_name#video=copy#audio=opus#hardware=qsv

The transcoded url wouldn't appear to the go2rtc streams list at all. I could paste the entire code but I really think that url line is the only thing affecting the result in this case, removing ffmpeg transcoding and using MSE would work just fine though (with audio) or webrtc (without audio). I'm using Reolink cameras if that matters. Reverting to v.1.9.4 and the streams would appear back again using that very same code. Reloading the add-on, rebooting the system etc. made no difference.

Tell me what other info you need and I'll try to provide it.

**Comment by AlexxIT** [comment]
#1417

**Comment by AlexxIT** [comment]
You can check master version (available via addon/docker). If there are no problems in it, I'll make a release.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.6
