### ISSUE TITLE
1.9.5 breaks rtsp discovery

### ISSUE THREAD

**Issue by robertboccia** [AlexxIT/go2rtc#1416]
1.9.5 seems to no longer discover the rtsp streams like it used to, webrtc card also no longer works with rtsp url

**Comment by kiwansky** [comment]
Just upgraded and noticed the same. In the logs I see that it tries to create a new stream but the stream is never established and not shown in the stream overview.

**Comment by AlexxIT** [comment]
Don't understand what you mean about RTSP discovery. There is no such feature.

**Comment by robertboccia** [comment]
in go2rtc i used to get the rtsp streams showing up as if they were automatically discovered by go2rtc, they no longer appear, also in my webrtc card, i used the rtsp url, as of the 1.9.5 update the camera feed just says loading.

Pic attached
![Screenshot 2024-10-29 072153](https://github.com/user-attachments/assets/177aeb0c-4c63-40d1-abf2-68bde61cd3a4)

**Comment by steuerlexi** [comment]
Yes, basically every webrtc card is now stuck in loading and I assume that this Issue #1415 is the same root cause. I hope it is easy to fix.

**Comment by AlexxIT** [comment]
#1417

**Comment by AlexxIT** [comment]
You can check master version (available via addon/docker). If there are no problems in it, I'll make a release.
