### ISSUE TITLE
WebRTC card stuck in loading with go2rtc v1.9.5

### ISSUE THREAD

**Issue by steuerlexi** [AlexxIT/go2rtc#1417]
With version 1.9.5 the webRTC card stuck in loading even if you configured a entity directly.

<img width="998" alt="image" src="https://github.com/user-attachments/assets/7948e182-6f8f-41d8-a01c-b79f8eab193d">

**Comment by Vorta** [comment]
Same issue. Have 3 cameras no longer loading after updating to v1.9.5.

**Comment by nmatei** [comment]
I've restored to preview version and works again.

**Comment by AlexxIT** [comment]
Source of the problem https://github.com/AlexxIT/go2rtc/pull/1355

**Comment by simonjh88** [comment]
Same here. Just updated, even restarted HA, no different. Checked multiple devices.

**Comment by 19lucian71** [comment]
Same here. Just updated, even restarted HA

**Comment by simonjh88** [comment]
How do we roll back? Never had to do that before....

**Comment by AlexxIT** [comment]
I'll try to publish fix today.

**Comment by AlexxIT** [comment]
You can check master version (available via addon/docker). If there are no problems in it, I'll make a release.

**Comment by mooseBringer** [comment]
I have the same problem. The stream does not appear in go2rtc addon. After reverting back to 1.9.4 it appears directly in the streams tab.

**Comment by Atsukio** [comment]
@AlexxIT Just wanted to confirm that the master version works perfectly on my end.

**Comment by TheScubadiver** [comment]
> How do we roll back? Never had to do that before....

Check Settings > System > Backups.

**Comment by simonjh88** [comment]
> > How do we roll back? Never had to do that before....
> 
> Check Settings > System > Backups.

The problem with that, is that it's going to revert any other changes or data collection since that point.... which is not ideal for me. I'll wait it out.

**Comment by TheScubadiver** [comment]
> > > How do we roll back? Never had to do that before....
> 
> > 
> 
> > Check Settings > System > Backups.
> 
> 
> 
> The problem with that, is that it's going to revert any other changes or data collection since that point.... which is not ideal for me. I'll wait it out.

I mean, only revert the go2rtc backup file.

**Comment by liakjim** [comment]
I fix this issue by adding the stream to addon config. 
Then at my custom wertc card i called the name of the camera. 

```type: custom:stack-in-card
cards:
  - type: custom:webrtc-camera
    url: camera1
    camera_view: live
    entities: null
  - type: entities
    entities:
      - entity: select.tapo_camera_motion_detection
        name: Motion Sensor
    style: |
      ha-card.type-entities {
        margin-right: 14px;
      }
      ha-card.type-entities #states {
        padding-top: 10px;
      }
```

**Comment by AlexxIT** [comment]
Better to check the master version and report the result. So many people have reported the problem and only three have tested the fix.

**Comment by AlexxIT** [comment]
The master version is not an update. It is a separate test version that must be installed manually instead of the release version.

**Comment by steuerlexi** [comment]
> The master version is not an update. It is a separate test version that must be installed manually instead of the release version.

I now have tested it. Works fine with all 9 camera´s that i Have 👍

**Comment by xitters** [comment]
> You can check master version (available via addon/docker). If there are no problems in it, I'll make a release.

Works perfectly master version for me

**Comment by RonnieRocket2** [comment]
Same problem here, had to go back to 1.9.4, I must learn to do a full backup every time I update though.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.6

**Comment by AlexxIT** [comment]
There is only one problem - Hass doesn't support selecting the addon version when installing.
The previous version isn't going anywhere. There's just no way to install it

**Comment by steuerlexi** [comment]
I updated the addon store and have been offered the 1.9.6 which I installed and works just fine. Thank you very much for that fast solution! 🤝

**Comment by simonjh88** [comment]
Thanks for quick turnaround @AlexxIT !

**Comment by mooseBringer** [comment]
Works great now, thanks @AlexxIT!
