### ISSUE TITLE
go2rtc 1.9.6 memory usage

### ISSUE THREAD

**Issue by berniecruz** [AlexxIT/go2rtc#1422]
I’ve noticed that version 1.9.6 continually increases memory usage, as observed in the system monitor, even when the processor is idle. Version 1.9.5, on the other hand, remains stable and does not cause a similar rise in memory usage.

**Comment by nmatei** [comment]
-- on camera views I get --
Cannot connect to host localhost: 1984 ssl:default [Multiple exceptions: [Errno 111] Connect call failed (::1', 1984, 0, 0), [Errno 111] Connect call failed ('127.0.0.1',
-- going to addons --
The add-on is not running. Do you want to start it now?
--
I guess this is related to memory usage, as after 1 day go2rtc crashes and need to restart it.
i'm using more cameras and that could lead to memory leeks.

**Comment by AlexxIT** [comment]
This one #1241
