### ISSUE TITLE
Support environment vars for config

### ISSUE THREAD

**Issue by kitchung** [AlexxIT/go2rtc#143]
Great project and easy to use!

I'd be wonderful if go2rtc.yaml can support use of:

>1. !include to modularize the config like Home Assistant
>>a. https://www.home-assistant.io/docs/configuration/splitting_configuration/
> 2. secrets.yaml file like Home Assistant
>>a. https://www.home-assistant.io/docs/configuration/secrets/
> 3. env vars like Frigate does with {FRIGATE_RTSP_PASSWORD}
>>a. https://docs.frigate.video/configuration/index#full-configuration-reference

**Comment by AlexxIT** [comment]
I don't think the go2rtc config has to be so complicated to support feature 1 or feature 2.
But, supporting the environment makes sense.
