### ISSUE TITLE
I always get rstp input error

### ISSUE THREAD

**Issue by maverik80** [AlexxIT/go2rtc#144]
good morning guys and happy new year, i'm using webrtc and go2 rtc at the latest versions but i'm always getting this error, and i can't get out of it, i'm new but i would like to understand, i'm using three rtsp streams but i keep getting error like in the pictures following and I would like to understand what I'm doing wrong, if I activate the watchdog it continues to work even if the component crashes. thank you all so much for being available
![error_go2rtc](https://user-images.githubusercontent.com/62015384/210344608-29985399-17c9-4189-baf5-dbd224df4f52.png)

**Comment by promowest** [comment]
Hi there and happy new year!
The same problem when I try view camera outside the local network where based the Home Assistant on Raspberry Pi 4.

When I'm home, on local network, everything goes fine. Video and audio. After living home... WebCRT card has nothing to show.

Thanks!

![F6B1AAD7-7BDD-4ABC-B197-9CDF9CCB9FE6](https://user-images.githubusercontent.com/118571835/211145480-0c95e68e-6cf6-4eaa-95d5-613d85f52195.jpeg)

**Comment by promowest** [comment]
Solved. You have to open the UDP range ports from your router, to your Home Assistant fix IP. Working smooth, with video + audio (one way). For two ways audio... Searching forward for a solution.

![DF59A670-5257-4716-A304-79BCB48F5FD8](https://user-images.githubusercontent.com/118571835/211167641-0dce1a06-cf8e-4e5e-a782-a24e32436b20.jpeg)

**Comment by maverik80** [comment]
> Solved. You have to open the UDP range ports from your router, to your Home Assistant fix IP. Working smooth, with video + audio (one way). For two ways audio... Searching forward for a solution.
> 
> ![DF59A670-5257-4716-A304-79BCB48F5FD8](https://user-images.githubusercontent.com/118571835/211167641-0dce1a06-cf8e-4e5e-a782-a24e32436b20.jpeg)

I use proxmox with VM and home assistant, in this case what port range do you have open? I only read about the 8554 and 8555. Thanks

**Comment by promowest** [comment]
I've opened only the UDP, in large range... Because I saw that the UDP ports used changes randomly.

**Comment by maverik80** [comment]
> Ho aperto solo l'UDP, in un ampio raggio... Perché ho visto che le porte UDP utilizzate cambiano in modo casuale.

well yes it's a solution but opening all those ports is not healthy .... for rtsp with Webrtc it says to listen to traffic on 8555 but anyway I get the same problems

**Comment by NickM-27** [comment]
> well yes it's a solution but opening all those ports is not healthy .... for rtsp with Webrtc it says to listen to traffic on 8555 but anyway I get the same problems

That's for TCP, the other user is referring to udp ports.

**Comment by maverik80** [comment]
> > beh si è una soluzione ma aprire tutte quelle porte non è salutare.... per rtsp con Webrtc dice di ascoltare traffico su 8555 ma comunque ottengo gli stessi problemi
> 
> Questo è per TCP, l'altro utente si riferisce alle porte udp.

sorry then I didn't understand what I should do, now on my Fritz I opened port 8555 in udp. which ones should I open and which range?

**Comment by AlexxIT** [comment]
In the future, it is better to attach logs as text, not as pictures. No need to change anything for the already attached logs.

**Comment by AlexxIT** [comment]
I hope problem fixed in https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.7
If not, please reopen issue.

**Comment by maverik80** [comment]
> Spero che il problema sia stato risolto in https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.7 In caso contrario, riaprire il problema.

thank you very much, the problem seems solved, I have no more errors, I will test until tomorrow. if everything is fine, I close the problem. thanks a lot again
