### ISSUE TITLE
Nest Cameras via Nest Integration no longer stream via Hass

### ISSUE THREAD

**Issue by edward3600** [AlexxIT/go2rtc#1440]
I am on Version: 1.9.6. Go2rtc installed as add-on on HA supervised. 

Problem occurred after updating Home Assistant to 2024.11

All nest cameras (i.e., Nest Doorbell and Outdoor Nest Cam) still streams fine via Nest integration, just not from go2rtc. They worked well prior to 2024.11.

Could this be related to changes in 2024.11 relating to camera streams?

https://www.home-assistant.io/blog/2024/11/06/release-202411/ 

This is my first post. Feel free to let me know if I missed relevant details that would help in troubleshooting/etc.

**Comment by felipecrs** [comment]
[Source: nest](https://github.com/AlexxIT/go2rtc#source-nest) can be used as an alternative.

**Comment by edward3600** [comment]
> [Source: nest](https://github.com/AlexxIT/go2rtc#source-nest) can be used as an alternative.

Thanks. I managed to get it to work with [https://github.com/AlexxIT/go2rtc/issues/1440#issuecomment-2462766842](url).

I had to dig up the required secret keys and tokens from /config/.storage/core.config_entries.

One thing I learned from my testing: I tried removing Nest integration and to reconfigure it again with 2024.11. It simply wouldn't want to be configured and just ends with 'error'.

When I rolled-back to 2024.10, I was able to get Nest integration to work again. So it is more than likely the cause for the problems seen with streaming Hass. But as mentioned before, I am able to get it to work with [https://github.com/AlexxIT/go2rtc/issues/1440#issuecomment-2462766842](url)

**Comment by peterguy04** [comment]
Hi @edward3600 

How did you add in the keys? I got them out of core.config_entries, but it's giving me error 400 or 404 depends (there was a weird 1// on 1 key) 

Did you have to do anything else other than add them in to the g2r config ?

**Comment by edward3600** [comment]
> Hi @edward3600
> 
> How did you add in the keys? I got them out of core.config_entries, but it's giving me error 400 or 404 depends (there was a weird 1// on 1 key)
> 
> Did you have to do anything else other than add them in to the g2r config ?

Hi @peterguy04, yes I recall the weird 1// too and I just included it in the go2rtc config. I too struggled to get it to work initially and I also had to refer to the https://console.developers.google.com/apis/credentials and https://console.nest.google.com/device-access/ to double check some values.

**Comment by peterguy04** [comment]
@edward3600 

Thanks for your reply, worked this time. not sure why it didn't last time.

**Comment by eric10k93** [comment]
I am looking for a fix for this too... I should have all the right values for the nest config in go2rtc... did you have to do anything special like quoting the tokens, or for characters like the // did you have to escape them?

**Comment by peterguy04** [comment]
> I am looking for a fix for this too... I should have all the right values for the nest config in go2rtc... did you have to do anything special like quoting the tokens, or for characters like the // did you have to escape them?

No, nothing special, but let go2rtc create the link for you rather than doing them manually

Add the values in the add tab of go2rtc under the nest option 

Device ID & Secret  -https://console.developers.google.com/apis/credentials

Project ID - https://console.nest.google.com/device-access/

Refresh token - /config/.storage/core.config_entries (search this file for "nest"  and get the token.

I think refresh token has a weird 1// before it,dont remove that.

Then click login and wait a few seconds, it will create a list of links, for each camera.  Copy and paste these into config as normal

**Comment by NodeJSmith** [comment]
@peterguy04 @eric10k93 What did you guys use for device id? Is this the HA entity id or something from Nest/Google directly? That's the one item I haven't been able to find in my config files or in either development console

**Comment by peterguy04** [comment]
@NodeJSmith 

I believe you can get the device ID from the Google home app  from Camera > settings > device information 

But tbh manually creating the URL never worked for me, using the nest option in the go2rtc webui populated the links for me and they worked great (didn't need device ID)

**Comment by eric10k93** [comment]
@NodeJSmith, yep, much easier to use the Nest option in go2rtc, so it's a much more guided setup... but if you do need the device id, the easiest way I know of to get it is through HA... set up a new automation using your Nest device and then just switch to the yaml view and it will show the device id

**Comment by NodeJSmith** [comment]
For some reason the settings page in the addon would only provide me one url, when i have two cameras. I was able to get the other using the code in the nest api here. In case anyone else stumbles upon this, the below python script will get you the ids, assuming you have everything else:

```python
import os

import requests

get_access_token_url = "https://www.googleapis.com/oauth2/v4/token"

client_id = os.environ.get("NEST_CLIENT_ID")
client_secret = os.environ.get("NEST_CLIENT_SECRET")
refresh_token = os.environ.get("NEST_REFRESH_TOKEN")
project_id = os.environ.get("NEST_PROJECT_ID")

data = {
    "grant_type": "refresh_token",
    "client_id": client_id,
    "client_secret": client_secret,
    "refresh_token": refresh_token,
}

res = requests.post(get_access_token_url, data=data)
resv = res.json()

access_token = resv["access_token"]

get_devices_url = f"https://smartdevicemanagement.googleapis.com/v1/enterprises/{project_id}/devices"


headers = {"Authorization": f"Bearer {access_token}"}

res = requests.get(get_devices_url, headers=headers)

device_data = res.json()

replace_value = f"enterprises/{project_id}/devices/"
for device in device_data["devices"]:
    device_type = device["type"]
    if device_type != "sdm.devices.types.CAMERA":
        continue

    display_name = device["parentRelations"][0]["displayName"]

    device_id = device["name"]
    device_id = device_id.replace(replace_value, "")

    print(f"Device Name: {display_name!r}, Device ID: {device_id!r}")

```

**Comment by Matuuu96** [comment]
I get answer "no sources" when pressing login. Where can i enter device id? On Go2RTC GUI i only have "client_id", "client_secret", "regresh_token" and "project_id" boxes.

**Comment by NodeJSmith** [comment]
@Matuuu96 you don't input the device id. After pressing login it should output a url per camera (although when I did it I only got one url even though I have two cameras, so I think there is a bug there somewhere). If it's saying no sources then it likely isn't seeing any cameras - possibly the same bug that impacted me, but hard to say on that. If you're comfortable with python you can use the script I posted above to get your device ids

**Comment by Matuuu96** [comment]
I got device ids like this:
> [@NodeJSmith](https://github.com/NodeJSmith), yep, much easier to use the Nest option in go2rtc, so it's a much more guided setup... but if you do need the device id, the easiest way I know of to get it is through HA... set up a new automation using your Nest device and then just switch to the yaml view and it will show the device id

But yeah still "no source"

**Comment by top1dash** [comment]
> > I am looking for a fix for this too... I should have all the right values for the nest config in go2rtc... did you have to do anything special like quoting the tokens, or for characters like the // did you have to escape them?
> 
> No, nothing special, but let go2rtc create the link for you rather than doing them manually
> 
> Add the values in the add tab of go2rtc under the nest option
> 
> Device ID & Secret -https://console.developers.google.com/apis/credentials
> 
> Project ID - https://console.nest.google.com/device-access/
> 
> Refresh token - /config/.storage/core.config_entries (search this file for "nest" and get the token.
> 
> I think refresh token has a weird 1// before it,dont remove that.
> 
> Then click login and wait a few seconds, it will create a list of links, for each camera. Copy and paste these into config as normal

I have entered in my credential in the add page, and the logs appear like it's working, but when i click on the stream link, it is all black.  I can see the stream in my google home app just fine.  Is there something i can paste here to help you see my config without revealing too many credentials?  Thanks for any help.  Both Gemini and Claude have failed to figure this out over a 2 week trial and error period.
