### ISSUE TITLE
How to achieve two-way voice

### ISSUE THREAD

**Issue by loveula** [AlexxIT/go2rtc#1460]
Please tell me how to use tapo c210 to achieve two-way voice function. I am in go2rtc.yaml that content is edited as follows . But the interface still does not display the 2 way audio option function .Please tell me how to do it .  Thank you!!
```
streams:
  camera.kitchen:
    - rtsp://<user>:<pass>@192.168.0.XXX/stream2
    - tapo://<admin:cloud password md5 hash upercase>@192.168.0.XXX
```

**Comment by AlexxIT** [comment]
What interface you talking about?

**Comment by loveula** [comment]
I refer to the operation method of this video. But 2 way audio does not appear in the stream option command of go2rtc.
https://www.youtube.com/watch?v=WnRJxneCUYE
![1731617156925](https://github.com/user-attachments/assets/f5d5c889-4c96-44bb-a90c-71503810c608)

**Comment by AlexxIT** [comment]
You should go to links page and select two way audio option there. You should have HTTPS access for your go2rtc WebUI.

**Comment by loveula** [comment]
Is this the option? But I still don’t have the microphone function after pressing it. Is it normal? Or do I need other settings?
![1731667659083](https://github.com/user-attachments/assets/fc11b2ab-1d2e-4003-a01e-ea5b8ec8dbbd)

**Comment by loveula** [comment]
Also, if I want to use go2rtc, do I need to install Frigate? Thank you!

**Comment by AlexxIT** [comment]
1. Are you sure `tapo` protocol works for you? You can leave it as single source and check video/audio from camera. If you have new camera firmware - it won't work for you
2. Are you sure you using HTTPS?

**Comment by loveula** [comment]
1. I can use go2rtc to view the video/audio from the camera. But I just can’t use the microphone function.
My tapo camera has a two-way voice function.
2.Yes, I am using HTTPS. But do webrtc settings and rtspTowebrtc also require related settings?

**Comment by AlexxIT** [comment]
You didn't answer my first question. Are you sure if the `tapo` protocol works for you?
With your config you getting video/audio from RTSP protocol.

**Comment by loveula** [comment]
I checked that my monitor firmware version is 1.4.3. Will this have any impact?

**Comment by AlexxIT** [comment]
You should leave ONLY tapo source and check. You don't needs rtsp source in your config.

**Comment by loveula** [comment]
Thank you sir . I got it . I deleted rtsp and left only tapo. But there is still only video and no microphone sound.
streams:
  camera.kitchen:
    - tapo://<admin:cloud password SHA-256 hash upercase>@192.168.0.XXX

**Comment by loveula** [comment]
Thank you!I tested it on my mobile phone and it worked normally.
Also, I would like to ask how to add a microphone button function to the interface?

**Comment by AlexxIT** [comment]
To add a microphone, it is necessary to have someone with JavaScript skills program it.
