### ISSUE TITLE
STUN: Candidate Error With IPv6

### ISSUE THREAD

**Issue by redelacruz** [AlexxIT/go2rtc#148]
When using STUN to obtain the external IP address of a server with an IPv6 address for WebRTC as per the instructions, go2rtc produces the following error:

```
12:08:12.926 WRN [webrtc] candidate error="address 2001:4451:xxxx:xxxx:xxxx:d23a:8555: too many colons in address"
12:08:16.962 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:197 > stream.AddConsumer error="sources unavailable: 1"
12:08:16.962 ERR [api.hass] exchange SDP error="sources unavailable: 1"`
```

**Comment by AlexxIT** [comment]
Fixed in https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.7

**Comment by redelacruz** [comment]
Just tested. Works now! Bravo on the quick fix! 👏
