### ISSUE TITLE
New Tapo firmware causes 401 authorization error

### ISSUE THREAD

**Issue by frstep** [AlexxIT/go2rtc#1482]
I upgraded a Tapo D130 to the latest firmware (1.1.9, 240716) and lost the ability to connect via
tapo://<accountpassword>@<IP_address>

I fixed this by switching the camera with one that was running and older firmware version (1.1.8).

I've not investigated this further, but thought I'd put this in the issue tracker in case this is something of which other people should be aware.  Tonight I'll try downgrading the first camera.

**Comment by AlexxIT** [comment]
There are similar issues. Do a search. I don't have a number near me.
