### ISSUE TITLE
No sound on HTTP-FLV

### ISSUE THREAD

**Issue by niklzz** [AlexxIT/go2rtc#1486]
Hi, there is an HTTP-FLV stream with the following parameters
<img width="507" alt="image" src="https://github.com/user-attachments/assets/408b361f-e738-4831-8de0-b8d8013faf5d">

but after adding a stream to go2rtc and viewing the rtsp stream, there is no sound.
this is how the probe section looks like, you can see that only the video stream is recognized

<img src="https://github.com/user-attachments/assets/8b2e7e9a-1b5c-4beb-80e2-2f9affbf737b" width=50% height=50%>

any idea how to fix it?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/30

I'm not sure if mp3 codec can be used inside web browser (for mp4 container). It's very rare codec for IP-cameras. So the task is not a priority.
You can use transcoding to some popular web codec.

**Comment by niklzz** [comment]
> You can use transcoding to some popular web codec.

how do I do that?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-ffmpeg

**Comment by niklzz** [comment]
> https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-ffmpeg
 
already try it, but i get errors
![image](https://github.com/user-attachments/assets/7ebf4302-8ce4-4278-a36b-769c76062fef)

in config i try
- ffmpeg:http://192.168.0.100:8081/stream/9210843#video=h264
and
- ffmpeg:http://192.168.0.100:8081/stream/9210843#video=h264#audio=pcmu

**Comment by niklzz** [comment]
> Probably this is stream from dom.ru

Без вариантов, не победить?)

**Comment by niklzz** [comment]
> You can try to use very old docker versions of go2rtc container.

Могли бы примерно подсказать номер сборки или что искать в ченжлоге?

**Comment by AlexxIT** [comment]
I have no idea where was old ffmpeg. You should try 1.0 - 1.8

**Comment by niklzz** [comment]
> I have no idea where was old ffmpeg. You should try 1.0 - 1.8

Попробовал сборку 1.0, но звука в стриме так и нет

![image](https://github.com/user-attachments/assets/6e923032-b484-4986-a970-02da0e01ee15)

получается ничего с этим не сделать?

**Comment by AlexxIT** [comment]
Have you used ffmpeg for transcoding audio?

**Comment by niklzz** [comment]
> Have you used ffmpeg for transcoding audio?

спасибо, заработало на сборе 1.5 с параметрами #video=h264#audio=pcmu

**Comment by AlexxIT** [comment]
Better to use #video=copy#audio=opus
