### ISSUE TITLE
Akuvox camera issue

### ISSUE THREAD

**Issue by yurkiv** [AlexxIT/go2rtc#1488]
I got error
`streams: wrong transport: RTP/AVP;unicast;mode=play;client_port=;server_port=51242-51243`
when I try to open my Akuvox door camera stream

My logs
20:28:14.514 | info | go2rtc version=1.9.7 platform=linux/amd64 revision=dbe9e4a
-- | -- | --
20:28:18.978 | trace | [api] ws msg type=webrtc/candidate
20:28:18.979 | trace | [webrtc] remote candidate=candidate:2487963791 1 udp 1686052607 46.172.151.41 64612 typ srflx raddr 192.168.31.31 rport 64612 generation 0 ufrag +nUt network-id 1 network-cost 10
20:28:18.983 | trace | [rtsp] client request:DESCRIBE rtsp://52.57.115.41:554/0C11051A945D RTSP/1.0CSeq: 1Accept: application/sdpRequire: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.9.7
20:28:19.014 | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedDate: Fri, Nov 29 2024 18:28:18 GMTServer: Streaming Server v0.1Session: qXnb3TMDM5jg7Fo4Q0edWww-Authenticate: Digest realm="AK VRTSPD", nonce="275939c124f841c7ecd9b4e9c57a64ed"Cseq: 1
20:28:19.014 | trace | [rtsp] client request:DESCRIBE rtsp://52.57.115.41:554/0C11051A945D RTSP/1.0Require: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.9.7CSeq: 2Authorization: Digest username="ak", realm="AK VRTSPD", nonce="275939c124f841c7ecd9b4e9c57a64ed", uri="rtsp://52.57.115.41:554/0C11051A945D", response="1804f4e11b3bdff5f815909ee27d52f6"Accept: application/sdp
20:28:19.047 | trace | [rtsp] client response:RTSP/1.0 200 OKServer: Streaming Server v0.1Session: qXnb3TMDM5jg7Fo4Q0edContent-Base: rtsp://52.57.115.41:554/live/ch00_0/Content-Length: 283Content-Type: application/sdpCseq: 2Date: Fri, Nov 29 2024 18:28:19 GMTv=0o=- 1 1 IN IP4 52.57.115.41s=Easy Rtsp 1.0i=Easyc=IN IP4 0.0.0.0t=0 0m=video 0 RTP/AVP 96b=AS:5000a=rtpmap:96 H264/90000a=fmtp:96 profile-level-id=42E01F;packetization-mode=1;sprop-parameter-sets=Z0LAM6tAWgk0IAAAAwAgAAAGUeMGVA==,aM48gA==a=control:trackID=0
20:28:19.047 | trace | [streams] check cons=0 prod=0 media=video, recvonly, H264
20:28:19.048 | trace | [streams] match cons=0 <= prod=0
20:28:19.048 | trace | [rtsp] client request:SETUP rtsp://52.57.115.41:554/live/ch00_0/trackID=0 RTSP/1.0Transport: RTP/AVP/TCP;unicast;interleaved=0-1CSeq: 3Authorization: Digest username="ak", realm="AK VRTSPD", nonce="275939c124f841c7ecd9b4e9c57a64ed", uri="rtsp://52.57.115.41:554/live/ch00_0/trackID=0", response="046dffffb7067da90c3ef692b6abfb3b"
20:28:19.047 | trace | [streams] check cons=1 prod=0 media=video, recvonly, H264
20:28:19.048 | trace | [streams] match cons=1 <= prod=0
20:28:19.074 | trace | [api] ws msg type=webrtc/candidate
20:28:19.075 | trace | [api] ws msg type=webrtc/candidate
20:28:19.075 | trace | [webrtc] remote candidate=candidate:2657824616 1 tcp 1518280447 192.168.31.31 9 typ host tcptype active generation 0 ufrag +nUt network-id 1 network-cost 10
20:28:19.076 | trace | [webrtc] remote candidate=
20:28:19.078 | trace | [rtsp] client response:RTSP/1.0 200 OKCache-Control: no-cacheCseq: 3Date: Fri, Nov 29 2024 18:28:19 GMTServer: Streaming Server v0.1Session: qXnb3TMDM5jg7Fo4Q0edTransport: RTP/AVP;unicast;mode=play;client_port=;server_port=52404-52405X-Rtp-Confuse: 0
20:28:19.079 | info | [streams] can't get track error=wrong transport: RTP/AVP;unicast;mode=play;client_port=;server_port=52404-52405

**Comment by AlexxIT** [comment]
This is very bad camera with wrong RTSP protocol realisation. Try to use ffmpeg source.
```
streams:
  camera1: ffmpeg:rtsp://...
  camera2: ffmpeg:rtsp://...#input=rtsp/udp
```
