### ISSUE TITLE
hevc even if video=h264 is set

### ISSUE THREAD

**Issue by woody4165** [AlexxIT/go2rtc#1495]
Hi all

I have this config, but if I go in the Net visualization I see hevc as video stream

```
  patio2:
  - rtsp://xxx:xxxx@192.168.1.135:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
  - ffmpeg:patio2#video=h264#audio=opus#audio=aac
```

![Screenshot 2024-12-03 alle 21 03 59](https://github.com/user-attachments/assets/f84479d0-47c2-4b0b-b684-9d51178d2b07)

It's an Imou cam IPC-F42D model

What can I do to force h264?

Thanks

**Comment by AlexxIT** [comment]
It's normal config and normal net. You showing first source of your stream. `127.0.0.1` is ffmpeg.
