### ISSUE TITLE
Aqara G4 basic setup questions

### ISSUE THREAD

**Issue by T1mey** [AlexxIT/go2rtc#1502]
Hello,

is there any way to get the Aqara G4 doorbell working without an Apple device (Homekit) with go2rtc?
I want to stream the video to a Google Nest Hub 2 if somebody pushes the bell.

Any advice would be helpful, otherwise I need to switch to the ugly reolink bell ;-)

**Comment by DMedina559** [comment]
If you have home assistant you could probably use the homekit device integration

**Comment by T1mey** [comment]
> If you have home assistant you could probably use the homekit device integration

Do I need an Apple device to host a homekit server (device)? Or could I usw the integration in HA standalone?

**Comment by DMedina559** [comment]
> > If you have home assistant you could probably use the homekit device integration
> 
> Do I need an Apple device to host a homekit server (device)? Or could I usw the integration in HA standalone?

No apple device required. I think you just need a Bluetooth adapter connected to HA if it uses that to pair 

https://www.home-assistant.io/integrations/homekit_controller/

**Comment by T1mey** [comment]
I completed the setup and can confirm that it's working.
Complicated setup but my usecase ist now working.

**Comment by Chewwwy92** [comment]
@T1mey is there anyway you could explain how you got this working? I have the aqara g4 set up as a homekit device but really want to get the stream of it. I would like to add it to frigate.

**Comment by T1mey** [comment]
> [@T1mey](https://github.com/T1mey) is there anyway you could explain how you got this working? I have the aqara g4 set up as a homekit device but really want to get the stream of it. I would like to add it to frigate.

basically you'll need to add it to 

apple home
aqara app (frome apple home)
homekit
go2rtc

and you will get the stream url's in/over go2rtc
