### ISSUE TITLE
Does Go2RTC stream Tapo cameras to HomeKit using the Tapo protocol with two-way audio support?

### ISSUE THREAD

**Issue by ch155260** [AlexxIT/go2rtc#1508]
I have tried streaming to HomeKit using both the Tapo and RTSP protocols, but I still can't hear my voice from the camera.

**Comment by AlexxIT** [comment]
1. go2rtc doesn't support HomeKit with two way audio yet.
2. Tapo has PCMA audio which doesn't supported in HomeKit protocol and you should use transcoding to OPUS.
