### ISSUE TITLE
wrong PIN format when clicking pair

### ISSUE THREAD

**Issue by humanBeer** [AlexxIT/go2rtc#151]
Not sure what to do
![image](https://user-images.githubusercontent.com/47748428/211094075-c8f00bcf-e5d6-4e50-abcb-257b6902fe0c.png)

 
When i click on pair:
![image](https://user-images.githubusercontent.com/47748428/211093814-52fcc9c2-b7aa-4d3c-a465-f027ac3147ca.png)

**Comment by NickM-27** [comment]
You need to enter the pin in the text box above before hitting pair

**Comment by humanBeer** [comment]
omg thats embarassing, i guess im blind

**Comment by humanBeer** [comment]
![image](https://user-images.githubusercontent.com/47748428/211098301-59dc6129-ad32-4efe-be57-4c6a08007af6.png)
well now i get this.

**Comment by AlexxIT** [comment]
As you already using Hass - it's better to pair camera with it. It is done more clearly in the interface there.
After that you can use this camera in go2rtc.
