### ISSUE TITLE
the config not work without internet

### ISSUE THREAD

**Issue by egmsystems** [AlexxIT/go2rtc#1518]
require 2 files
https://unpkg.com/ace-builds@1.33.1/src-min/mode-yaml.js
in 
http://go2rtc:1984/editor.html:35
const editor = ace.edit('config', {
    mode: 'ace/mode/yaml',
});
and
https://unpkg.com/ace-builds@1.33.1/src-min/theme-tomorrow_night_eighties.js
in
http://go2rtc:1984/main.js](http://192.168.0.161:1984/main.js:188
updateDarkMode();

**Comment by AlexxIT** [comment]
There are more external dependencies in go2rtc. All of them are not required to provide the basic functions. There are no plans to add them to the binary.

If you really want to - you can connect your local UI to the go2rtc binary. See the documentation for details
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-api
