### ISSUE TITLE
Version v1.9.7, when the input source is empty, pushes the video stream to RTSP through ffmpeg, and the frontend cannot preview the video stream

### ISSUE THREAD

**Issue by syvince** [AlexxIT/go2rtc#1523]
In version v1.9.7docker, when the input source is empty, the video stream is pushed to RTSP via ffmpeg, causing the frontend to be unable to preview the video stream.
reproduce issue:
I create go2rtc.yaml
```
streams:
  right:
  left:
  front:
  back:
  test:
  
rtsp:
  listen: ":8554"  
```
By using Python to output the object detection results to the RTSP empty stream, it can be seen in the net program that there is indeed input, but the front-end cannot open the video stream. When I switched to 1.9.4, this problem was solved

Here is the Python code I used
```
from ultralytics import YOLO
import cv2
import subprocess
import numpy as np

weight_path = "yolov8s.pt"
det_model = YOLO(weight_path)

camera_path = "test.mp4"

cap = cv2.VideoCapture(camera_path)
original_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
original_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))


rtsp_server_url = "rtsp://192.168.100.138:8554/test"
command = ['ffmpeg',
           '-y',
           '-f', 'rawvideo',
           '-pixel_format', 'bgr24',
           '-video_size', f'{original_width}x{original_height}',
           '-r', str(fps),
           '-i', '-',
           '-c:v', 'libx264',
           '-pix_fmt', 'yuv420p',
           '-preset', 'ultrafast',
           '-tune', 'zerolatency',
           '-f', 'rtsp',
           rtsp_server_url]
proc = subprocess.Popen(command, stdin=subprocess.PIPE)


while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    results = det_model.predict(frame, verbose=False)
    annotated_frame = results[0].plot()
    proc.stdin.write(annotated_frame.tobytes())


cap.release()
proc.stdin.close()
proc.wait()
```
By the way, may I ask if go2rtc can use hardware acceleration to speed up the RTSP stream to RTC for this input method that uses empty streams? I am using ffmpeg to push RTSP externally, Because the go2rtc service is on the public network and the camera stream is on the local area network, I am unable to write the ffmpeg command in the configuration of go2rtc

**Comment by syvince** [comment]
By the way, may I ask if go2rtc can use hardware acceleration to speed up the RTSP stream to RTC for this input method that uses empty streams? I am using ffmpeg to push RTSP externally

**Comment by AlexxIT** [comment]
This is probably fixed in latest master version.

**Comment by syvince** [comment]
Thank you very much, Got it. May I ask if go2rtc can use hardware acceleration to speed up the RTSP stream to RTC for this input method that uses empty streams? I am using ffmpeg to push RTSP externally, Because the go2rtc service is on the public network and the camera stream is on the local area network, I am unable to write the ffmpeg command in the configuration of go2rtc

**Comment by AlexxIT** [comment]
Hardware acceleration only related to transcoding. This part `'-c:v', 'libx264'`. Which you don't use in your software.

**Comment by syvince** [comment]
Thank you very much
