### ISSUE TITLE
I don't understand how to use this

### ISSUE THREAD

**Issue by atv2016** [AlexxIT/go2rtc#157]
Could i get some help ?

I currently use frigate camera entities only, i tried using RTMP but it's like 30 - 1 min behind. 
I also rather not add generic camera entities to add more RTSP streams and load up frigate/NVR/network/HA again.

I've used webrtc in the cards but i can't use that to stream or record, which is one of my use cases. I basically want to stream my frigate camera entities, or failing that, use RTSP if i have to.

Should i use this? How do i set this up ? What is the benefit of this over using generic camera entities with RTSP ?
Once i set this up can i stream/record my camera entities?

Thank you..

**Comment by NickM-27** [comment]
go2rtc is built into frigate 0.12, version 3.0 of https://github.com/AlexxIT/WebRTC is recommended for streaming in lovelace as it connects directly to go2rtc inside frigate. 

that component also enables the ability to cast the stream to a media player.

as far as record goes, you may need to be more specific what you're trying to achieve

**Comment by atv2016** [comment]
Thanks Nick.

So i used to use this with a RTSP stream:

![Screenshot 2023-01-09 at 13 33 53](https://user-images.githubusercontent.com/16917203/211322477-bcf2ea56-6bc9-42d7-a954-806992e78866.png)

If i use this with a camera entity it will say: only RTSP stream supported.
I'm assuming that's what you mean when you say "that component also enables the ability to cast the stream to a media player."

This is the webrtc integration i use
![Screenshot 2023-01-09 at 13 48 58](https://user-images.githubusercontent.com/16917203/211323052-e9fa16a2-db6f-45df-8872-bb9620b9f1b2.png)

So webrtc works fine for lovelace cards, or webrtc dash cast works fine for RTSP, but i can't use frigate camera entities with it directly.

Thanks for your help!

**Comment by NickM-27** [comment]
> So webrtc works fine for lovelace cards, or webrtc dash cast works fine for RTSP, but i can't use frigate camera entities with it directly.

You can use them, you just need to stop trying to use the camera entities and use the parts that are built in go2rtc. Instead of specifying the full rtsp url or anything you just need to specify the name of the camera that is setup in the frigate config. 

This is again assuming you are using frigate 0.12 and WebRTC Camera 3.0

**Comment by AlexxIT** [comment]
This docs: https://github.com/AlexxIT/WebRTC links to v3.0-beta version
But you could have installed an older (release) version with this docs: https://github.com/AlexxIT/WebRTC/tree/v2.3.1

**Comment by atv2016** [comment]
@NickM-27 

I use this in my docker-compose:
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: '256mb'

So assuming that is the latest stable release. Not sure how to check what webrtc version i'm using, i will take a look.
Yeah exactly, that's what i was hoping to do, i just wanted to either use the camera.stream or camera.record with frigate camera entities, but i keep getting the message saying it's not supported.

So you are saying as long as i run the latest frigate + webrtc latest it should work no problem. And these would be non-laggy, non-rtmp RTSP feeds/restreamed from frigate/go2rtc.

**Comment by atv2016** [comment]
> > So you are saying as long as i run the latest frigate + webrtc latest it should work no problem. And these would be non-laggy, non-rtmp RTSP feeds/restreamed from frigate/go2rtc.
> 
> 0.12 is still in beta so that explains why you are confused. In your case you would need RTMP to be enabled for the frigate camera entities to support those features. At this point I'd recommend updating to beta of both components as it should work much better

Aye, i tried RTMP with my current version but that was too laggy for me. But once i use the frigate beta and latest webrtc i don't need RTMP enabled anymore correct? Just going through the beta release notes now. Good stuff.

Anything major change in the frigate that my config would be unaware of :-) ?

Can i just update my docker line from image: blakeblackshear/frigate:stable to  blakeblackshear/frigate-v0.12.0-beta2 ? 

And i see i need to use this rtsp://frigate_ip:8554/config_camera_name rather then specify the frigate camera entity? Or can i do both.

**Comment by NickM-27** [comment]
> Can i just update my docker line from image: blakeblackshear/frigate:stable to blakeblackshear/frigate-v0.12.0-beta2 ?

all the breaking changes are covered at the top of the release notes

> And i see i need to use this rtsp://frigate_ip:8554/config_camera_name rather then specify the frigate camera entity? Or can i do both.

yes you can use that, but the beta frigate integration supports the new rtsp stream with camera entities anyway so no need to create one manually

**Comment by NickM-27** [comment]
> I meant from a i-don't-know-how-to-use-docker kinda way ;-)

You will need to expose port 8554

as far as the camera entities go you need the beta of https://github.com/blakeblackshear/frigate-hass-integration

in both cases you simply open HACS and then select the integration, choose redownload and then select "allow beta versions"

**Comment by atv2016** [comment]
I have frigate installed on a separate host from HA host.
So you are saying i need to enable beta versions for the frigate integration as well.
For the 8554 port expose i assume that's in addition to what i have in my current docker-compose file? e.g.:

          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"   # RTMP feeds



Do i even need webrtc separately if i already have frigate 12? go2rtc/webrtc seems to be included ? or not:
Advanced users - install the [go2rtc](https://github.com/AlexxIT/go2rtc#go2rtc-home-assistant-add-on) or [Frigate 12+](https://docs.frigate.video/) add-on.

**Comment by NickM-27** [comment]
> For the 8554 port expose i assume that's in addition to what i have in my current docker-compose file? e.g.:

yes but you can remove 1935

> Do i even need webrtc separately if i already have frigate 12? go2rtc/webrtc seems to be included ? or not:
Advanced users - install the [go2rtc](https://github.com/AlexxIT/go2rtc#go2rtc-home-assistant-add-on) or [Frigate 12+](https://docs.frigate.video/) add-on.

Correct, just point that integration at frigate_ip:1984 (which you will need to expose as well)

**Comment by atv2016** [comment]
ah yes 1935 is for rtmp which is gone now. gotcha.

so i expose 5000:5000
1984:1984

I guess one can still install webrtc if you want the fast lovelace card streaming ?

**Comment by atv2016** [comment]
I just get this when i click on redownload in HACS btw:


When downloaded this will be located in '/config/custom_components/frigate'
Remember that you need to restart Home Assistant before changes to integrations (custom_components) are applied.

Don't see an option for enabling beta version.

**Comment by NickM-27** [comment]
Maybe a screenshot? It might be behind a 3 dots menu

**Comment by atv2016** [comment]
It's a safari thing it seems, i see it on iPhone.

I have to choose from v4.0.0-beta2 or lower, which one should i choose for the 0.12.0 Beta 2 release?

When is the stable version released?

**Comment by NickM-27** [comment]
4.0.0 beta is directly linked to 0.12 so just the latest version 

And it will be stable when everything is working well, ¯\_(ツ)_/¯﻿ how long that'll be

**Comment by atv2016** [comment]
Do you think my old config would work without troubles ? Maybe i have to remote the rtmp is false line ?

**Comment by NickM-27** [comment]
You will probably need to fix things, which is covered in the breaking changes of the release notes

**Comment by atv2016** [comment]
Thank you so much for your help, i shall give this all a go tonight and pray it works after :-)

**Comment by atv2016** [comment]
size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554"
      - "1984:1984"

Just for making sure, the exposing of the 5000,8554,1984 is done on my frigate instance right. 8554 is the RTSP server, 1984 is the API, i think 1985 is webrtc, do i not need that as well ?

Also i see a comment about the live section going to restream -> jsmpeg. 

live:
  height: 640
  quality: 1

How do i move that/set that up under the new frigate?

**Comment by NickM-27** [comment]
> Just for making sure, the exposing of the 5000,8554,1984 is done on my frigate instance right. 8554 is the RTSP server, 1984 is the API

Correct, and 1984 is the go2rtc api

> i think 1985 is webrtc, do i not need that as well ?

no that is incorrect, 8555 is webrtc if you are not running has host networking mode

> Also i see a comment about the live section going to restream -> jsmpeg.
>
>live:
height: 640
quality: 1
>
>How do i move that/set that up under the new frigate?

Just move it to restream -> jsmpeg

```yaml
restream:
  jsmpeg:
    height: 640
    quality: 1
```

although I don't expect you'll need that anymore since you'd probably want to use the MSE or webrtc live view in frigate

**Comment by atv2016** [comment]
Done.

**Comment by AlexxIT** [comment]
It's better always use network host for every docker container. Except situations when you really know why you need port forward.

**Comment by atv2016** [comment]
Hi Alex, what do you mean by 'use network host for every docker container' ?

**Comment by Maxcodesthings** [comment]
He means to set this in your docker-compose configuration
```
network_mode: host
```
No need to specify ports if you do this it just maps all opened ports to host

**Comment by Maxcodesthings** [comment]
@NickM-27 bless you for this change
> new restream -> video_encoding option which can be used to re-encode the restream

Trying to re-encode for mobile devices at lower resolution was not going well for me, learning all billion options for ffmpeg was killing me. Ill have to look at the rest of this log to see how to set this up. 

Im guessing go2rtc is not needed in this frigate release in favor of it being baked into WebRTC? So the dependency is only WebRTC v3.0

**Comment by NickM-27** [comment]
> Im guessing go2rtc is not needed in this frigate release in favor of it being baked into WebRTC? So the dependency is only WebRTC v3.0

Not sure I follow, go2rtc is baked into frigate and you'd want to have WebRTC 3.0 point at frigate:1984 so it doesn't use its own

**Comment by Maxcodesthings** [comment]
That tracks better, you said that was coming.

So do you need WebRTC in this case if using Frigate Card?

**Comment by NickM-27** [comment]
> So do you need WebRTC in this case if using Frigate Card?

When you setup WebRTC 3.0 it asks for a server to point to, you would give it frigate_ip:1984 so it uses frigates embedded go2rtc server instead of running a separate one, that's all I'm saying.
