### ISSUE TITLE
alpha 0.9 "add" button is not working

### ISSUE THREAD

**Issue by wonderiuy** [AlexxIT/go2rtc#16]
Hello
in HASS I've just upgraded to alpha 0.9 and all my cameras disappeared. Trying to add result in "add" button not working
Auto discovering not working also (Axis IPCam and Anran/Dahua)

**Comment by AlexxIT** [comment]
Can't confirm that. All works fine. Maybe you have errors in addon logs?

**Comment by wonderiuy** [comment]
Restarting HASS still not working. Restarting the go2rtc worked :)

**Comment by AlexxIT** [comment]
Better to check logs before restart. If you have errors there - them should be fixed.

**Comment by wonderiuy** [comment]
After each HASS restart all of the cameras are lost

**Comment by AlexxIT** [comment]
Have you check logs?

**Comment by AlexxIT** [comment]
Check if problem persist in alpha.11

**Comment by wonderiuy** [comment]
It works, thank you
