### ISSUE TITLE
Question 2 way audio with ONVIF T

### ISSUE THREAD

**Issue by KoljaV** [AlexxIT/go2rtc#160]
Hello,

I try to get two audio setup up and running for my Dahua intercom. I sniffed the traffic with Wireshark and the Answer of the RTSP DESCRIBE from go2rtc looks promising (see Media Attribute "send only"):
<img width="618" alt="image" src="https://user-images.githubusercontent.com/25928990/211533945-4f8b3f3b-f9dd-4198-90f0-a179c8839760.png">
However, go2rtc does not initiate the audio backchannel with RTSP SETUP afterwards. 
This is my config:
```
streams:
  dahua_camera:
    - rtsp://admin:admin1234@192.168.178.110/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - ffmpeg:rtsp://admin:admin1234@192.168.178.110/cam/realmonitor?channel=1&subtype=0#audio=opus
```
just copied from the Readme.
Can someone tell me what I am doing wrong?

BR,
Kolja

**Comment by AlexxIT** [comment]
Looks ok. Have trying 2-way-aud page over HTTPS?
Also you not need Wireshark. Just increase log level to trace for rtsp.

**Comment by KoljaV** [comment]
> Looks ok. Have trying 2-way-aud page over HTTPS?
> Also you not need Wireshark. Just increase log level to trace for rtsp.

No, I did not try https. Could that initiate the rtsp SETUP command for audio back channel? I thought that it would not be able to do that as the code cannot see whether people using https or http ...

**Comment by NickM-27** [comment]
https is required for the browser to have access to the microphone

**Comment by KoljaV** [comment]
yeah, that's true. But that would mean that the backchannel would only be initiated if there is audio signals coming from the browser... I will give it a try and come back to that thread.

**Comment by AlexxIT** [comment]
You can temporary disable Chrome browser HTTPS restriction. Just read docs carfelly.

**Comment by KoljaV** [comment]
You were absolutely right. I've set up nginx for https and audio backchannel works! Thanks a lot!!!!!
