### ISSUE TITLE
How to run the binary on linux

### ISSUE THREAD

**Issue by nvvasilev** [AlexxIT/go2rtc#161]
I would like to run the binary on Linux and I tried setting up the following service:

_/etc/systemd/system/go2rtc.service_
```
[Unit]
Wants=network.target
[Service]
ExecStart=/usr/local/bin/go2rtc_linux_amd64
[Install]
WantedBy=multi-user.target
```
And config next to the app: /usr/local/bin/go2rtc.yaml

The app starts successfully and I can reach the Web UI but it looks like the configuration is not loaded because I am missing the configured camera from the config..

 How do I pass the configuration file path to the app 'go2rtc_linux_amd64'?

**Comment by AlexxIT** [comment]
`go2rtc_linux_amd64 -h`

**Comment by nvvasilev** [comment]
:D thanks

**Comment by AlexxIT** [comment]
By defaul go2rtc search config in "current work dir". I think that's the problem.
