### ISSUE TITLE
On-demand (Exec) script runs constantly if RTSP clients times out before source starts publishing

### ISSUE THREAD

**Issue by tsightler** [AlexxIT/go2rtc#163]
I believe there is a bug with exec source (possibly other on-demand sources) when the frontend client times out prior to the backend publishing.  Below you can see the logs from my application along with messages from go2rtc.  You can see that a client connects to the stream initially, and this runs the start-stream.sh script with the correct parameters as it should, this works perfectly to trigger my application code to start a stream.  However, due to various issues (network issues, slow service response, etc) this can sometimes take a long time or even fail completely.

In the case below my code is unable to start the stream before the RTSP client (VLC) times out (5 seconds seems to be the common RTSP timeout).  Overall, this is no big issue, I would expect go2rtc to simply see that it no longer has a client and stop the exec.  However, instead, go2rtc ignores that the client timed out and is no longer requesting the stream and instead keeps running the exec command.  Even if I force kill the script (for example, timeout with an error after 10 seconds), go2rtc will continue to re-run the exec command even though there are no longer any RTSP clients requesting the stream.  As far as I can tell it will do this forever, even if the stream eventually starts publishing.  It seems that, when a frontend client times or errors out, it is never removed as a client, and the on-demand stream effectively becomes an always-on stream.

```
  ring-rtsp [go2rtc] DBG [rtsp] new consumer stream=3ce1a1b144ac_live +7s
  ring-rtsp [go2rtc] DBG [streams] probe producer url=exec:/mnt/c/Users/tsigh/Documents/GitHub/ring-mqtt/scripts/start-stream.sh 3ce1a1b144ac live ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a1b144ac {output} +1ms
  ring-rtsp [go2rtc] DBG [exec] run url="exec:/mnt/c/Users/tsigh/Documents/GitHub/ring-mqtt/scripts/start-stream.sh 3ce1a1b144ac live ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a1b144ac rtsp://localhost:8554/6653381986c34366669eac944e9c06ac" +0ms
  ring-rtsp [Front Porch] Sending command to activate live stream ON-DEMAND +0ms
  ring-mqtt [Front Porch] Received set live stream state ON-DEMAND rtsp://localhost:8554/6653381986c34366669eac944e9c06ac +941ms
  ring-mqtt [Front Porch] ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a1b144ac/stream/state ON +1ms
  ring-attr [Front Porch] ring/a9ce28cb-fafb-421c-4508-29d54f48cbd3/camera/3ce1a1b144ac/stream/attributes {"status":"activating"} +941ms
  ring-mqtt [Front Porch] Starting a live stream session via Ring servers +1ms
  ring-rtsp [Front Porch] State indicates live stream is activating +78ms
  ring-rtsp [go2rtc] WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:202 > error=EOF +5s
  ring-rtsp [go2rtc] WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:202 > error=EOF +3ms
```

**Comment by tsightler** [comment]
Ok, if I understand the code correctly, I think I see why this is happening.  When a new consumer is registered, the code runs stream.AddConsumer() and creates a closer function to be used to remove that consumer once the connection is closed.  However, if the client connection times out, that is handled by error handler at line 202 when closes the connection and returns and never calls the closer() function, at which point, I don't think that the closer function will ever be called, thus there will forever be a consumer.

Admittedly, I've never written any golang, but that's what I think is happening anyway.  Not 100% sure of the proper fix, but maybe just need to call closer in the error handler?  I may give that a spin.

**Comment by tsightler** [comment]
OK, so modifying this code in cmd/rtsp/rtsp.go:
```
	if err := conn.Accept(); err != nil {
		log.Warn().Err(err).Caller().Send()
		_ = conn.Close()
		return
	}
```
to:
```
	if err := conn.Accept(); err != nil {
		log.Warn().Err(err).Caller().Send()
		_ = conn.Close()
		if closer != nil {
			closer()
		}
		return
	}
```

I have no idea if this is the correct way to fix this, but I couldn't reproduce the issue after this.

**Comment by AlexxIT** [comment]
You right! And you make right fix. I'm already did it. But not published yet. Just testing stability and other problems

**Comment by tsightler** [comment]
Great, thanks for confirming!  It seems to work just fine for me now, but maybe next time I'll have to confidence to just open a PR instead.

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.8
