### ISSUE TITLE
Latest 0.1-rc.8 appears to break RTSPtoWebRTC integration with HA when candidates defined

### ISSUE THREAD

**Issue by tsightler** [AlexxIT/go2rtc#165]
Perhaps I'm doing something wrong, but upgrading from 0.1-rc.7 to 0.1-rc.8 appears to break RTSPtoWebRTC integration with Home Assistant.  All I did was upgrade the addon and now I get:

`Failed to connect WebRTC stream: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. candidate:545229448 1 udp 2130706431 76.42.x.x 8555 typ host tcptype passive Invalid non-TCP candidate`

Looks like WebRTC integration in HA is being tripped up by the new UDP port offer?

**Comment by tsightler** [comment]
Hmm...OK, I need to investigate a little deeper as this appears to only be happening on one of my two instances.  Not sure why that would be as they are nearly identical other than the platform arch (one is dev running on Intel VM, the other is prod running on RPi).  It's the prod system that is not working because...well...of course it is!

**Comment by tsightler** [comment]
Seems to break when using candidates config, previous working config:
```
rtsp:
  listen: ""
webrtc:
  listen: ":8555"
  candidates:
    - <my_static_ip>:8555
```

I also tried using stun:8555, which previously would work as well, but this also breaks internal viewing.  If I remove the candidates lines completely, then internal viewing works fine (thus why dev system worked), but no external viewing even with both TCP/UDP forwarded.  When I add the line back it breaks all viewing in HA.

**Comment by NickM-27** [comment]
I'm using the WebRTC card (not using RTSP2WebRTC) & viewing in frigate frontend and just to add anecdotal data, I have no issues with `candidates` defined

**Comment by tsightler** [comment]
Yeah, not too surprising honestly, I feel like the error is coming from the WebRTC side in HA, based on the message feels like it doesn't expect UDP candidates.  I'm sure I could switch to the WebRTC card and it would work.  But, as I have it configured as documented here in this project, and it worked fine before, I thought it was worth reporting.

**Comment by tsightler** [comment]
Ah, I think the issue is that Go2RTC is creating the candidate line incorrectly, it's creating a UDP candidate, but then setting `tcptype passive` which is invalid as tcptype should be null for UDP candidates.

**Comment by felipecrs** [comment]
I can confirm that removing my entire `webrtc:` config "solves" the issue.

**Comment by tsightler** [comment]
I've confirmed that the issues is here:
> candidate:545229448 1 udp 2130706431 76.42.x.x 8555 typ host tcptype **passive**

That should not exist as spec says tcptype for UDP candidates should be null, thus the error message "Invalid non-TCP candidate".   I've submitted a PR for this here:  https://github.com/AlexxIT/go2rtc/pull/166.  Of course @AlexxIT may prefer a different fix.  In my head I wanted to use a conditional, but it seems golang doesn't have those?

**Comment by AlexxIT** [comment]
You right. Golang doesn't have conditional. I rewrote it a little bit. Because `TCPTypeUnspecified` is the default value (0).

https://github.com/AlexxIT/go2rtc/commit/a06462729d49df17ddb425ef9b885c99107837ee

**Comment by tsightler** [comment]
But that looks wrong to me, you have:
```
	if network == "udp" {
		config.TCPType = ice.TCPTypePassive
	}
```

But it's UDP that should be unspecified, so if your default to TCPTypeUnspecified, then you should override to TCPTypePassive for `network == "tcp"`.

**Comment by AlexxIT** [comment]
You right. My bad. Thanks!

**Comment by marcob79** [comment]
I was experiencing the same issue. 
I saw that a fix had been pushed to the master branch and I tested it successfully. 
Many tanks

**Comment by thinkjk** [comment]
Thanks for adding a fix. I'm running into the same issue. I'll wait for the new version to be pushed out.
