### ISSUE TITLE
Config editor shows 404

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#171]
![Screen Shot 2023-01-15 at 14 24 43 PM](https://user-images.githubusercontent.com/14866235/212568091-b679fa75-9966-45b4-9867-c6cd03b0db19.png)

**Comment by NickM-27** [comment]
Being run with `go2rtc -config="/config/frigate-go2rtc.yaml"`

**Comment by AlexxIT** [comment]
Looks like this is response when file not exists. But you can make changes and save file
https://github.com/AlexxIT/go2rtc/blob/cecbe4166c9f7e8b4eb8bd3910be5ae2b9e46151/cmd/api/config.go#L15-L18

**Comment by NickM-27** [comment]
I noticed on the main page it shows a file path for the config file which is incorrect. That may be part of it. 

It looks like go2rtc is appended the file to its run location, but the location I'm passing in is entirely different than that path

**Comment by NickM-27** [comment]
`/run/s6/legacy-services/go2rtc` is the go2rtc working directory and `/config/frigate-go2rtc.yaml` is the directory of the config. 

Go2rtc says the file is at `/run/s6/legacy-services/go2rtc/config/frigate-go2rtc.yaml` which is incorrect

**Comment by AlexxIT** [comment]
Oh. Looks like some problems in go with path join.

**Comment by AlexxIT** [comment]
@NickM-27 you can redownload binaries from rc.9. Them has fix

**Comment by NickM-27** [comment]
I think you can close this, fixed in my testing

**Comment by AlexxIT** [comment]
Should return an empty answer if there is no file. Or do a proper handling of the 404 error on the client.

**Comment by NickM-27** [comment]
This is what I see when only passing a raw config (not a file)

![Screen Shot 2023-01-16 at 07 33 57 AM](https://user-images.githubusercontent.com/14866235/212702705-ff0a1468-9a35-4863-8576-29f9dfb02ae5.png)

![Screen Shot 2023-01-16 at 07 34 05 AM](https://user-images.githubusercontent.com/14866235/212702727-a99f169b-c7f3-46cd-bd20-00fd0c0f2372.png)

I think the first part makes sense, but maybe don't show the config editor if there is no file to write to?

**Comment by AlexxIT** [comment]
Yes. You right.
Also you can pass file (not exist) and raw config. You should see your file (empty) here.

**Comment by NickM-27** [comment]
Fixed in 1.0.0
