### ISSUE TITLE
Env vars not used when sending raw config

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#176]
I have a stream defined with `backyard_cam: "ffmpeg:http://192.168.50.155/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=${FRIGATE_RTSP_USER}&password=${FRIGATE_BACKYARD_PW}#video=copy#audio=copy#audio=opus"` and the env vars are not being substituted despite being set

**Comment by NickM-27** [comment]
it does seem to be used for my `rtsp://user:${PASSWORD}` just not the http_flv example above

**Comment by NickM-27** [comment]
I also tried with a normal rtsp and it doesn't work either. I think this might be due to the config being passed in via raw text as opposed to a config file?

**Comment by AlexxIT** [comment]
Yes. Env vars not processed in raw config because they can be processed by Linux

**Comment by NickM-27** [comment]
Thanks, that makes sense 👍

**Comment by AlexxIT** [comment]
Oh. You plan to use this with this issue
https://github.com/blakeblackshear/frigate/pull/5106

**Comment by NickM-27** [comment]
Well we just wanted to understand, if it's purposefully not supported then we can support it manually, just wanted to make sure it would be consistent and not conflict.

**Comment by AlexxIT** [comment]
I can add this parsing. It's just a single line. But I think it's not make sense in real life

**Comment by NickM-27** [comment]
Agreed 👍

**Comment by AlexxIT** [comment]
Btw. Go2rtc config inside Frigate config is a good idea. I plan to do support this from go2rtc, but your solution better.

**Comment by NickM-27** [comment]
> Btw. Go2rtc config inside Frigate config is a good idea. I plan to do support this from go2rtc, but your solution better.

Thanks, it definitely made things simpler.
