### ISSUE TITLE
Added streams in go2rtc.yaml not showing in go2rtc addons dashboard

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/go2rtc#18]
Hi Alex
First of all I want to make it clear that I am using WebRTC without problems, but I have read that this addon will be a replacement in the future.
Likewise, I am not understanding the README well, how to configure or configure it, as I see instead with SonoffLAN (totally clear and complete)

I have 2 problems that I couldn't solve:
1) I have added as statements in go2rtc.yaml the streams of my 2 rtsp cameras, but then they do not appear in the addon panel
I did this because the camera key appears in the URL
2) Can the listening port be changed? I have put it in the yaml but it keeps listening to the api in 1984

Thank you very much and I hope I am not being too "dumb" by these questions.

Regards

go2rtc.yaml   (the indent are ok)
```
> streams:
>   comedor: 
>     - rtsp://xxxx:YYYY@192.x.y.z:554
>   calle: 
>     - rtsp://xxxx:BBBB@192.x.y.w:554
> 
> webrtc:
>   listen: ":8555"  # address of your local server (TCP)
>   candidates:
>     - stun:8555  # if you have dynamic public IP-address
> 
> api:
>   listen: "127.0.0.1:2000" # localhost
> 
> log:
>   rtsp: trace
> 
```
![1234](https://user-images.githubusercontent.com/65413059/186792570-e1b9c2f2-1d98-4833-986b-bd0c7f04459d.jpg)

**Comment by AlexxIT** [comment]
Your config ok, but it may be in wrong place. Where you put it? Have you restart add-on after change config?

**Comment by Gferretta** [comment]
Hi Alex

I Put it on Home Assistant config folder, **config/go2rtc.yaml**, together configuration.yaml, automations.yaml, etc.

Directly restarted "HA"

Nothing happend

Thanks

**Comment by AlexxIT** [comment]
You may have some YAML errors in config file.

**Comment by Gferretta** [comment]
> You may have some YAML errors in config file.

No errors in config.yaml

![yaaml](https://user-images.githubusercontent.com/65413059/186889364-efd04fef-9581-413e-80e4-0deca4053f1d.jpg)

Now I Test  **v0.1-alpha.10** and comment you
Thanks

**Comment by AlexxIT** [comment]
You can't test `go2rtc.yaml` with option from screen.

**Comment by Gferretta** [comment]
> You can't test `go2rtc.yaml` with option from screen.

okay
I had misunderstood your message.

erasing the line
api:

The "502: Bad Gateway" error no longer appears and the cameras can be seen fine.
But when I add it, with whatever port I put in, I get "502" error

**Comment by Gferretta** [comment]
> Show your config

https://github.com/AlexxIT/go2rtc/issues/18#issue-1351591550

**Comment by AlexxIT** [comment]
Check if you have errors in addon log with `alpha.11`

**Comment by AlexxIT** [comment]
Is problem still relevant?

**Comment by shifuoogway** [comment]
I am using current Linux binary and note that the go2rtc appears not to use the go2rtc.yaml stored in the binary's directory as per the instructions unless execution is from the directory. Maybe this is related. Is there a way to specify the yaml file from the command line?

**Comment by AlexxIT** [comment]
I think app searching config in current work directory. It does not always match the application directory.

**Comment by shifuoogway** [comment]
Thanks for that. Yep that is consistent with the observed behaviour.

**Comment by AlexxIT** [comment]
Reopen the issue if it is still relevant
