### ISSUE TITLE
WebRTC external access issue

### ISSUE THREAD

**Issue by conorlap** [AlexxIT/go2rtc#181]
WebRTC external access has been fine for me until rc9, now it isn't working. I've port forwarded 8555 on **both** TCP & UDP. 

Docker container is running in host mode and webrtc config is as below:

```
webrtc:
  candidates:
    - 192.168.0.22:8555
    - stun:8555
```
Local access is fine. I've went back to rc8 and remote WebRTC access is working fine.

**Comment by AlexxIT** [comment]
Are you sure you has public IP address? Because candidates and port forward means nothing if you don't.

**Comment by conorlap** [comment]
Not sure how but it's absolutely fine today! I've not made any changes since last night but it's now working 🤷🏻 

Thanks as always for your great work on this, it's really improved my Home Assistant & Frigate setup!
