### ISSUE TITLE
Disabling config editor

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#182]
Perhaps there should be an option like `-disable-config-editor` or `GO2RTC_DISABLE_CONFIG_EDITOR` which would make go2rtc web interface disable the editing functionality of the config file.

This would be useful in cases where go2rtc isn't installed in standalone, like when using through Frigate.

However, I'd recommend to keep the "Config" tab there, showing the active config, just don't allow users to change it.

Does it make sense?

**Comment by AlexxIT** [comment]
Config API won't work if user set only raw config without path to file:
https://github.com/AlexxIT/go2rtc/commit/6e49d51c33f0a529ba496ebdea8a46087ce3adbf

**Comment by felipecrs** [comment]
Awesome. Thank you!

**Comment by AlexxIT** [comment]
PS. Config API will work if user not set anything. Because it will be default `go2rtc.yaml` file in cwd.
