### ISSUE TITLE
Constantly Needing to Restart Addon to get Live Streams to Work

### ISSUE THREAD

**Issue by PablaV** [AlexxIT/go2rtc#184]
I am running addon on HA, and after about 15 mins of the addon running the live streams stop working. It just gets stuck on loading and in the addon logs I see "new consumer" request but then nothing happens no matter how long I let it load. This is the case for Chrome on windows and the iPhone app. The only way to fix this is restart the addon then streams load with no issue. If I use Frigate instead of WebRTC card, the streams load using HLS. I have also tried adding the streams to the config to see if that would help and am experiencing the same issue there too.

**Comment by AlexxIT** [comment]
Goto go2rtc WebUI and check active connections in moment of problem. Open info page for your stream and show result here.

Are you using rc.9 version?

**Comment by AlexxIT** [comment]
So, you no longer need to reload the addon?

**Comment by PablaV** [comment]
Happy to report back that the general v3.0 release of WebRTC card fixed the issue. Having another small issue with WebRTC but I'll post the issue there.

**Comment by PablaV** [comment]
I figured out what was causing this issue, if I set `mode: webrtc` the streams will successfully start for a short period using webRTC but then a little while later they stop. I was hoping to eliminate my streams from first starting using MP4 then reloading to use RTC, but seems like that doesn't work when I set the mode to only webrtc.
