### ISSUE TITLE
WebRTC external access

### ISSUE THREAD

**Issue by Morphy99** [AlexxIT/go2rtc#192]
I'm having trouble viewing webrtc streams from outside my network. I'm using the Frigate v12 beta 5 addon in HA OS and I've defined my external IP as a candidate. I've also opened port 8555 on my router and forwarded it to the local IP of my HA instance.

```
  webrtc:
    candidates:
      - xxx.xxx.xxx.xxx:8555
```

I've also tried with local ip:8555, stun:8555 but nothing works. 

I get the following on the addon starting:
[WARN] Failed to get IP address from supervisor

On shields up has reported the port as being open:
![image](https://user-images.githubusercontent.com/5853979/213994280-ba6fd502-02d0-479b-899f-8a6c074064b5.png)

I did think this was working as I was using the previous version of WebRTC Camera and it didn't report the protocol being used, which turned out to be MSE.

**Comment by Morphy99** [comment]
It's open as far as the settings show. 
![image](https://user-images.githubusercontent.com/5853979/214020698-066829d1-3167-4060-baf1-b5cfedf8e2a6.png)

> I don't know how the IP detection mechanism works in the Frigate addon. It is better to ask this in the Frigate project.

Ok, I did ask but they said to check the go2rtc settings and something about a symmetrical NAT but I don't think I have one of those.

**Comment by AlexxIT** [comment]
Well. Port forward only helps if you have public IP. It not related with symmetrical NAT.

If client and server not behind symmetric NAT - you not need any port forward.
https://tomchen.github.io/symmetric-nat-test/

**Comment by Morphy99** [comment]
I have a public IP yes and not behind a symmetric NAT.
So I just restarted my host as it occurred to me I hadn't tried that. Now Frigate won't start as the port 8555 is in use. Which then led me to realise the WebRTC Camera integration is using it... So I've disabled it now but I still can't connect. I didn't realise Frigate and WebRTC Camera can't coexist.

**Comment by NickM-27** [comment]
> I didn't realise Frigate and WebRTC Camera can't coexist.

they can, if you use version 3.0 of webrtc integration it will auto detect frigate 0.12 and use it as the webrtc provider (since they both use go2rtc internally)

**Comment by NickM-27** [comment]
you should use the browser console to get logs as to why webrtc isn't working

**Comment by AlexxIT** [comment]
@Morphy99 you need reinstall WebRTC Camera integration. It can automatically find external go2rtc and link to it.
So it won't run build-in go2rtc.

**Comment by Morphy99** [comment]
Ah ok! I didn't see any mention of this in either docs, apologies if I missed it! I removed the integration, then deleted from HACS, restarted HA core and then downloaded and added again. 

This time I get a prompt to add the server. It says to add it as http://localhost:1984 however that wouldn't work and neither would 127.0.0.1 so I added the Frigate hostname `ccab4aaf-frigate-fa-beta` which says success!

Wasn't able to load it still so I did a test with my laptop tethered to mobile data and the webrtc card looked as though it was going to play, the camera image is displayed however nothing after that. Then I went back to the Android app and started playing but very jerky and stop start. After a few minutes I went back to it and now it's playing fine! I have no idea why it took so long to play well, almost like it needed warming up!

**Comment by NickM-27** [comment]
> This time I get a prompt to add the server. It says to add it as http://localhost:1984 however that wouldn't work and neither would 127.0.0.1

That's because port 1984 isn't passed through on the addon by default for frigate

**Comment by Morphy99** [comment]
Sorry yes, of course. I've enabled that port and re-added the integration with localhost. Thanks Nick.

**Comment by AlexxIT** [comment]
So no problem? Close issue?

**Comment by Morphy99** [comment]
Yes I'll close it. It's stopped working again now but I think it's something to do with codecs.

**Comment by Morphy99** [comment]
Is there something that would prevent webrtc viewing from a device on a cell data network (4g/5g)? I have a HA instance on another LAN and when my mobile device is connected to another, completely separate LAN, via WiFi, webrtc works. When connected via the cellular network it doesn't.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/issues/378
