### ISSUE TITLE
Denoising camera stream with video filter in ffmpeg source

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#196]
Hi,

I'm looking for some help. The documentation says that `#raw=` can be used and there is even an example for `-vf`, a filter.

I'm trying to set `ffmpeg:<rtsp-url>#raw=-vf hqdn3d#video=h264` to denoise some CFTV cameras I have, but it fails with:

![image](https://user-images.githubusercontent.com/29582865/214165605-e8af6b6d-da4c-428c-b58e-3c20eb88c11b.png)

If I try with `ffmpeg:<rtsp-url>#raw=-vf hqdn3d#video=copy`, it fails with:

```
2023-01-23 22:39:04.913598584  Filtergraph 'hqdn3d' was defined for video output stream 0:0 but codec copy was selected.
2023-01-23 22:39:04.913604503  Filtering and streamcopy cannot be used together.
```

If I try with `ffmpeg:<rtsp-url>#raw=-vf hqdn3d` only:

```
Output file #0 does not contain any stream
```

Or, with `ffmpeg:<rtsp-url>#raw=-vf hqdn3d#video=`:

```
2023-01-23 22:45:12.442259468  22:45:12.441 DBG [webrtc] add consumer error="codecs not match: MP4V-ES"
2023-01-23 22:45:12.442264863  22:45:12.442 DBG [mp4] add consumer error="codecs not match: MP4V-ES"
```

**Comment by felipecrs** [comment]
Here are the input RTSP URL codecs information:

![image](https://user-images.githubusercontent.com/29582865/214168908-8dc02441-649e-4fd1-89e7-73c2dbc80f6d.png)

**Comment by AlexxIT** [comment]
`Filtering and streamcopy cannot be used together.`

You can't change stream without transcoding. Thats why rotation or resize also needs `#video=h264`.

**Comment by felipecrs** [comment]
I see. Do you have any idea why it fails with the below?

![image](https://user-images.githubusercontent.com/29582865/214307760-1e4e594b-d464-46e1-902a-98da6dda5bbc.png)

**Comment by AlexxIT** [comment]
Corrupted H264 codec. Or not respect specs.

**Comment by felipecrs** [comment]
Apparently it was only missing hardware acceleration. I added `#hardware=vaapi` and it worked just fine!

Out of curiosity, the filter didn't do anything useful (I could not see any difference). 😅
