### ISSUE TITLE
Large h265 stream not playing, no errors in logs

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#197]
I just got a new camera which has the ouptut:

```
  Metadata:
    title           : Session streamed by "preview"
    comment         : Preview_01_main
  Duration: N/A, start: 0.000625, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 4608x1728, 20.08 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

RTSP restream works great, but when I try to play it with MSE in Chrome it will show the first frame then not play. I know you mentioned you haven't tried with large streams, is there any extra logging that can be enabled to get more info on where the problem comes from?

**Comment by AlexxIT** [comment]
It may not be because of the size. H265 is a very diverse standard. It needs to be improved incrementally.

**Comment by NickM-27** [comment]
actually, I just tried with the substream (which is h264)

```
  Metadata:
    title           : Session streamed by "preview"
    comment         : Preview_01_sub
  Duration: N/A, start: 0.000438, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1536x576, 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

which still does not work with MSE, however it does work with webrtc

**Comment by NickM-27** [comment]
Fixed via https://github.com/AlexxIT/go2rtc/commit/e295bc4eaffa979e3fdf270e4be243c9d3720cc2

**Comment by AlexxIT** [comment]
OK. Problem was with audio codec
