### ISSUE TITLE
Discard audio track from source RTSP

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#198]
I have some cameras which are actually CFTV and I take their stream from my Hikvision DVR. They don't have any microphone, but my DVR's RTSP output adds a blank PCMU audio track.

I'd like to discard them with something like #audio=0 (similar to `backchannel=0`):

```yaml
my_cam: "rtsp://admin:123@192.168.1.12:554/Streaming/Channels/601#audio=0"
```

But instead I have to:

```yaml
my_cam: "ffmpeg:rtsp://admin:123@192.168.1.12:554/Streaming/Channels/601#video=copy"
```

Which probably takes unnecessary CPU cycles as it has to spawn a ffmpeg process.

**Comment by AlexxIT** [comment]
Supported in master:
```
streams:
  camera-video: rtsp://admin:123@192.168.1.12:554/Streaming/Channels/601#media=video
  camera-audio: rtsp://admin:123@192.168.1.12:554/Streaming/Channels/601#media=audio
```

**Comment by felipecrs** [comment]
That's awesome!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.7.0
