### ISSUE TITLE
Question: video freezes

### ISSUE THREAD

**Issue by RomchikL** [AlexxIT/go2rtc#20]
Hello!

Are there any restrictions (from the go2rtc server, browsers, or other platforms) on continuous video viewing from the server?

I can view a continuous video for a minute or two. Then the video freezes. At the same time, the log is good.

**Comment by AlexxIT** [comment]
Check info page about your stream. If send/receive fields updates in time.

**Comment by RomchikL** [comment]
When the camera freezes, these fields also freeze.

**Comment by AlexxIT** [comment]
Well. I think the camera stops sending data. Probably thinks no one's connected to it.
First, try to use ffmpeg in copy mode: `ffmpeg:{link}#video=copy`

**Comment by RomchikL** [comment]
Now the camera works continuously, but there are freezes for a few seconds.
About twice a minute the camera freezes (and the send/receive fields also freeze), but then (after 5-20 sec) the camera continues to work without my help.

**Comment by AlexxIT** [comment]
Well. Maybe ffmpeg reconnect to your camera continuously.
Have you check it in some other software? VLC maybe.

**Comment by RomchikL** [comment]
Ya,
VLC: there are short friezes (~0.5-1 sec), but streaming latency is ~2 sec.
The stream works for 0.5-3 minutes and the program stops the stream at all (the info page is "null").

Picture Entity card in HA:
Here camera works as in the latter comment (a lot of friezes for 2-10 sec). The latency is minimal.

**Comment by AlexxIT** [comment]
What camera model we talking about? Is it has brand mobile app?

**Comment by RomchikL** [comment]
Laxihub M3-TY with root, app - Smart life (Tuya).
But the camera does not have internet access. I can't view the picture in this app.
As a test, I can turn on internet access, but the stream will be through Tuya's server (not rtsp).

**Comment by AlexxIT** [comment]
All of the camera hacks, I've looked at, have very awful RTSP protocol implementation... Can you send link to the hack?

**Comment by RomchikL** [comment]
@AlexxIT 
Yep, it's me again ;)

**Comment by AlexxIT** [comment]
Can you send direct link to hack, not to author profile? Maybe some article about it.

**Comment by RomchikL** [comment]
The direct [link](https://github.com/guino/Merkury1080P)
, but here are just the differences.
The main hack is described [here](https://github.com/guino/Merkury720)

**Comment by maxi1134** [comment]
I experience similar issues with my streams.

It happens on the following devices, with a Reolink RLC-423 (https://reolink.com/us/product/rlc-423/)
Samsung S7 FE (Wifi 6)
Samsung a7 lite (Wifi 5)
My computer (Ryzen 3900X, 1gbps, 2080s)


I can tell on the tablet, by using the GPU logs, that the gpu usage drops to 0 when the stream freeze, as if no more data is received.

I will be happy to provide logs and debugging time

**Comment by AlexxIT** [comment]
@maxi1134 Test your RTSP in other programms first. VLC, default Hass stream without WebRTC, ffmpeg copy mode.

**Comment by AlexxIT** [comment]
You need to test all my examples.

**Comment by AlexxIT** [comment]
Is the problem still relevant?

**Comment by RomchikL** [comment]
For me the problem is not relevant. 
After the update everything works fine, thanks!
