### ISSUE TITLE
Incorrect button display in Web GUI

### ISSUE THREAD

**Issue by chex01** [AlexxIT/go2rtc#203]
In the Web GUI on the phone, the "Config" button is displayed incorrectly.

![Screenshot_2023-01-24-21-07-38-191-edit_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/12098416/214377462-5e9aed7c-46ff-43ce-aad7-146350976746.jpg)
![Screenshot_2023-01-24-21-08-18-502-edit_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/12098416/214377498-94817ed0-b023-47e6-9df7-8af89dfdb165.jpg)
![Screenshot_2023-01-24-21-08-36-665-edit_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/12098416/214377522-15439437-4f29-4fea-93a1-2514e9b5cdb4.jpg)
![Screenshot_2023-01-24-21-09-02-521-edit_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/12098416/214377301-1492fd48-137e-4bdc-845a-c3ae8080c2e2.jpg)

The menus on each page seem to be laid out differently.

**Comment by AlexxIT** [comment]
Not relevant in latest versions
