### ISSUE TITLE
webrtc integration Vs go2rtc for the picture glance

### ISSUE THREAD

**Issue by Claudio1L** [AlexxIT/go2rtc#206]
Hi,

just upgraded to 3.0.1, and after some adjustment seems working fine. A typical config I'm using is the following:

```
type: custom:webrtc-camera
entity: camera.cam_strada
style: 'video {aspect-ratio: 16/10; object-fit: fill;}'
mode: webrtc
ui: true
```

Now the question is:

how can I use picture glance card? It requires an entity to define the stream, but my entities as they are are generic cameras not processed by webrtc.

should I migrate to go2rtc addon?

Thanks

**Comment by AlexxIT** [comment]
Picture Glance support formats: HLS, sync WebRTC, MJPEG
WebRTC Camera support formats: async WebRTC, MSE, MP4, MJPEG

I recommend to use WebRTC Camera card. But if you want to use Picture Glance, you can install:

1. WebRTC Camera integration OR go2rtc addon OR Frigate addon
2. RTSPtoWebRTC integration with link to http://localhost:1984/

And your Picture Glance will play Generic cameras via WebRTC technology.

**Comment by Claudio1L** [comment]
Thanks Alex for clarifications. Just realized that shortcuts can be supported also on webrtc-camera, one of the reason I was evaluating Picture glance. I'll stay with webrtc integration for now. When will be more clear to me the advantages of the Add-on will eventually switch

**Comment by hsmptg** [comment]
But the state of these icons (shortcuts) will not change (unlike in the Picture Glance card), right?
