### ISSUE TITLE
H264 V380 camera

### ISSUE THREAD

**Issue by bartlebi** [AlexxIT/go2rtc#207]
Hello!
I have tried to add stream from china camera but can't see image via integration. Accessing stream page via integration i see next error on logs:
```
21:20:48.673 WRN github.com/AlexxIT/go2rtc/cmd/mp4/ws.go:56 > error=EOF
21:20:48.690 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:129 > error="codecs not match: H264,PCMA"
```
But adding rtsp stream from camera to vlc i see next information about codec:
`Кодек: H264 - MPEG-4 AVC (part 10) (h264)`
How to fix?

**Comment by AlexxIT** [comment]
It's better to use english for international repo. I need access to stream to check problem.

**Comment by bartlebi** [comment]
Okay, i will map rtsp port on router to camera and send you link via telegram.

**Comment by AlexxIT** [comment]
Fixed in 1.0.1

**Comment by keteflips** [comment]
> Hello! I have tried to add stream from china camera but can't see image via integration. Accessing stream page via integration i see next error on logs:
> 
> ```
> 21:20:48.673 WRN github.com/AlexxIT/go2rtc/cmd/mp4/ws.go:56 > error=EOF
> 21:20:48.690 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:129 > error="codecs not match: H264,PCMA"
> ```
> 
> But adding rtsp stream from camera to vlc i see next information about codec: `Кодек: H264 - MPEG-4 AVC (part 10) (h264)` How to fix?


Yo can get the audio from this camera stream?

**Comment by manalotobry** [comment]
How do we get the audio from this kind of camera? hope you can help

**Comment by tamzidpriyo** [comment]
How to add such camera? Shows blank on mse and webrtc, ffprobe responds with the stream as hevc (h265)
