### ISSUE TITLE
Stream only works for a few seconds, then gives error.

### ISSUE THREAD

**Issue by BIoob** [AlexxIT/go2rtc#21]
Hey, i added a frigate RTMP stream to the go2rtc.yaml file like this: 

`   rtmp_stream: rtmp://192.168.0.200/live/bureau_fr`

The stream works for a few seconds if I click on "webrtc" within the go2rtc dashboard, but stops after a few seconds, if I try to open the stream again it gives this error in docker log: 

`
14:01:20.934 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"`

If I click on "info" within the go2rtc dashboard it gives me this:

`[{"receive":0,"remote_addr":"192.168.0.200:1935","type":"RTMP client producer","url":"rtmp://192.168.0.200/live/bureau_fr"}]`

Any idea what i'm doing wrong or what's causing this? thanks!

**Comment by AlexxIT** [comment]
Try to enable global logs. debug or trace level. Maybe there will be something useful

**Comment by BIoob** [comment]
I'm not really sure how to do that? Sorry im not that advanced with all this stuff

I added this to my go2rtc.yaml:
`log:
  level: info # default level
  api: trace
  exec: debug
  ngrok: info
  rtsp: debug
  streams: debug
  webrtc: debug`

And now this shows up in logs:

`
14:26:59.454 DBG [webrtc] new consumer src=rtmp_stream


14:26:59.456 DBG [streams] probe producer url=rtmp://192.168.0.200/live/bureau_fr


14:27:00.711 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"`

Bit more info but not sure this helps :/

**Comment by BIoob** [comment]
Here is a trace log: 
```
14:49:10.183 DBG [app] arch=amd64 conf_size=523 cwd=/config os=linux

14:49:10.183 INF [rtsp] listen addr=:8554

14:49:10.184 INF [api] listen addr=:1984

14:49:18.736 DBG [webrtc] new consumer src=rtmp_stream

14:49:18.737 TRC [webrtc] offer:

v=0

o=mozilla...THIS_IS_SDPARTA-99.0 96986099561002 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 REMOVED

a=group:BUNDLE 0 1

a=ice-options:trickle

a=msid-semantic:WMS *

m=video 9 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98

c=IN IP4 0.0.0.0

a=recvonly

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:5 urn:ietf:params:rtp-hdrext:toffset

a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=extmap:7 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1

a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1

a=fmtp:120 max-fs=12288;max-fr=60

a=fmtp:124 apt=120

a=fmtp:121 max-fs=12288;max-fr=60

a=fmtp:125 apt=121

a=fmtp:127 apt=126

a=fmtp:98 apt=97

a=ice-pwd:bba27af720f2784762562f5f40f798cc

a=ice-ufrag:44a636bf

a=mid:0

a=rtcp-fb:120 nack

a=rtcp-fb:120 nack pli

a=rtcp-fb:120 ccm fir

a=rtcp-fb:120 goog-remb

a=rtcp-fb:120 transport-cc

a=rtcp-fb:121 nack

a=rtcp-fb:121 nack pli

a=rtcp-fb:121 ccm fir

a=rtcp-fb:121 goog-remb

a=rtcp-fb:121 transport-cc

a=rtcp-fb:126 nack

a=rtcp-fb:126 nack pli

a=rtcp-fb:126 ccm fir

a=rtcp-fb:126 goog-remb

a=rtcp-fb:126 transport-cc

a=rtcp-fb:97 nack

a=rtcp-fb:97 nack pli

a=rtcp-fb:97 ccm fir

a=rtcp-fb:97 goog-remb

a=rtcp-fb:97 transport-cc

a=rtcp-mux

a=rtcp-rsize

a=rtpmap:120 VP8/90000

a=rtpmap:124 rtx/90000

a=rtpmap:121 VP9/90000

a=rtpmap:125 rtx/90000

a=rtpmap:126 H264/90000

a=rtpmap:127 rtx/90000

a=rtpmap:97 H264/90000

a=rtpmap:98 rtx/90000

a=setup:actpass

a=ssrc:1827711710 cname:{5303b81f-1719-4d19-aafd-d0818cebf834}

m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101

c=IN IP4 0.0.0.0

a=recvonly

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1

a=fmtp:101 0-15

a=ice-pwd:bba27af720f2784762562f5f40f798cc

a=ice-ufrag:44a636bf

a=mid:1

a=rtcp-mux

a=rtpmap:109 opus/48000/2

a=rtpmap:9 G722/8000/1

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:101 telephone-event/8000

a=setup:actpass

a=ssrc:2772650522 cname:{5303b81f-1719-4d19-aafd-d0818cebf834}

14:49:18.738 TRC [streams] consumer:0:0 candidate media="video, recvonly, 120 VP8/90000, 124 RTX/90000, 121 VP9/90000, 125 RTX/90000, 126 H264/90000, 127 RTX/90000, 97 H264/90000, 98 RTX/90000"

14:49:18.738 DBG [streams] probe producer url=rtmp://192.168.0.200/live/bureau_fr

14:49:20.020 TRC [streams] consumer:0:1 candidate media="audio, recvonly, 109 OPUS/48000/2, 9 G722/8000, 0 PCMU/8000, 8 PCMA/8000, 101 TELEPHONE-EVENT/8000"

14:49:20.020 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
```

**Comment by AlexxIT** [comment]
Well. Same stream sometimes loads and sometimes don't. Ok. I'll try to repeat this situation myself.

Also you may get your stream with ffmpeg
```
streams:
  camera1: ffmpeg:{link}#video=copy
```

**Comment by BIoob** [comment]
with ffmpeg the stream does indeed load perfectly everytime but there is a lot more delay then when not using the ffmpeg command.
I wanted to use this so i could get the least delay possible in home assistant so not really worth it with ffmpeg.

**Comment by AlexxIT** [comment]
You may take RTSP link directly to go2rtc or Hass. Is it any problem with it?

**Comment by luzik** [comment]
I found the same today, but container restart fixed issue


```
[
  {
    "receive": 0,
    "remote_addr": "127.0.0.1:1935",
    "type": "RTMP client producer",
    "url": "rtmp://frigate/live/wejscie"
  }
]
```

```
go2rtc                    | 16:20:22.539 INF [api] listen addr=:1984
go2rtc                    | 16:20:22.539 INF [rtsp] listen addr=:8554
go2rtc                    | 16:20:22.540 INF [webrtc] listen addr=:8855
go2rtc                    | 16:20:22.540 INF [srtp] listen addr=:8443
go2rtc                    | 16:36:25.482 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
go2rtc                    | 16:36:25.482 ERR [api.hass] exchange SDP error="couldn't find the matching tracks"
go2rtc                    | 16:38:01.438 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
```

**Comment by rogerquake** [comment]
I noticed the same today. On Firefox (Windows11) the streams wouldn't start up at all. On Chrome, they would, but stopped working working a short time after. On another Windows 10 machine, everything seemed to be working fine though. I restarted the container and the non-working machine started working fine.

**Comment by luzik** [comment]
Got it again, anything I can check in that state before restarting container ?

**Comment by efaden** [comment]
I'm having this issue also sporadically on one camera.  Camera is a hikvision that I am using through Frigate.  The other two cameras I have are amcrest and also setup through frigate (e.g. frigate/live/camera)

**Comment by AlexxIT** [comment]
Reopen the issue if it is still relevant
