### ISSUE TITLE
FFmpeg failed at slow shutter speed camera / dark image

### ISSUE THREAD

**Issue by LckySndays** [AlexxIT/go2rtc#211]
Everytime I set the camera shutter to 1/3, when the night come with no lightning at all, the ffmpeg failed to transcode the video/audio
Changing the Shutter Speed to faster value temporarily will make the ffmpeg working again. Most of the time changing it back to 1/3 will make the transcoding stay working but sometimes not. 

I think the problem is more to the black/dark image video rather than the shutter speed
https://github.com/blakeblackshear/frigate/issues/5192
```
go2rtc version 1.0.1 linux/amd64
No go2rtc error log
```
Camera: 
```
2 x Hikvision DS-2CD3367WDV3-L
2 x Hikvision DS-2CD3T87WDA3-LS
```

**Comment by AlexxIT** [comment]
I need access to stream. I can't reproduce this with my cameras.
