### ISSUE TITLE
External FFMPEG process publish to RTSP stream?

### ISSUE THREAD

**Issue by zzachattack2** [AlexxIT/go2rtc#216]
Can go2rtc publish an rtsp stream from an external ffmpeg process? For example with rtsp-simple-server, any ffmpeg process can output to a new rtsp stream on whichever port the application is configured for. I am not sure if or how this could be done with go2rtc. The use case is where it's not optimal to run ffmpeg directly from go2rtc, due to also needing to pipe the ffmpeg output to stdout for a different application. Thanks.

**Comment by AlexxIT** [comment]
#137
