### ISSUE TITLE
Using python's aiortc to connect to go2rtc

### ISSUE THREAD

**Issue by KoljaV** [AlexxIT/go2rtc#217]
I am trying to connect python's aiortc to the WebRTC of go2rtc. Unfortunetlay, my offer is not answered. 

I observed that aiortc is sending an offer (see image) beginning with sdp instead of webrtc. Is that a problem?
<img width="145" alt="image" src="https://user-images.githubusercontent.com/25928990/215080426-60ceb851-4153-4ae9-83f1-fa4a36acf389.png">

BR,
Kolja

**Comment by AlexxIT** [comment]
What exactly are you doing? Are you trying to get a stream from go2rtc to python over the webrtc protocol?

**Comment by KoljaV** [comment]
Yes, exactly. But I found a different solution to finally enable 2 way audio in HomeKit for my Dahua Doorbell/Intercom. I am now using scrypted. Thanks a lot for your support!
