### ISSUE TITLE
HA slow when I enable go2rtc

### ISSUE THREAD

**Issue by marcelmah** [AlexxIT/go2rtc#218]
Hi,

I'm running HA on a real server in a VM running on ESXi.
The VM has 8 vCPU's and 16 GB of memory. Monitoring shows It's doing almost nothing.

When I enable go2rtc (now v 1.0.1, but the problem has been there since I tried it first a couple of weeks (and versions) ago) and with the RTSPtoWebRTC integration to automatically couple my 4 configured camera's in go2rtc.

When the go2rtc server is running, opening the HA app on my mobile slows down to the level I get popups about it not loading and if I want to wait. If I wait a bit longer, it will load... slowly. When I disable go2rtc all is fast again. I've tried multiple times as the first time I changed and installed other stuff to, so I had to rule them out.

Any thoughts on this?

**Comment by AlexxIT** [comment]
About problems with RTSPtoWebRTC integration you should ask in the Hass repo.

I recommend you to use WebRTC Camera custom integration.

**Comment by marcelmah** [comment]
This fixed itself about a day after I posted this...
