### ISSUE TITLE
Clarification with the Installation

### ISSUE THREAD

**Issue by OmegaMonster** [AlexxIT/go2rtc#22]
Hello @AlexxIT ,

I am using WebRTC at the moment and it works seamlessly on my side. I wanted to try the go2rtc but encountered several issues as Im very new for this.

Since I am using the docker version, I have pulled the go2rtc and added the go2rtc.yaml file in config folder (Where the automations.yaml, configuration.yaml located). I have attached my go2rtc.yaml file for your reference. But, I couldnt encounter any stream options in my home assistant. Im clueless at this point. Could you further assist me in this project please? Willing to learn here.

> Streams:
       Camera1: rtsp://USER:PASSWORD@192.168.X.YZ/Streaming/Channels/101

**Comment by AlexxIT** [comment]
You should setup volumes if you using docker version. Config folder auto setup only for Supervisor users.

**Comment by OmegaMonster** [comment]
Hello @AlexxIT

May I know how to setup volumes,Im so sorry, Im very new for this. Do you have any reference video/tutorial. Thank you in advance.

**Comment by OmegaMonster** [comment]
Hello @AlexxIT . Thank you so much for the reply. So basically, i have to create a config folder by myself? Im so sorry to ask you all these. Too new for this.
<img width="442" alt="Screenshot 2022-08-29 at 5 13 17 PM" src="https://user-images.githubusercontent.com/112365534/187167324-c6690ae3-8056-41fc-bd99-75f5a1a6eda6.png">

**Comment by OmegaMonster** [comment]
Thank you so much @AlexxIT for the response. Is there anyway for me to monitor the stream outside of the local network? I unable to view at the stream whenever I am not in the same network.

**Comment by AlexxIT** [comment]
All the answers are in the documentation. About config in docker section. About external access in WebRTC section.

**Comment by AlexxIT** [comment]
You can reopen this issue if still have questions.
