### ISSUE TITLE
unexpected problem sending snapshot to telegram

### ISSUE THREAD

**Issue by marcob79** [AlexxIT/go2rtc#222]
I'm using this wonderful compoennt since few months and I was also using it sending a snapshot with telegram as explained here

[https://github.com/AlexxIT/go2rtc/wiki/Snapshot-to-Telegram](url)

I was using also in a slighty different setup than showed in the example, such as

> service: telegram_bot.send_photo
> data:
>   url: http://localhost:1984/api/frame.mp4?src=camera1
>   target: 123456789

recently, probably since 1.0.1 release, it stopped working and i got the following error in home assistant logs.
Not sure if it is really related to go2rtc upgrade or HASS / supervisor upgrade

`Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:741
Integration: Telegram bot (documentation, issues)
First occurred: 10:26:15 (24 occurrences)
Last logged: 12:03:06

Status code 404 (retry #2) loading http://localhost:1984/api/frame.mp4?src=camera.box
Status code 404 (retry #3) loading http://localhost:1984/api/frame.mp4?src=camera.box
Status code 404 (retry #4) loading http://localhost:1984/api/frame.mp4?src=camera.box
Status code 404 (retry #5) loading http://localhost:1984/api/frame.mp4?src=camera.box
Can't load data in http://localhost:1984/api/frame.mp4?src=camera.box after 5 retries`

**Comment by AlexxIT** [comment]
Show your go2rtc config

**Comment by marcob79** [comment]
Sure.. My configuration is very simple, since camera are configured trought home assistant on the fly

> api:
>   listen: ":1984"  # HTTP API port ("" - disabled)
>   base_path: ""    # API prefix for serve on suburl
>   static_dir: ""   # folder for static files (custom web interface)
> 
> webrtc:
>   listen: ":8555"  # address of your local server (TCP)
>   candidates:
>     - stun:8555  # if you have dynamic public IP-address
> 
> log:
>   level: debug  # default level

**Comment by marcob79** [comment]
I just find out that RTSPtoWebRTC was disabled my mistake. 
Now is working again.

**Comment by AlexxIT** [comment]
RTSPtoWebRTC not related to snapshots.
You need to setup streams in the go2rtc config. Because the list of streams is cleared every time the addon is restarted.
If you request a snapshot before looking at the camera in the GUI, nothing will work.

**Comment by marcob79** [comment]
I was thinking like that so I tried also to look at the camera before triggering the snaps, but didn't work as well. 
I noticed that on go2rtc web gui, streams are no more populated automatically after I watch them in home assistant. It seems something different from old behavior.

**Comment by AlexxIT** [comment]
If the streams do not appear in the go2rtc interface, you are not watching the streams through it

**Comment by marcob79** [comment]
You are right. 
Anyway it is very strange because some days ago go2rtc was used correctly. 
On home assistant side there was nothing to be configured as far as I remember...
