### ISSUE TITLE
Issues with casting and delay

### ISSUE THREAD

**Issue by ricoroodenburg** [AlexxIT/go2rtc#23]
Hi,

At this moment I am testing a Google Nest Hub for casting some dashboards. 

Unfortunately, the streams doesn’t show anything except a black screen with a red banner with the text ‘Error with media stream’ for a few seconds.

With a browser such as Edge on Windows the stream is working with the default HA cards but with a delay of 2 seconds. The ‘old’ webRTC Camera integration doesn’t have this delay.

Home Assistant 2022.8.7
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest

go2RTC
Current version: 0.1-alpha.11

**Comment by ricoroodenburg** [comment]
> Hi,
> 
> At this moment I am testing a Google Nest Hub for casting some dashboards.
> 
> Unfortunately, the streams doesn’t show anything except a black screen with a red banner with the text ‘Error with media stream’ for a few seconds.
> 
> With a browser such as Edge on Windows the stream is working with the default HA cards but with a delay of 2 seconds. The ‘old’ webRTC Camera integration doesn’t have this delay.
> 
> Home Assistant 2022.8.7 Supervisor 2022.08.3 Operating System 8.5 Frontend 20220802.0 - latest
> 
> go2RTC Current version: 0.1-alpha.11

I think the default card is not using the addon. Hoe can I check if the addon is in use by a card? It’s not so clear for me since there is no custom card.

**Comment by AlexxIT** [comment]
Camera setting "Camera View":
- auto - snapshots every 10 seconds
- live - WebRTC if you have RTSPtoWebRTC integration installed

**Comment by ricoroodenburg** [comment]
Hi @AlexxIT, 

Thank you! I didn't install the RTSPtoWebRTC first.
After installing it, it's working fine without any delay.

I've returned the Google Nest Hub since it's very slow, I'll buy something else.
