### ISSUE TITLE
OSD/time mark on stream

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#234]
I have a Dahua VTO2202F-P-S2, and its default OSD is placed in a bad position:

![image](https://user-images.githubusercontent.com/29582865/216218976-990a2a8c-80cd-45f5-9618-c78acc4779a8.png)

As you can see, it sits right where the WebRTC card puts its "toggle fullscreen" button.

In its configuration, I can't put it in a different position. I can, at most, disable it:

![image](https://user-images.githubusercontent.com/29582865/216219234-28419911-ab6e-49aa-9565-0f214eab6796.png)

It would be nice if go2rtc had a feature to add this, so I could disable from VTO and enable it in go2rtc.

Anyway, I will totally understand if you think that this is not a good feature for go2trc.

**Comment by AlexxIT** [comment]
You can move fullscreen button via styles.
Adding timestamp is another issue. It will be transcoding with ffmpeg.

**Comment by AlexxIT** [comment]
Timestamp issue #127

**Comment by wsantos** [comment]
> You can move fullscreen button via styles. Adding timestamp is another existing issue. It will be transcoding via ffmpeg.

@AlexxIT How can we use styles? I'm trying to `object-fit: fill` to my grid but I can only do with some JS magic.
