### ISSUE TITLE
[Question] How to enable Hardware Acceleration? (Nvidia GPU)

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/go2rtc#24]
As the title states; I am looking at a way to use my GPU to decode the video feed, as it is my CPU is using 80% for a single feed in "Glances".

Thanks a lot for this project!

**Comment by AlexxIT** [comment]
Do you using ffmpeg stream source?

**Comment by maxi1134** [comment]
I do!

**Comment by AlexxIT** [comment]
You can use raw param like in docs for rotation:

```
ffmpeg:rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0#raw=-vf transpose=1#video=h264
```

**Comment by maxi1134** [comment]
Hi there,
Thanks for the answer!


I did find this command on the NVIDIA docs:

ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i input.mp4 -c:a copy -c:v h264_nvenc -b:v 5M output.mp4

But I am unsure on what parts I need to use after my feed input.

**Comment by maxi1134** [comment]
`ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i:rtsp://user:pass@192.168.0.210/h264Preview_01_main#raw= -c:a copy -c:v h264_nvenc`

Is this going in the right direction?

**Comment by AlexxIT** [comment]
Are you using Hassio or other Linux?

**Comment by maxi1134** [comment]
I use it on a Linux VM (in docker).

The Docker NVIDIA stuff is already installed and works for Frigate on that VM

**Comment by maxi1134** [comment]
Hi there,
I gave a bit more tries to this, but I think it boils down to the NVIDIA libraries not being installed in the Docker install.

**Comment by calisro** [comment]
> Hi there, I gave a bit more tries to this, but I think it boils down to the NVIDIA libraries not being installed in the Docker install.

You could roll your own ffmpeg binary though and point to it in the go2rtc.yaml config?

**Comment by maxi1134** [comment]
I tried doing so with the Binaries of Go2Rtc, but unfortunately I get this

`16:04:05.895 ERR [streams] probe producer error="unsupported scheme: ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i : libvpx -b:v 1M -maxrate 4M -c:a libvorbis#video=vp8" url="ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i :rtsp://admin:@192.168.0.210/h264Preview_01_main#raw=-c:v libvpx -b:v 1M -maxrate 4M -c:a libvorbis#video=vp8"`

**Comment by calisro** [comment]
What I meant was you can grab or build a ffmpeg binary with the required hwaccels and plop it in the configuration directory and use the 

```
ffmpeg:
  bin: ffmpeg    
```

to point to the path of that binary.  The one packaged with go2rtc (and frigate too) doesn't come with that but there is a build that does.  you can probably grab it from the frigate docker:

https://docs.frigate.video/configuration/nvdec/

**Comment by AlexxIT** [comment]
@maxi1134 read about exec source

**Comment by maxi1134** [comment]
I tried a lot in the last 6 days, too much to actually list. But nothing seems to work.

Is anyone looking for a tip/coffee in exchange for help?

**Comment by Maxcodesthings** [comment]
@maxi1134 
Since hw acceleration is not supported in go2rtc, my plan is to configure my stream in this order:
1. Frigate as the entry point to the RTSP stream. 
2. Configure Frigate to perform the encoding for the RTMP stream
```
# Optional: ffmpeg configuration
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
```
3. Use the Frigate integration into HA too add cameras
4. go2rtc along with RTSPtoWebRTC to "on the fly" convery these cameras to WebRTC

**Comment by NickM-27** [comment]
Hw accel should work just fine in go2rtc, just used a prebuilt binary like BtBn or jellyfin. We're also building go2rtc directly into frigate in the next release.

**Comment by Maxcodesthings** [comment]
@NickM-27 does this mean the streams from frigate will be webrtc instead of rtmp?

**Comment by NickM-27** [comment]
> @NickM-27 does this mean the streams from frigate will be webrtc instead of rtmp?

webRTC will be supported as a way to view in the frigate frontend and streams will be restreamed using rtsp

**Comment by Maxcodesthings** [comment]
That makes more sense than what i said, thanks. Ill look into a prebuilt binary, i think i was concentrating on bulilding one didnt think about that

**Comment by maxi1134** [comment]
> > @NickM-27 does this mean the streams from frigate will be webrtc instead of rtmp?
> 
> webRTC will be supported as a way to view in the frigate frontend and streams will be restreamed using rtsp


Does this mean that my camera would do something like this
`camera -> Frigate(withWebRTC)->home-Assistant?`

Instead of doing
`camera->webRTC->frigate`
in parrallel of
`camera->webrtc->homeassistant`

**Comment by NickM-27** [comment]
The frigate card should be able to support webRTC from frigate directly otherwise in HA you'll need to use frigates RTSP stream along with rtsp2webrtc or the webRTCCard

**Comment by maxi1134** [comment]
> The frigate card should be able to support webRTC from frigate directly otherwise in HA you'll need to use frigates RTSP stream along with rtsp2webrtc or the webRTCCard

A-fucking-one.

That is great news, transcoding, here we come. My 4k Cameras do not play well with my Samsung s7 FE

**Comment by Maxcodesthings** [comment]
> My 4k Cameras do not play well with my Samsung s7 FE
Yea no kidding cant stream 2k even on my Pixel 6

**Comment by AlexxIT** [comment]
The first priority is stable operation. No one needs hardware acceleration for dropping connection

**Comment by felipecrs** [comment]
@AlexxIT, can we have some kind of global option we can set in the `go2rtc.yaml`, like:

```
hw_accel_args: -whatever_args -i_want
```

That go2rtc would automatically inject in all ffmpeg calls without having to repeat them?

**Comment by NickM-27** [comment]
> @AlexxIT, can we have some kind of global option we can set in the `go2rtc.yaml`, like:
> 
> ```
> hw_accel_args: -whatever_args -i_want
> ```
> 
> That go2rtc would automatically inject in all ffmpeg calls without having to repeat them? Similar to how Frigate handles it.

It depends what you're doing. Frigate only does one way decoding. I imagine go2rtc would be a lot more transcoding which would require 2 sets of args and may be a bit more complicated.

**Comment by felipecrs** [comment]
Got it.

There's another thing: sometimes we need to add environment variables for the hwaccel to work correctly (as stated [here](https://docs.frigate.video/configuration/hardware_acceleration#:~:text=following%20environment%20variable-,LIBVA_DRIVER_NAME,-%3Di965%20to%20your) with LIBVA_DRIVER_NAME. It would be nice if this could be sorted out for the add-on users (since you can't pass arbitrary env vars like docker run).

Maybe during the initialization of the go binary you can read the `environment:` block in `go2rtc.yaml` and call the setEnv function to have it applied for all underlying processes. Again, similar to Frigate (at least from the user perspective).

**Comment by NickM-27** [comment]
> Maybe during the initialization of the go binary you can read the `environment:` block in `go2rtc.yaml` and call the setEnv function to have it applied for all underlying processes. Again, similar to Frigate (at least from the user perspective).

It would probably be easier to just provide a `LIBVA_DRIVER_NAME` env variable in the addon and default it to i965

**Comment by felipecrs** [comment]
If that isn't harm at all, yes, much better! Frigate could do it as well then.

**Comment by felipecrs** [comment]
Actually this may be trickier than I thought. Frigate image seems to add lots of different dependencies according to the architecture it's building from:

https://github.com/blakeblackshear/frigate/blob/47c1985c265f060daab8b6d492fdf424c20fe123/docker/Dockerfile#L95

Most likely hwaccel won't work for me unless these dependencies are set. To be worse, go2trc currently runs in Alpine, which make things harder as I can't simply copy what Frigate is doing.

I think I won't try to use hwaccel in go2rtc for now.

**Comment by AlexxIT** [comment]
No problem. Change `bin` param and add there whatever you want.

**Comment by AlexxIT** [comment]
Check this: https://github.com/AlexxIT/go2rtc/wiki/Hardware-acceleration

Docker users can try:
- `alexxit/go2rtc:master` version for Intel iGPU and Raspberry
- `alexxit/go2rtc:master-hardware` version for AMD GPU and NVidia GPU

Hass Add-on can try (in same addon repository):
- **go2rtc master** version for Intel iGPU and Raspberry
- **go2rtc master hardware** version for AMD GPU and NVidia GPU

Remember to temporary stop previous go2rtc container/add-on version.

**Comment by AlexxIT** [comment]
Hardware acceleration supported in latests versions
