### ISSUE TITLE
Securely Embedding WebRTC Streams with 2-way audio into Home Assistant Dashboards

### ISSUE THREAD

**Issue by aeozyalcin** [AlexxIT/go2rtc#242]
Hello, I am trying to integrate 2-way audio with my doorbell camera into my Home Assistant dashboard. I have seen many people on the forums using iframes to embed the existing `webrtc.html` file within Go2RTC. To do this, it looks like they end up exposing Go2RTC's port 1984/http, usually via Nginx. However, the way I see it, this is not secure at all as anyone with the link can have access to the cameras, even with HTTPS.

I would like to know if there is a way to do this securely without exposing go2rtc's http port. I dug into the source code of `webrtc.html`, and I see the following line where the web player establishes a socker connection to the Go2rtc server:
```
const ws = new WebSocket(`ws${baseUrl.substr(4)}/api/ws${location.search}`);
```
The only way I have been able to achieve this so far is by also exposing Go2RTC port 1984 to the internet, so that in practice, the socket URL ends up looking like this:
```
wss://example.domain.org/go2rtc/api/ws?src=camera_name
```
This is obviously very insecure. So something has to be done...

I took a quick look at what the WebRTC integration custom card does, and I see that it does what I am looking for. It establishes the socket connection to the Go2RTC server via authentication:
```
wss://example.domain.org/api/webrtc/ws?authSig=[SUPER LONG AUTH TOKEN]&url=camera_name
```

As I stated above, unfortunately I can't just use the WebRTC custom card for my application, since it does not support 2 way audio. So I am looking for a way to do this with iframes, where the content in the iframe somehow obtains a token like the webRTC card does. Thanks!

**Comment by AlexxIT** [comment]
I don't think opening port 1984 to the internet is a good idea. This functionality must be implemented in the card. This is what the WebRTC card was created for. But it does not support 2way audio yet.

**Comment by aeozyalcin** [comment]
> I don't think opening port 1984 to the internet is a good idea. This functionality must be implemented in the card. This is what the WebRTC card was created for. But it does not support 2way audio yet.

Yep I agree! I was surprised to see the number of people doing this on the HA forums.

I know you mentioned in other threads that you wouldn't be focusing on adding 2 way audio support to WebRTC anytime soon. If someone were to attempt to take a crack at this, where would you recommend they start in the WebRTC source code?

**Comment by AlexxIT** [comment]
All examples already in simple HTML code
https://github.com/AlexxIT/go2rtc/blob/master/www/webrtc.html

**Comment by aeozyalcin** [comment]
Ok I made some progress on this. I am starting with the webRTC custom card files, and using the go2rtc/webrtc.html as an example. I decided to use the webRTC custom card as a starting point, since it already handles signedPath authentication etc.

I was able to get the card to prompt for microphone use in HA. I achieved that by adding the getUserMedia() inside the setConfig function in webrtc-camera.js :
```
    setConfig(config) {
        if (!config.url && !config.entity) throw new Error("Missing `url` or `entity`");

        if (config.mode) this.mode = config.mode;
        // backward compatibility
        else if (config.mse === false) this.mode = 'webrtc';
        else if (config.webrtc === false) this.mode = 'mse';

        if (config.background) this.background = config.background;

        if (config.intersection === 0) this.visibilityThreshold = 0;
        else this.visibilityThreshold = config.intersection || 0.75;

        /**
         * @type {{
         *     url:string, entity:string, muted:boolean, poster:string, title:string,
         *     intersection:number, ui:boolean, style:string,
         *     ptz:{
         *         opacity:number|string, service:string,
         *         data_left, data_up, data_right, data_down,
         *         data_zoom_in, data_zoom_out, data_home
         *     },
         *     shortcuts:Array<{name:string,icon:string}>,
         *     mse:boolean, webrtc:boolean,
         * }} config
         */
        this.config = config;
        navigator.mediaDevices.getUserMedia({audio: true}) // <===
    }
```

I then attempt to add this audio input track to the stream like you do in the webrtc.html example. I decided onpcvideo() function could be a good place for this. So I changed it as follows:
```
    onpcvideo(ev) {
        if (!this.pc) return;
        console.debug('pc video...')
        /** @type {HTMLVideoElement} */
        const video2 = ev.target;
        const state = this.pc.connectionState;

        // Firefox doesn't support pc.connectionState
        if (state === "connected" || state === "connecting" || !state) {
            // Video+Audio > Video, H265 > H264, Video > Audio, WebRTC > MSE
            let rtcPriority = 0, msePriority = 0;

            /** @type {MediaStream} */
            const ms = video2.srcObject;
            if (ms.getVideoTracks().length > 0) rtcPriority += 0x220;
            if (ms.getAudioTracks().length > 0) rtcPriority += 0x102;


            if (this.mseCodecs.indexOf("hvc1.") >= 0) msePriority += 0x230;
            if (this.mseCodecs.indexOf("avc1.") >= 0) msePriority += 0x210;
            if (this.mseCodecs.indexOf("mp4a.") >= 0) msePriority += 0x101;

            if (rtcPriority >= msePriority) {
                this.video.srcObject = ms;
                this.play();
                this.pcState = WebSocket.OPEN;

                this.wsState = WebSocket.CLOSED;
                this.ws.close();
                this.ws = null;
                this.video.srcObject.getTracks().forEach(track => { const sender = this.pc.addTrack(track,this.video.srcObject) }); // <===
                console.debug("rtc ok!!!");
            } else {
                console.debug("closing pc");
                this.pcState = WebSocket.CLOSED;
                this.pc.close();
                this.pc = null;
            }
        }

        video2.srcObject = null;
    }
```

Well, I feel like I am pretty close, but of course, it doesn't work. Any hints are appreciated!

**Comment by AlexxIT** [comment]
`getUserMedia` generates tracks (only one for mic). And you should add this tracks to `RTCPeerConnection` on start. Before any `createOffer`.

**Comment by aeozyalcin** [comment]
Ok I got it working! The code is rough at the moment, but it appears to work very reliably! The only issue I am observing is when I refresh Homeassistant Lovelace page with the WebRTC card, for whatever reason, 2 websocket connections are created, with the first one closing after about 5 seconds. Then the second one carries one, and is what delivers the displayed content. This behavior seems to throw off the Go2RTC server, because I think it initially expects microphone input from the first connection that quits ~5 seconds later. Even though the second sustained connection continues to send mic data, Go2RTC does not seem to relay it to the endpoint. This doesn't happen if I navigate to the dashboard page normally with the buttons.

I think this is a good start to getting this function added. I can work on a PR if you'd like.

**Comment by AlexxIT** [comment]
I think this code should be totally reworked with delayer 2 way audio start.
This requires rewriting the server part. Which I don't have time for right now.

**Comment by AlexxIT** [comment]
I think this question not to go2rtc but to WebRTC technology

**Comment by aeozyalcin** [comment]
I had to initiate the audio transceiver as 'sendrecv' without assigning the microphone track to that transceiver, because starting it as 'recvonly' then attempting to change it to 'sendrecv' on the fly required renegotiation which was too complicated. 

When I hit the unmute button, I assign the microphone track to the audio transceiver, and that seems to work. However, it appears that Go2RTC server still doesn't know what to do with incoming audio tracks when there are multiple connections, even though only a single connection is sending audio. On the go2rtc info page, I can see that the client is sending packets, the server is receiving the packets, but it's not relaying the packets to the camera.

**Comment by AlexxIT** [comment]
Any changes to SDP require new negotiation.
