### ISSUE TITLE
config file is not set

### ISSUE THREAD

**Issue by morpheus8888** [AlexxIT/go2rtc#243]
i'm using go2rtc integration in frigate, but i dont understand i need to put the config file

![image](https://user-images.githubusercontent.com/49568239/216944308-e560ddf3-5482-471d-9a69-18d14a11e5c5.png)

**Comment by AlexxIT** [comment]
go2rtc config is part of Frigate config. Separate YAML section. You can't use this page if using go2rtc inside Frigate.
