### ISSUE TITLE
Dahua vto 2wayaudio and audio settings

### ISSUE THREAD

**Issue by morpheus8888** [AlexxIT/go2rtc#255]
![image](https://user-images.githubusercontent.com/49568239/218529338-abad941a-4bef-4dae-9ac9-78f1b40c30a9.png)

I am using the 2wayaudio function on my VTO dahua 2202F with satisfaction. The problem is that to make it work I had to set the correct bitrate with the happy onvif program, otherwise it doesn't work. In the vto web page I don't have any audio configuration to set. Everything works fine for a few days, after which the audio settings go back to the default settings and nothing works anymore and I have to set it again. Is there a definitive procedure to prevent this? The vto is updated to the latest firmware.

**Comment by felipecrs** [comment]
Yes, there is:

- This you can do: https://github.com/AlexxIT/go2rtc/issues/49#issuecomment-1288196783
- Maybe go2rtc will also support this in the future: https://github.com/AlexxIT/go2rtc/issues/105

So, I'd suggest you close this issue.

**Comment by AlexxIT** [comment]
#49
