### ISSUE TITLE
Put `video-rtc.js` in an `npm` package?

### ISSUE THREAD

**Issue by dermotduffy** [AlexxIT/go2rtc#261]
Is [video-rtc.js](https://github.com/AlexxIT/go2rtc/blob/master/www/video-rtc.js) intended to be used by other developers writing frontend code to connect to go2rtc on the backend? If yes, exposing the player as an npm package would be maximally convenient.

If it is not intended that 3rd party developers use this player, would also appreciate knowing that now.

Thank you for go2rtc!

**Comment by AlexxIT** [comment]
Everything inside the `www` folder is just examples of use. You can use `video-rtc.js` or `video-stream.js` or `stream.html` or `webrtc.html` or build your own code from the scratch.
I try not to break the API in updates, but I can't guarantee it :)

**Comment by dermotduffy** [comment]
OK -- I'll treat it like that then, and re-use parts as necessary. Thanks.

The project is adding "native" go2rtc support into [frigate-hass-card](https://github.com/dermotduffy/frigate-hass-card).
