### ISSUE TITLE
Increasing delay using webrtc through stream.html

### ISSUE THREAD

**Issue by Biavleren** [AlexxIT/go2rtc#262]
<h2>Current setup</h2>
At the moment I am running go2rtc behind a nginx reverse proxy on a ubuntu in-house server.
The .yaml is configured to get rtsp stream from a D-link camera, which works well, even from public IP.

<h1>Issue</h1>
When refreshing stream page the video feed is almost instant 1:1 with reality - measured to ~100 ms. However, the delay is slowly increasing to  ~300 ms (measured) and then stays there.
The same behavior is observed when running locally without proxy.

<h2>Use case</h2>
My use case is to iframe the stream on a webpage which controlls robots, so the latency is really important.
Any thoughts?

<h4>Friendly regards</h4>
David

**Comment by AlexxIT** [comment]
Check stream info. What technology you using for stream. WebRTC or MSE

**Comment by Biavleren** [comment]
Hi AlexxIT

**I am using webrtc.**

**The .yaml log is:**

log:
    exec: trace
    streams: trace
    webrtc: trace

**The console produces this:**
13:58:40.525 INF go2rtc version 1.1.2 linux/amd64
13:58:40.525 INF [api] listen addr=:1984
13:58:40.525 INF [rtsp] listen addr=:8554
13:58:40.526 INF [srtp] listen addr=:8443
13:58:40.526 INF [webrtc] listen addr=:8555
13:58:40.933 DBG [webrtc] new consumer url=ip_cam
13:58:40.934 TRC [webrtc] offer:
v=0
o=- 7907306455026627691 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 103 104 105 106 107 108 109 127 125 39 40 41 42 43 44 45 46 47 48 112 113 114 115 116 49
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Mezp
a=ice-pwd:Er75RWjC1t1+HfEARtrGGFhe
a=ice-options:trickle
a=fingerprint:sha-256 F3:39:54:34:CA:1E:13:93:94:FB:F3:09:14:88:5C:4E:9B:98:BE:58:04:DA:A1:B4:B3:CD:B9:41:81:9A:E8:7E
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:35 VP9/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=fmtp:35 profile-id=1
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:37 VP9/90000
a=rtcp-fb:37 goog-remb
a=rtcp-fb:37 transport-cc
a=rtcp-fb:37 ccm fir
a=rtcp-fb:37 nack
a=rtcp-fb:37 nack pli
a=fmtp:37 profile-id=3
a=rtpmap:38 rtx/90000
a=fmtp:38 apt=37
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:104 H264/90000
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 transport-cc
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=127
a=rtpmap:39 H264/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
a=rtpmap:40 rtx/90000
a=fmtp:40 apt=39
a=rtpmap:41 H264/90000
a=rtcp-fb:41 goog-remb
a=rtcp-fb:41 transport-cc
a=rtcp-fb:41 ccm fir
a=rtcp-fb:41 nack
a=rtcp-fb:41 nack pli
a=fmtp:41 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=f4001f
a=rtpmap:42 rtx/90000
a=fmtp:42 apt=41
a=rtpmap:43 H264/90000
a=rtcp-fb:43 goog-remb
a=rtcp-fb:43 transport-cc
a=rtcp-fb:43 ccm fir
a=rtcp-fb:43 nack
a=rtcp-fb:43 nack pli
a=fmtp:43 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=f4001f
a=rtpmap:44 rtx/90000
a=fmtp:44 apt=43
a=rtpmap:45 AV1/90000
a=rtcp-fb:45 goog-remb
a=rtcp-fb:45 transport-cc
a=rtcp-fb:45 ccm fir
a=rtcp-fb:45 nack
a=rtcp-fb:45 nack pli
a=rtpmap:46 rtx/90000
a=fmtp:46 apt=45
a=rtpmap:47 AV1/90000
a=rtcp-fb:47 goog-remb
a=rtcp-fb:47 transport-cc
a=rtcp-fb:47 ccm fir
a=rtcp-fb:47 nack
a=rtcp-fb:47 nack pli
a=fmtp:47 profile=1
a=rtpmap:48 rtx/90000
a=fmtp:48 apt=47
a=rtpmap:112 H264/90000
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 transport-cc
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtpmap:113 rtx/90000
a=fmtp:113 apt=112
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=rtpmap:49 flexfec-03/90000
a=rtcp-fb:49 goog-remb
a=rtcp-fb:49 transport-cc
a=fmtp:49 repair-window=10000000
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Mezp
a=ice-pwd:Er75RWjC1t1+HfEARtrGGFhe
a=ice-options:trickle
a=fingerprint:sha-256 F3:39:54:34:CA:1E:13:93:94:FB:F3:09:14:88:5C:4E:9B:98:BE:58:04:DA:A1:B4:B3:CD:B9:41:81:9A:E8:7E
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000

13:58:40.950 TRC [streams] consumer=0 candidate=0 media="video, recvonly, 96 VP8/90000, 97 RTX/90000, 98 VP9/90000, 99 RTX/90000, 100 VP9/90000, 101 RTX/90000, 35 VP9/90000, 36 RTX/90000, 37 VP9/90000, 38 RTX/90000, 102 H264/90000, 103 RTX/90000, 104 H264/90000, 105 RTX/90000, 106 H264/90000, 107 RTX/90000, 108 H264/90000, 109 RTX/90000, 127 H264/90000, 125 RTX/90000, 39 H264/90000, 40 RTX/90000, 41 H264/90000, 42 RTX/90000, 43 H264/90000, 44 RTX/90000, 45 AV1/90000, 46 RTX/90000, 47 AV1/90000, 48 RTX/90000, 112 H264/90000, 113 RTX/90000, 114 RED/90000, 115 RTX/90000, 116 ULPFEC/90000, 49 FLEXFEC-03/90000"
13:58:40.951 DBG [streams] probe producer url=rtsp://192.168.89.168:554/live2.sdp
13:58:40.956 TRC [streams] producer=0 candidate=0 media="video, sendonly, 96 H264/90000"
13:58:40.956 TRC [streams] match producer:0:0 => consumer:0:0 codec="96 H264/90000"
13:58:40.962 TRC [streams] consumer=0 candidate=1 media="audio, recvonly, 111 OPUS/48000/2, 63 RED/48000/2, 9 G722/8000, 0 PCMU/8000, 8 PCMA/8000, 13 CN/8000, 110 TELEPHONE-EVENT/48000, 126 TELEPHONE-EVENT/8000"
13:58:40.962 TRC [streams] producer=0 candidate=0 media="video, sendonly, 96 H264/90000"
13:58:40.962 TRC [streams] producer=0 candidate=1 media="audio, sendonly, 0 PCMU/8000"
13:58:40.962 TRC [streams] match producer:0:1 => consumer:0:1 codec="0 PCMU/8000"
13:58:40.970 DBG [streams] start producer url=rtsp://192.168.89.168:554/live2.sdp
13:58:40.971 TRC [webrtc] answer
v=0
o=- 2121681091319475429 1676555920 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 02:80:DD:24:42:F5:C8:2C:FB:FC:9B:B8:52:6C:43:6C:96:5D:84:CE:60:FB:91:EB:8A:9B:52:5F:2B:A1:A9:2D
a=extmap-allow-mixed
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVPF 102 106 112
c=IN IP4 0.0.0.0
a=setup:active
a=mid:0
a=ice-ufrag:pPaVxURXfrVzpmjT
a=ice-pwd:RlQcRQuUmkZCfylPKYsdTAsrVbLVxyoV
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtpmap:106 H264/90000
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=rtpmap:112 H264/90000
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 transport-cc
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:2379265425 cname:go2rtc
a=ssrc:2379265425 msid:go2rtc video
a=ssrc:2379265425 mslabel:go2rtc
a=ssrc:2379265425 label:video
a=msid:go2rtc video
a=sendonly
m=audio 9 UDP/TLS/RTP/SAVPF 111 0 8
c=IN IP4 0.0.0.0
a=setup:active
a=mid:1
a=ice-ufrag:pPaVxURXfrVzpmjT
a=ice-pwd:RlQcRQuUmkZCfylPKYsdTAsrVbLVxyoV
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:3689371603 cname:go2rtc
a=ssrc:3689371603 msid:go2rtc audio
a=ssrc:3689371603 mslabel:go2rtc
a=ssrc:3689371603 label:audio
a=msid:go2rtc audio
a=sendonly

13:58:40.972 TRC [webrtc] config candidate="candidate:3457781915 1 udp 2130706431 85.191.112.107 8555 typ host"
13:58:40.972 TRC [webrtc] local candidate="candidate:670601336 1 udp 2130706431 192.168.89.50 8555 typ host"
13:58:40.972 TRC [webrtc] config candidate="candidate:1944772987 1 tcp 2124414975 85.191.112.107 8555 typ host tcptype passive"
13:58:40.972 TRC [webrtc] local candidate="candidate:2584469912 1 tcp 2124414975 192.168.89.50 8555 typ host tcptype passive"
13:58:40.985 TRC [webrtc] remote candidate=
13:58:40.986 TRC [webrtc] local candidate="candidate:2624867244 1 udp 1694498815 85.191.112.107 38279 typ srflx raddr 0.0.0.0 rport 38279"


**Very appreciating your work of go2rtc!**

**Comment by AlexxIT** [comment]
There is no information about selected candidate. You need to check stream info. You can find it in WebUI

**Comment by Biavleren** [comment]
**you mean this:**

{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.x.x/live2.sdp/",
      "remote_addr": "192.168.x.x:554",
      "user_agent": "go2rtc/1.1.2",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 0 PCMU/8000"
      ],
      "tracks": [
        "96 H264/90000, sinks=1",
        "0 PCMU/8000, sinks=1"
      ],
      "recv": 16062250
    }
  ],
  "consumers": [
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:50578 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
      "send": 1371906
    }
  ]
}

**Comment by AlexxIT** [comment]
WebRTC using UDP. There is can't be any delay between go2rtc and browser. So problem with your camera. What model do you have?

**Comment by Biavleren** [comment]
Its a D-Link model DCS-4602EV. I have bought a Marshall Electronics CV605-BK HD PTZ Camera which I aspect to get tomorrow. I will let you know when I have any news. Thank you for your time for now :)

**Comment by Biavleren** [comment]
Received and installed the new camera today. No delay, and no increasing delay either. It was the camera. Thank you for your help!
