### ISSUE TITLE
Add Camera Name using API

### ISSUE THREAD

**Issue by hendisantika** [AlexxIT/go2rtc#266]
I know that if we want to add Camera URL we can use POSTMAN or using Web App

POSTMAN CURL:
```
curl --location --request PUT 'http://YOUR_URL/api/streams?src=rtsp%3A%2F%2Fadmin%3A010917oke%40IP_ADDRESS%3A554%2FStreaming%2FChannels%2F101'
```

And this
![image](https://user-images.githubusercontent.com/3713580/220094804-8677e1bb-d63c-4f71-a51e-d64b58d162cb.png)

My question is how we can add camera name if we add camera from Web App & POSTMAN without add it from gortc.yml file?

Thanks

**Comment by AlexxIT** [comment]
You need to add query `name` parameter. But remember, all this streams will be lost after go2rtc restart. Only yaml streams persistant.

**Comment by hendisantika** [comment]
Could please give me an example from above curl?

**Comment by hendisantika** [comment]
Oo. yes. It working. Thanks @AlexxIT
