### ISSUE TITLE
How many simultaneously viewers are supported?

### ISSUE THREAD

**Issue by Biavleren** [AlexxIT/go2rtc#267]
### Setup
go2RTC is setup with a RTSP camera. With ~5 viewers, the stream is running flawlessly. However, increasing the number of simultaneous viewers, the stream acts with dropouts (some times up to 10 second freeze and other times black screen).
The go2RTC application is put behind a reverse proxy nginx.
### Debug
No text in console using exec: trace in .yaml.

### Question
How many simultaneous viewers is go2Rtc designed to handle?

**Comment by AlexxIT** [comment]
It depends on what technology you using on clients.
Go2rtc sends data to all clients simultaneously. So stream will be delayed to worst TCP viewer. Even if it will be only two viewers.

**Comment by Biavleren** [comment]
Any suggestions of how to multiple viewers? add a media server, like janus https://janus.conf.meetecho.com/ ?

**Comment by AlexxIT** [comment]
You can use only WebRTC UDP. So there is no delay from clients.

**Comment by Biavleren** [comment]
When I try to stresstest (+ 6 viewers) I am using "&mode=webrtc" in the URL but still experience freezing i the streams. The freezing is both on local IP and public IP. However, through the ip-cams own GUI, (before go2RTC) the stream is fine.

**Comment by AlexxIT** [comment]
You can check stream info page. If there is UDP for all viewers or not

**Comment by Biavleren** [comment]
The drop-outs is shown on the picture where 8 views are running.  I have added a timestamp in the camera feed which can compaired. As the picture show there are mismatches with feeds, however the stream info shows webrtc client (UDP).

<img width="1838" alt="image" src="https://user-images.githubusercontent.com/71124726/220272414-2fc4d792-076d-4f9e-83d5-63873e40d0d1.png">

**Stream info**

{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.x.x:554/live/av1/",
      "remote_addr": "192.168.x.x:554",
      "user_agent": "go2rtc/1.1.2",
      "medias": [
        "video, sendonly, 96 H264/90000"
      ],
      "tracks": [
        "96 H264/90000, sinks=8"
      ],
      "recv": 79828762
    }
  ],
  "consumers": [
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:64395 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 79999910
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:53116 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 79999910
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:54133 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 72441108
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:63164 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 72441108
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:64234 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 45835993
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:64238 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 45835993
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:55883 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 4323124
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.x.x:59769 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
      "send": 4323124
    }
  ]
}

**Comment by AlexxIT** [comment]
I can see all your clients using UDP proto. It's impossible that UDP packets may be delayed, so problem on client side.

**Comment by Biavleren** [comment]
Thank you for your replies!
Honestly, I dont really know what to look for in chromes debugger. I have downloaded an internal Dump and inserted that into app.testrtc.com as shown in the first screendump. It clearly states that there are a packet loss of 15%...
### app.TestRTC.com analyse result
<img width="521" alt="debug1" src="https://user-images.githubusercontent.com/71124726/220290769-2b461b32-19f4-46e9-8ec0-bc28fdca56a5.png">

### Snippet of pm2 list output from nginx server
<img width="890" alt="debug2" src="https://user-images.githubusercontent.com/71124726/220290775-456364dd-30ea-4011-8ed4-38e2bca16b05.png">
As the snippets states does the go2rtc application not consume any ressources according to the pm2.

### Go2RTC web GUI
Shows that there are running 7 viewers, all UDP clients (webRTC)
<img width="233" alt="debug3" src="https://user-images.githubusercontent.com/71124726/220290776-4c421a64-5cec-4674-a367-cc9dd8816c2f.png">

**Comment by AlexxIT** [comment]
I can say for sure that the problem is not on the server side. go2rtc sends each frame at the same time for all clients.
If some clients show old frames - the problem is either on the client side or the network side.
And you should not look at nginx. WebRTC is P2P connection. Nginx is not involved in transferring this traffic.

**Comment by Biavleren** [comment]
### UPDATE!
I have not succeeded to find the exact bug in my current setup, however, I have tried implimenting go2RTC on two other computers (thinkpad L15 and a stationary workhorse, both windows), connected +20 viewers (mode=webRTC) with no lag at all. So my next move is to setup the stationary with NGINX and see if I shall throw the current go2RTC-hosting machine in the carbage-can... I will update the thread when I have updates :) Thank you AlexxIT!

**Comment by Biavleren** [comment]
### UPDATE!
I didn't manage to implement nginx and go2rtc on my windows machine. Instead I took a RPi 4 I had available and installed a fresh ubuntu image on it. Successfully installed nginx with SSL and proxy_passing to localhost:1984. Now I have a functioning go2RTC instance which i can iframe on my website. For now I have tested the setup with +15 simultaneously viewers with no lag, which is awesome. Still haven't found the maximum number of viewers yet.
Just a little update. Thank you for go2RTC! :D
