### ISSUE TITLE
error="codecs not match: PCMA" china DVR

### ISSUE THREAD

**Issue by bartlebi** [AlexxIT/go2rtc#268]
Hello! Trying to add stream from china DVR.
As i can see in VLC it has PCMA audio codec but trying look stream by go2rtc i see next error: 
ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:159 > error="codecs not match: PCMA"

Unfortunately the DVR does not have settings for choosing a codec for broadcasting

**Comment by AlexxIT** [comment]
This is error from MJPEG module. Of course MJPEG not support PCMA audio :)

**Comment by bartlebi** [comment]
But there is no image from mse or any other stream type i tried. How can i debug it?

**Comment by AlexxIT** [comment]
You can increase log level.

**Comment by bartlebi** [comment]
I've increase log level. 
But there is nothing useful (as i see) in the log:
```
19:56:14.264 INF go2rtc version 1.2.0 linux/amd64
19:56:14.265 INF [api] listen addr=:1984
19:56:14.266 INF [rtsp] listen addr=:8554
19:56:14.273 INF [srtp] listen addr=:8443
19:56:14.274 INF [webrtc] listen addr=:8555
19:56:23.780 DBG [streams] probe producer url=rtsp://admin:pass@192.168.1.55:554/unicast/c2/s0/live
19:56:23.788 DBG [webrtc] new consumer url=camera2
19:56:23.887 DBG [streams] stop producer url=rtsp://admin:pass@192.168.1.55:554/unicast/c2/s0/live
19:56:23.888 DBG [mp4] add consumer error="codecs not match: PCMA"
19:56:23.905 DBG [streams] probe producer url=rtsp://admin:pass@192.168.1.55:554/unicast/c2/s0/live
19:56:24.008 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:159 > error="codecs not match: PCMA"
19:56:24.013 DBG [streams] start producer url=rtsp://admin:pass@192.168.1.55:554/unicast/c2/s0/live
19:56:53.958 DBG [streams] stop producer url=rtsp://admin:pass@192.168.1.55:554/unicast/c2/s0/live
```

**Comment by AlexxIT** [comment]
You need to increase log level to trace for rtsp module.
I think you just need to use ffmpeg source.
This is suggested in readme in case of problem.

**Comment by bartlebi** [comment]
Main problem was unsuppported h265 in the browser.
