### ISSUE TITLE
Combination of #hardware and #video=mjpeg caused cropped image at 256pixel height.

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/go2rtc#270]
As the title states. This is what happens with this url:

URL used: 
    - ffmpeg:rtsp://X:X@192.168.50.9:8554/live0#video=mjpeg#hardware#rotate=90
    
    Result:
    
![image](https://user-images.githubusercontent.com/1342643/220215250-1c9b3f53-94e7-4ba1-8565-05edef4adc43.png)

Without #rotate=90:
![image](https://user-images.githubusercontent.com/1342643/220215306-f6b93268-e163-454e-b709-742a8d51f2a9.png)

**Comment by AlexxIT** [comment]
If you read docs carefully, you can see that hardware only supported for H264 for now. MJPEG and H265 has some known problems.

**Comment by maxi1134** [comment]
I tried removing #hardware and kept 


`    - ffmpeg:rtsp://X:X@192.168.50.9:8554/live0#video=mjpeg#rotate=90`
    
   The problem is still present. 256pixel high seems like a very odd number to bug on, perhaps a restriction somewhere?

**Comment by AlexxIT** [comment]
What size of your picture? #83

**Comment by maxi1134** [comment]
it is 2304x1296

**Comment by AlexxIT** [comment]
Thats the answer https://github.com/AlexxIT/go2rtc/issues/83#issuecomment-1286704116

**Comment by maxi1134** [comment]
Resolution of 1080p works perfectly. Along with #hardware

**Comment by AlexxIT** [comment]
Hardware option not working for MJPEG transcoding.

**Comment by maxi1134** [comment]
You sir are correct, I misremembered the line I was using at this moment.
