### ISSUE TITLE
How to pass resolution and FPS?

### ISSUE THREAD

**Issue by Chandramouli-P** [AlexxIT/go2rtc#276]
Hello,

Good evening. We are able to render the RTSP streams which are coming from the IP cameras on to web browser successfully. In this scenario, we are giving RTSP URL along with user name and password (credentials). But, I couldn't able to find where and how to give particular resolution, frames per second (FPS), bit rate, etc...

Can anyone suggest how and where to pass these parameters? Thank you.

Best Regards,
Chandramouli.

**Comment by NickM-27** [comment]
You'd either need to set that in the camera settings or you need to use the ffmpeg module to reencode the stream https://github.com/AlexxIT/go2rtc#source-ffmpeg

**Comment by AlexxIT** [comment]
You need to use transcoding via FFmpeg
