### ISSUE TITLE
Fix complex Content-Type for image/jpeg

### ISSUE THREAD

**Issue by efaden** [AlexxIT/go2rtc#278]
I have an old hikvision cube (2432) I have been trying to get to work correctly with go2rtc, but I am having issues with the snapshots.  Currently the camera is providing 2 streams (2048*1536 H264 audio and video, and 704*480 H264 audio and video).  I have two streams setup, one for main and one for the sub. As follows

```
  camera.garage:
    - rtsp://user:password@IP:554/Streaming/Channels/101?transportmode=unicast

  camera.garage_substream:
    - rtsp://user:password@IP:554/Streaming/Channels/102?transportmode=unicast
```

I tried adding the JPEG as an HTTP which can be found at - http://user:password@IP:554/Streaming/Channels/101/picture ... the 102 channel doesn't support JPEG.

The issue is that when I do that I get the following error.

```
WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="wrong Content-Type: image/jpeg; charset=\"UTF-8\"" url=http://user:password@IP/Streaming/Channels/101/picture?snapShotImageType=JPEG
```

When I manually look at the headers in chrome, I noticed that the Content-Type inculdes the the charset....  "image/jpeg; charset="UTF-8""

Which I am guessing is causing the issue. 

Is there a way around this?  I was thinking about setting up a nginx proxy to strip the headers, but that just seemed crazy....

**Comment by efaden** [comment]
Of note in the mpeg producer line 36 is:

````
	if ct == "image/jpeg" {
		return c.startJPEG()
	}
```

So the charset  is breaking that I assume.   Considering charset= blah is a valid value within content type seems like this should be modified to allow for that.

**Comment by efaden** [comment]
I think making the if statement 

```
if _, s, ok := strings.Cut(ct, "image/jpeg"); ok {
```

Would fix it.

**Comment by efaden** [comment]
Thanks.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.1
