### ISSUE TITLE
Is there a way to disable transcoding?

### ISSUE THREAD

**Issue by tomuta** [AlexxIT/go2rtc#281]
I'm not sure if this is possible or just not documented, but I am wondering if there is a way to disable ffmpeg transcoding. This obviously limits compatibility with clients, but would be a useful feature when using on e.g. a VPS with very limited shared resources.

**Comment by AlexxIT** [comment]
Disable? Go2rtc not transcoding anything be default.

**Comment by tomuta** [comment]
Thanks for the clarification.
