### ISSUE TITLE
configure go2rtc so that all cameras are selected when you open it

### ISSUE THREAD

**Issue by stamandr** [AlexxIT/go2rtc#282]
Does anyone know how to configure go2rtc so that all cameras are selected when you open it ?

![image](https://user-images.githubusercontent.com/51379504/224404596-33b4318e-6d7c-4ac5-a0af-6187a0ffe805.png)

**Comment by Write** [comment]
You need to manually add them to the config under streams: {}, not adding them here, and then they'll show up every time.

**Comment by stamandr** [comment]
Joffrey - Please elaborate.

"You need to manually add them to the config under streams: {}, not adding them here, and then they'll show up every time."

I have all these entries in my config. Do you have an example ?

**Comment by Write** [comment]
> Joffrey - Please elaborate.
> 
> 
> 
> "You need to manually add them to the config under streams: {}, not adding them here, and then they'll show up every time."
> 
> 
> 
> I have all these entries in my config. Do you have an example ?

Well if so, i'm not sure what is not showing up ? 
this why I deleted my comment, I' don't understand your problem.

**Comment by stamandr** [comment]
I am asking if there is a way to have all the cameras selected when you open go2rtc, as opposed to the default where you have to select them individually.

**Comment by Write** [comment]
well, no.
Is it for the "stream" feature ? if so you can just just copy the url, but my guess is that you already thought of that. 
An other option is to create an userscript that select all entry on load with Violentlonkey, but that would only work on desktop.
Or suggest it as a new feature. 
But what is your goal exactly, why do you want them all selected everytime ?

**Comment by stamandr** [comment]
I want them all selected so that I can select stream. Not having to select them individually.

**Comment by Write** [comment]
Well best bet is just to save the url then.

**Comment by stamandr** [comment]
Do you actually try what you suggest ?

**Comment by stamandr** [comment]
AlexxIT, I see you modified go2rtc so that you can easily select all with the recent update. Many thanks. Keep up the great work....

**Comment by stamandr** [comment]
Unfortunately a new issue issue has appeared. When you select all streams ( I have 12 streams ). One stream gets the error " webrtc/offer: stream not found " The last stream on the list is full sized. If all cameras are selected manually they all appear correctly...

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0

**Comment by stamandr** [comment]
Thanks... Keep up the good work
