### ISSUE TITLE
Audio Aqara G3 not work

### ISSUE THREAD

**Issue by sdavides** [AlexxIT/go2rtc#285]
Audio on Aqara G3 120C it does not work, video work

I added config:

```
streams:
  aqara_g3:
    - hass:Camera-Hub-G3-120C
    - ffmpeg:aqara_g3#audio=aac#audio=opus#async
```

**Comment by AlexxIT** [comment]
Where you trying to get audio?

**Comment by sdavides** [comment]
Hi AlexxIT, I try from all url possible into page link present on the component.

can you see this link? I created a method to control the camera through posts, maybe it helps you to implement other functions.
Are you Italian?
congratulations for your job. HI

https://github.com/sdavides/PTZ-AqaraCAM-Homeassistant

**Comment by AlexxIT** [comment]
Please show info page from WebUI when stream active.

You did an interesting research about cloud API. But only a couple of percent of users will be able to repeat it.

**Comment by sdavides** [comment]
![immagine](https://user-images.githubusercontent.com/31100253/227417708-f8c33a9d-f90a-4432-8664-7625515516fc.png)

I try link on:
![immagine](https://user-images.githubusercontent.com/31100253/227417785-1e4179fa-2ae0-4382-906f-36bbce696a07.png)

**Comment by sdavides** [comment]
I added config
`streams:
  aqara_g3:
    - hass:Camera-Hub-G3-120C
    - ffmpeg:aqara_g3#audio=aac#audio=opus#async`
and set up webrtc card with src=aqara_g3, the sound works
