### ISSUE TITLE
Samsung Galaxy Tab A8 - Android 13 issue

### ISSUE THREAD

**Issue by spawn451** [AlexxIT/go2rtc#286]
Unable to see the video on chrome as well as through the Home Assistant app on my Galaxy Tab A8 tablet. The video display screen remains black.
In firefox I get the message : webrtc/offer: codecs not match: H264,AAC
I tried everything but found no solution. However, it works fine on my PC. Is there any special configuration to do on the tablet? Thanks for your great work!

**Chrome**
WebRTC result : 
![webrtc](https://user-images.githubusercontent.com/87195479/224974728-adf017c2-ce79-4571-9c1b-ea0822c41e87.jpg)

MSE result : 
![mse](https://user-images.githubusercontent.com/87195479/224975077-f7353fa6-e638-45e2-89ca-031825dbded8.jpg)

**Comment by akmolina28** [comment]
Did you figure this out? I'm having the same problem. webrtc and mse won't load on my samsung tablet but work on my samsung phone, pc, etc...

**Comment by spawn451** [comment]
Hi, using the sub stream instead of the main stream of my camera (Reolink Video Doorbell Wifi) fixed my issue.

**Comment by akmolina28** [comment]
Thanks, I guess it's just a limitation of Samsung's tablets. It just won't decode high res video. Unfortunately this includes clips and recordings too.

**Comment by NickM-27** [comment]
You can use chrome://media-internals to get more info on why it fails

**Comment by LavermanJJ** [comment]
I'm running into the same issue. The video won't playback using webRTC or MSE. 
Error from chrome://media-internals:

```
error: "video decoder initialization failed"

error: {"code":15,"data":{},"group":"PipelineStatus","message":"","stack":[{"file":"media/renderers/video_renderer_impl.cc","line":303]}
```

Does this really mean, that H264 is not supported on Galaxy Tab A8 in Chrome. Or is it just the UHD "coded size"?

Strange thing is, using VLC on the Galaxy Tab A8 it works. Just within HASS (via Frigate) or Chrome it's not working.

**Comment by NickM-27** [comment]
VLC and browser playback use different engines in the phone so it makes sense that one may work while another doesn't

**Comment by AlexxIT** [comment]
It can be because hi video profile. You can check it in WebUI info.

**Comment by bradfree63** [comment]
I stumbled here looking for a solution to the same issue. I have this tablet mounted as a wall panel running Fully Kiosk. Live video plays fine however Frigate recordings do not. I have tried using HA app and chrome with exactly the same results. Did anyone find a solution?

**Comment by johnwilson1969** [comment]
Same issue for me. 

[{"alpha mode":"is_opaque","codec":"h264","coded size":"2560x1920","color space":{"matrix":"BT709","primaries":"BT709","range":"LIMITED","transfer":"BT709"},"encryption scheme":"Unencrypted","has extra data":false,"hdr metadata":"unset","natural size":"2560x1920","orientation":"0°","profile":"h264 main","visible rect":"0,0 2560x1920"}]

Seems to know what the video file is all about....

**Comment by stingone** [comment]
Same here. works well in VLC not in the browser. only the substreams wil load.

**Comment by Peter71131** [comment]
I belive i have the same Problem. By me its working in firefox. But fully kiosk or chrome are not working.

**Comment by Peter71131** [comment]
My cam provides 2 diffrent qualityis.

If I use the lower quality, it seems it works.

{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.188.81:554/stream2/",
      "remote_addr": "192.168.188.81:554",
      "user_agent": "go2rtc/",
      "sdp": "v=0\r\no=- 14665860 31787219 1 IN IP4 192.168.188.81\r\ns=Session streamed by \"TP-LINK RTSP Server\"\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:4096\r\na=range:npt=0-\r\na=control:track1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; profile-level-id=4D0016; sprop-parameter-sets=Z00AFoqKUFAX/LNkAAAPoAAB1MAQ,aO48gA==\r\nm=audio 0 RTP/AVP 8\r\na=rtpmap:8 PCMA/8000\r\na=control:track2\r\n",
      "medias": [
        "video, recvonly, H.264 Main 2.2",
        "audio, recvonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=221014, senders=1",
        "8 PCMA/8000, bytes=343040, senders=1"
      ],
      "recv": 578618
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 192.168.188.110:48813",
      "user_agent": "Mozilla/5.0 (Linux; Android 13; 23073RPBFG Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, AV1, H264, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=221014, receivers=1",
        "8 PCMA/8000, bytes=343040, receivers=1"
      ],
      "send": 578068
    }
  ]
}


If i use the higher one it is not working


{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.188.81:554/stream1/",
      "remote_addr": "192.168.188.81:554",
      "user_agent": "go2rtc/",
      "sdp": "v=0\r\no=- 14665860 31787219 1 IN IP4 192.168.188.81\r\ns=Session streamed by \"TP-LINK RTSP Server\"\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:4096\r\na=range:npt=0-\r\na=control:track1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; profile-level-id=4D0032; sprop-parameter-sets=Z00AMoqKUBQAWtNkAAAPoAAB1MAQ,aO48gA==\r\nm=audio 0 RTP/AVP 8\r\na=rtpmap:8 PCMA/8000\r\na=control:track2\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.0",
        "audio, recvonly, PCMA/8000"
      ],
      "receivers": [
        "96 H264, bytes=6890710, senders=3",
        "8 PCMA/8000, bytes=933888, senders=3"
      ],
      "recv": 7913290
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 192.168.188.110:37219",
      "user_agent": "Mozilla/5.0 (Linux; Android 13; 23073RPBFG Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, AV1, H264, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=6890710, receivers=1",
        "8 PCMA/8000, bytes=933888, receivers=1"
      ],
      "send": 7923613
    },
    {
      "type": "MSE/WebSocket active consumer",
      "remote_addr": "192.168.188.110:34294",
      "user_agent": "Mozilla/5.0 (Linux; Android 13; 23073RPBFG Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Safari/537.36",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML"
      ],
      "senders": [
        "96 H264, bytes=6890710, receivers=1",
        "8 FLAC/8000, bytes=933888, receivers=1"
      ],
      "send": 9055140
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.188.95:63250 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=354234, receivers=1",
        "8 PCMA/8000, bytes=49152, receivers=1"
      ],
      "send": 408521
    }
  ]
}

**Comment by johnwilson1969** [comment]
Yeah I had narrowed it down to a resolution limitation in the Android
webkit/chrome I reduced resolution and was able to get it working as well.

**Comment by AlexxIT** [comment]
Only solution is transcoding or change viewer device.

**Comment by Peter71131** [comment]
> Solution is transcoding or change viewer device.

Thanks Alexx. Final Question for this before i setup the transcoding.
Why Mozilla Firefox showes everything fine, and Chrome and Fully Kiosk are not able to play the Stream?

**Comment by Peter71131** [comment]
Transcoding is working. But not so happy because i belive there should be another problem. Or i dont understand the problem. 
However for now this is the solution for my Tapo c320ws Streams to my android 13 Tablet.

```
  Kamera1:
    - ffmpeg:rtsp://admin123:admin123@192.168.188.81:554/stream1#video=h264#hight=1920#width=1080#audio=copy
```

**Comment by stingone** [comment]
How can i convert the streams below to a ffmpeg? with 1920x1080 without audio.

rtmp://192.168.1.25/bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=pass
rtsp://admin:pass%21@192.168.1.25:554/h264Preview_01_sub

**Comment by Peter71131** [comment]
> Peter71131



> Transcoding is working. But not so happy because i belive there should be another problem. Or i dont understand the problem. However for now this is the solution for my Tapo c320ws Streams to my android 13 Tablet.
> 
> ```
>   Kamera1:
>     - ffmpeg:rtsp://admin123:admin123@192.168.188.81:554/stream1#video=h264#hight=1920#width=1080#audio=copy
> ```



I am still unhappy that i need to transcode the streams of the Tapo c320ws cam for my tablet if i would like to use another browser as firefox, and don`t understand really the root cause, but @AlexxIT your Project is extreamly awesome and i like it really. Is there nowhere an donate buttom?

**Comment by AlexxIT** [comment]
All info on GitHub profile page.
