### ISSUE TITLE
Ezviz DB1 WebRTC issue

### ISSUE THREAD

**Issue by ajvalent333** [AlexxIT/go2rtc#290]
WebRTC does not load for Ezviz DB1 (Hikvision) camera on a different LAN or via VPN (MSE/mp4 work fine). The stream gets stuck on "loading". 

Strangely, WebRTC does load on cellular data for that camera. I can also access other streams remotely with WebRTC like the Big Buck Bunny RTSP stream (https://www.wowza.com/developer/rtsp-stream-test).

This issue must be specific to this camera. Is there a fix?

Let me know if I should share any logs...

![image](https://user-images.githubusercontent.com/89750517/225736780-9560b235-d161-422b-82bb-041ac29ed27e.png)

![image](https://user-images.githubusercontent.com/89750517/225737672-52c73dd6-6d10-4073-bafd-87fe37274203.png)

**Comment by AlexxIT** [comment]
Is this stream works for you in the same LAN with RTC technology?

**Comment by ajvalent333** [comment]
Yes that is correct, including cellular data. Issue is when on a separate LAN or VPN.

**Comment by ajvalent333** [comment]
Issue resolved with v1.6.0
