### ISSUE TITLE
Publishing RTSP stream from Larix Broadcaster ?

### ISSUE THREAD

**Issue by Write** [AlexxIT/go2rtc#293]
Hi,

Thanks for go2rtc, amazing tool and working great.

I'm trying to ditch rtsp-simple-server completely, but the last missing piece is how to "publish" a stream from an app called Larix Broadcaster (available on both iOS and Play Store). Basically the app can only "push" the stream to a server, we can't "grab" the stream from the device directly.

So my question is: Is there a way to publish such stream directly to go2rtc ? 

Thanks.

**Comment by NickM-27** [comment]
This is covered in the docs https://github.com/AlexxIT/go2rtc#incoming-sources

**Comment by Write** [comment]
Indeed creating an empty stream and publishing to it was enough, thanks again.

**Comment by Write** [comment]
Is there a way to check via HTTP Api if a stream is published to this path or not ?

**Comment by Write** [comment]
Well, ugliest healthcheck of the world for now

```
#!/bin/bash
if (/usr/bin/ffmpeg -y -rtsp_transport tcp -i rtsp://10.0.0.125:8554/entry -frames 1 /root/scripts/snap.png -timeout 1 2> /dev/null)
then
     echo "OK" > /root/nginx_html/entry_status
else
         echo "KO" > /root/nginx_html/entry_status
fi
```

**Comment by AlexxIT** [comment]
GET /api/streams?src=stream_name

**Comment by Write** [comment]
thanks, super awesome!
