### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by Benni1123** [AlexxIT/go2rtc#294]
I use the Reolink E1 Outdoor with the sub RTSP channel. The bitrate is 256kbit/s. When I run the stream on one device for a long time, there is a delay of up to 11 seconds. What is the reason for this?

**Comment by AlexxIT** [comment]
This is known problems with some Reolink cameras.
Check go2rtc 1.3.0. If the problem still exists - it cannot be fixed with these cameras.
As I know - Reolink cameras has awful RTSP protocol support.
