### ISSUE TITLE
URL shortener

### ISSUE THREAD

**Issue by sneakythr0ws** [AlexxIT/go2rtc#295]
Hi!
It would be nice to be able to shorten the RTSP URL(and other). It is long.
URL formatting(hide under tag) is not possible in some places.
The addon probably doesn't store the state, but you can use some hash to shorten the URL.

example:
http://192.168.1.122:1984/stream.html?src=rtsp://user:longpassword@192.168.1.146:8554/Streaming/Channels/1001&mode=webrtc
->
hash = shortHash('rtsp://user:longpassword@192.168.1.146:8554/Streaming/Channels/1001')
http://192.168.1.122:1984/stream.html?src={hash}&mode=webrtc

**Comment by AlexxIT** [comment]
This is temporary streams without **name**. If you add stream with name to the go2rtc.yaml - src will be name.
Also 1.3.0 allow you to add stream with name
