### ISSUE TITLE
Unable to Add repository in MomeAssistant

### ISSUE THREAD

**Issue by Muelner** [AlexxIT/go2rtc#300]
Hi,

Iget en error adding the repository in HA with the below error:

Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/AlexxIT/go2rtc /data/addons/git/efc3606a stderr: 'Cloning into '/data/addons/git/efc3606a'... fatal: unable to access 'https://github.com/AlexxIT/go2rtc /': URL using bad/illegal format or missing URL '

**Comment by AlexxIT** [comment]
This is wrong addon URL
