### ISSUE TITLE
Not working external web interface

### ISSUE THREAD

**Issue by MaxBocharovDev** [AlexxIT/go2rtc#302]
Hello/Привет. I have two trusted private network. 

Step1. In first network I install on server docker with go2rtc 
Step2 Added api in go2rtc.yaml
```
api:
  listen: ":1970"
```

Web interface and streams are working on `localhost:1970`. But I have a problem to resolve a `xxx.xxx.xxx.xxx:1970` from second network. 

Step3 Added port in docker-compose.yml
```
ports:
- "1970:1970"
```
Still not working. I check with netstat, 1970 port in status listen. 

It is my network configaration problem or may I added something in go2rtc config to solve a problem?

**Comment by AlexxIT** [comment]
It's your network configuration problems
