### ISSUE TITLE
Two way audio for companion app 

### ISSUE THREAD

**Issue by Bobbik1** [AlexxIT/go2rtc#305]
As above. Is there any chance for 2 way audio with companion app? As I assume Iphone is quite difficult to handle it, but Android?

**Comment by AlexxIT** [comment]
Two way audio work on both iPhone and Android apps

**Comment by Bobbik1** [comment]
But stream from media player only, or also the  microphone?

**Comment by AlexxIT** [comment]
Two way audio means both audio
