### ISSUE TITLE
Sending video to Telegram with sound Отправка видео в Telegram со звуком

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#306]
I am currently using 1.3.0
And even earlier I could follow the link
"http://localhost:1984/api/stream.mp4?src=DoorCamCh1&video=h264,h265&audio=aac,opus,mp3,pcma,pcmu&duration=15"
I could send video from the camera and doorbell to Telegram with sound, but now I don’t.
Я сейчас использую 1.3.0
И вот еще раньше я мог по ссылке
"http://localhost:1984/api/stream.mp4?src=DoorCamCh1&video=h264,h265&audio=aac,opus,mp3,pcma,pcmu&duration=15"
Мог отправлять видео с камеры и дверного звонка в Telegram со звуком, а сейчас нет.

**Comment by AlexxIT** [comment]
You need to check stream info in the WebUI just after telegram service call. To check what codecs inside.

**Comment by TokarevSergey** [comment]
How to do it?  I looked in the stream info video=h264&audio=pcmu.  All the same.  But before that it worked, but now it doesn't.  Sending is only possible
   http://localhost:1984/api/stream.mp4?src=DoorCamCh1&audio=pcmu&duration=15
 but then only the sound comes.

Как это сделать? Я смотрел в информации по потоку video=h264&audio=pcmu. Все так же. Но до этого работало, а сейчас нет. Отправить получается только
  http://localhost:1984/api/stream.mp4?src=DoorCamCh1&audio=pcmu&duration=15
но тогда приходит только звук.

**Comment by AlexxIT** [comment]
Open WebUI and click info link

**Comment by TokarevSergey** [comment]
> Откройте WebUI и нажмите информационную ссылку

Добрый день.
Вот что показывает камера при стриме.
Good afternoon.
Here's what the camera shows when streaming.
![image](https://user-images.githubusercontent.com/98225056/227943348-1f9d04db-cf29-4b5d-85b0-a4a9296ad4ec.png)

Если я указываю в автоматизации вот так:
If I specify in automation like this:
![image](https://user-images.githubusercontent.com/98225056/227943652-1a98ad4d-b958-432f-805a-cc5457457647.png)
то в Telegram вообще ничего не приходит просто пусто нет сообщения вобще.
then nothing comes to Telegram at all, just empty there is no message at all.

А если ставлю вот так:
And if I put it like this:
![image](https://user-images.githubusercontent.com/98225056/227943977-2e01f50d-3073-4c28-a17f-5ba368b6981d.png)
то в Telegram приходит видеофайл с белым фоном и записаным аудио.
then a video file with a white background and recorded audio comes to Telegram.
![image](https://user-images.githubusercontent.com/98225056/227946428-b88d7f1d-cb2f-4c63-9fae-32465f98b997.png)

Как мне настроить отправку видео со звуком в Telegram, чтобы работало так как раньше до версии 1.3.0

**Comment by TokarevSergey** [comment]
> Откройте WebUI и нажмите информационную ссылку

Добрый день.
Вот что показывает камера при стриме.
Good afternoon.
Here's what the camera shows when streaming.
![image](https://user-images.githubusercontent.com/98225056/227943348-1f9d04db-cf29-4b5d-85b0-a4a9296ad4ec.png)

Если я указываю в автоматизации вот так:
If I specify in automation like this:
![image](https://user-images.githubusercontent.com/98225056/227943652-1a98ad4d-b958-432f-805a-cc5457457647.png)
то в Telegram вообще ничего не приходит просто пусто нет сообщения вобще.
then nothing comes to Telegram at all, just empty there is no message at all.

А если ставлю вот так:
And if I put it like this:
![image](https://user-images.githubusercontent.com/98225056/227943977-2e01f50d-3073-4c28-a17f-5ba368b6981d.png)
то в Telegram приходит видеофайл с белым фоном и записаным аудио.
then a video file with a white background and recorded audio comes to Telegram.
![image](https://user-images.githubusercontent.com/98225056/227946428-b88d7f1d-cb2f-4c63-9fae-32465f98b997.png)

Как мне настроить отправку видео со звуком в Telegram, чтобы работало так как раньше до версии 1.3.0

**Comment by NickM-27** [comment]
The url you are sending telegram only has `&audio=` which means you are requesting the stream without video. If you want video then you need to ask for it `stream.mp4?src=DoorCamVStreetCh2&video&audio=pcmu&duration=15`

**Comment by TokarevSergey** [comment]
> URL-адрес, который вы отправляете, имеет только телеграмму, `&audio=`что означает, что вы запрашиваете поток без видео. Если вы хотите видео, вам нужно попросить его`stream.mp4?src=DoorCamVStreetCh2&video&audio=pcmu&duration=15`

Да я же выше писал что так вообще ничего не приходит так не работает. Если в строку дорбавитьт слово "video" вобще неприходит.

**Comment by AlexxIT** [comment]
You showing info with active WebRTC. You need to check info with active `stream.mp4` call. You can open this link in any browser. But change localhost to your server address.

**Comment by TokarevSergey** [comment]
> Вы показываете информацию с активным WebRTC. Вам нужно проверить информацию с активным `stream.mp4`вызовом. Вы можете открыть эту ссылку в любом браузере. Но измените localhost на адрес вашего сервера.

Попробую обьяснить еще раз.
У меня несколько видео камер Hikvision и дверной звонок Hikvision которые подключены go2rtc по протоколу rtsp
До того как я обновился на версию go2rtc 1.3.0 я мог отправлять короткие видео ролики в телеграм используя автоматизацию. И это работало!!!!
I'll try to explain again.
I have several Hikvision video cameras and a Hikvision doorbell connected to go2rtc via rtsp protocol.
Before I upgraded to go2rtc 1.3.0, I was able to send short video clips to Telegram using automation. And it worked successfully!!!
![image](https://user-images.githubusercontent.com/98225056/227983472-7006407c-42e1-4462-a6bf-a64e40cf494f.png)
Я мог поставить любую ссылку из ниже преведенных и у меня приходило видео на телеграм со звуком.
I could put any link below and I got a telegram video with sound.
http://10.0.1.83:1984/api/stream.mp4?src=DoorCamVStreetCh2&video=h264&audio=pcmu&duration=15
http://10.0.1.83:1984/api/stream.mp4?src=DoorCamVStreetCh2&video=h264,h265&audio=pcmu&duration=15
http://10.0.1.83:1984/api/stream.mp4?src=DoorCamVStreetCh2&video&audio=pcmu&duration=15
http://10.0.1.83:1984/api/stream.mp4?src=DoorCamVStreetCh2&video=all&audio=pcmu&duration=15
После тоно как я обновился до версии go2rtc 1.3.0 я перестал получать короткий видеоролик в телеграм вообще. Тоесть он просто не приходит. Эти ссылки перестали работать.
After I upgraded to go2rtc 1.3.0, I stopped receiving a short video in telegram at all. I mean, he just doesn't come. These links have stopped working.
Вот мой конфиг go2rtc 
Here is my go2rtc config
![image](https://user-images.githubusercontent.com/98225056/227985856-b6fd001d-e217-428c-aa53-e64fdd24293b.png)
![image](https://user-images.githubusercontent.com/98225056/227986159-1cd74406-ad36-48c6-b6b8-93b87afc3ec5.png)
![image](https://user-images.githubusercontent.com/98225056/227986321-fa00eef7-bc7f-4ba5-a4d0-ecdbf130e345.png)
![image](https://user-images.githubusercontent.com/98225056/227986470-a654c575-0bf7-4f16-8f0b-269cb1a8b9cf.png)

**Comment by AlexxIT** [comment]
There is no point in writing the same thing several times. It is better to do what I wrote above.

**Comment by TokarevSergey** [comment]
> Нет смысла писать одно и то же несколько раз. Лучше сделать то, что я написал выше.

Если несколько раз подрят запустить вот эту ссылку.
http://10.0.0.100:1984/api/stream.mp4?src=DoorCamCh1&video=h264&audio=pcmu&duration=5
вылетает интеграция go2rtc 1.3.1

If several times podryat run here this link.
http://10.0.0.100:1984/api/stream.mp4?src=DoorCamCh1&video=h264&audio=pcmu&duration=5
go2rtc 1.3.1 integration crashes

![image](https://user-images.githubusercontent.com/98225056/228050950-c4eb2839-0035-47b6-8856-71763db48124.png)

**Comment by TokarevSergey** [comment]
> Нет смысла писать одно и то же несколько раз. Лучше сделать то, что я написал выше.

Вот что я нарыл.
Если поставить такую ​​ссылку:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&duration=15"
в телеграм приходит файл (видео есть, звука нет)
Here's what I've churned out.
If you put a link like this:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&duration=15"
a file arrives in telegram (there is a video, no sound)

Если поставить такую ​​ссылку:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264&duration=15"
в телеграм приходит файл (видео есть, звука нет)
Here's what I've churned out.
If you put a link like this:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264&duration=15"
a file arrives in telegram (there is a video, no sound)

Если поставить такую ​​ссылку:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&audio=pcmu&duration=15"
в телеграм приходит файл (нет видео, есть звук)
If you put a link like this:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&audio=pcmu&duration=15"
a file arrives in telegram (no video, there is sound)

Если поставить такую ​​ссылку:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video&audio&duration=15"
Telegram вообще ничего не получает.
If you put a link like this:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video&audio&duration=15"
Telegram does not receive anything at all.

Если поставить такую ​​ссылку:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264&audio=pcmu&duration=15"
Telegram вообще ничего не получает.
If you put a link like this:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264&audio=pcmu&duration=15"
Telegram does not receive anything at all.

Если поставить такую ​​ссылку:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264,h265&audio=pcmu&duration=15"
Telegram вообще ничего не получает.
If you put a link like this:
"http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264,h265&audio=pcmu&duration=15"
Telegram does not receive anything at all.

Помогите мне как получить видео в телеграм созвуком. Спасибо.
Help me how to get telegram video with sound. Thank you.

**Comment by TokarevSergey** [comment]
> Нет смысла писать одно и то же несколько раз. Лучше сделать то, что я написал выше.


Help me how to get telegram video with sound. Thank you.

**Comment by TokarevSergey** [comment]
После обновления все работает. Спасибо.
