### ISSUE TITLE
How does go2rtc prioritize streams from the same camera?

### ISSUE THREAD

**Issue by redelacruz** [AlexxIT/go2rtc#308]
Hi, Alex!

I was just wondering how go2rtc prioritizes multiple streams from the same camera. I have a CCTV connected via ethernet and Wi-Fi, with different IPs for each connection type.

So, in my config, I have the following:
```
streams:
  outdoor_front_hd: 
    # wired
    - rtsp://secret:secret@192.168.2.11:554/user=admin_password=_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream
    # wireless
    - rtsp://secret:secret@192.168.2.10:554/user=admin_password=_channel=0_stream=0&protocol=unicast&onvif=ture.sdp?real_stream
```
Given my config above, will go2rtc prioritize the wired stream because it comes first in the config? Or does it prioritize streams (exactly the same stream, just from different addresses) some other way?

Ideally, I want it to prioritize the wired stream but use the wireless as a failover in case some smartass decides to cut the cable to the camera before sneaking into my home.

**Comment by AlexxIT** [comment]
Go2rtc queries all sources one by one. It will stop when all client codecs will match. Everything will work like you want.

**Comment by redelacruz** [comment]
Awesome! Thanks!
