### ISSUE TITLE
Add support TCP MPEG-TS source

### ISSUE THREAD

**Issue by lolorc** [AlexxIT/go2rtc#310]
hi there,
I'm using licamera-vid to stream off my raspberry cam, see https://www.raspberrypi.com/documentation/computers/camera_software.html#tcp

Would it be possible to add the tcp:// input scheme to go2rtc ?

**Comment by lolorc** [comment]
oh thanks for the very quick response !

I've tried both tcp://localhost:8888 with a ffmpeg process listening to 8888
I've also tried with a stream fetching directly from the raspberry pi. (ffprobe reports "Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 15 fps, 15 tbr, 1200k tbn, 30 tbc" from libcamera-vid)

In both cases it doesn't connect to any of the tcp source, it just says:
```
18:06:46.631 DBG [streams] can't stop none producer
18:06:46.631 DBG [mp4] add consumer error="sources unavailable: 1"
18:06:46.636 DBG [webrtc] new consumer src=tcp
18:06:46.638 DBG [streams] can't stop none producer
18:06:46.638 DBG [webrtc] add consumer error="sources unavailable: 1"
18:06:46.638 DBG [streams] can't stop none producer
18:06:46.639 DBG [streams] can't stop none producer
18:06:46.639 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:160 > error="sources unavailable: 1"
```

works indeed ok with an rtsp source, sorry this my first time with go2rtc, I've discovered it using frigate-dev. :-)

I don't get the http stuff from https://github.com/AlexxIT/go2rtc/commit/8fde2b6fe58377761a29562eeed9216a31c84b31#diff-fc0897c02733c250d6c63b5b598b27369ee1fe04d3d27b351bdd4cefe5282578R28-R29

**Comment by lolorc** [comment]
rtsp-simple-server does now support raspberry pi cam with libcamera, so it might not be worth spending more time on this "enhancement", up to you :-)
anyway, thanks again for the super quick response !

**Comment by AlexxIT** [comment]
Are you sure you using master version?

**Comment by lolorc** [comment]
Hi,
I've just compiled it from source, feeding go2rtc with "ffmpeg re" works while a direct connection to the tcp port served by libcamera doesn't.

**Comment by AlexxIT** [comment]
You can share this stream to me (TCP port 8888):
https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet

You can check my contacts in my GitHub profile.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.3.2
