### ISSUE TITLE
Telegram bot send mute video

### ISSUE THREAD

**Issue by sashakozlov86** [AlexxIT/go2rtc#318]
Good afternoon  According to the following example, I set up sending a video with a specified duration to my telegram bot, but the videos come without sound, although in fact there is sound from the camera when opening a live stream in g2rtc.  I tried to set additional parameters like: ...&audio=mp3,aac,pcma,pcmu,opus&... but it doesn't help.  Is it possible to send video with sound from cameras to Telegram and how to do it?  Thank you very much!

example I was referring to:
service: telegram_bot.send_video
data:
  url: http://localhost:1984/api/stream.mp4?src=camera1&duration=5

**Comment by TokarevSergey** [comment]
Вот вот и я об этом писал.
Here is what I wrote about it.

**Comment by calisro** [comment]
Looks like telegram needs mp4 and that the URL is correct you're using.  But does the source contain that codec?  If not, you'd need to transcode it.

**Comment by TokarevSergey** [comment]
> Похоже, телеграмме нужен mp4 и что URL-адрес правильный, который вы используете. Но содержит ли источник этот кодек? Если нет, вам нужно будет перекодировать его в источнике вашего stream.mp4 (camera1).
> 
> https://github.com/AlexxIT/go2rtc#source-ffmpeg
> 
> Я думаю что-то вроде этого, но совершенно ничего не проверял.
> 
> ```
>   camera_main:
>     - rtsp://127.0.0.1:8554/camera1
>     - ffmpeg:rtsp://127.0.0.1:8554/camera1?audio#audio=aac
> ```
> 
> ```
> service: telegram_bot.send_video
> data:
> url: http://localhost:1984/api/stream.mp4?src=camera_main&duration=5
> ```
> 
> Так как это будет использовать hls, это будет медленно. :)

In the next thread, I wrote that telegram video came with sound at the link http://localhost:1984/api/stream.mp4?src=camera1& video=h264&audio=pcmu&duration=5 in version 1.2.0.
 But it doesn't work in version 1.3.1, you can get either video - http://localhost:1984/api/stream.mp4?src=camera1&duration=5 , or audio - http://localhost:1984/api/stream.mp4  ?src=camera1&audio=pcmu&duration=5.
 It seems that they will fix it in the new version.

**Comment by sashakozlov86** [comment]
Good afternoon  That is, you have to wait for the g2rtc update, should they fix it there?

**Comment by TokarevSergey** [comment]
> Добрый день То есть надо ждать обновления g2rtc, там должны исправить?

As far as I understand, yes. I'm really looking forward to getting this fixed.

**Comment by sashakozlov86** [comment]
Хорошо, спасибо большое!

**Comment by AlexxIT** [comment]
Please open camera1 stream in WebUI and show stream info. I need to know codecs inside.

**Comment by TokarevSergey** [comment]
Yes, the codecs inside are normal.  Everything is as it was before.  It's just that now when I put the API command to get video and audio together in the video link, it doesn't come.  It can come once out of 100 triggers, or the first one comes, but the astral ones do not.  And this is exactly if you send an api request for video and audio together separately, they work.

{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://10.0.0.11:554/ISAPI/Streaming/Channels/101/",
      "remote_addr": "10.0.0.11:554",
      "user_agent": "go2rtc/1.3.1",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=1617609, senders=1"
      ],
      "recv": 1632700
    },
    {
      "url": "isapi://admin:1234567@10.0.0.11:80/"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 10.0.0.192:46107",
      "user_agent": "Mozilla/5.0 (Linux; Android 11; SM-A305FN Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 11; SM-A305FN)",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, AV1, H264, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000"
      ],
      "senders": [
        "96 H264, bytes=1617609, receivers=1"
      ],
      "send": 1635227
    }
  ]
}

**Comment by TokarevSergey** [comment]
> Пожалуйста, укажите информацию о потоке в WebUI. Мне нужно знать кодеки внутри.

Did I do everything right?

**Comment by AlexxIT** [comment]
@TokarevSergey yes. I'll check if Telegram can handle PCMU audio. Not sure about it.

**Comment by TokarevSergey** [comment]
> @TokarevSergeyда. Я проверю, может ли Telegram обрабатывать звук PCMU. Не уверен в этом.

В Телеграмме звук PCMU работает. Я же вам уже писал, что все работало на версии 1.2.0 мне в телеграм приходило видео если я посылал api в таком виде: "http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264&audio=pcmu&duration=15"
А сейчас в версии 1.3.1 я могу отправить в телеграм толькл либо видео по api: "http://10.0.0.100:1984/api/stream.mp4?src=DoorCamVStreet&video=h264&duration=15"

**Comment by AlexxIT** [comment]
I have checked. PCMU/PCMA works in Telegram but not on all platforms!
I can't hear sound on macOS and iPhone. But can hear sound on Android.

Also there is some bug in the 1.3.1 and mp4 stream with audio may crash. So if you can't get any video - this is bug and will be fixed.
If you get video without audio - this is your device problem.

Important to use link with this params: `video=h264,h265&audio=aac,opus,mp3,pcma,pcmu`
Because by default mp4 format will use only AAC audio. Because every player can play it (also Apples).

If you  have PCMU/PCMA audio and want to hear it on Apple devices (maybe some others, I don't know) - you need to use transcoding to AAC.

**Comment by TokarevSergey** [comment]
> Я проверил. PCMU/PCMA работает в Telegram, но не на всех платформах! Я не слышу звук на macOS и iPhone. Но слышно звук на Android.
> 
> Также в 1.3.1 есть некоторая ошибка - поток mp4 со звуком может вылетать. Так что, если вы не можете получить какое-либо видео - это ошибка, и она будет исправлена. Если вы получаете видео без звука - это проблема вашего устройства.
> 
> Важно использовать ссылку с этими параметрами: `video=h264,h265&audio=aac,opus,mp3,pcma,pcmu` потому что по умолчанию формат mp4 будет использовать только аудио AAC. Потому что в нее может играть каждый игрок (яблоки тоже).
> 
> Если у вас есть звук PCMU/PCMA и вы хотите слушать его на устройствах Apple (может быть, на каких-то других, я не знаю) — вам нужно использовать транскодирование в AAC.

Thanks for the help. As far as I understand, the sound will be fixed in the next version. I have an android.

**Comment by TokarevSergey** [comment]
> Я проверил. PCMU/PCMA работает в Telegram, но не на всех платформах! Я не слышу звук на macOS и iPhone. Но слышно звук на Android.
> 
> Также в 1.3.1 есть некоторая ошибка - поток mp4 со звуком может вылетать. Так что, если вы не можете получить какое-либо видео - это ошибка, и она будет исправлена. Если вы получаете видео без звука - это проблема вашего устройства.
> 
> Важно использовать ссылку с этими параметрами: `video=h264,h265&audio=aac,opus,mp3,pcma,pcmu` потому что по умолчанию формат mp4 будет использовать только аудио AAC. Потому что в нее может играть каждый игрок (яблоки тоже).
> 
> Если у вас есть звук PCMU/PCMA и вы хотите слушать его на устройствах Apple (может быть, на каких-то других, я не знаю) — вам нужно использовать транскодирование в AAC.

Thank you videos now come in telegram with sound.  But there is a nuance now some videos with a white static image and all the videos stopped autoplaying.

![Screenshot_20230417-221449_Telegram](https://user-images.githubusercontent.com/98225056/232589716-ec54eaa2-a9c3-4e0d-be4a-91e25c3415c3.jpg)

**Comment by AlexxIT** [comment]
@TokarevSergey maybe problem depends on camera model and video codec

**Comment by TokarevSergey** [comment]
> @TokarevSergeyвозможно проблема зависит от модели камеры и видеокодека

Thanks a lot.  Everything is in order, everything worked.  As I understand it, Telegram is trying to adapt itself.  Sorry I didn't understand right away.

**Comment by sashakozlov86** [comment]
Good afternoon  Unfortunately, I have Dahua VTO2202FP and VTO2211G-WP call panels when sending video to Telegram using the format link: http://localhost:1984/api/stream.mp4?src=vhodnaya_dver_hq&video=h264,h265&audio=aac,opus,mp3,  pcma,pcmu&duration=25 no sound.  That is, the method offered by you unfortunately does not work in this case.  The Telegram client is installed on an Android phone.  Thank you!

**Comment by AlexxIT** [comment]
I did not say that PCMA/PCMU will work on all Androids. It works on my individual Android.
PCMA/PCMU inside MP4 is not a standard. No wonder it doesn't work somewhere.

**Comment by sashakozlov86** [comment]
![Screenshot_2023-04-18-12-01-27-54_4aed3257f278fcf7bfa3abd644e23333](https://user-images.githubusercontent.com/93244850/232728167-5ff9f3ef-f60f-44da-8fc4-894d9e00154d.jpg)

Thank you!  As I understand it, the PCM codec, which is just the same obstacle.  Is it possible to somehow re-encode to the required format when receiving a video from this link?  Maybe add some argument to the link?  Thank you!

**Comment by sashakozlov86** [comment]
![Screenshot_2023-04-18-12-06-08-39_c2be9d5517208fee91e0861c39fd2f31](https://user-images.githubusercontent.com/93244850/232729525-ff70a060-06d7-4954-ba96-ca1c3c964bba.jpg)

**Comment by TokarevSergey** [comment]
> Спасибо! Я так понимаю, кодек PCM, что как раз и является препятствием. Можно ли как-то перекодировать в нужный формат при получении видео по этой ссылке? Может быть, добавить какой-нибудь аргумент в ссылку? Спасибо!


Try updating the firmware and playing around with the call settings in the web interface.

**Comment by TokarevSergey** [comment]
> ![Screenshot_2023-04-18-12-06-08-39_c2be9d5517208fee91e0861c39fd2f31](https://user-images.githubusercontent.com/93244850/232729525-ff70a060-06d7-4954-ba96-ca1c3c964bba.jpg)

No no, look at what codec you have here.
![image](https://user-images.githubusercontent.com/98225056/232731028-08ca7b69-ea60-4e96-a045-aaeea76328ed.png)

**Comment by sashakozlov86** [comment]
![Screenshot_2023-04-18-12-44-36-39_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/93244850/232738971-f7650407-2c92-4194-b68b-51d1ed19df2f.jpg)

**Comment by sashakozlov86** [comment]
![Screenshot_2023-04-18-12-47-26-29_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/93244850/232739694-975b7e6c-7490-4179-b3f5-912ff8458004.jpg)


Как-то так, друг.

**Comment by sashakozlov86** [comment]
I tried to do this: ffmpeg:http://localhost:1984/api/stream.mp4?src=vhodnaya_dver_hq&duration=25#video=copy#audio=opus but the video does not come to Telegram at all

**Comment by TokarevSergey** [comment]
> Пробовал делать так: ffmpeg: http://localhost:1984/api/stream.mp4?src=vhodnaya_dver_hq&duration=25#video=copy#audio=opus но видео вообще не приходит в Telegram

Check the settings, I have such a codec on Hikvision
![image](https://user-images.githubusercontent.com/98225056/232747223-5e109a6c-ff72-4e2d-8461-ced4f92ed96a.png)

**Comment by sashakozlov86** [comment]
Unfortunately, as I understand it, in the Dahua call panel settings web interface there is no way to select or change the codec, and as I understand from the screenshots attached above, their audio codec is PCM

**Comment by sashakozlov86** [comment]
Решил проблему следующим способом. Может кому пригодится.

В Homeassistant заходим по SMB и в папке: /config/scripts создаём файл *.sh (например: get_vto_stream.sh), далее в нем прописываем и сохраняем:

#!/bin/bash

set -eu

readonly creds='LOGIN: PASSWORD'
readonly host='IP_ADRESS:PORT'

curl --silent --digest --user "${creds}" --globoff \
    "http://${host}/cgi-bin/configManager.cgi?action=setConfig&Encode[0].MainFormat[0].Audio.Compression=AACEncode[0].MainFormat[0].Audio.Frequency=32000" >&2 &

echo "rtsp://${creds}@${host}/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif"
В настройке go2rtc прописываем:

streams:
  vto:
    - echo: /config/scripts/get_vto_stream.sh
 
Таким образом при запуске потока в go2rtc запускается скрипт дающий команду вызывной панели Dahua VTO обрабатывать аудиопоток в кодексе AAC 32 кб/сек.

Необходимо сохранить и перезагрузить go2rtc.

После этого при вызове службы Telegram: Send video по команде http://localhost:1984/api/stream.mp4?src=vto&video=h264,h265&audio=aac,opus,mp3,pcma,pcmu&duration=25 у меня в Телеграмме появляется видео со звуком. Надеюсь кому-то поможет.

Спасибо AlexxIT за разработку замечательного плагина и https://github.com/felipecrs за наводку по скрипту. Всем удачи, друзья!

**Comment by AlexxIT** [comment]
@sashakozlov86 your codec L16 = PCM. At the moment it is not supported at all in MP4

**Comment by sashakozlov86** [comment]
> @sashakozlov86 your codec L16 = PCM. At the moment it is not supported at all in MP4


Спасибо! Я уже написал приемлемое для меня решение выше. Как вариант можно ещё прописать: - ffmpeg:название_камеры#audio=OPUS.

Спасибо!
