### ISSUE TITLE
WebRTC sterams from RTSP source don't work at all with v1.3.1

### ISSUE THREAD

**Issue by tsightler** [AlexxIT/go2rtc#319]
Hi @AlexxIT,

The ring-mqtt project currently uses go2rtc v1.2.0 as an RTSP proxy and the recommended setup for Home Assistant is to use the go2rtc addon with RTSPtoWebRTC integration.  With go2rtc addon v1.2.0 this worked perfectly.

However, as soon as I upgrade to v1.3.1, I can no longer view the streams at all, either in HA, or directly via the go2rtc web UI.  Weirdly, when I try to view the stream in the go2rtc web UI, it shows MSE instead of RTC.  Looking at the logs between working 1.2.0 and not working 1.3.1, I can't really see much difference, other than no logs from the stream component, but perhaps you didn't include those in the stream engine rewrite?

The only other obvious difference is in the candidate list in the WebRTC answer.  For 1.2.0 I get:

a=candidate:3440736625 1 udp 2130706431 192.168.60.51 8555 typ host
a=candidate:3440736625 2 udp 2130706431 192.168.60.51 8555 typ host
a=candidate:625380155 1 udp 1694498815 74.126.133.11 37933 typ srflx raddr 0.0.0.0 rport 37933
a=candidate:625380155 2 udp 1694498815 74.126.133.11 37933 typ srflx raddr 0.0.0.0 rport 37933
a=candidate:1894123665 1 tcp 2124414975 192.168.60.51 8555 typ host tcptype passive
a=candidate:1894123665 2 tcp 2124414975 192.168.60.51 8555 typ host tcptype passive

With with 1.3.1 there is:

a=candidate:3440736625 1 udp 2130706431 192.168.60.51 43050 typ host
a=candidate:3440736625 2 udp 2130706431 192.168.60.51 43050 typ host
a=candidate:625380155 1 udp 1694498815 74.126.133.11 52425 typ srflx raddr 0.0.0.0 rport 52425
a=candidate:625380155 2 udp 1694498815 74.126.133.11 52425 typ srflx raddr 0.0.0.0 rport 52425
a=candidate:1894123665 1 tcp 2124414975 192.168.60.51 8555 typ host tcptype passive
a=candidate:1894123665 2 tcp 2124414975 192.168.60.51 8555 typ host tcptype passive

As you can see, the internal UDP candadates appear to be using dynamic port with 1.3.1 instead of using the same 8555 port as tcp.  I don't know any reason why this would not work in my environment, but it's the only other difference I see.

I'm really at a loss, it seems straightforward, but also seems 100% reproducible.  If I revert to 1.2.0 it always works perfectly.  Any help or guidance for additional troubleshooting would be greatly appreciated.  I will try upgrading the go2rtc component in ring-mqtt to 1.3.1 as well, but it's just RTSP, so I would think that would not be the issue, the problem seems like it's on the WebRTC side.

I've attached logs if you are interested in looking at them.
[go2rtc_120.log](https://github.com/AlexxIT/go2rtc/files/11128282/go2rtc_120.log)
[go2rtc_131.log](https://github.com/AlexxIT/go2rtc/files/11128283/go2rtc_131.log)

**Comment by rchiileea** [comment]
same for me alll that shows up is this now

![image](https://user-images.githubusercontent.com/87599807/229524240-404d5757-0c8e-4c5d-9592-23f1db578989.png)

**Comment by broyuken** [comment]
Restoring a 1.2 snapshot didn't help me with my ring-mqtt streaming either.

**Comment by tsightler** [comment]
> Restoring a 1.2 snapshot didn't help me with my ring-mqtt streaming either.

Can you please verify that you tested this on a day other than April 5th as Ring live streaming has been down pretty much all day.  Previously I've seen zero cases where reverting to 1.2 didn't resolve the issue.

Also, with v5.2.1 of ring-mqtt I upgraded the source RTSP server to go2rtc 1.3.1 as well, and now, with that version, I get video but no audio, which is confusing because it does show an audio stream is active, but there's just silence.  I need to somehow find time to dig into it deeper, but time is not something I have much of for the next few weeks.

**Comment by broyuken** [comment]
> Restoring a 1.2 snapshot didn't help me with my ring-mqtt streaming either.

Restoring to 1.2 worked just fine, ring was having some issues yesterday, we're all good today.

**Comment by kylepyke** [comment]
Same issue here. Mine seem to work on the very first instantiation, but then never again. I have to restore from a HA backup in order to get the functionality back, and then it again works only once.

**Comment by tsightler** [comment]
I've tried everything I can think of to make this work.  I upgraded to go2rtc in ring-mqtt to use v1.3.1 for the RTSP server and this seems to make video work, but audio never works via WebRTC no matter what I've tried, other than downgrading the go2rtc addon to 1.2.0, which will then make it work.

I've also tried other RTSP clients and all of them work from the very same RTSP source, so I believe that this has to be something to do with the WebRTC side in go2rtc 1.3.x, but I haven't been able to figure it out.

**Comment by tsightler** [comment]
Seems like this is basically the same issue as reported in https://github.com/AlexxIT/go2rtc/issues/309.

**Comment by kylepyke** [comment]
Have you tried the other webRTC project RTSPtoWeb? I'm having the same issue there as well... Makes me think this might be a HA backend bug.

**Comment by tsightler** [comment]
I don't believe it is an HA bug because it fails directly in the go2rtc web UI, which is completely independent of anything to do with HA itself.

Also, RTSPtoWeb has very limited support for audio codecs in general, I think it may only support PCM audio codec (aLaw/uLaw).

**Comment by AlexxIT** [comment]
@tsightler random port for UDP candidates is the expected behavior.

I have found that UDPMux does not work well under heavy loads. This is not noticeable when go2rtc is sending streams away. But it is very noticeable when go2rtc receives streams.

So I have enabled only TCPMux by default:
https://github.com/AlexxIT/go2rtc/blob/c44aaebd65a6c0f12866970976b7d00df37afacf/cmd/webrtc/init.go#L24

But if you want - you can enable both TCP and UDP Mux for WebRTC via yaml config.
I still don't know which option is better. I'm experimenting.

**Comment by tsightler** [comment]
@AlexxIT Thanks for the feedback, makes sense.  However, that doesn't seem to be related to the issue I'm seeing with v1.3+.  I can get video to work, but audio never works.  It seems like the client knows there is supposed to be an audio stream as I get volume controls while, for streams with no audio the volume controls are greyed out.

I'm not sure if this is only impacts certain types of Opus audio streams or what (my streams have both Opus and AAC), but I think I saw some other reports with a similar issue with Opus streams, so maybe that's the common issue.

Open to any suggestions or can provide any logs.

**Comment by AlexxIT** [comment]
@tsightler thanks for your logs. Very helpful. I can see a problem. SDP without `control` is processed not properly. All my cameras have it. That's why I didn't see such a bug.

**Comment by tsightler** [comment]
Looks like this is fixed with go2rtc 1.3.2, at least, it seems to be working for me now.  Thanks!

**Comment by broyuken** [comment]
Can confirm this works for me as well.

**Comment by tsightler** [comment]
Closing as this seems to be resolved with 1.3.2.
