### ISSUE TITLE
Возможна ли поддержка rtsp-samsung-tv / Is it possible to support rtsp-samsung-tv

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#324]
Скажите пожалуйста, возможно ли добавить поддержку этого сервера в вашей интеграции.
Чтобы можно было смотреть видео на телевизорах Tizen.
Спасибо.
https://github.com/vzakharchenko/rtsp-samsung-tv

Please tell me if it is possible to add support for this server in your integration.
 To be able to watch videos on Tizen TVs.
 Thank you.
 https://github.com/vzakharchenko/rtsp-samsung-tv

**Comment by AlexxIT** [comment]
No. Don't plan to support anything similar.

**Comment by AlexxIT** [comment]
There is an opportunity. YandexStation integration support streaming music to Tizen TV. But I don't want to spent time for research that problem.
