### ISSUE TITLE
ffmpeg output address

### ISSUE THREAD

**Issue by JasonPulse** [AlexxIT/go2rtc#328]
Is there a way to change the output path of the ffmpeg {output} tag right now its rtsp://localhost:8554.  On my install localhost actually does not point to the container that go2rtc is running in

**Comment by skrashevich** [comment]
you can redefine input preset:
```
ffmpeg:
  myinput: "-fflags nobuffer -flags low_delay -timeout 5000000 -I rtsp://IP_AND_PORT_OF_CONTAINER_THAT_GO2RTC_IS_RUNNING_IN"
```

**Comment by JasonPulse** [comment]
That does not seem to affect the output

splitting the argument list: Option not found
12:20:22.207 DBG [exec] run url="exec:ffmpeg -hide_banner -v error -allowed_media_types video+audio -fflags nobuffer -flags low_delay -timeout 500000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -I rtsp://<go2rtc address>:8554 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/eee60ae7051b69a04edb9f5e72c0a3ac"

The local host at the output is the problem

**Comment by skrashevich** [comment]
you can re-define output the same way, but it's a dirty hack:

```
ffmpeg:
  output: "-user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://remote-host/stop-gap-solution-handler"
```

"output" in this code is internal magic name, don't change it

**Comment by JasonPulse** [comment]
Gotcha thanks I was just worried about the GUID at the end of the output and if that would get copied or appended to the end of anything like this.  

Thanks for the help.
