### ISSUE TITLE
MJPEG VAAPI transcoding not working

### ISSUE THREAD

**Issue by rbray89** [AlexxIT/go2rtc#329]
Just making a note here that HW VAAPI MJPEG transcoding from an H.264 RTSP stream isn't working. The RTP logging reports that the Color format is not supported.

I'm trying to find the solution independently so I can report the fix, but so far I've been unable to get the mjpeg_vaapi encoder working with my RTSP streams in any capacity.

**Comment by NickM-27** [comment]
This is expected

<img width="829" alt="Screenshot 2023-04-03 at 8 36 40 PM" src="https://user-images.githubusercontent.com/14866235/229672342-5bfc5b4b-3d65-4645-a435-71f4f06db434.png">

**Comment by AlexxIT** [comment]
You totally right. RTSP can't handle MJPEG after hardware acceleration. I have plan to change from RTSP to HTTP for MJPEG from FFmpeg. But don't have time yet.

**Comment by AlexxIT** [comment]
This was fixed https://github.com/AlexxIT/go2rtc/releases/tag/v1.5.0
