### ISSUE TITLE
Windows Defender Warning for `go2rtc_win64.zip`: `Trojan:Script/Wacatac.B!ml`

### ISSUE THREAD

**Issue by strarsis** [AlexxIT/go2rtc#33]
Windows Defender warns against a malicious program when downloading [`go2rtc_win64.zip`](https://github.com/AlexxIT/go2rtc/releases/download/v0.1-alpha.11/go2rtc_win64.zip): `Trojan:Script/Wacatac.B!ml`.

This is probably a false-positive. But can this be modified so now warnings occur at all?

**Comment by AlexxIT** [comment]
Unfortunately, this is "normal" situation for go applications...

- https://go.dev/doc/faq#virus
- https://groups.google.com/g/golang-nuts/c/lPwiWYaApSU
- https://www.virustotal.com/gui/file/82cf4b29a82ad989d385a5c84c233bd29e806ca0c851e5006a6e7af64f9cbd42?nocache=1
