### ISSUE TITLE
roborock no streams

### ISSUE THREAD

**Issue by ckdo8008** [AlexxIT/go2rtc#334]
https://github.com/AlexxIT/go2rtc/tree/master/pkg/roborock/api.go
```
func GetBaseURL(username string) (string, error) 

"https://cniot.roborock.com", 
"https://usiot.roborock.com", 
"https://euiot.roborock.com,"
"https://ruiot.roborock.com"
```
You must be able to select one of cniot, usiot, and euiot.

**Comment by AlexxIT** [comment]
Do you have an account that can't find this API? I thought it worked for all regions.
`https://euiot.roborock.com/api/v1/getUrlByEmail?email=xxx`

**Comment by ckdo8008** [comment]
sorry.
I was misunderstanding how to get the url.
