### ISSUE TITLE
webrtc.html enables audio when no audio codec is present

### ISSUE THREAD

**Issue by calisro** [AlexxIT/go2rtc#335]
I was using the go2rtc GUI to send to my shield and other devices when doorbells were pressed.   I purposefully strip the audio from the source like this because if audio is enabled when sent to android_tv, it will pause the currently running program.  So for months, i've stripped it and I can send the audio-less video in pipup without disturbing the  currently running movie:

```
  garage_noaudio: #Used directly by automation link
    - rtsp://127.0.0.1:8554/garage_main?video
```

I then reference this URL in pipup and send to shield tv:

```
http://xxxxxxxx:1984/webrtc.html?src=garage_noaudio
```

The audio is absent from the codec but the player now in latest releases enables audio anyway which is shouldn't.  The audio should be disabled on the player if no audio is present in the source.  

This may be niche but is there any way to make this smarter to disable the player audio if no audio is in the source like it did up until now??  I'd rather not resort to having to maintain a different version of the webrtc.html code if possible for this to all work.

**Comment by aurelmarius** [comment]
I have the same problem described here. I'm trying to strip audio from rtsp but it seems by adding ?video=copy but testing in vlc reports that audio codec is still there. I know ffmpeg have an -an option for this but i can't get it working.

**Comment by calisro** [comment]
What you're reporting is a different issue. My rtsp stream doesn't have audio when it is stripped.  It's simply that the go2rtc UI enables the sound in the player which it didn't do in previous releases. I'd suggest you open a different issue with logs.

**Comment by aurelmarius** [comment]
@calisro Yes, i made a mistake in config. Now i have your problem. On latest release embedded player enables audio stream even if it doesn't exist. I downgraded to 1.2.0 and everything is ok now, pipup on nvidia shield is working without problems.

**Comment by AlexxIT** [comment]
Looks like this already fixed in the latest version: `/webrtc.html?src=rtsp-dahua1&media=video`
