### ISSUE TITLE
Audio and Video in Different Channel

### ISSUE THREAD

**Issue by radoprajitno** [AlexxIT/go2rtc#341]
Hi All.

Im Using Yi-Hack M-Star and Allstar-V2
Anyhow, it comes with separated audio and video channels.

So it looks something like this:
Video Output >> rtsp://192.168.1.27/ch0_1.h264
Audio Output >> rtsp://192.168.1.27/ch0_2.h264

I would like to know how,
is there any posibilities to combine the 2 separated Audio and Video channel to works in go2rtc as a single stream?

thanks

**Comment by AlexxIT** [comment]
Just setup stream with two sources
https://github.com/AlexxIT/go2rtc#source-rtsp
https://github.com/AlexxIT/go2rtc#codecs-negotiation
