### ISSUE TITLE
How to avoid "[streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"?

### ISSUE THREAD

**Issue by kylepyke** [AlexxIT/go2rtc#344]
I can't seem to get around this error. I understand from other threads that this is a "normal" error, but is there anything I can do to avoid this?

This is all I have in my config:

```
streams:
    basement: 
        - rtsp://USER:PASS@192.168.1.240:554/cam/realmonitor?channel=1&subtype=0
        - ffmpeg:basement#audio=opus
```

The stream loads fine in VLC, but doesn't load in the Frigate lovelace card, or in the go2rtc webUI.

**Comment by AlexxIT** [comment]
#311
