### ISSUE TITLE
watermark not possible ? 

### ISSUE THREAD

**Issue by perfectwebtech** [AlexxIT/go2rtc#345]
watermark not possible ?

**Comment by calisro** [comment]
Such a vague issue. Lol. 3 words?  If you want to watermark your stream, I believe you can do that with ffmpeg parameters.  Go2rtc doesn't care.

**Comment by AlexxIT** [comment]
Similar to #201
Whole ffmpeg in your hands. You can do with it whatever you want. Just need to check ffmpeg docs.
