### ISSUE TITLE
Streams not loading since 1.3+

### ISSUE THREAD

**Issue by marcelmah** [AlexxIT/go2rtc#349]
Hi, 

I notice that since version 1.3(.1) that my 4 rtsp cams stop streaming. It's not all 4 at the same time. Only solution is to reboot the HA addon. Sometimes one reboot does not get all 4 back and I reboot the addon again.

Did not have this issue on 1.2, if I downgrade to 1.2 the issue is gone.

It happens multiple times a day.

Anyone else experience the same?
How can I debug to provide more information?

**Comment by marcelmah** [comment]
So this morning I woke up to this:
![woke_up](https://user-images.githubusercontent.com/19894281/231667150-594383da-ac19-4da6-9637-ca4f5a7079c3.png)

Rebooted the addon, got this after the first and second reboot:
![reboot_1_and_2](https://user-images.githubusercontent.com/19894281/231667143-081325ee-d5d3-4a4b-b0ec-486627aa1b56.png)

Third reboot:
![reboot_3](https://user-images.githubusercontent.com/19894281/231667148-ae0670f8-4c3b-4863-b732-7e823632374d.png)

Working after 4 reboots:
![reboot_4_all_working](https://user-images.githubusercontent.com/19894281/231667149-7b7ad26c-59c3-40d4-a1eb-0ae4ebd566c7.png)

**Comment by AlexxIT** [comment]
You need to check go2rtc logs. Maybe some errors there.
You need to provide more info about setup. How you config them.

**Comment by marcelmah** [comment]
Hi @AlexxIT 

is this enough? or do I need to set a specific module in another logging mode?
I changed the names, usernames, passwords and IP's.

camera1 is a Tuya based doorbell 'hacked'  to allow RTSP.
camera2,3 and 4 are Foscam X4
I use the substreams (h264) for my Samsung Tablets on every floor as dashboards, they don't work with h265 (in Fully Kios Browser).

The config is:
api:
  listen: ":1984"
  base_path: ""
  static_dir: ""
  origin: ""

ffmpeg:
  bin: ffmpeg
  global: "-hide_banner"
  file: "-re -stream_loop -1 -i {input}"
  http: "-fflags nobuffer -flags low_delay -i {input}"
  rtsp: "-fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i {input}"
  output: "-user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
  # ... different presets for codecs

hass:
  config: ""

log:
  format: ""
  level: info

rtsp:
  listen: ":8554"
  username: "username"
  password: "password"

srtp:
  listen: ":8443"

streams:
  camera1: rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
  camera2: rtsp://username:password@192.168.1.141:88/videoSub
  camera2_h265: rtsp://username:password@192.168.1.141:88/videoMain
  camera3: rtsp://username:password@192.168.1.140:88/videoSub
  camera3_h265: rtsp://username:password@192.168.1.140:88/videoMain
  camera4: rtsp://username:password@192.168.1.142:88/videoSub
  camera4_h265: rtsp://username:password@192.168.1.142:88/videoMain

webrtc:
  listen: ":8555"
  candidates: []

07:45:12.496 INF go2rtc version 1.3.1 linux/amd64
07:45:12.496 INF [api] listen addr=:1984
07:45:12.496 INF [rtsp] listen addr=:8554
07:45:12.498 INF [srtp] listen addr=:8443
07:45:12.501 INF [webrtc] listen addr=:8555
07:45:17.413 INF [streams] create new stream url=rtsp://username:password@192.168.1.56:8554/camera1cam?video=all&audio=all
07:45:19.007 INF [streams] create new stream url=rtsp://username:password@192.168.1.56:8554/camera2?video=all&audio=all
07:45:19.320 INF [streams] create new stream url=rtsp://username:password@192.168.1.56:8554/camera3cam?video=all&audio=all
07:45:20.067 INF [streams] create new stream url=rtsp://username:password@192.168.1.56:8554/camera4cam?video=all&audio=all
07:52:32.668 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:34182->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
09:06:47.606 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:44598->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
09:32:22.572 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:37386->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
09:55:47.315 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
09:55:47.448 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
10:00:09.986 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="size 60665 < 74800: RTP header size insufficient for extension" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
10:18:32.550 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:46610->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
10:35:24.354 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
10:35:24.533 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
11:03:00.957 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
11:03:00.993 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
11:30:00.885 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
11:30:00.901 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
11:57:01.766 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
11:57:01.876 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
12:13:05.833 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
12:13:05.849 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
12:40:29.273 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
12:40:29.333 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
12:53:34.871 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
12:53:34.922 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
13:07:00.862 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
13:07:00.864 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
13:07:47.424 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:37372->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
13:38:37.354 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:50054->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
13:43:00.531 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
13:43:00.566 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:13:09.660 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:13:09.697 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:34:56.691 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:34:57.234 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:35:02.300 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:54558->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
14:46:51.105 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:46:51.130 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:57:43.020 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
14:57:43.130 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
15:13:17.826 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
15:13:18.053 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
15:42:52.347 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
15:42:52.380 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
15:57:02.218 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:50748->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
16:11:29.041 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
16:11:29.175 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
16:34:08.314 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
16:34:08.329 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
16:41:10.458 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
16:41:10.637 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
17:03:26.827 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
17:03:27.179 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
17:08:52.156 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 192.168.1.56:52040->192.168.1.60:8554: read: connection reset by peer" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
17:16:32.897 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
17:16:32.975 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
17:21:16.849 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="RTP header size insufficient: 3 < 4" url=rtsp://username:password@192.168.1.60:8554/Streaming/Channels/101
18:05:48.748 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
18:51:20.110 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
19:05:59.339 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
20:06:00.314 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"
20:56:41.142 INF [streams] can't get track error="RTSP GetTrack from wrong state: HANDLE"

**Comment by AlexxIT** [comment]
Well. "RTSP GetTrack from wrong state: HANDLE" is another known bug #311
