### ISSUE TITLE
Help Figuring out how to set it up

### ISSUE THREAD

**Issue by DavidePieri** [AlexxIT/go2rtc#353]
Hi! Im new into these softwares and honestly i have close to no idea how to make this work properly.
Ill start with a general description of what i need to do and what ive done so far!
I have a Tapo Camera (C110) and i would like to display the camera in fluidd while printing, as a usb plugged webcam basically. I have installed go2rtc and started the setup of `/etc/go2rtc.yaml` with:
```
streams:
 cam:
  - rtsp://user:password@192.168.0.75:554/stream1
```
and `/etc/systemd/system/go2rtc.service` with:
```
[Unit]
Description=go2rtc
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/go2rtc_linux_arm -config /etc/go2rtc.yaml
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=go2rtc
User=root
Group=root
Environment=PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin


[Install]
WantedBy=multi-user.target
```
then enabled and started the .yaml. i should now be able to check everything from here `http://rockpi.local:1984/` but it doesn't work at all, meaning that the browser gets back with the error _can't reach the page_ from chrome.
Hope you can help me out cause i've been working on this for a lot, trying different githubs that didn't work too. Thanks!!

**Comment by AlexxIT** [comment]
First try to run binary from console.

**Comment by DavidePieri** [comment]
Hi Alex! Nice to hear you and thanks for your reply! As i said i have a really limited knowledge on this so I don’t want to miss understand what you mean with that, could you be a bit more precise? Thanks!!

**Comment by AlexxIT** [comment]
I cannot teach you how to run programs on linux. There are special forums for that. You'd better ask there.
