### ISSUE TITLE
How to play 4 simultaneous streams ?

### ISSUE THREAD

**Issue by StephanGR** [AlexxIT/go2rtc#354]
Hello everyone !

Thanks for this awesome project !!

I've added 4 rtsp sources but I want to stream all of them into one single stream

How can I do that ?

Thanks a lot

**Comment by AlexxIT** [comment]
Just use ffmpeg https://github.com/AlexxIT/WebRTC/issues/73#issuecomment-1221529663

**Comment by gans200** [comment]
streams:
    mosaic: exec:ffmpeg -i rtsp://admin:pass@192.168.252.223/axis-media/media.amp -i rtsp://root:pass@192.168.252.221/axis-media/media.amp -vcodec libx264 -tune zerolatency -filter_complex "[0:v]scale=640:-1[v0];[v0][1:v]hstack=inputs=2" -f rtsp {output}

**Comment by RyanEwen** [comment]
> ```yaml
> streams:
>     mosaic: exec:ffmpeg -i rtsp://admin:pass@192.168.252.223/axis-media/media.amp -i rtsp://root:pass@192.168.252.221/axis-media/media.amp -vcodec libx264 -tune zerolatency -filter_complex "[0:v]scale=640:-1[v0];[v0][1:v]hstack=inputs=2" -f rtsp {output}
> ```

Can you share some additional context on how this is used?

**Comment by mateuszdrab** [comment]
Just to add my 4 cents, I generated a 4x4 mosaic using the below:

```yaml
streams:
    mosaic_2x2: exec:ffmpeg -rtsp_transport tcp -fflags nobuffer -flags low_delay -i "rtsp://source1:8554/cam1?video" -rtsp_transport tcp -fflags nobuffer -flags low_delay -i "rtsp://source2:8554/cam2?video" -rtsp_transport tcp -fflags nobuffer -flags low_delay -i "rtsp://source3:8554/cam3?video" -rtsp_transport tcp -fflags nobuffer -flags low_delay -i "rtsp://source4:8554/cam4?video" -filter_complex "[0:v]scale=640:360[v0];[1:v]scale=640:360[v1];[2:v]scale=640:360[v2];[3:v]scale=640:360[v3];[v0][v1][v2][v3]xstack=inputs=4:layout=0_0|640_0|0_360|640_360[out]" -map "[out]" -c:v libx264 -preset ultrafast -tune zerolatency -f rtsp {output}
```

My cameras output `896x512` on substream but this seems to scale well into 720p which I aim to cast using HA (using generic camera integration) to my Chromecast.
