### ISSUE TITLE
Fix HLS support after v1.3

### ISSUE THREAD

**Issue by pravardhanreddy** [AlexxIT/go2rtc#356]
I have an rtsp stream which I can view in VLC as well as gstreamer. When I try to view it on the web GUI it just shows a gray screen with some pixelation on the top left. I get the following logs

```
20:34:06.780 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
20:34:06.781 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023/04/15 20:34:46 http: panic serving 10.0.0.69:38556: interface conversion: interface {} is *mp4.Consumer, not *core.Listener
goroutine 21 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1850 +0xbf
panic({0xb52e20, 0xc000120960})
	runtime/panic.go:890 +0x262
github.com/AlexxIT/go2rtc/cmd/hls.handlerStream({0xd397d0, 0xc000198000}, 0xc000342000)
	github.com/AlexxIT/go2rtc/cmd/hls/hls.go:87 +0xb94
net/http.HandlerFunc.ServeHTTP(0xc00050daf0?, {0xd397d0?, 0xc000198000?}, 0x0?)
	net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0002260d5?, {0xd397d0, 0xc000198000}, 0xc000342000)
	net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xc0002c8870?}, {0xd397d0, 0xc000198000}, 0xc000342000)
	net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc00013f4a0, {0xd39ff0, 0xc0001ac5a0})
	net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	net/http/server.go:3102 +0x4db
```

I am basically trying to get my Logitech webcam to play properly in home assistant. I know this project supports USB webcams but the CPU usage was too high with it. I found this project https://github.com/mpromonet/v4l2rtspserver and installed it in docker and passed the device as 
```
---
version: "2.1"
services:
  server:
    image: mpromonet/v4l2rtspserver
    container_name: v4l2rtspserver
    devices:
      - /dev/video0
    ports:
      - '7001:8554'
    network_mode: bridge
    restart: unless-stopped
```
The CPU usage was less than 1%. I am guessing that it is taking the MJPEG stream from the camera directly and putting it on rtsp. I can view the stream with gstreamer with zero latency using the following command
```
gst-launch-1.0 rtspsrc location=rtsp://10.0.0.69:7001/ts latency=0 ! decodebin ! videoconvert ! autovideosink sync=false
```
Please help figuring out the issue. It would also be nice if one could add the USB camera directly with such low CPU usage (no ffmpeg transcoding/conversion)

**Comment by AlexxIT** [comment]
This is known panic for HLS ouput. It have been fixed in latest master version.
And you haven't show go2rtc config.
