### ISSUE TITLE
How to determine USB camera details (ffmpeg) for config/go2rtc.yaml

### ISSUE THREAD

**Issue by lindsaymarkward** [AlexxIT/go2rtc#358]
Thanks for this project, @AlexxIT :) 
I've spent some time trying to figure out how to stream my 2 USB cameras for Home Assistant using go2rtc, and I'd like to confirm some details.
My cameras are connected by USB to my Raspberry Pi 4B running Raspberry Pi OS 64-bit. 
Both cameras are Microsoft® LifeCam HD-3000.
I followed some details in #159 and finally got a working stream using this in the config/go2rtc.yaml: 
```
streams:
  lounge: ffmpeg:device?video=0&resolution=1280x720#video=h264#raw=-pix_fmt yuv420p
```
I tried lots of things before finding those specific settings, then I tried many variations. I don't need to set the resolution, but nothing else I change works.
The thing I don't understand is why I need `yuv420p` and how anyone would know this :)
Here's what I get in a console when I run `v4l2-ctl -d /dev/video0 --list-formats`:
```
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'YUYV' (YUYV 4:2:2)
	[1]: 'MJPG' (Motion-JPEG, compressed)
```

I also tried this with `--list-formats-all`, which reports the resolutions as well.

So, I would have thought I'd need `yuyv422` not `yuv420p` but that doesn't work.
I also can't get any kind of mjpeg/mjpg (instead of h264), but I'm honestly just guessing based on what seems to make sense.

So, is there a way to know what the settings should be based on what the camera reports when probed?

**Comment by AlexxIT** [comment]
Well. I don't have much experience with V4L2.

`pix_fmt yuv420p` is output format from ffmpeg and H264 codec
`YUYV 4:2:2` is input format to ffmpeg

Theoretically if you have "good" pixel format on the input, you don't need `pix_fmt` param on the output.
FFmpeg spend CPU time on converting pix fmt from one to another. Thats why I have removed it by default.

**Comment by lindsaymarkward** [comment]
Thanks for the reply. That's helpful to know a bit more about output and input. It would be super if there's anyone who knows more about how to configure cameras deterministically and could post here. I'd be happy to update docs if I understood more :)
I would expect there's some way to probe the camera (or system) and determine from the result what the config should be to make the camera work best.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Blog/issues/11
