### ISSUE TITLE
Green video after ffmpeg transcoding with scale

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/go2rtc#36]
Hey Alex,
Here's hoping you're doing good!

I've been using this since release and must say I am very pleased with the performance, except for that small kernel panic thing that you are working on.

I was thinking about an issue that I encounter, where my main PTZ camera can either send a very high resolution ( 2k) or a very low resolution (480p). The highest resolution seems too high to be properly streamed to my tablets, and the lower one is simply abhorrent quality-wise.

**Feature**: I was thinking, would it be wise to implement a quick argument to downscale videos?
For instance, reduce the height and width by a factor of X. This could use the hardware acceleration provided by FFmpeg.

Thanks for reading!

**Comment by maxi1134** [comment]
I tried using "ffmpeg:rtsp://admin:Jesus420@192.168.0.210/h264Preview_01_main#raw=-vf scale="480:-1""

And got this as a result in the "info" page, yet the pages MSE and WEBRTC do not load:

![image](https://user-images.githubusercontent.com/1342643/189497357-6f6be5f3-2d67-457c-9697-2089e0e87650.png)

**Comment by maxi1134** [comment]
For those wondering, I found a solution;

"    - ffmpeg:rtsp://admin:password@192.168.0.210/h264Preview_01_main#raw=-vf "scale=-1:720"#video=h264"

**Comment by calisro** [comment]
I was just about to paste that. :)

**Comment by maxi1134** [comment]
Although it works well on VLC. the stream bugs on Go2rtc interface and on Hass

Any idea why?

![image](https://user-images.githubusercontent.com/1342643/189498965-17e04e5c-bd47-4d8d-89a5-c635f1b324bc.png)

**Comment by AlexxIT** [comment]
I'll try to repeat the problem myself

**Comment by maxi1134** [comment]
Hey there!

The MSE Streams loads then instantly freeze and never recovers.

**Comment by maxi1134** [comment]
This seems to also happen with transpose=1

**Comment by AlexxIT** [comment]
Will be fixed in next `beta.6`

**Comment by AlexxIT** [comment]
Should be fixed. Reopen this issue in not
https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-beta.6
