### ISSUE TITLE
RTSP streams supplied to go2rtc return error=EOF, but work in VLC

### ISSUE THREAD

**Issue by teymur1988** [AlexxIT/go2rtc#360]
Hi there AlexxIT,

Thanks for your efforts in making something like this! I'm using go2rtc within frigate docker installation. I've got Amcrest 1041B cameras. I use scrypted for homekit secure video support, so scrypted is connected to the camera directly via camera's rtsp link. Then scrypted is rebroadcasting camera streams exactly as it is with no codec change. The scrypted stream requires no auth and it's basicly like this: `rtsp://scrypted.local:port/ajsdaljdsaljdsaljlkkja` this plays well in VLC but as soon as it's pasted into go2rtc, go2rtc won't start. Below are the log file and go2rtc config attached. If anything else is needed I'll be happy to provide. Thanks.
[go2rtc-logs.txt](https://github.com/AlexxIT/go2rtc/files/11252744/go2rtc-logs.txt)
Could you please help with this. 
[go2rtc-config.txt](https://github.com/AlexxIT/go2rtc/files/11252743/go2rtc-config.txt)

**Comment by AlexxIT** [comment]
As I know, you can override build in Frigate go2rtc version
