### ISSUE TITLE
WebRTC mode crackling sound

### ISSUE THREAD

**Issue by spawn451** [AlexxIT/go2rtc#361]
I use the Reolink Video Doorbell, when I use the WebRTC stream the sound crackles on the other hand in MSE mode no worries. 

Is this normal? My setup is as follows:

```
  reolink:
    - rtsp://admin:password@192.168.10.51:554/Preview_01_sub
    - ffmpeg:reolink#audio=opus
```

**Comment by AlexxIT** [comment]
Show stream info json from go2rtc WebUI when you have "crackling" sound.
Can you recognize speech in that crackling sound? Or it totally broken?

**Comment by spawn451** [comment]
Is this the json ?
{
  "producers": [
    {
      "url": "rtsp://admin:password@192.168.10.51:554/Preview_01_sub"
    },
    {
      "url": "ffmpeg:reolink#audio=opus"
    }
  ],
  "consumers": []
}

Yes, but it sounds metallic

**Comment by swbouman** [comment]
same issue here. audio is horrible, but I can hear the bird. On my YouTube stream, decoded with ffmpeg I putted a noise cancelling filter on top of the stream. Then the sound is gone. 

{
  "producers": [
    {
      "type": "RTSP source",
      "url": "rtsp://192.168.178.61/0",
      "remote_addr": "192.168.178.61:554",
      "user_agent": "go2rtc/1.2.0",
      "medias": [
        "video, sendonly, 96 H264/90000",
        "audio, sendonly, 104 MPEG4-GENERIC/48000"
      ],
      "tracks": [
        "96 H264/90000, sinks=3",
        "104 MPEG4-GENERIC/48000, sinks=3"
      ],
      "recv": 1211461163
    },
    {
      "type": "RTSP source",
      "url": "rtsp://localhost:8554/48cb56f59a21ada0aa5c6aa2e3e42cb1",
      "remote_addr": "127.0.0.1:46366",
      "user_agent": "ffmpeg/go2rtc",
      "medias": [
        "audio, sendonly, 96 OPUS/48000/2"
      ],
      "tracks": [
        "96 OPUS/48000/2, sinks=1"
      ],
      "recv": 1310219
    }
  ],
  "consumers": [
    {
      "type": "RTSP client",
      "url": "rtsp://127.0.0.1:8554/Vogelhuis?video=copy\u0026audio=aac",
      "remote_addr": "127.0.0.1:48332",
      "user_agent": "FFmpeg Frigate/0.12.0-da3e197",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 97 MPEG4-GENERIC/48000"
      ],
      "tracks": [
        "96 H264/90000, sinks=3",
        "97 MPEG4-GENERIC/48000, sinks=3"
      ],
      "send": 1211461163
    },
    {
      "type": "RTSP client",
      "url": "rtsp://192.168.178.7:8554/Vogelhuis",
      "remote_addr": "192.168.178.7:37602",
      "user_agent": "Lavf58.45.100",
      "medias": [
        "video, recvonly, 96 H264/90000",
        "audio, recvonly, 97 MPEG4-GENERIC/48000"
      ],
      "tracks": [
        "96 H264/90000, sinks=3",
        "97 MPEG4-GENERIC/48000, sinks=3"
      ],
      "send": 2642664022
    },
    {
      "type": "RTSP client",
      "url": "rtsp://localhost:8554/Vogelhuis?audio",
      "remote_addr": "127.0.0.1:46356",
      "user_agent": "go2rtc/ffmpeg",
      "medias": [
        "audio, recvonly, 96 MPEG4-GENERIC/48000"
      ],
      "tracks": [
        "96 MPEG4-GENERIC/48000, sinks=3"
      ],
      "send": 1252592
    },
    {
      "type": "WebRTC client",
      "remote_addr": "udp4 prflx 192.168.178.20:49615 related :0",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4.1 Safari/605.1.15",
      "send": 63049708
    }
  ]
}

**Comment by AlexxIT** [comment]
Well. Both you transcoding AAC to PCMA or OPUS for WebRTC.
I think we need to work with the ffmpeg settings. Maybe can find better ones.

**Comment by swbouman** [comment]
Hey Alexx,

For YouTube I use the following command to reduce noise:  `-af "afftdn=nr=10:nf=-40:tn=1"`

Hope this points in the right direction. I need to transcode the audio, because camera is only producing  AAC sound.

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0

**Comment by spawn451** [comment]
Thanks, issue fixed!
