### ISSUE TITLE
go2rtc won't rebroadcast a stream which was put in the config with entity_id

### ISSUE THREAD

**Issue by teymur1988** [AlexxIT/go2rtc#368]
Hi Alexx, 

I've installed go2rtc as addon to HA. Maybe this has to do with the new version of go2rtc 1.3.2, but I noticed that I wasn't able to playback the stream from the following config, which used to work well before: 

```
streams:
  "camera.doorbell": ffmpeg:{input}#video=copy#audio=opus
```
So having the config above in go2rtc v 1.3.2 I can no longer use `rtsp://localhost:8554/camera.doorbell` to play my camera stream in a webrtc card, neither can I use `rtsp://homeassistant_ip:8554/camera.doorbell` in VLC player. However if I go to UI of go2rtc and try to stream camera.doorbell in the broswer then it works OK. 

A workaround: 

To be able to use go2rtc's  rebroadcasted rtsp link, the stream needs to have the camera's rtsp link, as in connect directly to the camera:

```
streams:
  doorbell: 
    - rtsp://admin:password@doorbellcamera.local/cam/realmonitor?channel=1&subtype=0
    - ffmpeg:doorbell#audio=opus
```
So if the config is as above, then `rtsp://localhost:8554/doorbell` will work in the card and  `rtsp://homeassitant_ip:8554/doorbell` will work in VLC player.

Could you please look into this? Thank you.

**Comment by AlexxIT** [comment]
`{input}` template will work only after you open this stream from Hass lovelace.

**Comment by teymur1988** [comment]
> `{input}` template will work only after you open this stream from Hass lovelace. It will be cleared on every go2rtc restart.
> If you can put direct link to camera to the go2rtc config - better do it.

I see what you mean now. I’ll better include rtsp links directly yo the camera. Thanks.
