### ISSUE TITLE
2-way audio link not present in webui

### ISSUE THREAD

**Issue by TheDescender** [AlexxIT/go2rtc#370]
So, I've been trying to get 2-way audio working on my TP-link TAPO camera through the go2rtc HA addon, but for some reason the 2-way audio link doesn't display for the camera on my webui: https://i.imgur.com/yLgK620.png

I've gone through the documentation on how to setup 2-way audio for TAPO cameras, even followed this video: https://www.youtube.com/watch?v=WnRJxneCUYE

It appears I've done the config correctly, but the 2-way audio link shown in the video just isn't present for me. **What am I overlooking?**
```
streams: 
    camera.carport_camera_hd_stream:
        - rtsp://Username:Password@192.168.1.XXX:554/stream1
        - tapo://admin:E6BXXXAAXXXXXXXX469BXXXXX4A0CD@192.168.1.XXX
```
The video and one way audio feed over rtsp work great btw, besides me being an idiot it was easy setup and good documentation. 

I will also add that for some reason opening the go2rtc HA webui from within Home Assistant gives me a cloudflare gateway error, which is something no other addon does or has ever done for me. My HA access is tunneled through a secure cloudflare tunnel using cloudflared and my own domain. I assume the normal webui outside of HA should also just have the 2-way audio link, so this likely has no impact, but I mention it so everyone is aware of the context. https://i.imgur.com/TENuTRe.png

I scanned the issues board for a similar or related problem but couldn't find any, if you know of a post with the same or a related issue, please kindly direct me to it.

**Comment by NickM-27** [comment]
you just click on "links" and then there will be a two way audio link on that page

**Comment by TheDescender** [comment]
Am I being an idiot? I noticed the WebRTC Magic section on this page already, but I have no clue what to select here to how to open a stream with the two way audio option selected. What link would I click here? [https://i.imgur.com/95qOWUm.png](url)

**Comment by NickM-27** [comment]
Just click what you want (most likely you want video+audio+microphone) and then click webrtc.html and off you go

**Comment by TheDescender** [comment]
Ok I need to likely change my nginx connections since the stream won't load over https, but my browser did request microphone access so I assume that worked. Thank you very much now I feel like an absolute clown. Is this in the documentation anywhere under the 2-way audio section? (So I can feel every more stupid)

**Comment by dancer16121983** [comment]
Hi.
First i think you have to have an "https://" URL.
Then i solved my problem using another way of "login" for the streams tapo part. I used:

streams:

  tapo_cam:
    - rtsp://myUSER:myPASS@192.168.1.202:554/stream1 (user and password set up inside the app for nvr and onvif)
    - tapo://CLOUDpasswordPLAINTEXT@192.168.1.202   (my cloud password in plaintext and used instead of 
                                                                                          - tapo://admin:PASSWORDinM5Duppercase@192.168.1.202)

Then restarted, went to links. At the end in the WEBRTC MAGIC part i chose 2nd option "video+audio+microphone = two way audio from camera"

and ctrl+click "webrtc.html local WebRTC viewer"

it gave me a link with this data (the "XXXXXXXXX" are a unique code for your URL)
https://homeassistantURL/api/hassio_ingress/XXXXXXXXXXXXXXXXXXXXXXXXXXXX/webrtc.html?src=tapo_cam&media=video+audio+microphone

and created a elements card in home assistant to use that link.

Hope i could help in some way.

Next project is to try 2 way audio with a dafang3 camera with dafang hacks firmware.
