### ISSUE TITLE
Problem with configuring HTTPS access

### ISSUE THREAD

**Issue by TheDescender** [AlexxIT/go2rtc#371]
Title pretty much says it all. The stream works perfectly fine over HTTP, but once I try going over HTTPS the stream fails to load in and just gets stuck on a grey loading screen. https://i.imgur.com/nomLQHh.png

Mainly curious if anyone has run into this issue and could give a general pointer as to why this happens. I've tried port-forwarding my HA on the requisite ports, the camera directly and making changes in my nginx proxy manager, but so far seems this has had no impact. Feels like i'm overlooking something simple.

Please let me know if you have any more information on this topic.

**Comment by AlexxIT** [comment]
I don't know what HTTPS you are talking about. You need to provide more info

**Comment by TheDescender** [comment]
Yeah I realize I might've been unclear. More specifically, when I open the web interface directly over HTTP and access my Tapo camera feed over rtsp the stream works fine. 

But when I access the web interface directly over HTTPS and access the same camera feed, the connection never loads and I'm presented with the indefinite loading screen in my original post.

For HTTPS I'm using a proxied Cloudflare DNS with their free SSL cert, I've port forwarded on port 1984, 8554 and 8555. Additionally, when accessing the webui from inside HA through my Cloudflared tunnel, I get a 502 gateway error.

I'm really not sure how to test anything further besides setting up a DMZ host to ensure the issue not port related, since there aren't any specific errors when using the web interface directly. Hence why I was hoping others may have recognized the issue.

**Comment by AlexxIT** [comment]
Maybe you should ask on the Home Assistant forum how to set up external HTTPS access.
I don't think the problem is related to go2rtc.

**Comment by TheDescender** [comment]
All my other add-ons work perfectly fine with my current https setup in HA. And as I indicated, when I access the go2rtc addon's webui directly from a browser over HTTP at HAserverip:1984 it works just fine. And the stream loads.

When I portforward the go2rtc ports to my HA host machine, accessing the webui directly from a browser at the url I've defined in my DNS works fine too. It's just that at this point the stream doesn't load.

It really seems like an issue caused by the way https connections are dealt with by the go2rtc HAaddon.

I'll try to using the docker container instead and see if the problem persists to see if it's related to my specific DNS setup.

**Comment by TheDescender** [comment]
@AlexxIT I can confirm the same behavior when using just the docker container on a separate machine. 

For the record I am on a symmetric NAT, but I have forwarded the recommended ports to the container host machine and have even tried to set the server running the go2rtc container as a dmz host. Camera stream still doesn't load in over an https connection using cloud flare (non) proxied dns and ssl. 

I really don't understand what in my network could prevent the camera stream from loading when accessing the stream over https, when loading the go2rtc webUI works perfectly fine. Considering in this instance HA is completely out of the picture, I'm hesitant to post on the HA forums for this topic. Is there any more information I could provide you that might give you a clue as to what the issue could be?

**Comment by TheDescender** [comment]
@AlexxIT Not intended to rush/annoy you, but I want to emphasize that this issue is definitely related to go2rtc and not exclusive to the HA addon, as the same problem occurs using the standalone Docker container as mentioned in my previous post.

Any indication of what you think may cause this problem would be appreciated.

**Comment by AlexxIT** [comment]
Unfortunately, I do not have the opportunity to teach you how to configure HTTPS.

**Comment by TheDescender** [comment]
In another effort to troubleshoot this, I have a question. Should the HA webui be accessible through ingress over http? 
When accessing the web-ui over ingress I end up with a 502-bad gateway error as can be seen in the attached image.

![image](https://github.com/AlexxIT/go2rtc/assets/43969610/170d0a89-ed20-4be8-b748-42603d69db54)

Go2rtc server is running on same machine as HA.
What could cause HA to throw this error when redirecting to a container within the same local network?

**Comment by AlexxIT** [comment]
If go2rtc installed as addon with default API port - this feature should work.

**Comment by TheDescender** [comment]
Ok turns out no using the default port was the problem all along. Defining a non-standard port just completely bricked both the ingress from HA and the https connection when go2rtc was hosted in a separate machine's container. Both work now.

I was accessing go2rtc over port 1985 instead of 1984, is there a second configuration option somewhere to properly redirect the HA addon to this port that I overlooked?

I recall reading another post that had issues with non-standard port ingress here #28 , maybe unrelated.

**Comment by AlexxIT** [comment]
No. Custom ingress port not supported.

**Comment by TheDescender** [comment]
Alright. Well good to know it's a limitation and not me being an idiot. 

Still weird that the non-standard port would also cause these https connection issues using the seperate docker instance of go2rtc and that no one posted about this problem before. (Do people not change their default ports? Lol)

You have any future plans for supporting custom ports for ingress? Or are there specific HA limitations restricting you to do that?

**Comment by pergolafabio** [comment]
Hey @TheDescender , we're you now able to connect to the go2rtc addon on https? Can you tell me how?

**Comment by TheDescender** [comment]
@pergolafabio hate to disappoint you, but since I got the HA interface plugin to work, I swapped to just using that. And in coming weeks I will switch completely to using frigate to do all my cams, which has Alex's Go2RTC built into it. All this meaning I don't know how exactly to access the go2rtc interface over https, but I imagine its as easy as just forwarding the (DEFAULT) port on your router to the host machine and using your own ssl certificate. You can get one free from cloudflare for your domain.

**Comment by pergolafabio** [comment]
Hey, I use nginx now for go2rtc, no need to open ports, and I secured the go2rtc webpage with user/pass

**Comment by TheDescender** [comment]
Yeh ok same what I did during testing. Excluding the user/pass which I didn't know it had. Glad you found something that works for you :)

**Comment by pgswow** [comment]
> Hey, I use nginx now for go2rtc, no need to open ports, and I secured the go2rtc webpage with user/pass

Hello! could you just give an example of an nginx configuration to secure go2rtc?

**Comment by pergolafabio** [comment]
See here:

https://github.com/AlexxIT/go2rtc/issues/542#issuecomment-1969240227
