### ISSUE TITLE
multi-source 2-way codecs negotiation question/issue

### ISSUE THREAD

**Issue by teymur1988** [AlexxIT/go2rtc#372]
Hi Alexx, 

I have the following config for my Amcrest 1041B camera:
Note: By default this camera streams in H264/AAC

```
streams:
  doorbell_sub: 
    - rtsp://admin:password@doorbellcamera.asus/cam/realmonitor?channel=1&subtype=1
    - ffmpeg:doorbell_sub#audio=opus
```

Below is my WebRTC card config:

```
type: custom:webrtc-camera
url: rtsp://localhost:8554/doorbell_sub
```
Shouldn't this be automatically working and choose whatever audio codec is needed no matter what client I access it from? 
The issue I'm currently facing with this config is that I'm getting sound on windows (chrome) but no sound on iOS (companion app). 

Logs when accessing from PC and iOS. 
[go2rtc-access-from-ios-companion-app.txt](https://github.com/AlexxIT/go2rtc/files/11276131/go2rtc-access-from-ios-companion-app.txt)
[go2rtc-access-from-windows-chrome.txt](https://github.com/AlexxIT/go2rtc/files/11276133/go2rtc-access-from-windows-chrome.txt)

If I change my config to the following, then the opposite will happen, no sound on windows (chrome) and sound on iOS  (companion app):

```
type: custom:webrtc-camera
url: rtsp://localhost:8554/doorbell_sub?video=copy&audio=opus
```

As a workaround I've used the following WebRTC card config (I just guessed it, I didn't actually know this was possible) and it seems to be working on both the pc and ios.

```
type: custom:webrtc-camera
url: rtsp://localhost:8554/doorbell_sub?video=copy&audio=aac&audio=opus
```

Below are some questions, ideas/brainstorming:

Can this issue of mine be caused by a high latency connection? I'm currently offshore and use VSAT. My minimum ping time to the first router ashore is 600-700ms at best. Internet speed is 3-4Mbps. Could it be that something just times out while this codec negotiation is happening? I assume go2rtc hasn't been tested at these conditions where there is a high latency network  between client and server.

Any inputs are appreciated. Thanks!

**Comment by NickM-27** [comment]
what you really want to set for `url` is just the name of the camera

```yaml
type: custom:webrtc-camera
url: doorbell_sub
```

and it will work the way you want

**Comment by teymur1988** [comment]
> what you really want to set for `url` is just the name of the camera
> 
> ```yaml
> type: custom:webrtc-camera
> url: doorbell_sub
> ```
> 
> and it will work the way you want

Wow, it does work! I wish I knew this earlier! Thanks a lot!
