### ISSUE TITLE
ERROR: "listen tcp :1984: bind: address already in use"`

### ISSUE THREAD

**Issue by jjvelar** [AlexxIT/go2rtc#373]
Hi!

I am getting this error that prevents Go2RTC to start within Home Assistant (I have also Frigate 0.12 installed):

`FTL [api] listen error="listen tcp :1984: bind: address already in use"`

Please, advise.
Thanks!

José

**Comment by NickM-27** [comment]
you have multiple services running on 1984. That being said, frigate includes go2rtc with all features available so there should be no reason to run another instance of go2rtc
