### ISSUE TITLE
Roborock S6 no video

### ISSUE THREAD

**Issue by pinkfloydFR** [AlexxIT/go2rtc#376]
Hi,

Trying to access my roborock camera but all i got when i click stream in go2rtc webui is infinite loading with sometimes a "mse" message :  

Sorry, corrected ( diabled security dot ) and understood that video only available during cleaning.

**Comment by AlexxIT** [comment]
So no issue for you?

**Comment by pinkfloydFR** [comment]
No all is good for my side, sorry for the  inconvenience !
