### ISSUE TITLE
Remove FFmpeg buffer because have problems with MJPEG

### ISSUE THREAD

**Issue by teymur1988** [AlexxIT/go2rtc#378]
Hi there,

I've got the following config:

```
streams:
  doorbell_sub:
    - rtsp://admin:password@doorbellcamera.asus/cam/realmonitor?channel=1&subtype=1
    - ffmpeg:doorbell_sub#audio=opus
    - ffmpeg:doorbell_sub#video=mjpeg
```
 
When I'm trying to play the mjpeg video with this link `http://10.10.10.29:1984/api/stream.mjpeg?src=doorbell_sub` VLC gives an error. Logs are attached. Could you please help?

Thanks
[go2rtc-logs-mjpeg.txt](https://github.com/AlexxIT/go2rtc/files/11297744/go2rtc-logs-mjpeg.txt)

**Comment by AlexxIT** [comment]
You can try fast fix:
```yaml
ffmpeg:
  output: "-user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
```

**Comment by teymur1988** [comment]
Hi Alexx,

Thanks. It worked. 

Will this line cause any trouble when the bug is fixed in the future release?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.5.0
