### ISSUE TITLE
Unknown input format: 'alsa'

### ISSUE THREAD

**Issue by dbuezas** [AlexxIT/go2rtc#385]
I'm trying to add the audio stream from the computer's microphone to a webcam and it looks like ffmpeg doesn't understand alsa.

```log
2023-04-26 17:21:24.668965652  19:21:24.668 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="exec:ffmpeg -hide_banner -f alsa -ac 1 -i default -c:a libopus -ar:a 24000 -ac:a 1 -rtsp_transport tcp -f rtsp {output}"
2023-04-26 17:21:24.669170517  19:21:24.669 DBG [exec] run url="exec:ffmpeg -hide_banner -f alsa -ac 1 -i default -c:a libopus -ar:a 24000 -ac:a 1 -rtsp_transport tcp -f rtsp rtsp://localhost:8554/94d563a6e4086c5ba65bae599d547651"
2023-04-26 17:21:24.673742836  Unknown input format: 'alsa'
```

This command works perfectly if I run it from ssh, so the microphone does work fine.
```bash
ffmpeg -hide_banner -f alsa -ac 1 -i default -c:a libmp3lame -ar:a 24000 -ac:a 1 output.mp3
```

Here's my intended config:
```
go2rtc:
  log:
    exec: trace

  streams:
    webcam: 
      - "ffmpeg:device?video=1&resolution=640x480#video=mjpeg"
      - "exec:ffmpeg -hide_banner -f alsa -ac 1 -i default -c:a libopus -ar:a 24000 -ac:a 1 -rtsp_transport tcp -f rtsp {output}"
```
But it makes go2rtc crash while starting, so I am adding the "exec:ffmpeg..." stream via the web UI to test it instead.

Note: And I am using it through frigate, which uses v1.2.0 of go2rtc. Replacing it with v1.4.0 makes my computer crash (runs out of ram) after a while.

Do you have any suggestion?
Can I maybe replace the ffmpeg version somehow?

Thank you for this awesome application!

**Comment by AlexxIT** [comment]
Have you tried you command inside Frigate docker container?
Because FFmpeg, audio devices and audio drivers inside docker container may be different

**Comment by dbuezas** [comment]
I have not, would you be so kind and share with me how to do that? :) 

Side note: I tried using pulse instead. This also works in ssh but not in go2rtc:
```
2023-04-26 18:17:56.891609589  20:17:56.891 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="exec:ffmpeg -hide_banner -f pulse -ac 1 -i \"alsa_input.usb-GENERAL_GENERAL_WEBCAM_JH0319_20210727_v017-02.mono-fallback\" -c:a aac -ar:a 16000 -ac:a 1 -rtsp_transport tcp -f rtsp rtsp://localhost:8554/webcam_audio"
2023-04-26 18:17:56.891685094  20:17:56.891 DBG [exec] run url="exec:ffmpeg -hide_banner -f pulse -ac 1 -i \"alsa_input.usb-GENERAL_GENERAL_WEBCAM_JH0319_20210727_v017-02.mono-fallback\" -c:a aac -ar:a 16000 -ac:a 1 -rtsp_transport tcp -f rtsp rtsp://localhost:8554/webcam_audio"
2023-04-26 18:17:56.897667958  alsa_input.usb-GENERAL_GENERAL_WEBCAM_JH0319_20210727_v017-02.mono-fallback: No such process
```

**Comment by AlexxIT** [comment]
`docker exec -it <container name> bash`

**Comment by dbuezas** [comment]
I indeed can't
<img width="791" alt="image" src="https://user-images.githubusercontent.com/777196/234690087-c9290081-fc54-40d8-b815-44c8266ad935.png">

**Comment by NickM-27** [comment]
Frigate only includes the go2rtc binary. It uses its own version of ffmpeg which seems to not support this codec

**Comment by AlexxIT** [comment]
You can try go2rtc default and hardware version. They based on different linux and may have different drivers:
https://hub.docker.com/r/alexxit/go2rtc

**Comment by dbuezas** [comment]
Thank you both! 

I tried the go2rtc v1.4.0, go2rtc master and go2rtc hardware standalone AddOns and I get these errors:

## Microphpone Audio

```
21:52:02.000 DBG [exec] run url="exec:ffmpeg -hide_banner -f alsa -ac 1 -i default -c:a libopus -ar:a 16000 -ac:a 1 -rtsp_transport tcp -f rtsp rtsp://localhost:8554/cb2d591555b389176122d37b17768f53"
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (Error loading shared library /usr/lib/alsa-lib/libasound_module_pcm_pulse.so: No such file or directory)
[alsa @ 0x7f83ae090100] cannot open audio device default (No such device or address)
default: I/O error
```

The stream config is:
`      - exec:ffmpeg -hide_banner -f alsa -ac 1 -i default -c:a libopus -ar:a 16000 -ac:a 1 -rtsp_transport tcp -f rtsp {output}`

So it looks that the default addon doesn't work for me either.

---
## Jmpeg Video
Interestingly, my video strem didn't work either 
`ffmpeg:device?video=1\u0026resolution=640x480#video=mjpeg`
```
21:56:31.465 DBG [exec] run url="exec:ffmpeg -hide_banner -f v4l2 -video_size 640x480 -i /dev/video2 -c:v mjpeg -force_duplicated_matrix:v 1 -huffman:v 0 -pix_fmt:v yuvj420p -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -bufsize 8192k -f rtsp rtsp://localhost:8554/73784e8f2d2e802d998d116ed45ce529"
Input #0, video4linux2,v4l2, from '/dev/video2':
...
[swscaler @ 0x7efc8e718040] [swscaler @ 0x7efc8e2ff040] deprecated pixel format used, make sure you did set range correctly
[mjpeg @ 0x7efc92832880] Either both buffer size and max rate or neither must be specified
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

But with a lot of fiddling I got the webcam video to work with (video only):
`exec:ffmpeg -hide_banner -f v4l2 -i /dev/video2 -c:v mjpeg -force_duplicated_matrix:v 1 -huffman:v 0 -pix_fmt:v yuv420p -color_range 2 -an -user_agent ffmpeg/go2rtc -rtsp_transport tcp -bufsize 8192k -maxrate 4096k -f rtsp {output}`

(note that `ffmpeg:device?video=1#resolution=640x480#video=mjpeg` does work in the frigate embedded go2rtc v1.2.0 )

**Comment by dbuezas** [comment]
It looks like what I'm trying to do is not within go2rtc, so I'll close this issue. Thanks you both for your support, it was very educational for me to tinker with this!

**Comment by dbuezas** [comment]
I ended up making a very simple addon that has ffmpeg, pulse and alsa installed and runs an arbitrary command as a service (setup via configuration tab). If anybody needs it, ping here and I'll put it in github

**Comment by AlexxIT** [comment]
Show how you do it. Maybe I can implement it to go2rtc docker version

**Comment by dbuezas** [comment]
That would be awesome!
I asked for this in https://github.com/AlexxIT/go2rtc/issues/403

**Comment by AlexxIT** [comment]
Ok. Lets continue there
