### ISSUE TITLE
wrong response on DESCRIBE

### ISSUE THREAD

**Issue by cscoppafox** [AlexxIT/go2rtc#391]
Hello, this just started happening on all cameras:

```
12:10:01.034 INF go2rtc version 1.4.0 linux/amd64
12:10:01.035 INF [api] listen addr=:1984
12:10:01.035 INF [rtsp] listen addr=:8554
12:10:01.035 INF [srtp] listen addr=:8443
12:10:01.035 INF [webrtc] listen addr=:8555/tcp
12:10:30.982 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/init.go:232 > error="wrong response on DESCRIBE"
12:10:30.982 ERR [api.hass] exchange SDP error="wrong response on DESCRIBE"
12:11:18.317 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/init.go:232 > error="wrong response on DESCRIBE"
12:11:18.317 ERR [api.hass] exchange SDP error="wrong response on DESCRIBE"
12:11:22.244 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/init.go:232 > error="wrong response on DESCRIBE"
12:11:22.244 ERR [api.hass] exchange SDP error="wrong response on DESCRIBE"
12:11:36.266 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:160 > error="wrong response on DESCRIBE"
12:11:43.717 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:160 > error="wrong response on DESCRIBE"
12:11:54.191 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/init.go:232 > error="wrong response on DESCRIBE"
12:11:54.191 ERR [api.hass] exchange SDP error="wrong response on DESCRIBE"
12:11:59.383 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/init.go:232 > error="wrong response on DESCRIBE"
12:11:59.383 ERR [api.hass] exchange SDP error="wrong response on DESCRIBE"
12:12:49.116 ERR github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:160 > error="wrong response on DESCRIBE"
```

<img width="672" alt="image" src="https://user-images.githubusercontent.com/111901305/235200461-b81ea2d0-d2c8-4ac5-bdeb-7c46c4b0d19e.png">

**Comment by cscoppafox** [comment]
UPDATE:  Ripped out RTSPtoWebRTC addon, restarted dockers and things are working again.  I think my problem is that ring-mqtt and go2rtc are fighting over port 8554 ... so if you have any thoughts on how both containers should be configured as far as that port, that would be great.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/111901305/235249129-2b2160eb-eb7f-4813-8163-38c7ab2976b8.png">

**Comment by NickM-27** [comment]
just configure one to be a different port, two services can't share the same port but if you run one in bridge mode you can map a different host port to 8554 of the container port

**Comment by cscoppafox** [comment]
I'm running Unraid, I'm looking at the settings for ring-mqtt and that port isn't even configured, I think it just automatically assigns it, same with go2rtc.

**Comment by NickM-27** [comment]
Then they are both running in host mode and like I said, you need to not be running one in host mode

**Comment by cscoppafox** [comment]
That's where it gets confusing for me, because on Unraid, there's certain combinations where something on the host can't see the docker containers and vice-versa.  I guess I'll try moving ring-mqtt to a bridge and see what happens.

**Comment by NickM-27** [comment]
I use unraid, it has a very standard docker setup. any issues like that are just going to be due to docker misconfigurations

**Comment by cscoppafox** [comment]
It doesn't work if I switch ring-mqtt into a bridge, probably because HA is in host mode.  I think the issue is that ring-mqtt has a "lite" version of go2rtc cooked in, but I was taught that you need the full version installed, along with the RTSPtoWebRTC addon installed in HA.  With that setup I can play Ring camera live, or the last 5 events with almost no delay.  I'm just trying to figure out what settings I need to change to prevent these 2 from fighting.  (Like I said it's all working right now, but I think it's picky about startup order... the right one has to grab that port I guess)

**Comment by cscoppafox** [comment]
Would that go here?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/111901305/235252069-66ad8627-f24a-4541-bb1b-cabb36144d57.png">

**Comment by cscoppafox** [comment]
Blank config because ring-mqtt talks to it and auto populates all the streams:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/111901305/235252269-97f7a6f3-6650-4fa8-a38f-baec954cba56.png">

**Comment by cscoppafox** [comment]
Got it working, no more conflict.  Thanks for the help!

![image](https://user-images.githubusercontent.com/111901305/235256268-1ab3eadd-cba0-4c35-8052-c441f8f2efc6.png)

**Comment by AlexxIT** [comment]
I think problem solved. Thanks @NickM-27
