### ISSUE TITLE
Roborock S6 MaxV in Homeassistant

### ISSUE THREAD

**Issue by peteh** [AlexxIT/go2rtc#399]
Hi, 

I'm kinda lost with the steps in the readme to integrate the cam of the roborock s6 maxv. 

I have installed the webrtc camera intergration via HACS because I'm running homeassistant in docker. 

However, I kinda don't know what's the next step to get the camera of my 6maxv into HA. Did I miss a step? 
What's the architecture, do I need to run the docker for go2rtc as well?

**Comment by peteh** [comment]
I managed by using the docker container. 

0. added the hacs webrtc camera integration
1. downloaded and started the docker service
2. I went to the webui on port 1984, logged in with my roborock account
3. Copied the URL into the webrtc cam custom card in homeassistant
4. I have the swipe pattern on my phone, so the app does not ask for pin but for pattern. I changed the pin to match my swipe pattern (here you have to imagine the swipe buttons are numbers as seen on the phone keyboard)
5. Profit

**Comment by AlexxIT** [comment]
WebRTC Camera has old go2rtc inside. Without Roborock source. That's why external go2rtc helps
