### ISSUE TITLE
How to edit yaml to add a stream correctly

### ISSUE THREAD

**Issue by Chaot1** [AlexxIT/go2rtc#400]
I try to add a stream using the config editor on webpage and i also tried to edit the go2rtc.yaml
`sudo nano /etc/go2rtc.yaml`
i also tried different ways to add may camera, but ist still won't start.
`streams:
door: rtsp://192.168.8.92:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream`
`streams:
door: rtsp://rtsp:192.168.8.92:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream`

whats my fault?
When i add the camera as temorary stream it works perfect, but after a reboot the stream is off.

**Comment by andrew-lemon** [comment]
I think it needs to be revised as below. Everything needs to be on its own line with proper indenting. Look at the examples in the instructions carefully.

'''streams:
  door:
    - rtsp://192.168.8.92:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
    - rtsp://rtsp:192.168.8.92:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream'''

**Comment by Chaot1** [comment]
Thank you. Now it works

`streams:
  door:
    - rtsp://192.168.8.92:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream`
