### ISSUE TITLE
Fix panic with only audio for MP4/MSE

### ISSUE THREAD

**Issue by spawn451** [AlexxIT/go2rtc#404]
I use go2rtc to stream video + audio from an esp32-cam to which I have connected an INMP441 microphone.
I created a web page with 2 iframes that allow me to have video and audio at the same time without any delay!
It works well with version 1.3.2 and 1.4.0 but only on Linux (docker). 
On Windows this crashes go2rtc with the following message:
![image](https://user-images.githubusercontent.com/87195479/235483245-30ad000b-0f77-4d45-b842-93a7ba43c5bd.png)

My go2rtc.yaml

  espcam_video: http://192.168.10.57:81/mjpeg/1
  espcam_audio: ffmpeg:http://192.168.10.57#audio=opus
  
 Audio comes from esp32-cam through a http server serving a web page with this configuration :
 
 video controls="" autoplay="" name="media" source src="http://192.168.10.57/ type="audio/wav">
 
 It's not very blocking but if ever you or someone has an idea it would be interesting to know the cause of the crash.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
