### ISSUE TITLE
I want to know the client's monitoring time ?

### ISSUE THREAD

**Issue by volkankoc** [AlexxIT/go2rtc#405]
How can I get the start and stop date/time of a consumer to watch the broadcast.
for ex:
Watch started:      13:00:50
Watch stoppped:  13:10:00 like

"I want to impose a certain watch time restriction on the broadcast."

**Comment by AlexxIT** [comment]
There is no such API. You can get the debug logs for the streams module to check the start and stop times of a consumer. But there are no consumer IDs.

**Comment by volkankoc** [comment]
Extracting logs is a long and difficult task. Do you have a different suggestion? Also, how can I separate the viewers because there is no consumer id?

**Comment by volkankoc** [comment]
Can you help me ?

**Comment by AlexxIT** [comment]
There is no such feature and it is not planned in the near future
