### ISSUE TITLE
remote ffmpeg streaming source confusion

### ISSUE THREAD

**Issue by nebulous** [AlexxIT/go2rtc#407]
![image](https://user-images.githubusercontent.com/177510/236009899-c842b13b-67c5-401b-af7f-d4da7281cadc.png)

**What I'm trying to achieve:** 

I have a usb webcam on a remote computer which I'd like to make available as a source to go2rtc which I have running on my home assistant server. I'd like to be able to view said camera stream in home assistant. The examples in the docs all seem to be focused on executing ffmpeg on the same host as go2rtc, but what I'd like to do is to use ffmpeg on a remote machine to stream over the network _to_ go2rtc. Hopefully the picture above makes my goal more clear.

**What I've tried so far:**

assorted permutations of the following, checking the go2rtc web interface to see if a new stream appears:
remote computer: `ffmpeg -i /dev/video0 -c:v copy -f rtsp -rtsp_transport tcp rtsp://go2rtchostIP:8554`

Can anyone help me understand what I'm missing?

**Comment by AlexxIT** [comment]
You can't send stream to the root for RTSP server. Go2rtc does not know how to name this stream. You need to name it.
https://github.com/AlexxIT/go2rtc#incoming-sources

**Comment by nebulous** [comment]
Thanks, that was the bootstrap I needed.

For future travelers, per docs @AlexxIT linked above, the following worked justFine™

1. create empty stream as a placeholder for go2rtc to accept data 

```yaml
streams:
  foocam:
```

2. then on the remote box, target the newly-created stream
`ffmpeg -i /dev/video0 -c:v copy -f rtsp -rtsp_transport tcp rtsp://go2rtchostIP:8554/foocam`

**Comment by pabst2k** [comment]
Thank you nebulous, I tried to get this work for hours without success
