### ISSUE TITLE
Support nest WebRTC cameras?

### ISSUE THREAD

**Issue by Inrego** [AlexxIT/go2rtc#408]
I have one of the newer cameras that only support WebRTC. Are there plans to support these cameras? Would love to use it in frigate and some homebrew software

**Comment by AlexxIT** [comment]
Someone needs to give me credential to Google account with this cameras. Same as for Home Assistant integration.

I can't do anything without access to working protocol.

**Comment by Inrego** [comment]
Our camera is in the toddler's room to monitor her during the night. I'd have to discuss it with the wife before giving access.

I'll get back to you

**Comment by AlexxIT** [comment]
You can hide the picture. But better if camera has timestamp so I can know if picture changes.
You can find my contacts in the github profile.

**Comment by cthach** [comment]
For anyone searching for a solution to this. I was able to get it working by using the [Nest source](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-nest). I can submit a PR with an in-depth guide if folks are interested.

I'm seeing a separate issue now with stream stability but that is a separate issue I'll raise.

**Comment by cthach** [comment]
> For anyone searching for a solution to this. I was able to get it working by using the [Nest source](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-nest). I can submit a PR with an in-depth guide if folks are interested.
> 
> I'm seeing a separate issue now with stream stability but that is a separate issue I'll raise.

Submitted #1297 as a possible fix to stability issues.

Got a few thumbs ups. I'll work on another PR with that guide.

**Comment by msantos142** [comment]
> > For anyone searching for a solution to this. I was able to get it working by using the [Nest source](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-nest). I can submit a PR with an in-depth guide if folks are interested.
> > I'm seeing a separate issue now with stream stability but that is a separate issue I'll raise.
> 
> Submitted #1297 as a possible fix to stability issues.
> 
> Got a few thumbs ups. I'll work on another PR with that guide.

Did you ever get to put the guide together? Tks
