### ISSUE TITLE
Add support RTSP over WebSocket (ex. for Axis cameras)

### ISSUE THREAD

**Issue by drott** [AlexxIT/go2rtc#415]
Axis Cameras support a mode where they provide an RTP endpoint / stream over websockets.
Some more info may be found here:
https://github.com/AxisCommunications/media-stream-library-js/tree/main/player

Example endpoint:
`ws://{camera host and http port}/rtsp-over-websocket`

It would be convenient to be able to extract the stream from there and use it in home assistant without transcoding.

**Comment by AlexxIT** [comment]
Why is this necessary? Cameras can't handle another protocol?
Can you record the first dump via Wireshark? The first few seconds.

**Comment by drott** [comment]
On cameras for which a user does not have admin access and which are firewalled or only have HTTP(S) access, the rtsp stream (that the camera supports) may not be accessible. One alternative is still the MJPEG stream which works but uses higher bandwidth / less efficient encoding / image quality. That's why I would find it useful to access the H264 stream. I'll try to record a dump.

**Comment by drott** [comment]
> Can you record the network dump via Wireshark? The first few seconds.

I shared a pcap trace with you in email.

**Comment by AlexxIT** [comment]
You have a difficult situation. This is a WebSocket with Digest authorization. The standard libraries do not support this.
And I can't emulate this behavior somewhere in my own environment.
I need access to the camera. Through port forwarding on router or through a tunnel for the http port:
https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet

**Comment by drott** [comment]
Do you mean you can't emulate the server side of this behaviour for testing?

**Comment by AlexxIT** [comment]
You can try latest master version.
Your camera has auth for WebSocket and has no auth for RTSP.
My camera (Dahua) has no auth for WebSocket but has auth for RTSP.

```
streams:
  axis-rtsp-ws:  rtsp://192.168.1.123:4567/axis-media/media.amp?overview=0&camera=1&resolution=1280x720&videoframeskipmode=empty&Axis-Orig-Sw=true#transport=ws://user:pass@192.168.1.123:4567/rtsp-over-websocket
  dahua-rtsp-ws: rtsp://user:pass@192.168.1.123/cam/realmonitor?channel=1&subtype=1&proto=Private3#transport=ws://192.168.1.123/rtspoverwebsocket
```

**Comment by drott** [comment]
> `axis-rtsp-ws:  rtsp://192.168.1.123:4567/axis-media/media.amp?overview=0&camera=1&resolution=1280x720&videoframeskipmode=empty&Axis-Orig-Sw=true#transport=ws://user:pass@192.168.1.123:4567/rtsp-over-websocket`

🤩🥳 Amazing, thank you so much for adding that so quickly. Great work!

That's working well for me. For now, I am locally mirroring this specific camera using go2rtc master, and then feeding that via an `rtsp://` link pointing to localhost to home assistant (while HA doesn't have the latest master yet). Is that the most efficient way to connect the two instances, or how do I best forward?

**Comment by AlexxIT** [comment]
I don't know why even need to add cameras as an RTSP stream in HA at all.
WebRTC Camera integration can work without it.
Snapshots and record you can also do without it.

**Comment by chrislawso** [comment]
Anyone have success adding axis cams? Can someone explain like I am 5years old how to add an axis camera? 

When I put in onvif the following:
rtsp://user:pw@1.2.3.4/onvif/device_service
then go2rtc displays:
AXIS AXIS P3343 stream0	rtsp://user:pw@1.2.3.4/onvif/device_service?subtype=profile_1_h264
AXIS AXIS P3343 stream1	rtsp://user:pw@1.2.3.4/onvif/device_service?subtype=profile_1_jpeg

When I try to add rtsp://user:pw@1.2.3.4/onvif/device_service?subtype=profile_1_h264 to a temp stream I get errors on the go2rtc webrtc view page.
