### ISSUE TITLE
Sluggish MSE feed for Wyze v2 rtsp

### ISSUE THREAD

**Issue by my-umd** [AlexxIT/go2rtc#416]
I have both Wyze v2 and v3 on Wyze's rtsp firmware.  Tried with both go2rtc v1.2 and v1.3.  Wyze v2 camera MSE is very sluggish (verified on two units).  See spin wheel almost every 2-3 seconds.  The feed is really unusable.  Wyze v3 cameras work fine.  Did not find any report on such issue.  Anybody know why?   Thanks.

**Comment by AlexxIT** [comment]
MSE only works fine for good stream and good network between go2rtc and viewer.
There is no way to fix wheel on MSE if you have it because you received data not in real time.
