### ISSUE TITLE
Android IP Camera Reboots

### ISSUE THREAD

**Issue by GitJaxder** [AlexxIT/go2rtc#419]
The Android phone I'm using with one of the many IP Camera apps reboots daily at 0300. After the phone reboots, the IP Camera app opens automatically. This phone sits on a VLAN with zero access to anything outside of the VLAN by default.

My go2rtc docker container also sits on this VLAN and my firewall is configured to allow go2rtc to communicate with Frigate/Home Assistant.

When this reboot occurs, the go2rtc docker container needs to be rebooted before a camera stream is sent to Frigate/Home Assistant.

Now here's my question:
Is there a way to configure go2rtc to be tolerant of the phone's reboot?

**Comment by AlexxIT** [comment]
> When this reboot occurs, the go2rtc docker container needs to be rebooted before a camera stream is sent to Frigate/Home Assistant.

I don't understand whole process. And why go2rtc should be rebooted.

**Comment by GitJaxder** [comment]
Thank you for the response! I'm sorry I haven't replied sooner.

I think that there might be something wrong with the phone itself maybe? I'll have to do some more digging. I initially thought that go2rtc was not properly reconnecting, but from looking at it today, it _seems_ fine? I'm going to close this for now and if I find that I need assistance, I will open another request.
