### ISSUE TITLE
https://10.0.0.100:1984/

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#422]
Good afternoon. Tell me, is it possible to access the web interface via https instead of http on the local network? This is required to open a web page with a microphone and two-way audio. Thank you.

**Comment by spawn451** [comment]
This is possible as for any web page whether on a local network or on the Internet.
You just need to install a SSL or TLS certificate.
There are several ways to do this, self signed certificate(you can use OpenSSL), certificate signed by a CA (Let's Encrypt for example with the use of a reverse proxy like HAProxy or NGINX) etc..

**Comment by AlexxIT** [comment]
It is beyond the scope of this project to teach you how to configure HTTPS.

Personally, I have preferred to use Caddy for several years.

**Comment by pergolafabio** [comment]
> This is possible as for any web page whether on a local network or on the Internet. You just need to install a SSL or TLS certificate. There are several ways to do this, self signed certificate(you can use OpenSSL), certificate signed by a CA (Let's Encrypt for example with the use of a reverse proxy like HAProxy or NGINX) etc..

Hey, how can I add an SSL certificate for this go2rtc addon? I already use let's encrypt and the basic nginx for my HA instance,  but when I try to access https://IP:1984 , I get an insecure page, probably cause the certificate is missing... not sure how I can add it to this addon?
