### ISSUE TITLE
WebTorrent

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#424]
Good afternoon.  Tell me what am I doing wrong?
 Camera set up everything works.
 Set up WebTorrent config
 And I can't click on the WebTorrent permalink.
![Screenshot_20230507-085457_Chrome](https://user-images.githubusercontent.com/98225056/236660385-3b0934d5-7024-4e11-a6ab-17ac4a2c9f31.jpg)
The link that is generated temporarily works.
Why is my permalink not working?
 Thank you.
https://alexxit.github.io/go2rtc/#share=Admin111111&pwd=111111&media=video+audio+microphone

**Comment by AlexxIT** [comment]
You need to be more careful with YAML.
"super-secret-share" = share name

https://github.com/AlexxIT/go2rtc#module-webtorrent

**Comment by TokarevSergey** [comment]
> Вам нужно быть более осторожным с YAML. "super-secret-share" = общее имя
> 
> https://github.com/AlexxIT/go2rtc#module-webtorrent

I can not create a name where to get

**Comment by TokarevSergey** [comment]
> Вам нужно быть более осторожным с YAML. "super-secret-share" = общее имя
> 
> https://github.com/AlexxIT/go2rtc#module-webtorrent

Permalink not working
![image](https://user-images.githubusercontent.com/98225056/236667269-6c10d29e-02bb-497e-9b5f-e4a52235250a.png)

**Comment by AlexxIT** [comment]
```yaml
webtorrent:
  shares:
    Admin111111:
      pwd: "111111"
      src: DoorBell
```

**Comment by TokarevSergey** [comment]
Thank you very much work

**Comment by TokarevSergey** [comment]
> ```yaml
> webtorrent:
>   shares:
>     Admin111111:
>       pwd: "111111"
>       src: DoorBell
> ```

Скажите пожалуйста а возможно ли получить ссылку чтобы звук был включен?
Спасибо
![image](https://user-images.githubusercontent.com/98225056/236694208-ad73fd69-2d12-4886-81c5-ff8b4d951476.png)

**Comment by AlexxIT** [comment]
No. This is uncontrollable browser behaviour.
