### ISSUE TITLE
Support for wyoming output protocol

### ISSUE THREAD

**Issue by luzik** [AlexxIT/go2rtc#427]
While latest home assistant update introduces new voice support, it's missing piece of making home camera acts as a microphone provider. I am not sure if this is the optimal way for providing such an endpoint.

There is documentation:
https://github.com/rhasspy/rhasspy3/blob/master/docs/wyoming.md

But I am not sure is mic is supported by existing HA integration:
https://www.home-assistant.io/integrations/wyoming/
https://github.com/home-assistant/core/tree/dev/homeassistant/components/wyoming

**Comment by AlexxIT** [comment]
As I can see, Hass support only STT and TTS for now:
https://github.com/home-assistant/core/blob/04c298b772bba02ca7b4ffd5cb2220859e471e9a/homeassistant/components/wyoming/config_flow.py#L54-L55

Theoretically go2rtc can provide `audio-chunk`. But I don't understand what software will request them.

Looks like `rhasspy3` support different adapters. And go2rtc can be `mic` adapter. But all current adapters uses stdin/stdout:
https://github.com/rhasspy/rhasspy3/blob/master/examples/satellite/configuration.yaml

So I don't understand right place for go2rtc.

**Comment by luzik** [comment]
Ok, I will reopen this when wyoming integration will support mic.

I wrongly assume that project like:
https://www.home-assistant.io/projects/thirteen-usd-voice-remote/
Are using such connector, but they interact directly with voice_assistant
https://github.com/home-assistant/core/blob/dev/homeassistant/components/esphome/voice_assistant.py

**Comment by AlexxIT** [comment]
So. At your suggestion, I made a couple of new integrations. I think that's enough for now.

https://github.com/AlexxIT/StreamAssist
https://github.com/AlexxIT/FasterWhisper

**Comment by luzik** [comment]
Wow ..thats awesome! Installing and testing right now 🥳
