### ISSUE TITLE
WebRTC stream doesn't start externally if not enough movement or unless camera is moved using PTZ

### ISSUE THREAD

**Issue by kosmosnautti** [AlexxIT/go2rtc#429]
I'm running go2rtc (1.5.0) as standalone with one RTSP stream (Reolink E1 Zoom), and the target is to use Home Assistant with the WebRTC Camera integration to display the stream.

I'm using Cloudflare Tunnels to open Home Assistant to Internet. I also opened up port 8555 (TCP & UDP) in my home router, as the target is to serve the stream using WebRTC.

Now, the problem is that for some reason I can't receive any video feed/stream doesn't start, if there's not enough movement in front of the camera or until I use the PTZ-controls of the camera. After that I will get a brief live feed while the camera is moving, until the camera stops and then the feed just freezes (I can see that immediately after the PTZ-movement stops, the timestamp coming from the camera as an overlay to the feed stops ticking). If I move the camera again, the feed unfreezes for the time of the camera movement.

The same thing is happening no matter if I'm trying to view the feed from Home Assistant or from the go2rtc stream viewer externally. From local network it works from both as it should.

I would like to know if this is a configuration issue, or what is the way to tackle this so that I would have a continuous live feed when accessing the stream externally?

For now, I have my go2rtc configuration as follows:
`webrtc:`
`  candidates:`
`    - stun:8555`

In case it's of any help, when I open up the stream using WebRTC from the go2rtc stream viewer, I can see this traffic on wss://go2rtc.domain.tld/api/ws?src=Stream:

![image](https://github.com/AlexxIT/go2rtc/assets/112827877/bf9f4791-279f-46ac-875f-048002706b8b)

Under the red boxes is my current public home IP-address which has port 8555 opened, and under the yellow boxes is the LAN IP-address of the server that's running go2rtc in my home network.

**Comment by AlexxIT** [comment]
What is the resolution and bitrate of your stream? Try the same thing on a low bitrate stream.

**Comment by AlexxIT** [comment]
There is known problem with WebRTC + UDP + high bitrate
https://habr.com/ru/companies/flashphoner/articles/480006/
