### ISSUE TITLE
Tapo 2 way audio not working on v1.5, works on v1.4

### ISSUE THREAD

**Issue by cvroque** [AlexxIT/go2rtc#431]
Hello!

I use 2 way audio on two Tapo models: C100 and C310, here is configuration for one of em:

> streams:
>     baby:
>       - rtsp://name:password@192.168.168.168:554/stream1 
>       - tapo://admin:MD5PASSWORDHASH@192.168.168.168

When running v1.4 I can use two way audio normally, but once I updated to v1.5 it just doesn't work. 

There are no error logs, what info should I collect in order to help understand this issue?

Thanks in advance!

**Comment by AlexxIT** [comment]
Are you sure if you go back to 1.4, two way audio will work? Maybe the problem is something else.

**Comment by cvroque** [comment]
Turns out I can't reproduce the issue anymore, thanks for the project and sorry for taking your time!
