### ISSUE TITLE
WebRTC (home assistant), Go2RTC, 2 way audio

### ISSUE THREAD

**Issue by bigjme93** [AlexxIT/go2rtc#437]
This is more of a question than anything but others may find this useful, i'm unsure which side to post this on (WebRTC vs Go2RTC) so i'm going to go here and see

I have a Reolink doorbell and have been keeping an eye on the 2 way support for a while and have held of updating until now as people seem to be having ok luck with it

I have a number of tablets that constantly stream the doorbell through go2rtc (v1.2) with audio and all is good, this is streamed through WebRTC in the home assistant companion app

I'd like to update to the latest version (1.5) and enable 2 way audio for 2 new cards I wish to use for mobile phones
I'd then like to leave the tablets alone so they are one way audio only and have these cards with 2 way

From what i can gather, if i upgrade to 1.5, i presume the back channel will auto detect and all devices will start to 2 way audio as i watch them all via webrtc

So my questions are:
1. Is there a way to have the WebRTC card exclude back channel for certain cards and not others? Even if this requires an additional camera stream be added to go2rtc where i can specifically request to not include it
2. Is there a way to have go2rtc auto load the stream if i added a second version so its pre-connected  (without needing a client connected) ready for when a client wants the stream? This is for faster loading times as the doorbell currently takes a few second to initially connect

Again, this may be the wrong place for this so let me know if it is and i will ask over at WebRTC

Regards,
Jamie

**Comment by bigjme93** [comment]
As you can tell, i've been watching this a while, sorry. 1.5 is the version I meant, i will update the question :)

**Comment by AlexxIT** [comment]
1. WebRTC card does not support two way audio yet
2. Go2rtc does not support constant loading of the stream if no one is watching it yet

You can disable two way audio for rtsp source with `#backchannel=0` option
https://github.com/AlexxIT/go2rtc#source-rtsp
