### ISSUE TITLE
Outputs not compatible with Blue Iris

### ISSUE THREAD

**Issue by erikpendragon** [AlexxIT/go2rtc#443]
I am getting Video, but no sound in blue iris.
The output codecs don't align with any of the inputs to blue iris.
Can we get a codec that is supported by blue iris added?

**Comment by NickM-27** [comment]
Surely Blue Iris supports AAC audio

**Comment by erikpendragon** [comment]
I have tried, I am running go2rts that is included in frigate 12.
when I goto the go2 page port:1984 I get the links, and they work there. 
so I am getting sound into go2.
but it does not want to acknowledge it in blue iris

**Comment by NickM-27** [comment]
> but it does not want to acknowledge it in blue iris

right, that is most likely an issue with the stream that is being pulled since by default frigate applies a default_query that only pulls AAC audio. So the URL you are using in Blue Iris should have `?video&audio` at the end of it

**Comment by erikpendragon** [comment]
I have tried rtsp://192.168.1.96:8554/m_f_hallway_main?video=all&audio=all
I have tried others according to the doc, but none seemed to work

**Comment by NickM-27** [comment]
then it is likely to be a blue iris config issue, go2rtc does not change the codec from the camera unless you configure it to and even then blue iris supports them

**Comment by erikpendragon** [comment]
I have even tried transcoding, and forcing the codec on the blue iris side.
my request comes more from the default that Blue iris wants is "64 kbps G.711. u-law"
and I was hoping that could be added as a transcode option.

**Comment by NickM-27** [comment]
go2rtc is fully customizable, you can add whatever transcode options you want

**Comment by erikpendragon** [comment]
I have tried the ones listed in the docs.
unfortunately, I can't find any other examples of someone using the output of go2 into blue iris.
maybe I am thinking of this problem wrong.

**Comment by erikpendragon** [comment]
ohh, I did not know this. thank you.
where do I pout these?

**Comment by erikpendragon** [comment]
found out where, made my own like you just showed, output works in vnc, doesn't work in blue iris.
thank you for your help, I will reach out to blue iris to see if they can help me.
