### ISSUE TITLE
Проблема при отправке записи в Telegram

### ISSUE THREAD

**Issue by oneminc** [AlexxIT/go2rtc#444]
Если отправлять запись в telegram следуя этой инструкции: https://github.com/AlexxIT/go2rtc/wiki/Snapshot-to-Telegram#record-from-h264-or-h265-camera , то
файл видео полученный в телеграмм называется "2_1234567890123456789.mp4 src=g2h dura" и при его воспроизведении нет звука. Если файл переименовать, то звук появляется, но посмотреть его можно только в стороннем плеере

**Comment by TokarevSergey** [comment]
Read below play with codecs.  My android works like this:

http://localhost:1984/api/stream.mp4?src=DoorBell&video=h264&audio=pcmu&duration=15

**Comment by oneminc** [comment]
> Read below play with codecs. My android works like this:
> 
> http://localhost:1984/api/stream.mp4?src=DoorBell&video=h264&audio=pcmu&duration=15

Проблема не в том, что звука нет в файле, а в том, что в телеграм файл прилетает с неверным расширением, в случае, если я прописываю кодеки, то расширение уже выглядит так: "mp4 src=g2h vide"

**Comment by TokarevSergey** [comment]
> > Ниже читайте игру с кодеками. Мой андроид работает так:
> > http://localhost:1984/api/stream.mp4?src=DoorBell&video=h264&audio=pcmu&duration=15
> 
> Проблема не в том, что звука нет в файле, а в том, что в телеграмме файл прилетает с неверным расширением, в случае, если я прописываю кодеки, то расширение уже выглядит так: "mp4 src=g2h vide"

You forgot "?"  Look how I am.  I think it's important.  All my files are viewed in telegram and video and audio.

**Comment by TokarevSergey** [comment]
Ahh, the sound is gone.  Used to be now no.  Damn broke again.  It seems again in the new version of the problem.

**Comment by TokarevSergey** [comment]
Ahh, the sound is gone.  Used to be now no.  Damn broke again.  It seems again in the new version of the problem.

**Comment by TokarevSergey** [comment]
Yes, I understand.
 The video has the wrong file resolution.
 You can watch it in Telegram but without sound.
 In short, the sound on the video broke again.

**Comment by oneminc** [comment]
> You need to ask the author to correct it.

Я призвал его в чате HA в телеге. Ждемс

**Comment by TokarevSergey** [comment]
Это похоже у всех на новой версии.

**Comment by AlexxIT** [comment]
Issue should be written in English

**Comment by TokarevSergey** [comment]
> Проблема должна быть написана на английском языке


Okay, I'll describe it now. problem right.

**Comment by oneminc** [comment]
> > Проблема должна быть написана на английском языке
> 
> Okay, I'll describe it now. problem right.

Problem with codec AAC in Android, but it is not exactly
There is sound if you play the file, for example, in Telegram on mac

**Comment by TokarevSergey** [comment]
> > > Проблема должна быть написана на русском языке
> > 
> > 
> > Хорошо, сейчас опишу. проблема правильная.
> 
> Проблема с кодеком AAC в Android, но это не точно Звук есть если проигрывать файл например в Telegram на mac

The sound with the settings [&video=h264&audio=pcmu&duration=15] worked for me in the previous version, only it was fixed in the previous version. It's a pity.
