### ISSUE TITLE
Problem !!! There is no sound in the video, the file resolution is wrong when sending to Telegram.

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#446]
Good afternoon.
The sound disappeared again when sending a video to Telegram. It was also noticed that the file that is sent to Telegram has the wrong extension and name: “2_5436073062107720221.mp4 src=DoorCam”, but should: “2_5436073062107720221.mp4”.
Please fix the sound. Thank you.

**Comment by oneminc** [comment]
Today we checked it with AlexxIT.  If you change the file extension to the correct one, then nothing will change, there is no sound in Telegram on Android

**Comment by TokarevSergey** [comment]
> Сегодня проверили с AlexxIT. Если изменить расширение файла на правильное, то ничего не изменится, в Телеграм на Андроиде нет звука

The problem with the sound was in version 1.3.x after it was fixed in version 1.4.x and the sound appeared. And in version 1.5.x, the sound disappeared again. Earlier I discussed this problem with the lack of sound.

**Comment by AlexxIT** [comment]
There was problem with AAC audio codec #444

**Comment by AlexxIT** [comment]
@TokarevSergey 
1. What audio codec does your camera have?
2. Show your Hass automation for sending video.

**Comment by TokarevSergey** [comment]
> @TokarevSergey
> 
> 1. Какой аудиокодек у вашей камеры?
> 2. Покажите свою автоматизацию Hass для отправки видео.

![image](https://github.com/AlexxIT/go2rtc/assets/98225056/d1b47356-d32f-4868-bdcd-5867ebdb209e)
Here is my automation.

![image](https://github.com/AlexxIT/go2rtc/assets/98225056/ed1493b7-689e-45f4-bd04-1d0aa40809f5)
Here are my codecs.

Please help me figure it out.

**Comment by AlexxIT** [comment]
And show go2rtc yaml for your stream

**Comment by TokarevSergey** [comment]
![image](https://github.com/AlexxIT/go2rtc/assets/98225056/cdb1b3dd-478c-48a4-8d7e-6a88106cf015)
Here you are

**Comment by TokarevSergey** [comment]
> Икажи по go2rtc yaml для своего стрима

Here you are

**Comment by TokarevSergey** [comment]
> И покажи go2rtc yaml для своего стрима

![image](https://github.com/AlexxIT/go2rtc/assets/98225056/b076b3b3-3ad2-4216-9fa6-1ad73b0d5f69)

**Comment by AlexxIT** [comment]
Stop sharing your webtorrent password. Anyone in internet can view your streams

**Comment by TokarevSergey** [comment]
> Прекратите делиться своим паролем веб-торрента. Любой человек в Интернете может просматривать ваши трансляции


Damn sorry. I'll change it later thanks.

**Comment by TokarevSergey** [comment]
> И покажи go2rtc yaml для своего стрима

![image](https://github.com/AlexxIT/go2rtc/assets/98225056/f775e158-d52f-49d3-bbc9-a7b30df5ba1a)

**Comment by TokarevSergey** [comment]
> @TokarevSergey
> 
> 1. Какой аудиокодек у вашей камеры?
> 2. Покажите свою автоматизацию Hass для отправки видео.

I threw everything at you.  Tell me if it is possible to receive video with sound.  Help.

**Comment by TokarevSergey** [comment]
Thank you everything works after the update
