### ISSUE TITLE
Fisheye video with ffmpeg

### ISSUE THREAD

**Issue by nunokaneco** [AlexxIT/go2rtc#448]
Hello 

First of all thank you for your work developing this too!!

I just found this info https://stackoverflow.com/questions/62238714/how-to-de-warp-180-degree-or-360-degree-fisheye-video-with-ffmpeg related to the Fisheye video with ffmpeg

I just what to test the ffmpeg filters that is mentioned in this site 

```
ffmpeg -i input.mp4 -vf v360=fisheye:equirect:id_fov=360 output.mp4
```

The may idea is to use the display form the  Fisheye camera to be "split" as I can also use in the main APP in a 3th party apps like Home Assistant ... 

I try to use the GO2RTC adding a stream as this in order to firts try/test rotating the image from the camera, but without success for now 

```
ffmpeg:rtsp://admin:Mypassword@192.168.1.xxx:554/av_stream/ch0#video=h264#rotate=90
```

Can you please let me know if I can play this kind of filters or even if I can rotate de image as your information in the site applied to my fish eye Camera? 

```
  # [RTSP] video with rotation, should be transcoded, so select H264
  rotate: ffmpeg:rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0#video=h264#rotate=90
```

Thank you for your support and best regards

**Comment by AlexxIT** [comment]
Do you have a regular RTSP stream in go2rtc working without FFmpeg source?

**Comment by nunokaneco** [comment]
> Do you have a regular RTSP stream in go2rtc working without FFmpeg source?

Yes I have the RTSP stream is working great

**Comment by nunokaneco** [comment]
> Do you have a regular RTSP stream in go2rtc working without FFmpeg source?

Hello @AlexxIT  I successfully added and rotated the 

´´´ffmpeg:rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0#video=h264#rotate=90 stream ´´´

I just need to adjust the link to my IP camera. Thank you 

Now once the link have some diferente characters to appling the FFmpeg filter like 

´´´-vf v360=fisheye:equirect:id_fov=360 output.mp4´´´

Can you please help me in order to get the possible correct link created in order to apply this FFmpeg filter? 

Thank you

**Comment by AlexxIT** [comment]
Don't use rotate param. It's incompatible with other filters
```
streams:
  camera1: ffmpeg:rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0#video=h264#raw=-vf v360=fisheye:equirect:id_fov=360
```

**Comment by nunokaneco** [comment]
> Don't use rotate param. It's incompatible with other filters
> 
> ```
> streams:
>   camera1: ffmpeg:rtsp://rtsp:12345678@192.168.1.123/av_stream/ch0#video=h264#raw=-vf v360=fisheye:equirect:id_fov=360
> ```

Thank you for your reply 


I tested this links with success 

Show image directly without any change as fish eye
  ffmpeg:rtsp://admin:MyPassword@192.168.2.XXX:554/h264Preview_01_main#video=h264

Show image rotated 90º as fish eye
  ffmpeg:rtsp://admin:MyPassword@192.168.2.XXX:554/h264Preview_01_main#video=h264#rotate=90
  
  I try to use the link adapted as you mentioned in the last post without the rotate "filter"
streams:
  ffmpeg:rtsp://admin:MyPassword@192.168.2.XXX:554/h264Preview_01_main#video=h264#raw=-vf v360=fisheye:equirect:id_fov=360  
  
But when I try to use this link I'm receiving a error msg 

![image](https://github.com/AlexxIT/go2rtc/assets/33290686/87b27947-fae2-4378-acec-4243759a9349)

I also try to adapting the Link to in order to test
  ffmpeg:rtsp://admin:MyPassword@192.168.2.XXX:554/h264Preview_01_main#video=h264#raw=-vf 
  
  It appears that I can't load the "filter" -vf  ... The same msg appears with the error 
  
![image](https://github.com/AlexxIT/go2rtc/assets/33290686/5c097e86-eed7-4654-8573-1cb24ee860e7)

Any suggestion to solve this issue?

Thank you

**Comment by AlexxIT** [comment]
You need increase log level and check logs

**Comment by nunokaneco** [comment]
> You needs to increase log level and check logs

Just use this or other way to get this logs ? What kind of logs do you need ? Thank you 
´´´
log:
  level: info  # default level
  api: trace
  exec: debug
  ngrok: info
  rtsp: warn
  streams: error
  webrtc: fatal
  ´´´

**Comment by nxarmada** [comment]
I hate to add to the issue here but it is related.  When I attempt the below ffmpeg process crashes 

`ffmpeg:rtsp://root:pass@10.0.200.23/axis-media/media.amp#raw=-vf v360=fisheye:output=flat:w=1920:h=1080:yaw=56:pitch=20:roll=-105`

When I add the camera with the following the camera works.

`rtsp://root:pass@10.0.200.23/axis-media/media.amp`

**Comment by nunokaneco** [comment]
> You needs to increase log level and check logs



> You needs to increase log level and check logs

Hello @AlexxIT 

Regarding the log Level can you please let me know what level do you need in order to check this issue ? 

By the way This Log Level configurations is to be configured in the config.ymal file? 

https://github.com/AlexxIT/go2rtc#module-log

Thank you for your support and best regards
