### ISSUE TITLE
HomeKit Restreaming -> AKA homekit device

### ISSUE THREAD

**Issue by cybertza** [AlexxIT/go2rtc#453]
Hi Good work!

Whats the pipeline look like to have go2rtc function like a homekit bridge?

I am currently using frigate and the speed between frigate -> HA -> Apple tv and Scrypted -> Apple tv is not even in the same century, so would like to leverage off this out of the frigate instance directly since thats on a different box as my HASS.

**Comment by AlexxIT** [comment]
Go2rtc haven't support output to HomeKit yet. You need to search another software for this task.

**Comment by cybertza** [comment]
Hi, thanks I am aware it doesn’t support it yet, and I have found other software “scrypted” that does it.

I was asking if it’s in the pipeline and what the expected time for it is, and if there is help needed with it.

**Comment by kusold** [comment]
@AlexxIT Did 1.7.0 complete this ticket? It looks like HomeKit is now an output.

**Comment by AlexxIT** [comment]
Yes. It can be closes

**Comment by cybertza** [comment]
https://github.com/AlexxIT/go2rtc#module-homekit
is the documentation
