### ISSUE TITLE
USB Capture card (Audio)

### ISSUE THREAD

**Issue by Moncortec** [AlexxIT/go2rtc#454]
Hi, would be possible implement enable audio for this?

I use HDMI encoder with, works perfect, video + audio, 0 delay.

USB works fine only video, best quality image, but without audio.

https://www.amazon.com/Plugable-HDMI-Video-Capture-Card/dp/B0BVGQQ2JP?ref_=ast_sto_dp

Please this software is great!!! 
In the future implement this feature.

**Comment by AlexxIT** [comment]
You can do anything with exec source and FFmpeg. Check some closed issues.
Go2rtc just haven't any helpers for autodetect audio on your Linux server.

**Comment by Moncortec** [comment]
I don't understand much, but I can make inside go2rtc this?

**Comment by Moncortec** [comment]
How can add audio format??
ffmpeg:-#input=-f v4l2 -input_format mjpeg -video_size 1280x960 -i /dev/video0#video=copy

**Comment by dbuezas** [comment]
some examples (not necessarily very good ones but they do work) in #403

**Comment by AlexxIT** [comment]
ALSA audio supported https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
