### ISSUE TITLE
MSE does not work with the MSE player

### ISSUE THREAD

**Issue by mainmaster** [AlexxIT/go2rtc#458]
Example
https://codesandbox.io/s/intelligent-breeze-8wsu0

websocket waits for a message
{"type":"mse","value":"avc1.640029,avc1.64002A,avc1.640033,mp4a.40.2,mp4a.40.5,flac,opus"}
instead of immediately starting to send data

**Comment by AlexxIT** [comment]
Flussonic player can work only with Flussonic server.
MSE cannot be a standard because there must be a codec exchange.
There is no standard for exchanging MSE codecs.
