### ISSUE TITLE
ffmpeg.go calls for video flag instead of audio - Beta 6

### ISSUE THREAD

**Issue by wvdeadhead** [AlexxIT/go2rtc#46]
Go2RTC Beta 6

If using the following RTSP stream to scale a 4k camera to 1080p and copy the AAC audio track:

ffmpeg:rtsp://User:Pass@1.2.3.4:554/cam/realmonitor?channel=1&subtype=0#raw=-s hd1080#video=h264#audio=copy

The copy audio flag instead tries to copy the video.  Line 123 of ffmpeg.go states the following instead of -codec:a copy:

```
			for _, audio := range query["audio"] {
				if audio == "copy" {
					s += " -codec:v copy"
				} else {
					s += " " + tpl[audio]
				}
			}
```

This causes the following error:  "couldn't find the matching tracks"

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-beta.8
