### ISSUE TITLE
Error "cannot unmarshal !str 'roborock...' into struct{}" when trying to setup Roborock camera

### ISSUE THREAD

**Issue by Heisenberg2980** [AlexxIT/go2rtc#465]
After following the steps from https://github.com/AlexxIT/go2rtc#source-roborock, in the last step "Copy roborock://... source for your vacuum and paste it to go2rtc.yaml config" this error is displayed:

![image](https://github.com/AlexxIT/go2rtc/assets/58039006/73809b86-a49a-421f-910c-8d7f02f21c2a)

**Comment by AlexxIT** [comment]
```yaml
streams:
  myrobot1: roborock://...
```

**Comment by Heisenberg2980** [comment]
Thank you @AlexxIT for the quick response, and it works!!
