### ISSUE TITLE
Is there any known cheap camera compatible with ONVIF Profile T?

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#467]
Sorry, I'm not sure if there is a better place to make this question, but:

I wonder if someone knows any cheap camera which I can buy on AliExpress that supports 2-way audio with ONVIF Profile T (integrates with go2rtc), except for Hikvision and Dahua because they are usually very expensive.

**Comment by conorlap** [comment]
I don't think it's ONVIF Profile T but 2-way audio works on this and it's relatively affordable!

https://www.amazon.co.uk/TP-Link-Security-Rotational-Required-Storage/dp/B08ZNTM1X1?th=1

https://github.com/AlexxIT/go2rtc#source-tapo

**Comment by felipecrs** [comment]
Wow, that's cheap indeed. Thank you!

**Comment by felipecrs** [comment]
I found this one as well:

https://pt.aliexpress.com/item/1005005059763135.html

It seems decently good, the description claims support for ONVIF Profile T, and it's very cheap.

**Comment by ferbulous** [comment]
> I found this one as well:
> 
> https://pt.aliexpress.com/item/1005005059763135.html
> 
> It seems decently good, the description claims support for ONVIF Profile T, and it's very cheap.

Have you tried it? Looks interesting with dual camera

**Comment by felipecrs** [comment]
Actually I don't need a camera like that, I need an external camera. I just wanted to share my finding :)

**Comment by felipecrs** [comment]
I found another camera, which I think may be compatible: https://pt.aliexpress.com/item/1005005933441615.html

The reason why I think it will be compatible is because:

1. It says it's plug and play with Hikvision NVRs, including 2 way audio support
2. There is no app for this camera, so how else can 2 way audio work if not by ISAPI or ONVIF Profile T?

**Comment by ferbulous** [comment]
> I found another camera, which I think may be compatible: https://pt.aliexpress.com/item/1005005933441615.html
> 
> The reason why I think it will be compatible is because:
> 
> 1. It says it's plug and play with Hikvision NVRs, including 2 way audio support
> 2. There is no app for this camera, so how else can 2 way audio work if not by ISAPI or ONVIF Profile T?

Is that on promo? Packs some nice feature with that price

**Comment by felipecrs** [comment]
You can actually find more listings of the same camera if you search. I did not search very thoroughly.

**Comment by felipecrs** [comment]
Guys, forget about ONVIF Profile T. The best thing ever was support for 2-way audio over dvrip. This works for ANY camera that uses the ICSee app. I have this one, for example:

https://aliexpress.com/item/1005005731238053.html

But there are several other SUPER CHEAP chinese cameras compatible with ICSee which works with go2rtc 2-way audio flawlessly.

Also do a favor to yourself and never buy a Tuya-based camera btw. :D

**Comment by ferbulous** [comment]
> Guys, forget about ONVIF Profile T. The best thing ever was support for 2-way audio over dvrip. This works for ANY camera that uses the ICSee app. I have this one, for example:
> 
> https://aliexpress.com/item/1005005731238053.html
> 
> But there are several other SUPER CHEAP chinese cameras compatible with ICSee which works with go2rtc 2-way audio flawlessly.
> 
> Also do a favor to yourself and never buy a Tuya-based camera btw. :D

Thanks, that's indeed a very nice price
What exactly the right keyword if need to search for more compatible cameras with ICSee?
2-way audio over dvrip?

**Comment by felipecrs** [comment]
I don't know too. But normally they have the ICSee icon in some of the photos.

**Comment by felipecrs** [comment]
By the way I don't recommend that camera at all. I was just using as a proof that 2-way audio works.

It has two main issues:

1. H265 only
2. The 2 cameras are not different streams. They are actually combined in a 16:18 stream. Very difficult to make it work nice with Frigate detection for example.

**Comment by ferbulous** [comment]
> By the way I don't recommend that camera at all. I was just using as a proof that 2-way audio works.
> 
> It has two main issues:
> 
> 1. H265 only
> 2. The 2 cameras are not different streams. They are actually combined in a 16:18 stream. Very difficult to make it work nice with Frigate detection for example. That is even why I reported this: [Cannot use hardware acceleration to split stream #578](https://github.com/AlexxIT/go2rtc/issues/578)

Thanks, I was wondering how the dual streams work or how to handle them with frigate
Some of their cameras have some pretty cool feature like the 2 way video and audio with the baby camera.
Do any of their camera models still use H264 or they've completely migrated to H265?

**Comment by felipecrs** [comment]
Sorry bro, I really searched no further than this one, so I don't know.

I think there are several manufacturers making cameras for ICSee. Maybe there are better ones. 

But I would be surprised if there were no H264 ones.
