### ISSUE TITLE
Unifi AI 360

### ISSUE THREAD

**Issue by ab-tools** [AlexxIT/go2rtc#468]
Trying to get the [Unifi AI 360](https://eu.store.ui.com/eu/en/collections/unifi-camera-security-dome-360/products/uvc-ai-360) camera fully working with go2rtc including 2-way-audio.

I've got that far that video is fully working, but no audio (no direction) yet.

That's what I have done so far:

1. I enabled the medium quality RTSPS stream in the camera advanced settings:
![image](https://github.com/AlexxIT/go2rtc/assets/1347603/65e0f055-94aa-4b1d-939c-b109904209b7)
2. Then I added the stream to the configuration. This is done with `rtspx` instead of `rtsps` and without `?enableSrtp` as suggested in the readme:
```
streams:
  unifi_ai_360: rtspx://192.168.16.1:7441/7migbj9afSiYF7uP
```

I can now access the camera video successfully with this URL in my web browser:
http://localhost:1984/webrtc.html?src=unifi_ai_360&media=video+audio+microphone

The result is that I can see the video stream without problems, but I do not hear audio, not on the camera speaker and also not the other way round in the browser when I speak towards the camera microphone. Tested both with Chrome and Firefox browsers.

For reference, that's the info output from the camera:
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsps://192.168.16.1:7441/7migbj9afSiYF7uP/",
      "remote_addr": "192.168.16.1:7441",
      "user_agent": "go2rtc/1.5.0",
      "medias": [
        "audio, recvonly, MPEG4-GENERIC/48000",
        "audio, recvonly, OPUS/48000/2",
        "video, recvonly, H.264 Main 4.0"
      ],
      "receivers": [
        "97 H264, bytes=106243150, senders=1",
        "96 OPUS/48000/2, bytes=8855322, senders=1"
      ],
      "recv": 116166832
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 192.168.16.128:51429",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264",
        "audio, recvonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, TELEPHONE-EVENT/8000",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, TELEPHONE-EVENT/8000, L16"
      ],
      "receivers": [
        "109 OPUS/48000/2, bytes=620292, senders=0"
      ],
      "senders": [
        "126 H264, bytes=15352090, receivers=1",
        "109 OPUS/48000/2, bytes=1184960, receivers=1"
      ],
      "recv": 701460,
      "send": 16828115
    }
  ]
}
```

Did I miss any additional configuration entry to enable audio?

Thanks in advance
Andreas

**Comment by AlexxIT** [comment]
Strange situation. Looks like go2rtc choose opus codec. Don't know why you can't hear it.

Also I can see opus receiver for consumer. It shouldn't happen.

You can try MSE. Maybe AAC audio codec will work for you.

You camera doesn't support open two way audio standard. So two way audio won't work for you any way.
