### ISSUE TITLE
Need help adding JS (for video.muted = false) script

### ISSUE THREAD

**Issue by Cr4z33** [AlexxIT/go2rtc#472]
Not really a go2rtc, but I really love it and need to fix an annoying issue with my video doorbell stream always muted when loading into Home Assistant.

Someone on YouTube said:

_**It's possible to automaticly unmute by adding this lines to the webrtc.html**_
`var video = document.getElementById("video");
video.oncanplaythrough = function () {
    video.muted = false;
}`

As far as I know there's no webrtc.html file generated from the go2rtc HA Supervisor integration right? 🤔

**Comment by AlexxIT** [comment]
The default sound in the video is controlled by complex algorithms and is highly dependent on the browser.

Browsers deal with spammers and advertisers.

It all depends on how you opened the page with the video, how it has an embedded video, how often you visit it and so on, what version of your browser and on what OS.

https://github.com/AlexxIT/go2rtc/blob/ba68bcb89e82672986710fa7e7ce6d5cd55d68ad/www/video-rtc.js#L158-L165

**Comment by Cr4z33** [comment]
Thanks @AlexxIT for clearing it out, but forgive me if I keep asking... 😅

Is the `video-rtc.js` file already applied by default or do I have to add anything to enable it?

**Comment by AlexxIT** [comment]
`video-rtc.js` is used in the `stream.html`

**Comment by Cr4z33** [comment]
Oh OK and would there be a way to have a JS file for WebRTC stream too?

I need WebRTC for bi-directional video doorbell communication. :)

**Comment by AlexxIT** [comment]
You can just try to add play code to `webrtc.html` file

**Comment by Cr4z33** [comment]
Oh OK I thought there was no webrtc.html file in your repo?

**Comment by lovelyelfpop** [comment]
How to modify webrtc.html of ha integration
