### ISSUE TITLE
Config tab broken in master

### ISSUE THREAD

**Issue by dbuezas** [AlexxIT/go2rtc#478]
<img width="835" alt="image" src="https://github.com/AlexxIT/go2rtc/assets/777196/5c1f11bd-a2ac-4aba-8ab6-bbeade211275">
It looks like the byte array is loaded into the text box instead of the string

**Comment by dbuezas** [comment]
The first bad commit is 888159d2b684dc90b6c36a952c0bee3f4c2a067e

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
