### ISSUE TITLE
Working with snapshots

### ISSUE THREAD

**Issue by lavrenkov-sketch** [AlexxIT/go2rtc#482]
Good afternoon, I want to thank you for such a wonderful application and ask: could you explain or teach how to take pictures with a minimum time delay?
There is a Hikvision camera from which you need to take instant snapshots.
It sends data via RTSP protocol. It is possible to use hardware acceleration based on cuda or intel cpu. 

When I get snapshots I get `DBG [mjpeg] transcoding time=119.221632ms`. Can this be accelerated? And why does transcoding happen, is it possible to take a RAW frame to speed up the process? Is it possible to somehow say not to stop the stream while no clients so as not to establish a connection again

**Comment by HausnerR** [comment]
Hey, just wanted to start similar discussion!

I have RTSP h264 input stream. I need to make camera snapshots at around 2fps.
It looks like go2rtc waits for i-frame every time snapshot is requested and then converts it to MJPEG to serve JPEG.

On go2rtc 1.2.0 I had something like this:
```
ffmpeg:rtsp_hd.entrance#video=copy#audio=copy#video=mjpeg#raw=-q:v 2 -r 2
```
It add transcoding at 2fps to mjpeg and add another stream to RTSP. That way I was connected to h264 stream for recording and when I wanted snapshot - go2rtc used mjpeg stream to serve it to me.

It does not work now in 1.5.0. Stream works but again generating snapshots is really slow. In my case max I'm able to make is one frame per 2 seconds.

Maybe someone have idea how to make it/improve it.

**Comment by AlexxIT** [comment]
@lavrenkov-sketch you can get raw frame in mp4/h264/h265 format

@HausnerR you can setup separate stream with only one codec `video=mjpeg` without `video=copy`

**Comment by HausnerR** [comment]
@AlexxIT yes, but then I need to be constantly connected to two streams. Can I somehow force stream to generate output without consumers?

**Comment by AlexxIT** [comment]
You can point one go2rtc ffmpeg source to another go2rtc stream. So it will be two streams, but only one connection to camera

**Comment by HausnerR** [comment]
Yes, I have it that way, I mean that I need to connect to MJPEG stream separately to keep it generating JPEGs.

**Comment by AlexxIT** [comment]
Please let me know if the problem is relevant

**Comment by mmerickel** [comment]
@HausnerR did you ever come up with a solution for this latency issue? I'm running into this myself where the snapshot is waiting for keyframes on an H264 RTSP stream and hence receiving a significant amount of latency (often 1.5 seconds or so).

**Comment by AlexxIT** [comment]
@mmerickel you can try to setup another stream with same source only for snapshots.

**Comment by mmerickel** [comment]
@AlexxIT I just saw this after opening https://github.com/AlexxIT/go2rtc/issues/1736 - apologies but I guess we can move the conversation over there to separate it. I think I'm not clear on what parameters I should configure on that second stream if you could offer any more detail on that. Thank you!
