### ISSUE TITLE
Please tell me how to still receive video with sound in telegram ??? Can not understand??? Help???

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#483]
Please tell me how to still receive video with sound in telegram ??? Can not understand??? Help???

**Comment by AlexxIT** [comment]
#446

**Comment by TokarevSergey** [comment]
> #446

Well, there is no instruction on how to set up sending video with audio to telegrams. Help. Answer if it is possible then how? If not, then simply answer that it is not possible. After all, it worked before.

**Comment by TokarevSergey** [comment]
Everything worked before. Why is it not working now and how to fix it?????

**Comment by TokarevSergey** [comment]
Please explain to me.
