### ISSUE TITLE
Sound on Tapo Cameras (C200)

### ISSUE THREAD

**Issue by dsimop** [AlexxIT/go2rtc#486]
[BUG]
When using the `rtsp` url of a Tapo Camera (i.e. C200) in `(mode: webrtc)`, the sound sounds chopped/crackling.
_Respective Format_:  
**url: rtsp://admin:password@192.168.1.123**

On the other hand, when replacing it with the `tapo` protocol, the sound is transmitted without any problems.
_Respective Format_: 
**url: tapo://admin:MD5-PASSWORD-HASH@192.168.1.123**

Both were tested using the `custom:webrtc-camera` card directly in HA, using the go2rtc 1.5.0 version.
The camera uses the PCM ALAW (alaw) audio codec.

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
