### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by pcmv-dev** [AlexxIT/go2rtc#50]
So I have it all set up and everything is working including external access by port forwarding (TCP 8555 port) and so I have a security question... is this safe and what are potential risks?

Now I read through the documents and found nothing on how I could access cameras via HTTP url. I had to find it in the posts from users in the Home Assistant forums. 
`http://IP:1984/webrtc.html?src=CAM` <--- These urls should be documented or if it is then it's not apperent

**Comment by AlexxIT** [comment]
Have you read Security section from readme?

**Comment by pcmv-dev** [comment]
I have. "external access to WebRTC TCP port is not a problem" But was just curious if this would in anyway expose the camera urls, but if its just encrypted media data then there is little or no concern? Sorry I am not very knowledgeable in the network side of it.

**Comment by AlexxIT** [comment]
You can only access the cameras from the web through HTTP API port (1984 by default). Media encryption keys also transmitted through this port.
You shouldn't open the API port to the external network without any additional authorization.
Hassio users should not be worried about external access to this port because they using Hass Ingress feature.

**Comment by pcmv-dev** [comment]
Oh ok understood thanks

**Comment by shifuoogway** [comment]
Thanks for the development. It's working great for me in fronting a few RTSP streams, transcoding them to the required format then making them available for use via RTSP. I note that the RTSP in Go2RTC is coded for TCP. Is it possible to specify UDP for RTSP streams? This will be helpful when transmitting multiple streams over a noisy network link. TCP retries can cause delays to one stream but not another. I note that WebRTC uses UDP to ameliorate this problem. .

**Comment by AlexxIT** [comment]
UDP have some cons:

It may have problems with connection in some network configuration. And very few people will be able to understand the reason and fix it.

It may lose or mix up the packets. And the user may miss a few seconds of video.

I have added TCP for WebRTC for reliable external access.

**Comment by shifuoogway** [comment]
I guess it's really horses for courses. They are just different tools. Packet losses is a natural Ethernet characteristic, the difference is that whereas TCP retries - therefore can add delay, UDP discards to maintain currency. Packet sequencing is not so much an issue for small networks.  TCP probably best for say NVR but UDP likely better for live CCTV vision.

**Comment by AlexxIT** [comment]
I think there are no more questions about this issue.
