### ISSUE TITLE
does go2rtc not support certain symbols when used in passwords for urls?

### ISSUE THREAD

**Issue by thewan056** [AlexxIT/go2rtc#502]
Hi I am trying to use go2rtc in Frigate in HAOS. When attempting to follow the instructions in Frigate Docs for go2rtc, nothing seems to work. Going into the logs for go2rtc I keep seeing `error="parse` and `invalid URL escape` followed by a section of my password that has a symbol in it. I used a password manager to generate it and as far as I can see in your documentation there is no mention or recommendation to not use symbols in passwords. 
Anyway changing the password now would be a lot of work seeing as I have to change it in multiple places and I would like to avoid that if it is possible.

The same URL worked fine when not using go2rtc in frigate, as in direct ffmpeg. It also worked fine when I validated it in VLC.
I have also been using the same URL and password for a different NVR before this without issues for years. So far I have only encountered this problem in go2rtc. I hope it can be fixed instead of requiring me to change my passwords everywhere and for every camera I own.

**Comment by AlexxIT** [comment]
Maybe golang has more strict URL validator than other software. You can manually encode special symbols:
https://en.wikipedia.org/wiki/URL_encoding
https://www.urlencoder.org/

**Comment by thewan056** [comment]
Yeah this works fine. I suggest adding this to your documentation/troubleshooting/FAQ. Thanks alot.
