### ISSUE TITLE
Unable to use two way audio hikvision CCTV

### ISSUE THREAD

**Issue by hannan1987** [AlexxIT/go2rtc#507]
I have configure hikvision DS-2DE2C400MW-DE(S7) inside go2rtc but unable to use two way audio.

The cctv support ISAPI for two way audio.

Here is the output from info page
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.0.105:554/Streaming/Channels/101/",
      "remote_addr": "192.168.0.105:554",
      "user_agent": "go2rtc/1.5.0",
      "medias": [
        "video, recvonly, H.264 Main 5.0"
      ],
      "receivers": [
        "96 H264, bytes=682548, senders=1"
      ],
      "recv": 688884
    },
    {
      "url": "isapi://admin:password123@192.168.0.105:80/"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host 192.168.0.167:53799",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16"
      ],
      "senders": [
        "102 H264, bytes=682548, receivers=1"
      ],
      "send": 690139
    }
  ]
}

**Comment by NickM-27** [comment]
how are you requesting two way talk? it does not look like you are trying to do two way talk correctly

**Comment by hannan1987** [comment]
Here are my configuration in go2rtc

```
streams:
    hikvision1:
    - rtsp://admin:password123@192.168.0.105:554/Streaming/Channels/101
    - isapi://admin:password123@192.168.0.105:80/

**Comment by NickM-27** [comment]
Right, how are you trying to use two way audio though

**Comment by hannan1987** [comment]
Im trying to use two way audio using webrtc.

![audio 3](https://github.com/AlexxIT/go2rtc/assets/119158038/13dffd43-f4ad-4978-bf07-8ad00fa36f8f)

**Comment by NickM-27** [comment]
To use two way audio in webrtc you need to specifically request it, it is not enabled in the defaults streams view.

**Comment by hannan1987** [comment]
Thank you. It is working now.

Need to add backchannel=0 ro reduce hissing sound.

Here is my final configuration 

```
streams:
    hikvision1:
    - rtsp://admin:password123@192.168.0.105:554/Streaming/Channels/101#backchannel=0
    - isapi://admin:password123@192.168.0.105:80/

**Comment by AlexxIT** [comment]
Looks like the problem is solved

**Comment by projectdimpreza** [comment]
> Thank you. It is working now.
> 
> Need to add backchannel=0 to reduce hissing sound.
> 
> Here is my final configuration
> 
> ```
> streams:
>     hikvision1:
>     - rtsp://admin:password123@192.168.0.105:554/Streaming/Channels/101#backchannel=0
>     - isapi://admin:password123@192.168.0.105:80/ 
> ```

How did you manage to make it work? I have the same settings but i only got live feed and audio to work.. but im not hearing my android phone mic audio from the camera speaker.. by the way my camera dont have speaker.. its behind a HIKVISION DVR that has a speaker plug in to it..
