### ISSUE TITLE
Support for ffmpeg seeking

### ISSUE THREAD

**Issue by vdecine** [AlexxIT/go2rtc#509]
Passing the ss parameter (http://ffmpeg.org/ffmpeg.html#Main-options) via url does not seem to work.
I tried to add this to the config:

```
ffmpeg:
  skip30: "-ss 00:00:20"
```

and then created a stream like this: ffmpeg:test.mp4#skip30
Maybe I am missing something, but it seems that using this parameter is not supported.

**Comment by AlexxIT** [comment]
In this release you can use `ffmpeg:test.mp4#raw=-ss 00:00:20`
In next release you will be able to use templates `ffmpeg:test.mp4#raw=skip30`

**Comment by vdecine** [comment]
Thanks for the quick reply, unfortunatly this results in "ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:177 > error="exec: exit status 1" while ffmpeg:test.mp4 works fine. Is there somekind of verbose flag to see what is going on?

**Comment by AlexxIT** [comment]
log exec trace. Read about logging in the readme

**Comment by AlexxIT** [comment]
Thanks. Will be fixed

**Comment by vdecine** [comment]
This problem persists in 1.6 for me. I create two streams in the config file like this:

```
streams:
  plain: ffmpeg:test.mp4
  skip: ffmpeg:test.mp4#raw=-ss 00:00:20
```

The first one works fine the second one does not, resulting in this log output (repeats over and over):

```
13:36:56.541 DBG [exec] run url="exec:ffmpeg -hide_banner -v error -re -i test.mp4 -ss 00:00:20 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
13:36:56.645 DBG [exec] run launch=104.8698ms
13:36:56.646 DBG [streams] start producer url=ffmpeg:test.mp4#raw=-ss 00:00:20
13:37:11.646 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:159 > error="read tcp 127.0.0.1:8554->127.0.0.1:56698: i/o timeout" url="ffmpeg:test.mp4#raw=-ss 00:00:20
```



However running 

`ffmpeg -hide_banner -v error -re -i test.mp4 -ss 00:00:20 -c copy seeked.mp4`

on the command line results in a file (seeked.mp3) start starts at the 20th second of the test.mp4 file.

**Comment by AlexxIT** [comment]
Well. I don't see any difference in commands. So problem in something else...
