### ISSUE TITLE
Hass to go2rtc support

### ISSUE THREAD

**Issue by calisro** [AlexxIT/go2rtc#51]
Last release we can now reference internal HASS entity_id feeds like this which is great (thank-you):

```
streams:
  "camera.kitchen_2": 
    - "{input}"
    - ffmpeg:{input}#audio=opus
```

This brings a bit of a confusion to the UI and documentation though. We can access that camera via the webrtc link in the UI (but only while its actually also being viewed in HASS):

`https://xxxxx.org/go2rtc/webrtc.html?src=camera.kitchen_display`

^ you can't do that before viewing that camera in HASS directly to initialize it within go2rtc.  Which also means these won't work  in HASS:

```
rtsp://xxxxx.org:8554/camera.kitchen_2
```

We get this:
```
18:56:48.532 DBG [rtsp] new consumer stream=camera.kitchen_2
18:56:48.637 WRN [streams] start error="malformed MIME header: missing colon: \"\\xb9G%i7\\x9c@\\x16\\xaa\\x9b\\x9e\\x95G^r\\ax\\xa1ϥji\\xb2\\xcd!\\x15f@|\\xfdȥ\\xe4\\x05vb\\xfd\\xa1Tt[,\"" 
```

I'm not sure if this is supposed to work.  But my use case is I would like to expose these 'dynamic url' cameras or other integration cameras via entitiy_id in the go2rtc.yaml.  Like this:

```
  "camera.kitchen_2":
    - "{input}"
    - ffmpeg:{input}#audio=opus
  kitchen_2_noaudio:
    - rtsp://127.0.0.1:8554/camera.kitchen_2?video
```

and also be able to reference those cameras as rtsp streams outside of HA..

**Comment by AlexxIT** [comment]
Hass doesn't have API for getting actual link to stream. It is not possible to do this at this moment. #80
