### ISSUE TITLE
Extra stream / MSE error in go2rtc when using "Name" button to select all streams.

### ISSUE THREAD

**Issue by sleepyjay890** [AlexxIT/go2rtc#514]
I found I had 5 camera streams but was getting 6 streams when selecting "Name" box for all streams, then clicking "stream" button. The 1st box always says "mse:stream not found" on top left, and "error"" on top right.
The temporary fix to display the correct number of streams, and none with errors, is to select all names individually then press "stream". If you use the top "Name" select buttom to select all, then press "stream"  you get the error.
I would like to see some stream information overlayed on each video stream to identify easily which stream/codec etc is causing the problem.

1. Screenshot of mse error and extra 1st channel (the one with error) when all "Name" select button used.
<img width="723" alt="pl1" src="https://github.com/AlexxIT/go2rtc/assets/79058047/f519f10f-1602-4dcf-8312-af872619062f">

2. Screenshot of "name" select screen before "stream" button pressed as per 1.
<img width="293" alt="pl2" src="https://github.com/AlexxIT/go2rtc/assets/79058047/12165040-540d-4510-a1e8-a27a0ab45ae9">

3. Screenshot of only 5 correct video streams about to start.  All play fine, i've disabled audio tracks on 2 cameras I couldnt disable audio internally.
<img width="708" alt="pl3" src="https://github.com/AlexxIT/go2rtc/assets/79058047/72bebd37-6f55-48a7-96a7-97b2890eded2">

4.  Screenshot of all names selected individually without using "Name" button" as per 3.
<img width="296" alt="pl4" src="https://github.com/AlexxIT/go2rtc/assets/79058047/697e6db7-aaf7-4297-a1cb-e7e049f19652">

**Comment by AlexxIT** [comment]
This is already fixed. Will be in next release https://github.com/AlexxIT/go2rtc/pull/466

**Comment by sleepyjay890** [comment]
> Thanks. This is already fixed. Will be in next release #466
Thanks heaps, I'm learning some Linux pretty fast now and hoping to start a home automation business locally soon. Playing with Sonoff/Ewelink/Swann NVR8580 and cams, plus Fronius solar inverter, Tesla Powerwall, and another inverter I think SMA brand 8 years old now. Swann/Panoeagle/TPlink cameras. Interesting mix. Still to fine tune codecs and understand ffmpeg mostly now.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
