### ISSUE TITLE
After update, all my camera feeds disappeared. 

### ISSUE THREAD

**Issue by chester512** [AlexxIT/go2rtc#518]
I have go2rtc running in a docker on unraid.  I have home assistant running as a VM on the same unraid server.  I have been using go2rtc  to stream my cctv cameras to my HA dashbaord (via webrtc).  After updating go2rtc this morning, all of my stream are not working and giving me an error "mse: stream not found".  Any suggestions as to where to start.

**Comment by AlexxIT** [comment]
Old WebRTC integration doesn't support new go2rtc version
