### ISSUE TITLE
Adding UV4L WebRTC source

### ISSUE THREAD

**Issue by bdunn44** [AlexxIT/go2rtc#519]
I am attempting to add a WebRTC stream from UV4L installed on my Raspberry Pi as a go2rtc source. I've confirmed everything works (MJPEG, JPEG, H264, and WebRTC streams) via the UV4L web interface. I'm using this configuration:
```
streams:
  my-cam: webrtc:ws://rpi-address:8080/stream/webrtc
```

...but am getting this error:

```
wrong answer: webrtc/offer
```

I imagine this has something to do with the websocket coordination that occurs to setup the connection but I'm no expert. Is anyone able to give me pointers on how to debug this?

**Comment by AlexxIT** [comment]
Websocket format supported only for go2rtc as WebRTC server.

**Comment by bdunn44** [comment]
I'm shocked by the response time - thank you!

This makes sense after re-reading the documentation. I misinterpreted. Thanks again for the quick guidance
