### ISSUE TITLE
Add support pcm_s16le audio

### ISSUE THREAD

**Issue by gtxaspec** [AlexxIT/go2rtc#523]
in go2rtc, currently supported is pcm_s16be, can support for pcm_s16le included as well?  this would help compatability with certain wyze cameras which use pcm_s16le

**Comment by AlexxIT** [comment]
Can you provide more info how you pass this data to go2rtc?
I'm not sure that `pcm_s16be` was right choose. And maybe `pcm_s16le` more common standard.

**Comment by gtxaspec** [comment]
we are capturing the audio from alsa which is in pcm_s16le format, then we:

 `exec:ffmpeg -hide_banner -f alsa -ac 1 -i hw:0,0 -c:a copy f rtsp {output}` to go2rtc`

 ...obviously s16le doesn't work at the moment but this is how we would do it.

**Comment by AlexxIT** [comment]
Can you enable trace logs for rtsp module. I need to check SDP part from FFmpeg.

**Comment by AlexxIT** [comment]
FFmpeg + RTSP + pcm_s16le has a problem. FFmpeg doesn't pass info about codec name and params...
I can see you set only one channel for your camera. Please check what the default sample rate:
```
ffmpeg -hide_banner -f alsa -ac 1 -i hw:0,0 -c:a copy -f null -
```

**Comment by gtxaspec** [comment]
@AlexxIT 

```
[root@WCV3:~]# ffmpeg -hide_banner -f alsa -ac 1 -i hw:0,0 -c:a copy -f null -
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, alsa, from 'hw:0,0':
  Duration: N/A, start: 1689415357.800710, bitrate: 256 kb/s
  Stream #0:0: Audio: pcm_s16le, 16000 Hz, mono, s16, 256 kb/s
[NULL @ 0x775fc040] Requested output format 'null' is not a suitable output format
pipe:: Invalid argument
[root@WCV3:~]# 
```

**Comment by AlexxIT** [comment]
OK. Looks like I can detect codec based on bitrate. It always constant for specific sample rate + channels settings.

**Comment by AlexxIT** [comment]
OK. You can try latest master version. Do you need binary or you can build it yourself?

**Comment by gtxaspec** [comment]
If you can provide mipsle binary I can test

**Comment by AlexxIT** [comment]
[go2rtc_linux_mipsel.zip](https://github.com/AlexxIT/go2rtc/files/12063801/go2rtc_linux_mipsel.zip)

**Comment by gtxaspec** [comment]
@AlexxIT confirmed working!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.1
