### ISSUE TITLE
autostart

### ISSUE THREAD

**Issue by Jumbo125** [AlexxIT/go2rtc#524]
hy
great work

i added some streams via webbrowser port 1984.
works great.

how can i save the streams and set the prgoram to autostart, if i restart my linux

**Comment by Jumbo125** [comment]
if i try to run the file with cronjob, it don't run in te background. 
i checked it with ps command

**Comment by AlexxIT** [comment]
Persistent streams must be added via config. For autostart feature I'm using docker. Otherwise you should use systemd or another linux stuff, I'm not familiar with.

**Comment by Jumbo125** [comment]
thank you
i do it with cron tab
it works
