### ISSUE TITLE
WebTorrent - domain

### ISSUE THREAD

**Issue by hoanglongutc** [AlexxIT/go2rtc#525]
Hi,
![image](https://github.com/AlexxIT/go2rtc/assets/35026043/b0cd6b6c-8fe6-4b65-baf7-0a375b270e77)
Can I change the domain name in this shared link?
Example: https://mydomain.xyz/go2rtc/#share=02SNtgjKXY&pwd=wznEQqznxW&media=video+audio
Thanks!

**Comment by AlexxIT** [comment]
Yes. This is single static html file:
https://github.com/AlexxIT/go2rtc/blob/master/website/index.html

**Comment by hoanglongutc** [comment]
Can you guide me in more detail, when I choose to share the default link taken by domain name: https://alexxit.github.io/go2rtc/#share=xxx&media=video+audio
how can i change by private domain: https://mydomain.xxx/go2rtc/#share=xxx&media=video+audio

![image](https://github.com/AlexxIT/go2rtc/assets/35026043/e1d00309-5578-44da-b944-552f92698547)

**Comment by AlexxIT** [comment]
Just change domain manually. From one to another.

**Comment by hoanglongutc** [comment]
> Just change domain manually. Fro

is there a way to set my domain as default and when creating the default share link according to my domain name and just copy and send

**Comment by hoanglongutc** [comment]
> Just change domain manually. From one to another.

May I ask a little more detail about security:
When I create a share link, where will this information be stored? Who has the authority to administer these links and how is security guaranteed?
Excuse me because I don't really understand this technology

**Comment by AlexxIT** [comment]
You need copy static files from www folder of project. Fix default url. And set custom static folder in go2rtc config.

**Comment by AlexxIT** [comment]
Dynamic link credentials stored in the app memory. Them cleared after go2rtc restart

**Comment by hoanglongutc** [comment]
> Fix default url. And set custom static folder in go2rtc config.
Can you send me step by step instructions for this part? Thanks a lot
