### ISSUE TITLE
Go2RTC WebUI Stream = Perfect / HAOS PictureGlance = White Screen

### ISSUE THREAD

**Issue by dredjohn21** [AlexxIT/go2rtc#527]
Apologies if this isn't the best place to ask the question:
Does anyone know why I get a white screen player when using the HAOS Picture Glance card, pointing to the WebRTC entity?  (I have no issues when playing the stream via the "stream" link off the go2rtc webUI page)

My HAOS steps:
1. Go2RTC (v1.60) added via add on in HAOS (latest version)
2. Under go2rtc streams I added my Ring Doorbell RTSP stream
```
streams:
  front_doorbell: rtsp://03cabcc9-ring-mqtt:8554/mystreamnumber_live
```
4. In devices I added a generic camera with a still image and URL to go2rtc URL
```
static image: http://homeassistant.local:8123{{ states.camera.front_door_snapshot.attributes.entity_picture }}
stream: rtsp://127.0.0.1:8554/front_doorbell
authentication: basic
frame rate: 20hz
checkboxes at bottom (e.g. verify SSL): all unchecked
```
5. On dashboard I added a lovelace picture glance card
```
camera_view: live
type: picture-glance
entities: []
title: Front Doorbell
camera_image: camera.front_door_snapshot
entity: camera.front_doorbell
```

When I tap on the camera static image from dashboard I get player with white screen and no video plays.  I have same issue on my MacBook and iPhone (using HA app).  

I have NO ISSUES when going to the add on page for go2rtc and tapping "stream" next to the camera commands.  The video loads quickly and I see the RTC logo in the top right corner.

I tried comparing the "info" details between the two and don't see any major differences.

This is the output from the "stream" link
STREAM FROM LINK
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://03cabcc9-ring-mqtt:8554/mystreamnumber_live",
      "remote_addr": "172.30.33.4:8554",
      "user_agent": "go2rtc/1.6.0",
      "medias": [
        "audio, recvonly, MPEG4-GENERIC/48000/2",
        "audio, recvonly, OPUS/48000/2",
        "video, recvonly, H.264 High 5.0"
      ],
      "receivers": [
        "98 H264, bytes=12093295, senders=1",
        "97 OPUS/48000/2, bytes=308594, senders=1",
        "96 MPEG4-GENERIC/48000/2, bytes=755636, senders=0"
      ],
      "recv": 13299221
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.1.28:55450 related :0",
      "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15",
      "medias": [
        "video, sendonly, H264, RTX, VP8, VP9, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, ISAC/16000, G722/8000, PCMU/8000, PCMA/8000, CN/16000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/16000, TELEPHONE-EVENT/8000, L16"
      ],
      "senders": [
        "96 H264, bytes=12093295, receivers=1",
        "111 OPUS/48000/2, bytes=308594, receivers=1"
      ],
      "send": 12559433
    }
  ]
}
```

This is the output from dashboard and lovelace card:
STREAM FROM CAMERA

```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://03cabcc9-ring-mqtt:8554/mystreamnumber_live",
      "remote_addr": "172.30.33.4:8554",
      "user_agent": "go2rtc/1.6.0",
      "medias": [
        "audio, recvonly, MPEG4-GENERIC/48000/2",
        "audio, recvonly, OPUS/48000/2",
        "video, recvonly, H.264 High 5.0"
      ],
      "receivers": [
        "98 H264, bytes=3189208, senders=1",
        "97 OPUS/48000/2, bytes=81033, senders=1"
      ],
      "recv": 3505400
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/Hass sync passive consumer",
      "remote_addr": "udp4 prflx 192.168.1.28:52397 related :0",
      "user_agent": "HomeAssistant/2023.7.2 aiohttp/3.8.4 Python/3.11",
      "medias": [
        "video, sendonly, H264, RTX, VP8, VP9, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, ISAC/16000, G722/8000, PCMU/8000, PCMA/8000, CN/16000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/16000, TELEPHONE-EVENT/8000, L16"
      ],
      "senders": [
        "96 H264, bytes=3189208, receivers=1",
        "111 OPUS/48000/2, bytes=81033, receivers=1"
      ],
      "send": 3096964
    }
  ]
}
```

Any ideas on how to resolve?  My goal is to have a static image on the dashboard so I don't trigger live recordings on my ring doorbell unnecessarily, and then when I tap to see the video playing.

**Comment by AlexxIT** [comment]
I don't have any ideas. Usually the screen is black or green. But I've never seen a white screen in case of problems

**Comment by dredjohn21** [comment]
Thanks for the response, @AlexxIT 

If you have a minute could you skim the setup approach I outlined.  Does it look like I did it right?  Maybe I messed up something and that's why I'm not seeing the right experience off the lovelace picture glance card - vs - using the stream link from the rtc web ui.

**Comment by AlexxIT** [comment]
Picture glance possible, but not recommended setup

**Comment by deezid** [comment]
I would love to use the picture entity card using go2rtc like it's possible using rtsptoweb - webrtc integration.
Last time I tried to have both go2rtc and rtsptpweb - webrtc installed it messed up everything because both 8554 and 8555 ports were blocked. 

Just using go2rtc works fantastic and lagfree, but only inside the webrtc custom card, would still like to use the picture entity card as well though...
