### ISSUE TITLE
Fix creating stream on the fly

### ISSUE THREAD

**Issue by roma777roma** [AlexxIT/go2rtc#534]
i have 6 cameras and i see them through home assistant with webrtc. After the update I see the same stream on the 6 cameras even if they have 6 different ip addresses. Tried to reset the webrct component nothing, tried to reset the go2rtc component but nothing, restarted hassio but nothing. Restored to version 1.5.0 and everything works.

**Comment by AlexxIT** [comment]
How you setup this streams in the Home Assistant?

**Comment by roma777roma** [comment]
I'll just give 2 examples:

type: custom:webrtc-camera
url: rtsp://user:pass@192.168.0.30:88:554/Streaming/Channels/102/
view_layout:
  grid-column: 1 / 5
  grid-row: 1 / 5
style: |
  ha-card {
    background: none;
    box-shadow: none;
  }
  
  type: custom:webrtc-camera
url: rtsp://user:pass@192.168.0.30:88/videoSub
view_layout:
  grid-column: 1 / 5
  grid-row: 5 / 9
style: |
  ha-card {
    background: none;
    box-shadow: none;
  }



and this is the result:

![immagine](https://github.com/AlexxIT/go2rtc/assets/60389878/549628e5-691d-472c-b757-99889459ecdb)


with version 1.6.1 I have 3 identical images of the first camera and in the other page where there are 3 other cameras always the same image of the first

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.2
