### ISSUE TITLE
Webrt stream reboot.

### ISSUE THREAD

**Issue by averhoev** [AlexxIT/go2rtc#536]
I'm using frigate with go2rtc. When I use an different version of go2rtc other then the embedded one (go2rtc 1.2) the stream freezes after 35 seconds. I raised an issue with frigate (see #7210) and they recommended to reach out to you. According to them the TCP connection is broken after 5 seconds causing the stream to close after 35 seconds as after 30 seconds of inactivity the WEBRTC stream is closed. 

If I use the stand alone version of go2rtc al is working fine. 

i'm using a reolink doorbell wifi

**Comment by AlexxIT** [comment]
You don't have problems on latest go2rtc and has problems on old go2rtc?

**Comment by averhoev** [comment]
I have no issue with the in frigate embedded version (1.2) but as soon as I use the custom go2rtc version by instructions on this page "https://docs.frigate.video/configuration/advanced/" it freezes freezes in frigate after 35 seconds and if i look at the go2rtc webinterface it restarts after 35 seconds. 

versions I tested 1.3, 1.4, 1.5, 1.6 and 1.6.1. they all stop at exact the same moment each time

**Comment by AlexxIT** [comment]
You need to enable trace log level for rtsp module and collect some logs.
You can do it on standalone go2rtc on any PC in your network.

**Comment by averhoev** [comment]
Enclosed trace 3 files.

1. Frigate with version 1.2 --> working
2. Frigate with version 1.6.1 --> not working
3. Standalone version 1.6.1 --> working

Each of the logs have done the same. start the frigate or go2rtc. Wait until started then open a webrtc stream. Wait until it freezes or till at least 50 seconds then copy the trace files. If more or something alse is needed please let me know.

[Frigate working RTSP TRace.txt](https://github.com/AlexxIT/go2rtc/files/12113762/Frigate.working.RTSP.TRace.txt)
[GO2RTC standalone working RTSP TRace.txt](https://github.com/AlexxIT/go2rtc/files/12113763/GO2RTC.standalone.working.RTSP.TRace.txt)
[Frigate NOT working RTSP TRace.txt](https://github.com/AlexxIT/go2rtc/files/12113764/Frigate.NOT.working.RTSP.TRace.txt)

**Comment by AlexxIT** [comment]
Can you leave only one stream in the NOT working log. And with only one source.

**Comment by averhoev** [comment]
As requested. Enclosed log file from start with one source. i tried twice between 8:03-8:05 and 8:15-8-17. In both cases the stream restarted 2/3 times. Hope this is what you need.

[not working 1 source.txt](https://github.com/AlexxIT/go2rtc/files/12116958/not.working.1.source.txt)

**Comment by averhoev** [comment]
any insights on this?

**Comment by AlexxIT** [comment]
Can check in two weeks

**Comment by AlexxIT** [comment]
I can't see any special in your logs. All looks fine

**Comment by AlexxIT** [comment]
Please let me know if the problem is relevant
