### ISSUE TITLE
Add support webrtc go2rtc source with auth

### ISSUE THREAD

**Issue by sandstormkeshav** [AlexxIT/go2rtc#539]
Hi!
I'm trying to add a webrtc source (go2rtc), the instance that I am trying to source the video from has an API password. This prevents me from connecting to it.
I tried
webrtc:ws://admin:pass@192.168.1.123:1984/api/ws?src=camera1
But it did not work, is there anything else I can try?

If I remove the api password then it works fine.

**Comment by sandstormkeshav** [comment]
@AlexxIT could you please let me know if logs would be helpful for this? It's possible I am not encoding the password in the URL the correct way, so just want to make sure the example above is correct.

**Comment by AlexxIT** [comment]
It may not work if you have special symbols in password

**Comment by sandstormkeshav** [comment]
> It may not work if you have special symbols in password

Hi @AlexxIT I tried making my password "password" but it still does not work, were you able to make it work?

**Comment by AlexxIT** [comment]
I have no problems with any symbols in password

**Comment by AlexxIT** [comment]
You right. This wasn't supported earlier.

**Comment by sandstormkeshav** [comment]
Thank you for confirming, and I see your commit has added this feature, thank you very much!
