### ISSUE TITLE
RTSPS streams from Unifi Protect G4 cameras fail due to certificate error - Beta 6

### ISSUE THREAD

**Issue by wvdeadhead** [AlexxIT/go2rtc#54]
Go2RTC Beta 6

When trying to configure a Unifi Protect G4 camera with its RTSPS stream, the following error is received:

probe producer error="x509: certificate is valid for 127.0.0.1, fe80::1, not 1.2.3.4" url=rtsps://1.2.3.4:7441/mdJbbmZvXj0j6vcz?enableSrtp

**Comment by AlexxIT** [comment]
Check it #15
