### ISSUE TITLE
Query: How to configure the Imou cameras for Dual Audio

### ISSUE THREAD

**Issue by mannish-kumar** [AlexxIT/go2rtc#548]
Hi,

I am not sure if this is the right forum to discuss. I recently tried to enable Dual Audio for one of my Imou Cue 2 Camera but it didn't work. The camera has two rtsp stream urls, I added both of them to go2rtc config. 
I could hear one way audio (from camera to mobile/pc) but the dual audio didn't work for me.
Even though I could see the live stream but couldn't here any audio on either side. 

I need help to know if Imou cameras supported for dual audio.

**Comment by AlexxIT** [comment]
Check stream info for active stream in WebUI. Probably your camera doesn't support two way audio standards. And uses some proprietary protocol.

**Comment by mannish-kumar** [comment]
This is what I have under the stream info.  I am new to this and not able to conclude anything.

Could you please help?

**Comment by AlexxIT** [comment]
So your camera doesn't support open two way audio standards. It can't be helped.

**Comment by mannish-kumar** [comment]
Most of the brands doesn't mention much details in their specs in India. Do you know any cameras that supports this and I can buy.

How about Tapo C110. As per the video on youtube (https://youtu.be/WnRJxneCUYE) it looks like it is supported.
