### ISSUE TITLE
Http 401 for non admin users in HA

### ISSUE THREAD

**Issue by sneakythr0ws** [AlexxIT/go2rtc#550]
Hi!
I see http 401 if I call `stream.html` using non admin user or from private window.
How to authorize it or give access?

**Comment by AlexxIT** [comment]
Probably you try to open addon web page. You only can do it from Hass interface.

**Comment by sneakythr0ws** [comment]
I took url for `stream.html` from `go2rtc` ha addon `links` page. 
As I understand it uses ingress of addon.
`https://host:8123/api/hassio_ingress/...g9WMFzyhngpb1zm.../stream.html?src=rtsp://host:8532/cam`
Is it possible to configure security of addons ingress?

**Comment by sneakythr0ws** [comment]
Ok. I just opened it on 1984

**Comment by MrS4u** [comment]
> Ok. I just opened it wuthout HA

Hello @sneakythr0ws how did you do it?
