### ISSUE TITLE
Casting Home Assistant View Doesn't Work

### ISSUE THREAD

**Issue by Sian-Lee-SA** [AlexxIT/go2rtc#553]
Using  picture-glance works fine when using browser etc but when I cast the view to my Nest hub (only element on the page) it just shows a still image and doesn't stream. Switched back to RTSPtoWeb which works fine.

**Comment by AlexxIT** [comment]
Picture Glance, go2rtc and RTSPtoWebRTC not related with each other. So you need to provide more info

**Comment by Sian-Lee-SA** [comment]
![image](https://github.com/AlexxIT/go2rtc/assets/11685433/db4308e0-1e56-44e0-ae82-6c1b912c4f7e)


Using go2rtc url is causing the issues with casting when using that instead of the one in the screenshot (screenshot is for reference and understanding)

**Comment by AlexxIT** [comment]
Well. This is WebRTC integration. Not Picture Glance. Still can't understand what case didn't work for you.

**Comment by Sian-Lee-SA** [comment]
![image](https://github.com/AlexxIT/go2rtc/assets/11685433/28aa4677-7d2f-42eb-8872-a4bc3976d243)

Not sure whats really tripping you up and honestly I don't really care, I'm just pointing out a problem with your code and that it's not behaving as it should, whether you do something about it or not ain't my problem. There's an alternative that working for me regardless.

**Comment by Sian-Lee-SA** [comment]
Also for clarity sakes its actually RTSPtoWebRTC

![image](https://github.com/AlexxIT/go2rtc/assets/11685433/22bf1868-04c2-417c-9864-011a047298c8)

Just the sub page displays it as WebRTC

![image](https://github.com/AlexxIT/go2rtc/assets/11685433/4e8e848e-bab0-40bc-9b14-61f520d9ecd2)
