### ISSUE TITLE
Problem with the edge browser

### ISSUE THREAD

**Issue by karask007** [AlexxIT/go2rtc#556]
I have a problem with the edge browser it always gives me an error when I try to visit the streming how can I go about solving it an example I usually use a camera with onvif protocol by accessing directly with a link eg: http://xxxx.com:1984/ stream.html?src=rtsp%3A%2F%2Fxxx%3xxxxi%4010.20.30.333%3A554 it works on chrome but not on edge and firefox can anyone help me?

**Comment by AlexxIT** [comment]
You need provide more info. For example error message. Maybe your camera has h265 codec and your edge doesn't support it.

**Comment by karask007** [comment]
I have a hyundai HYU-414N camera with onvif protocol the chrome browser with the example link from before works with chrome instead with edge and firefox no how do I fix this yours is a great product simple to use and perfect for me the error message it is unknown error in the upper left instead of error only in the upper right of the screen

**Comment by AlexxIT** [comment]
Just read docs about codecs.

**Comment by karask007** [comment]
ok thanx Alex
