### ISSUE TITLE
SDP for the RTSP stream missing "a:control" entries

### ISSUE THREAD

**Issue by rb2k** [AlexxIT/go2rtc#560]
So this is a bit of an odd issue given that I haven't looked at this myself, but I thought I'd share regardless.

I have recently tried to use go2rtc as a source for "Blue Iris", a popular security/nvr software.
Somehow, I have not been able to get it to accept the RTSP stream (or any stream for that matter) originating at go2rtc even though VLC worked well and the codecs were fine according to ffprobe.

I reached out to the Blue Iris support and after some back and forth and me providing a demo RTSP link they found the issue. According to them it was that:

> The SDP for the RTSP stream was missing the "a:control" entries, which Blue Iris was expecting.

From what I understand, in RTSP, SDP is used to describe available streams. If you have multiple streams (e.g. an audio and a video stream), you can use a=control:[...] to tell them apart.

They will fix that on the Blue Iris side in one of the upcoming releases, but I thought I'd mention it just in case that's something that go2rtc has control over and it would be something that potentially trips up other software.

**Comment by cjvirtucio87** [comment]
I'm using https://github.com/blakeblackshear/frigate, which uses `gortc` to essentially proxy multiple streams. I'm seeing `a=control:*` when connecting to the camera directly, but it's missing when connecting to `gortc`:

```
$ ffmpeg -i rtsp://10.101.1.50:8554/frontdoor -an -vn -y -loglevel debug -f null -

...

[tcp @ 0x560cc8488380] Successfully connected to 10.101.1.50 port 8554
[rtsp @ 0x560cc8485340] SDP:
v=0
o=- 1 1 IN IP4 0.0.0.0
s=go2rtc/1.2.0
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=<some hash>; profile-level-id=420032
m=audio 0 RTP/AVP 97
a=rtpmap:97 MPEG4-GENERIC/8000
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1588
```

**Comment by AlexxIT** [comment]
You using very old go2rtc version

```
v=0
o=- 1 1 IN IP4 0.0.0.0
s=go2rtc/1.6.2
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4D401E;sprop-parameter-sets=Z01AHqaAoD2QAA==,aO48gAA=
a=control:trackID=0
m=audio 0 RTP/AVP 97
a=rtpmap:97 MPEG4-GENERIC/16000
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408
a=control:trackID=1
```
