### ISSUE TITLE
[Question] how to set alaw codec for restream? (or where do I find all the audio codec names?)

### ISSUE THREAD

**Issue by distante** [AlexxIT/go2rtc#563]
I am trying to restream a TAPO C200 camera. Just using `rtsp://my-server-ip:8554/my-cam` fails while getting the audio while `rtsp://my-server-ip:8554/my-cam?video=h264&audio=all` works.

I would like to set the audio directly to `alaw` since that is what theoretically works. But I have not found how to do it.

I tried `audio=alaw` and `audio=a-law` without success. 

How can I do this?

Thanks!

**Comment by AlexxIT** [comment]
pcma, pcmu

**Comment by distante** [comment]
Thank you @AlexxIT ! Is there a place where I could see all those names?

**Comment by AlexxIT** [comment]
Some here
https://github.com/AlexxIT/go2rtc/blob/4baa3f5588e122c73d0ec8cba966199aafe87edf/pkg/core/core.go#L15

Some here
https://github.com/AlexxIT/go2rtc/blob/4baa3f5588e122c73d0ec8cba966199aafe87edf/pkg/core/media.go#L184

**Comment by distante** [comment]
Nice, thanks a lot!
