### ISSUE TITLE
Use Get /api/stream.mp4?src=cam1&duration=5 to download, but not stop after 5 second

### ISSUE THREAD

**Issue by xiaolei0125** [AlexxIT/go2rtc#577]
* I have try to use `curl -O http://192.168.1.105:1984/api/stream.mp4?src=cam1&duration=5&filename=test1.mp4`  or `wget http://192.168.1.105:1984/api/stream.mp4?src=cam1&duration=5&filename=test1.mp4` to download mp4 file,  
* the curl or wget command continue run , not stop after duration=5 second later,  it seem the th param duration=5 not take effect.
Please help me, thank you

**Comment by AlexxIT** [comment]
What go2rtc version you using?

**Comment by xiaolei0125** [comment]
@AlexxIT   v1.6.2 - 2023-07-20,   use browser to download is ok.

**Comment by AlexxIT** [comment]
I don't understand. Do you have problems or not?

**Comment by xiaolei0125** [comment]
@AlexxIT   Open the URL in browser and download it normal,   but use curl or wget  to download the url , the curl or wget cannot stop, continue to download

**Comment by AlexxIT** [comment]
Double check you using right URL. Because go2rtc drops connection after timeout.

**Comment by dzek69** [comment]
@xiaolei0125 you HAVE TO quote anything that contains "&"

BAD:
`curl -O http://192.168.1.105:1984/api/stream.mp4?src=cam1&duration=5&filename=test1.mp4`


GOOD:
`curl -O "http://192.168.1.105:1984/api/stream.mp4?src=cam1&duration=5&filename=test1.mp4"`

**Comment by xiaolei0125** [comment]
@dzek69 thanks
