### ISSUE TITLE
Add support B-frames from MPEG-TS to MP4/MSE

### ISSUE THREAD

**Issue by gtxaspec** [AlexxIT/go2rtc#583]
Internet based http source, video is slow, beind the audio.  Sometimes the video is OK, but skips every x frames.

always happens in MSE/webrtc & rtsp client streams

version: latest master

i can PM you the URL if you need it for testing if you want.

video works fine directly from source in browser and using ffplay.

**Comment by AlexxIT** [comment]
Yes. You can PM link to me.

**Comment by gtxaspec** [comment]
B-Frames not supported in WebRTC, causing issues.

**Comment by AlexxIT** [comment]
I have added support to MP4

**Comment by gtxaspec** [comment]
working well in latest master.  thank you!
