### ISSUE TITLE
Save or record video

### ISSUE THREAD

**Issue by eerison** [AlexxIT/go2rtc#585]
is there anyway to save the camera stream ? small video's pieces.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#module-mp4

**Comment by eerison** [comment]
> https://github.com/AlexxIT/go2rtc#module-mp4

I see the link that you informed, and I know that is possible hit the endpoint and pass duration+filename

But how to use this to save video automatically? should I use a cronjob for this? or is there other way?

**Comment by AlexxIT** [comment]
You can use cron if you want.
