### ISSUE TITLE
Get webrtc stream from wyze-bridge

### ISSUE THREAD

**Issue by kevkid** [AlexxIT/go2rtc#588]
Hi I want to get the webrtc stream from wyze bridge. I am not sure how to do it?

Reading the documentation:
https://github.com/AlexxIT/go2rtc#source-webrtc
for [docker-wyze-bridge](https://github.com/mrlt8/docker-wyze-bridge) I can get the webrtc url and it looks like this:
`http://<wyze-bridge-ip>:8889/backyard-side-camera`
As the docs state I can use echo to get the url that looks like: `webrtc:http://<wyze-bridge-ip>:5000/signaling/camera1?kvs#format=wyze`
I can use the request library and grab the html, but I don't understand what I am looking for exactly? As I understand webrtc is dynamic and p2p, so I can understand the link being dynamic. 

What would a script look like that can get me the url? I tried following along with: https://github.com/AlexxIT/go2rtc/wiki/Source-Echo-examples but they explicitly look for a .3mu url.

Current script:
```
import re
import sys
from urllib.parse import urljoin
from urllib.request import urlopen
html = urlopen("<wyze-bridge-ip>:8889/front-yard-cam").read().decode("utf-8")
```

**Comment by AlexxIT** [comment]
With `webrtc:http://<wyze-bridge-ip>:5000/signaling/camera1?kvs#format=wyze` source go2rtc connects direct to Amazon servers.
Looks like `http://<wyze-bridge-ip>:8889/backyard-side-camera` is address of this project
https://github.com/bluenviron/mediamtx#webrtc-clients

**Comment by kevkid** [comment]
> With `webrtc:http://<wyze-bridge-ip>:5000/signaling/camera1?kvs#format=wyze` source go2rtc connects direct to Amazon servers. Looks like `http://<wyze-bridge-ip>:8889/backyard-side-camera` is address of this project https://github.com/bluenviron/mediamtx#webrtc-clients

Thank you, I am just a little confused as to what the actual url should look like?
Should it look like this:
```
go2rtc:
  streams:
    back_side: webrtc:http://<wyze-bridge-ip>:8889/backyard-side-camera
```
or
```
go2rtc:
  streams:
    back_side: http://<wyze-bridge-ip>:5000/signaling/camera1?kvs#format=wyze
```

The former gives me:
[rtsp] error="SetRemoteDescription called with no ice-ufrag" stream=back_side

The latter seems to work, atleast it did. I thought the amazon server one was:
`webrtc-kinesis: webrtc:wss://...amazonaws.com/?...#format=kinesis#client_id=...#ice_servers=[{...},{...}]`

**Comment by AlexxIT** [comment]
Both of your urls wrong. You should use exact as example
`webrtc:http://<wyze-bridge-ip>:5000/signaling/<camera-name>?kvs#format=wyze`

You can open url in your browser and it should response with connection credentials
`http://<wyze-bridge-ip>:5000/signaling/<camera-name>?kvs`

So format:
`webrtc:<working-url>#format=wyze`

**Comment by kevkid** [comment]
> Both of your urls wrong. You should use exact as example `webrtc:http://<wyze-bridge-ip>:5000/signaling/<camera-name>?kvs#format=wyze`
> 
> You can open url in your browser and it should response with connection credentials `http://<wyze-bridge-ip>:5000/signaling/<camera-name>?kvs`
> 
> So format: `webrtc:<working-url>#format=wyze`

This is correct, using this works: webrtc:http://<wyze-bridge-ip>:5000/signaling/<camera-name>?kvs#format=wyze

and if we remove the webrtc: part and put the rest in the browser you get some kind of json.

Thank you, and was funny seeing you drop in to the wyze-bridge comment :)

**Comment by ryang3d** [comment]
Was following this discussion here and on the wyze-bridge issue tracker this morning. I can't seem to get this to work.

Is it necessary to run any script like @kevkid shows in his OP, or is formatting the config like below what should do the trick?

`go2rtc:
  streams:
    back_side: webrtc:http://<wyze-bridge-ip>:5000/signaling/<camera-name>?kvs#format=wyze`

I have go2rtc (upgraded to latest/current version) running from inside a frigate docker container and the docker-wyze-bridge in a separate container. I'm able to stream RTSP feeds from the wyze-bridge to frigate using go2rtc, but webrtc just refuses to work (I get the black screen with "No frames have been received, check error logs" message). Using the above format doesn't work, and I've tried a few other things with no luck... what am I missing? 🤔

**Comment by kevkid** [comment]
btw I never got it to do anything with the secript, Here it is in the documentation though: 
https://github.com/AlexxIT/go2rtc#source-webrtc

**Comment by ryang3d** [comment]
> btw I never got it to do anything with the secript, Here it is in the documentation though: https://github.com/AlexxIT/go2rtc#source-webrtc

Yeahhh, that's what I thought. I've looked at that documentation page so many times now xD. No such luck here yet, but nice to hear that it is working for you

**Comment by AlexxIT** [comment]
I got it. The documentation is confusing. Only kinesis users needs scripts.

echo script should output (echo) supported link in go2rtc format. For example:

```bash
echo "wss://...amazonaws.com/?...#format=kinesis#client_id=...#ice_servers=[{...},{...}]"
```
