### ISSUE TITLE
Add check for empty H265 packet #589

### ISSUE THREAD

**Issue by rajesindia** [AlexxIT/go2rtc#589]
![screenshot](https://github.com/AlexxIT/go2rtc/assets/23351731/b6ef1be2-5ee2-449d-afa6-8a60ac110959)

Hi,

It seems while using the Hikvision playback rtsp url, the tool is getting crashed.
RTSP Url works fine when i open it via VLC or any player.

RTSP format would be like: rtsp://{username}:{password}@{ipaddress}:{rtspport}/Streaming/tracks/101?starttime={utc in epoch}&endtime={utc in epoch}

Here is the codec details. Trying to open it with MSE mode.

![image](https://github.com/AlexxIT/go2rtc/assets/23351731/ccbf4dac-de34-4eac-85b8-7a4a4bd57937)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/331
