### ISSUE TITLE
-analyzeduration 1000M -probesize 1000M

### ISSUE THREAD

**Issue by itsolon** [AlexxIT/go2rtc#594]
The Question is, where in this software under frigate go2rtc should this be configured?
```
2023-08-23 16:53:46.354341190  [2023-08-23 16:53:46] ffmpeg.Einfahrt.record         ERROR   : [rtsp @ 0x5559fd560ec0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
2023-08-23 16:53:46.354446651  [2023-08-23 16:53:46] ffmpeg.Einfahrt.record         ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

**Comment by AlexxIT** [comment]
Are you sure this response from go2rtc?

**Comment by itsolon** [comment]
Ups
I'm sure it's from ffmpeg which is inside this
Bit when I go via go2rtc as I did with the other cams the frigate log shows error and the video is black
I think stream 0 is too big ?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlexxIT** [comment]
I think your stream has some trash. Because default ffmpeg params should handle 99.99% cameras on marker.
You can change any params you want. Just read docs:
https://github.com/AlexxIT/go2rtc#source-ffmpeg

**Comment by itsolon** [comment]
I already saw this docu but to be honest .. parameter change there was no example
Maybe the cam is trash itself but with VLC and edge etc everything works
Even if I give frigate the stream directly then everything is recorded
Only the way via go2rtc does not work
I already tried 1.2.0 and 1.6.2

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NickM-27** [comment]
Frigate is using ffmpeg, so you should use the ffmpeg input in go2rtc for that camera.

**Comment by AlexxIT** [comment]
But errors in logs from FFmpeg. It's not go2rtc issue

**Comment by itsolon** [comment]
"update" 
the error logs in ffmpeg are there, but i found one recurring entry in go2rtc too
WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.23.0.2:55378->192.168.7.24:554: i/o timeout" url=rtsp://192.168.7.24:554/stream1?username=admin&password=password

**Comment by AlexxIT** [comment]
Camera haven't send packet to go2rtc during 5 second

**Comment by itsolon** [comment]
Can I extend that period for test?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlexxIT** [comment]
Master version support custom timeout:
```
streams:
  camera1: rtsp://...#timeout=30
```

**Comment by itsolon** [comment]
Feedbak if i put #timeout=30 then its treated like a comment #

i found out that the issue occurrs when i link the mainstream an the substream  in config and then later use it

ACTUAL SITUATION
STREAMS:
    einfahrt_main:
      - rtsp://192.168.7.24:554/stream0?username=admin&password={FRIGATE_RTSP_PASSWORD}#timeout=30
    einfahrt_sub:
      - rtsp://192.168.7.24:554/stream1?username=admin&password={FRIGATE_RTSP_PASSWORD}

NOT WORKING FOR ME:
  Einfahrt:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/einfahrt_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/einfahrt_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 720
      height: 480
    live:
      stream_name: einfahrt_main
    ui:
      order: 0
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog

WORKING FOR ME: (Workaround)
  Einfahrt:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/einfahrt_main
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.7.24:554/stream1?username=admin&password={FRIGATE_RTSP_PASSWORD}
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 720
      height: 480
    live:
      stream_name: einfahrt_main
    ui:
      order: 0
    objects:
      track:
        - person
        - bicycle
        - motorcycle
        - cat
        - dog


where is my fault? i do not see ?

**Comment by skrashevich** [comment]
- **"**rtsp://192.168.7.24:554/stream0?username=admin&password={FRIGATE_RTSP_PASSWORD}#timeout=30**"**
Otherwise, # starts the comment and is not part of the url

**Comment by itsolon** [comment]
> `- "rtsp://192.168.7.24:554/stream0?username=admin&password={FRIGATE_RTSP_PASSWORD}#timeout=30"` Without quotes, # starts the comment and is not part of the url

Thank you very much that seems to do the trick,
my camera is obviously as slow as 0,01 % of the cams out there
(im referencing to Alex's statement)

but with your Tip - now including quotes - the software waits 30 seconds and timeouts error message is away..

it worked already.. thats great , now im experimenting with values inside cam menu, audio aac directly instead of g711a or u
or H265 / H265+ / H264 codec in main stream 

i know that detect stream needs H264 which i have adjusted as well as 5 fps.

now i have another interesting message in go2rtc 

panic: runtime error: slice bounds out of range [:8192] with capacity 504

in general i think if im adjusting too "high values" then problems occur.

of course i want to draw out the maximum of quality my cam can deliver but not so much that the periphery like go2rtc or frigate do not run anymore..

its great software 👍

**Comment by AlexxIT** [comment]
@itsolon show full panic error with line numbers

**Comment by mattkasa** [comment]
@AlexxIT I am trying to use a Vikylin PTZ-4825X-IS that has a really slow to start stream and ran across this issue, and I tried 1.7.1 so that I could use `#timeout=90`, and I think I might be getting the same panic that @itsolon is, it happens as soon as I try to view the stream where I used `#timeout=90`.

Here's the full error:

```
2023-09-11 19:38:58.387321835  [INFO] Starting go2rtc...
2023-09-11 19:38:58.507663094  19:38:58.507 INF go2rtc version 1.7.1 linux/amd64
2023-09-11 19:38:58.508052612  19:38:58.508 INF [api] listen addr=0.0.0.0:1984
2023-09-11 19:38:58.508656341  19:38:58.508 INF [rtsp] listen addr=0.0.0.0:8554
2023-09-11 19:38:58.508983978  19:38:58.508 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-09-11 19:39:03.963023312  panic: runtime error: slice bounds out of range [:8192] with capacity 444
2023-09-11 19:39:03.963033718  
2023-09-11 19:39:03.963071783  goroutine 199 [running]:
2023-09-11 19:39:03.963077510  github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.RTPDepay.func5(0xc0001d2d80)
2023-09-11 19:39:03.963101397  	github.com/AlexxIT/go2rtc/pkg/aac/rtp.go:24 +0x357
2023-09-11 19:39:03.963105658  github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP.func1()
2023-09-11 19:39:03.963127588  	github.com/AlexxIT/go2rtc/pkg/core/track.go:146 +0x9b
2023-09-11 19:39:03.963131919  created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 77
2023-09-11 19:39:03.963156713  	github.com/AlexxIT/go2rtc/pkg/core/track.go:140 +0x359
2023-09-11 19:39:03.972870302  [INFO] The go2rtc service exited with code 2 (by signal 0)
2023-09-11 19:39:04.985269822  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
```

Let me know if I can provide any more details :bow:
