### ISSUE TITLE
Go2RTC - answer a call via frigate card and be able to speak (Iphone User on Home Assistant))

### ISSUE THREAD

**Issue by asafalfa** [AlexxIT/go2rtc#598]
Hey there,
quick question, Everything operates properly I am able to receive video and two-way audio, and I can answer and end calls via a web browser. (utilizing a frigate card with go2rtc)

But when I attempt the same via my iPhone, I can only listen but not speak.
In Settings → Home Assistant, there is no toggle option for the microphone, so I assume it is disabled.

any idea guys?

**Comment by skrashevich** [comment]
When using Safari, it is necessary to connect via https in order to access the microphone.

**Comment by asafalfa** [comment]
I understand, but im executing it from the home assistant app so this is different compared to surf it via web browser.
My expectation is that Home assistant APP will ask to give permission to use MIC



> When using Safari, it's necessary to connect via https in order to access the microphone.

**Comment by asafalfa** [comment]
So if i use the Frigate card - from the home assistant app it will request me to enable MIC via Home assistant APP.

Again doing the same with Andruid's phone entering the Home Assistant app works and 2 way call is just fine!.
This is only with iPhone implementation - which is different

**Comment by asafalfa** [comment]
Hey @AlexxIT  Have any idea where can i mention this ?

I really have no idea who can explain this behaveir since that is happening in every iphone.

Looks like Mic is not even an option to toggle on/off..
compare to android.

Any Ideas ? :/

**Comment by asafalfa** [comment]
*** update
iOS via Safari + zero trust WORKS!
iOS via Home assistant + Zero trust - Not works ---- so this is something with the Home Assistant App on iOS…
iOS via Chrome + Zero trust - Not work

**Comment by asafalfa** [comment]
you will laugh at me, so in the HA app i configured the external with http - which worked but for us to get the Microphone you have to log in via HTTPS only ... and that fix the problem:)

No i just breaking my head how to set the intenal URL also with HTTPS  since right now it regular http - Not sure how to do that:).

**Comment by asafalfa** [comment]
You can resolve it .. adding the url to HA with HTTPS fixed the issue :)
