### ISSUE TITLE
Go2RTC - Frigate 0.12 - Dahua RTSP Stream and Complex Passwords

### ISSUE THREAD

**Issue by craigcurtin-dev** [AlexxIT/go2rtc#602]
Guys,

Just setup Frigate 0.12 in a docker container - running well - i am now wishing to enable go2rtc

I am cutting and pasting the RTSP line from one of my camera defintions in Frigate (that is working fine) and attempting to use that stream with go2rtc.

So the existing line is 

path: rtsp://Viewer:xxxxx@172.16.101.155:554/cam/realmonitor?channel=1&subtype=1

The password is a complex one that contains !)@^ as part of the password 

This is happily accepted by Frigate - but Go2RTC appears to have a problem and can not connect to the stream - is there an issue with using complex characters in the password - and if so is there a way to either escape them or provide a list of what are OK characters ?

Craig

**Comment by AlexxIT** [comment]
https://www.urlencoder.org/

**Comment by craigcurtin-dev** [comment]
OK tried that and it is saying that there is an error with the username/password even after urlencode

I assume based on this that there is certain range of acceptable characters.

If i was to pass it in through the config file would this make any difference - rather than hard coding on the line with RTSP ?

If i know what the accepted characters are then i could potentially change the password also

Craig

**Comment by AlexxIT** [comment]
This method works. You doing something wrong.
You can Google standards for accepted URL charts. You can't use some charts without urlencoding.
