### ISSUE TITLE
mse: unknown error

### ISSUE THREAD

**Issue by rajesindia** [AlexxIT/go2rtc#603]
Hi,

When i try to add an rtsp stream and play it with mse mode, it throws unknown error. I was able to do that in Intel Windows machine. Only difference is its AMD Radeon Windows Machine. Moreover, it could not detect the FFMPEG Hardware as well.

ERROR | ffmpeg:...#video=h264#hardware=dxva2
ERROR | ffmpeg:...#video=h265#hardware=dxva2
ERROR | ffmpeg:...#video=mjpeg#hardware=dxva2
ERROR | ffmpeg:...#video=h264#hardware=cuda
ERROR | ffmpeg:...#video=h265#hardware=cuda

I have kept ffmpeg exe in the same folder as go2rtc exe.

**Comment by AlexxIT** [comment]
After chatting on Telegram, it turned out that the browser does not support H265
