### ISSUE TITLE
How do I connect the RTSP camera to HomeKit, is there a specific configuration method?

### ISSUE THREAD

**Issue by PWMFI** [AlexxIT/go2rtc#606]

**Comment by AlexxIT** [comment]
Answer in the docs

**Comment by PWMFI** [comment]
How do I add it to my Apple family after the configuration is complete, am I configuring it correctly?
![微信截图_20230903224123](https://github.com/AlexxIT/go2rtc/assets/63692121/3cd9b1e5-8c75-4324-8000-70035e11ac63)

**Comment by AlexxIT** [comment]
Your config wrong

**Comment by PWMFI** [comment]
I just followed the configuration in the documentation, can you be specific about my configuration error
