### ISSUE TITLE
After using go2rtc, do you still need the WebRTC Camera plugin to display the picture in the lovelace of homeassistant?

### ISSUE THREAD

**Issue by PWMFI** [AlexxIT/go2rtc#608]

**Comment by AlexxIT** [comment]
It's up to you decide, how you want to watch stream. You can use WebRTC integration or Frigate card or RTSPtoWebRTC integration to watch stream without delay

**Comment by PWMFI** [comment]
How a camera streaming using go2RTC generates entities inside HomeAsistant
