### ISSUE TITLE
Another problem with sending video to Telegram

### ISSUE THREAD

**Issue by TokarevSergey** [AlexxIT/go2rtc#612]
Good afternoon. Please tell me, after the update, the video from one of the cameras in the telegram stopped coming, everything worked before.

![image](https://github.com/AlexxIT/go2rtc/assets/98225056/4c8e4ee2-beb5-4f6c-a918-04144c2e6a58)
![image](https://github.com/AlexxIT/go2rtc/assets/98225056/0859e538-f783-4237-a4fe-481dcfe15632)
![image](https://github.com/AlexxIT/go2rtc/assets/98225056/1f98b6ac-7788-41b2-9057-cca40c2deb5b)

Tell me what am I doing wrong? Thank you.

**Comment by AlexxIT** [comment]
I need someone else to confirm the problem
