### ISSUE TITLE
Can't view WebRTC stream even with ngrok. (Frigate)

### ISSUE THREAD

**Issue by victorlee115** [AlexxIT/go2rtc#617]
This is my current config
<img width="364" alt="image" src="https://github.com/AlexxIT/go2rtc/assets/126674491/217dbfb9-ea35-4a1c-9b6a-201587cc5e86">

<img width="889" alt="image" src="https://github.com/AlexxIT/go2rtc/assets/126674491/2fbd47ed-944a-4d33-8e40-04e2a45dc067">

I use Cloudflare tunnels and have a symmetrical NAT. Am I missing something?

**Comment by AlexxIT** [comment]
Your config looks fine. Does WebRTC work on a local network?

**Comment by AlexxIT** [comment]
#348
