### ISSUE TITLE
ESeeCloud, dvr163 --> error="streams: wrong response: 404 Not Found"

### ISSUE THREAD

**Issue by IliasEagle** [AlexxIT/go2rtc#619]
Hello, 

this is more of a question than an issue. 

I have a YESKAMO NVR (K8208-W) the streams of which I can access via the ESeeCloud app.
Using the "bubble" configuration I added under the streams
```
...
camera.yeskamo1: bubble://admin:********@192.168.68.148:80/bubble/live?ch=1&stream=0
camera.yeskamo2: bubble://admin:********@192.168.68.148:80/bubble/live?ch=2&stream=0
```
My configuration looks like this

![image](https://github.com/AlexxIT/go2rtc/assets/93916516/d5e319f8-7fe9-4bd0-b0bf-18e6466487b0)

When I press stream on camera.yeskamo1 or camera.yeskamo2 I get:
`error="streams: wrong response: 404 Not Found"`

the respective log section states:
```
09:56:34.954 TRC [api] GET /stream.html?src=camera.yeskamo1 172.30.32.2:51616
09:56:35.039 TRC [api] GET /video-stream.js 172.30.32.2:51616
09:56:35.083 TRC [api] GET /video-rtc.js 172.30.32.2:51616
09:56:35.140 TRC [api] GET /api/ws?src=camera.yeskamo1 172.30.32.2:51616
09:56:35.559 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: wrong response: 404 Not Found"
09:56:38.824 TRC [api] GET /api 172.30.32.2:46658
09:56:38.825 TRC [api] GET /api/streams 172.30.32.2:46668
```

Without having any understanding of what's really going on, my impression is that go2rtc is trying to get the stream on the NVR subnetwork address `172.30.32.2`

Checking the NVR configuration, there is no such IP:
![image](https://github.com/AlexxIT/go2rtc/assets/93916516/beafd5bb-7941-49f9-983c-04d3fd33a618)

Am I on to something, or is this that I have it completely wrong?

----

Here is the NVR network settings config 

![image](https://github.com/AlexxIT/go2rtc/assets/93916516/8facba64-5205-4716-9b47-b883d7944a0a)

----

Not sure how relevant it is but there is a software called CMS which using the NVR username and password and port **10000** I can see the camera streams. 

For what is worth I tried port 10000 with go2rtc and I get a timeout error. 

----

Заранее большое спасибо. Надеюсь, не трачу твое время зря
С уважением Илья!

**Comment by AlexxIT** [comment]
`172.30.32.2` - this is docker IP address of your Hass server. I think you open go2rtc WebUI via Hass addon ingress feature

**Comment by IliasEagle** [comment]
Понятно!

Благодорю за время ответить на мои вопрос!

Буду искать далее как то.  Ищю новее firmware дила моего NVR от YESKAMO (изготовитель) так как знаю подобные системы с новее firmware подерживают RTSP.

Продолжай ольтличную работу! go2rtc отличини и полезный проект! Спасибо!

С уважением, 
Илья

**Comment by DrRamm** [comment]
So after all which config use for K8208-W with enabled RTSP stream?
![image](https://github.com/AlexxIT/go2rtc/assets/4704811/f1a8797d-0bf1-4232-8819-f127bb24b816)
