### ISSUE TITLE
Symmetric NAT remediation 

### ISSUE THREAD

**Issue by gedw99** [AlexxIT/go2rtc#621]
https://github.com/pion/turn Looks like it might be a good basis for this blocker..

**Comment by AlexxIT** [comment]
Don't know what you want to say. But TURN in the docs with setup example:
https://github.com/AlexxIT/go2rtc#module-webrtc

**Comment by gedw99** [comment]
https://github.com/pion/turn/issues/12#issuecomment-388717017

Talks about NAT aspects and so may melody with Symetric NAT.

**Comment by AlexxIT** [comment]
What the point of your link?
