### ISSUE TITLE
Hass ONVIF?

### ISSUE THREAD

**Issue by efaden** [AlexxIT/go2rtc#624]
In the instructions it says

`Hass > Settings > Integrations > Add Integration > [ONVIF](https://my.home-assistant.io/redirect/config_flow_start/?domain=onvif) > Host: 127.0.0.1, Port: 1984`

But when I point the onvif integration at my Go2RTC instance on port 1984 it returns an error.  Does this only work if you have an Onvif camera?

**Comment by AlexxIT** [comment]
This instruction works. You need to provide more info about problem

**Comment by efaden** [comment]
I followed the instructions...

Went to add the onvif, and pointed it to the go2rtc API/web port and it just says no onvif server found at that port.  It's there something in go2rtc I need to enable?  Otherwise the web interface works fine.
![Screenshot_20230910-143730](https://github.com/AlexxIT/go2rtc/assets/12599300/d26ed0a6-1099-4173-b253-690383863e74)

**Comment by efaden** [comment]
Go2rtc Web interface is available at that IP and port. It's running inside of frigate

**Comment by AlexxIT** [comment]
Maybe you using outdated go2rtc version

**Comment by efaden** [comment]
It's the one built into frigate...  which as it turns out it's 1.2... so it's fairy old.  I think I'm going to run in another docker and just do it separately.
