### ISSUE TITLE
CSS MIME type webrtc.html

### ISSUE THREAD

**Issue by spawn451** [AlexxIT/go2rtc#625]
This is not an issue but only a question.
I want to load a custom css file on the webrtc.html page but I think the server is configured to MIME type ('text/plain').
Is there a way to specify something like  w.Header().Add("Content-Type", "text/css") for that page or at the server level?
I tried to adapt it in your code but I didn't succeed.
By the way, thanks for this great application.

**Comment by AlexxIT** [comment]
I think golang set right content-type to all files.

**Comment by spawn451** [comment]
This is the error message in the browser console when I try to load my custom.css file.
![image](https://github.com/AlexxIT/go2rtc/assets/87195479/7d007322-bbfa-4a94-a30a-bf406eefb823)

**Comment by AlexxIT** [comment]
Have you set custom static_dir folder via yaml? Show css file content

**Comment by spawn451** [comment]
I thought that by default (without specifying anything in the configuration file) static_dir was www
Using this works  :) Thanks!
api:
  static_dir: "www"
