### ISSUE TITLE
Simple guide to embed video stream into existing django webapp project?

### ISSUE THREAD

**Issue by cerahmed** [AlexxIT/go2rtc#629]
Hi there Alex,

Thanks a bunch for this superb project! I have been using WebRTC HA plugin for months and really loving it.

I have a django webapp served by Apache on a RPi-4 that I use to control devices around my house. I've spent quite some time trying to understand how I can embed the video stream into my django web html's as part of my web app.

Things I've done so far:

1) Installed the binary ARM-64 on _another_ RPi.
2) Configured go2rtc.yaml with my Hikvision RTSP urls and credintials.
3) I can view the cameras' live streams over http://theotherpi:1984/ seamlessly.

Now I couldn't find a guide on how I can embed this stream on my main RPi django webapp. Been looking around the WebRTC source code but I don't know what are the minimum files required to make it work + how to go about it.

If Alex or any other folk could point be to the right direction I'd be so greatful.

**Comment by AlexxIT** [comment]
1. Most simple is to use iframe
2. More complicated is to copy the code from stream.html
3. And the hardest part is proxying the go2rtc API through python

I don't know your level and can't teach you how to code.

**Comment by cerahmed** [comment]
Hi Alex, thanks for the prompt response.

1) I have tried iframe and it works fine, but it has some cons so I want to be able to replicate HA WebRTC, which is quicker and more reliable.

2) I'm quite comfortable with JS, but I don't know which URL API I should use when copying stream.html. In addition, what are the minimal JS files required to make stream.html work? If you could provide a brief guide it would be appreciated.

**Comment by AlexxIT** [comment]
If you comfortable with JS, just check browser network console for stream.html. There is all answers

**Comment by cerahmed** [comment]
I don't know why I haven't thought of inspecting the network. I'll do so and close this question if I don't have further clarifications!

Thanks Alex.

**Comment by cerahmed** [comment]
Ok so after looking at another issue, adding the following to `go2rtc.yaml` solved the issue:

``` Yaml
api:
  origin: "*"
```

Closing the question now as it's working perfectly. Thanks a bunch Alex.
