### ISSUE TITLE
Error adding Roborock Camera

### ISSUE THREAD

**Issue by rodolfomachado** [AlexxIT/go2rtc#636]
Hi, 

I´m trying to add Roborock Camera and I'm getting the following error:

![image](https://github.com/AlexxIT/go2rtc/assets/42542786/9745d0a5-6de2-4629-8454-ffc3b9fec086)

What am I missing?

**Comment by rodolfomachado** [comment]
Two things:

I added "streams" and there were a missing space between : and //

![image](https://github.com/AlexxIT/go2rtc/assets/42542786/354ea8f3-b5c9-43f6-bf08-47b8aff97ab4)

Now it shows in the web ui but it's not working 

![image](https://github.com/AlexxIT/go2rtc/assets/42542786/29e19425-c31c-4f60-8070-5bd4eec7aff2)

**Comment by AlexxIT** [comment]
A lot of mistakes.
```yaml
streams:
  vacuum1: roborock://...
```
