### ISSUE TITLE
MSE Stream Getting Stuck in the web (stream.html)

### ISSUE THREAD

**Issue by Akash521** [AlexxIT/go2rtc#644]
Hi @AlexxIT,

I'd like to express my gratitude to you first. Your solution has proven to be highly valuable for numerous individuals.

I'm not encountering any problems running this project initially. However, after a period of about 2 to 3 minutes, the real-time streaming in the browser, as seen in "stream.html," pauses automatically. I've verified that the WebSocket connection is still receiving binary data, but the HTML video player stops playback. To resume streaming, I have to refresh the "stream.html" page.

Is there a way to work around this issue?

**Comment by AlexxIT** [comment]
#543
