### ISSUE TITLE
Home Assistant 2023.9.2 addon not start and no log at all

### ISSUE THREAD

**Issue by bmiki75** [AlexxIT/go2rtc#648]
I have installed both go2rtc Hardware transcoding for Intel (VAAPI) and Raspberry (V4L2). and go2rtc master hardware on Home Assistant 2023.9.2 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest and it is impossible to start them it immediately shot down Log show nothing 
I have tried to clean previous go2rtc.yaml file but nothing change
Component log show only first time i start it:
```
13:06:15.438 INF go2rtc version 1.7.1 linux/arm64
13:06:15.440 INF [api] listen addr=0.0.0.0:1984
13:06:15.441 INF [rtsp] listen addr=0.0.0.0:8554
13:06:15.442 INF [webrtc] listen addr=0.0.0.0:8555/tcp
```
and nothing more both with empty of full(bubble ) go2rtc.yaml

**Comment by bmiki75** [comment]
In the home assistant log i have found:
2023-09-21 09:37:55.774 ERROR (MainThread) [homeassistant.components.hassio.handler] /addons/a889bffc_go2rtc-master/start return code 500
2023-09-21 09:37:55.781 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/a889bffc_go2rtc-master/start -

**Comment by AlexxIT** [comment]
Is this HassOS? What hardware do you have?

**Comment by sdwhwk** [comment]
I too am having trouble starting it in Home Assistant 2023.10.1, OS 10.5 running on a Raspi 4.Logs are the same.

**Comment by bmiki75** [comment]
i have solved with a complete shut down not a restart of hassio i think it is something related to container stuck.
