### ISSUE TITLE
DeckLink Duo

### ISSUE THREAD

**Issue by keith8496** [AlexxIT/go2rtc#651]
Is it possible to use a Blackmagic DeckLink Duo as an input device? I suspect that it is possible, but I can't find the right syntax.

The following command creates a MKV file from the DeckLink input:

```
ffmpeg \
	-hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -format_code Hp29 -f decklink -i 'DeckLink SDI (2)' -vf 'format=nv12,hwupload' -map 0:0 -map 0:1 -threads 1 -c:v h264_vaapi -maxrate 3000k -g 60 -c:a aac multiview.mkv
````
	
Can this command be modified to work under ffmpeg exec?

Thank you in advance
- Keith

**Comment by AlexxIT** [comment]
```
streams:
  stream: exec:ffmpeg -re -i /media/BigBuckBunny.mp4 -c copy -rtsp_transport tcp -f rtsp {output}
```

**Comment by keith8496** [comment]
I got it to work with something like this. I think I was using single quotes but needed double quotes. I will close this issue.

`exec:ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -format_code Hp29 -f decklink -i "DeckLink SDI (2)" -vf format=nv12,hwupload -threads 1 -c:v h264_vaapi -maxrate 3000k -bufsize 6000k -g 60 -tune zerolatency -c:a aac -rtsp_transport tcp -f rtsp {output}`

**Comment by AlexxIT** [comment]
This will be near same:
```
streams:
  stream: ffmpeg:DeckLink SDI (2)#video=h264#hardware=vaapi#input=-format_code Hp29 -f decklink -i "{input}"
```

```
ffmpeg -hide_banner -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_flags allow_profile_mismatch -format_code Hp29 -f decklink -i "DeckLink SDI (2)" -c:v h264_vaapi -g 50 -bf 0 -profile:v high -level:v 4.1 -sei:v 0 -an -vf "format=vaapi|nv12,hwupload,scale_vaapi=out_range=tv" -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}
```
