### ISSUE TITLE
Reolink Duo Floodlight WiFi main stream not loading "codecs not matched"

### ISSUE THREAD

**Issue by chinswain** [AlexxIT/go2rtc#654]
Hi Alex,

I have a Reolink Duo Floodlight WiFi, when adding the main stream I get this error:

22:15:37.497 DBG [webrtc] add consumer error="streams: codecs not matched: H265, AAC => VP8, RTX, VP9, H264, OPUS, G722, PCMU, PCMA, TELEPHONE-EVENT, S16B, S16L"

The sub stream works correctly.

 MAIN: rtsp://xxxx:xxxx@192.168.86.12:554/h264Preview_01_main
 SUB: rtsp://xxxx:xxxx@192.168.86.12:554/h264Preview_01_sub

Both streams work correctly in VLC.

Main:

4608*1728
15 FPS
5120 Kbps

Sub:
1536*576
15 FPS
1024 KBps

Using Version: 1.7.1

**Comment by NickM-27** [comment]
what are you trying to use? it looks like you are trying to use webrtc and the main stream is h.265 which is not compatible with h.265

**Comment by chinswain** [comment]
My main setup is Frigate with it's internal go2rtc but I've installed a standalone docker of the latest go2rtc to test.

I've tried every streaming option on the go2rtc web interface.

I'm not sure if this camera is H265 on the main stream, I'll do some googling. Is it not possible to use it if it is?

**Comment by NickM-27** [comment]
reolink duo is only h.265 on the main stream. webrtc does not support h.265 (except in safari with experimental settings) and MSE only supports h.265 in browsers that support h.265

**Comment by chinswain** [comment]
Ahh that explains it - I'll return it and find another that is compatible.

Thanks for your help.
