### ISSUE TITLE
Question about go2rtc vs mediamtx

### ISSUE THREAD

**Issue by rourke750** [AlexxIT/go2rtc#658]
I currently have 2 wifi enabled cameras that Im trying to use with frigate.  So what I've been doing is I set up both cameras to use https://github.com/bluenviron/mediamtx and then feed that to go2rtc in frigate.  Everything works more or less but if I try to feed my camera link directly I have pauses and dropped frames (I know wifi cameras) but it works using MediaMTX between my camera and go2rtc.  

So my main question is what are they doing there that allows my camera to function better than using go2rtc directly?

**Comment by AlexxIT** [comment]
MediaMTX uses RTSP UDP by default. Go2rtc supports RTSP UDP only via ffmpeg source. Maybe it helps for you
