### ISSUE TITLE
Support `?audio=aac` as RTSP URL parameter

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#66]
It seems that only the other codecs are supported in the URL for now. Since my camera does NOT support setting the default codec as AAC, it would be useful to use go2rtc for the transcoding from PCM to AAC.

**Comment by felipecrs** [comment]
Oh, the reason why I want AAC is because I want to supply the go2rtc RTSP back to Frigate. So that:

1. go2rtc relays the camera's rtsp, so that I prevent multiple connections to the camera
2. Frigate gets the camera stream from go2rtc
   - But Frigate requires the camera audio to be in AAC, so that the clips, recordings and also Chromecast streaming works well
3. When streaming the Frigate camera from HA through RTSPToWebRTC, go2rtc automatically selects the RTSP stream rather than Frigate's own RTMP, which decreases the latency in 1-2 seconds.

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.2
