### ISSUE TITLE
Fix onvif source: invalid control character in URL

### ISSUE THREAD

**Issue by boerti71** [AlexxIT/go2rtc#662]
Hej!
I'm using Home assistant:
Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

I also edited the go2rtc.yaml file in Home assistants file editor:
```
streams:
  entre: onvif://admin:xxxxxxx@192.168.1.72:80
```
I also tried with
```
onvif://adminxxxxxx@192.168.1.72:80?subtype=MainStreamToken
```
but I alway get the Invalind character error.

here is the log...
```
17:39:09.132 INF go2rtc version 1.7.1 linux/amd64
17:39:09.132 INF [api] listen addr=0.0.0.0:1984
17:39:09.136 INF [rtsp] listen addr=0.0.0.0:8554
17:39:09.136 INF [webrtc] listen addr=0.0.0.0:8555/tcp
17:39:33.764 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: parse "\r\n": net/url: invalid control character in URL"
```
any ideas?

Thanks!

**Comment by AlexxIT** [comment]
It will be easier if you can provide access to your stream (80 port)
https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet

**Comment by AlexxIT** [comment]
#638

**Comment by AlexxIT** [comment]
@boerti71 have you tested fix?

**Comment by boerti71** [comment]
I'm sorry, but i installed in the meantime Frigate on an raspi 4...

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.0
