### ISSUE TITLE
Choppy camera sound in HomeKit

### ISSUE THREAD

**Issue by VladNord** [AlexxIT/go2rtc#667]
I have Hikvision camera with built-in microphone. 
When I watch the stream directly from go2rtc- flawless, but exported to HomeKit camera has choppy sound, picture is ok
Sound codec g711ulaw (tried another- no luck)

Here is config:

Thanks for help!

```
streams:
  home_cam_outdoor:
    - rtsp:/*****/ISAPI/Streaming/Channels/101
    - ffmpeg:home_cam_outdoor#audio=opus  

homekit:
  home_cam_outdoor:            
    pin: 12345678         
    name: home_cam_outdoor      
```

**Comment by AlexxIT** [comment]
Known problem

**Comment by civita** [comment]
It seems like this is related to incorrect timestamp increment (ts incr). According to [RFC 7587](https://datatracker.ietf.org/doc/html/rfc7587), ts incr of a 48k sampling rates and 20ms frame size will be `960`, or ts incr = `frame size(ms) * sampling rate(k)` I'm adding this into `srtp/session.go`. However, depends on connection type of iOS devices (Cellular/Wi-Fi), frame size will be other than 20 (60 on Cellular connection). Mismatched frame size results in no sound.

**Comment by civita** [comment]
Update: I am able to get HomeKit Opus Audio working on Cellular connection (frame size 60ms) by repacketize three 20ms frames into one packet (with some hard-coded blocks). It would be better if ffmpeg args can be modified after `SelectedStreamConfig` is retrieved from iOS devices.

**Comment by AlexxIT** [comment]
As said in the RFC 7587 - your timestamp wrong. But maybe Apple also doesn't respect this RFC.

```
   Opus supports 5 different audio bandwidths, which can be adjusted
   during a stream.  The RTP timestamp is incremented with a 48000 Hz
   clock rate for all modes of Opus and all sampling rates.  The unit
   for the timestamp is samples per single (mono) channel.  The RTP
   timestamp corresponds to the sample time of the first encoded sample
   in the encoded frame.  For data encoded with sampling rates other
   than 48000 Hz, the sampling rate has to be adjusted to 48000 Hz.
```

**Comment by civita** [comment]
You are correct. It looks like apple doesn't follow RFC 7587 for Opus audio according to [Hap spec](https://github.com/ljezny/Particle-HAP/blob/master/HAP-Specification-Non-Commercial-Version.pdf) (11.2.1 Streaming Requirements). Instead, timestamp is based on [RFC 3550](https://datatracker.ietf.org/doc/html/rfc3550#section-5.1). If I understand correctly, it uses "sampling period" as timestamp increment, so 48k sampling rate in 20ms frame will be: 0.02(s)*48000(1/s)=960. (somehow matches frame size(ms) * sampling rate(k))

**Comment by AlexxIT** [comment]
I have tested Scrypted (because I don't have HomeKit camera with OPUS support):
- Sample rate: 8000, RTPTime: 20, Config: 12, Code: 0, Time inc: 480
- Sample rate: 16000, RTPTime: 20, Config: 8, Code: 0, Time inc: 480
- Sample rate: 24000, RTPTime: 20, Config: 8, Code: 0, Time inc: 480
- Sample rate: 8000, RTPTime: 40, Config: 12, Code: 2, Time inc: 480
- Sample rate: 8000, RTPTime: 60, Config: 12, Code: 3, Time inc: 480
- Sample rate: 24000, RTPTime: 60, Config: 8, Code: 3, Time inc: 480

**Comment by AlexxIT** [comment]
And test for FFmpeg:
- Sample rate: 8000, Frame duration: 20, Config: 12, Code: 0, Time inc: 960
- Sample rate: 16000, Frame duration: 20, Config: 8, Code: 0, Time inc: 960
- Sample rate: 24000, Frame duration: 20, Config: 4, Code: 0, Time inc: 960
- Sample rate: 8000, Frame duration: 40, Config: 12, Code: 2, Time inc: 1920
- Sample rate: 8000, Frame duration: 60, Config: 12, Code: 3, Time inc: 2880
- Sample rate: 16000, Frame duration: 60, Config: 4, Code: 3, Time inc: 2880

**Comment by civita** [comment]
> I have tested Scrypted (because I don't have HomeKit camera with OPUS support):
> 
> * Sample rate: 8000, RTPTime: 20, Config: 19, Code: 0, Time inc: 480
> * Sample rate: 16000, RTPTime: 20, Config: 23, Code: 0, Time inc: 480
> * Sample rate: 24000, RTPTime: 20, Config: 23, Code: 0, Time inc: 480
> * Sample rate: 8000, RTPTime: 40, Config: 19, Code: 2, Time inc: 480
> * Sample rate: 8000, RTPTime: 60, Config: 19, Code: 3, Time inc: 480
> * Sample rate: 24000, RTPTime: 60, Config: 23, Code: 3, Time inc: 480

Are you using Scrypted as HomeKit camera input in go2rtc? No sure if constant 480 ts incr is due to this [`timekeeper`](https://github.com/AlexxIT/go2rtc/blob/master/pkg/homekit/client.go#L226).

> And test for FFmpeg:

This looks reasonable since it follows RFC 7587:

    +---------+-----------------+-----+-----+-----+-----+------+------+
    |   Mode  |        fs       | 2.5 |  5  |  10 |  20 |  40  |  60  |
    +---------+-----------------+-----+-----+-----+-----+------+------+
    | ts incr |       all       | 120 | 240 | 480 | 960 | 1920 | 2880 |
    |         |                 |     |     |     |     |      |      |
    |  voice  | NB/MB/WB/SWB/FB |  x  |  x  |  o  |  o  |  o   |  o   |
    |         |                 |     |     |     |     |      |      |
    |  audio  |   NB/WB/SWB/FB  |  o  |  o  |  o  |  o  |  x   |  x   |
    +---------+-----------------+-----+-----+-----+-----+------+------+

In my test I used generic rtsp camera and add audio=opus/16000:

```
streams:
  test:
    - ffmpeg:rtsp://...:...@.../...
    - ffmpeg:test#video=copy#audio=opus/16000
homekit:
  test:
    pin: ...
    pairings:
      - client_id=...
```

**Comment by AlexxIT** [comment]
You was right about "timekeeper". Thanks! It was made for AAC-ELD.
I have changed previous message about Scrypted.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.5
