### ISSUE TITLE
Aqara G4 Doorbell in frigate and also in HomeKit keeping HKSV

### ISSUE THREAD

**Issue by bgoncal** [AlexxIT/go2rtc#668]
Is it possible to pair the G4 with go2rtc, then use it in frigate and also expose the doorbell back to HomeKit keeping HKSV and two-way audio?

**Comment by AlexxIT** [comment]
Yes https://github.com/AlexxIT/go2rtc/releases/tag/v1.7.0

**Comment by husnainali09** [comment]
Does anyone have a basic howto or yaml part on how to achieve this ?
