### ISSUE TITLE
Upgrade from go2rtc version 1.2.0 linux/amd64 to go2rtc 1.7.0 on latest Frigate breaks MSE

### ISSUE THREAD

**Issue by atv2016** [AlexxIT/go2rtc#671]
Not sure when this happened, but i just upgraded my frigate from 12.0 to 13.0-beta2 and it does not show MSE streams in go2rtc anymore.

I logged this on frigate GitHub as well on https://github.com/blakeblackshear/frigate/issues/8056.

**Comment by atv2016** [comment]
@AlexxIT  Ok, so I loaded the config from go2rtc in frigate into a stand-alone go2rtc so it’s using the direct rtsp streams.

same behaviour, only webrtc works. Not sure if there is a workaround available by setting it so that it always opens in webrtc ?

**Comment by atv2016** [comment]
Not sure if helpful, but I’m using these cameras:

https://www.amazon.co.uk/gp/aw/d/B00KPSARL4?psc=1&ref=ppx_pop_mob_b_asin_title

**Comment by atv2016** [comment]
@AlexxIT Any update on this? From other issues here and in Webrtc as well it seems whatever changed in MSE has been a problem for many users. Can we identify and rollback those changes ?

**Comment by AlexxIT** [comment]
Well. No any useful info about this issue that can helps to find problem.

**Comment by atv2016** [comment]
I guess you can compare the go2rtc (1.2.0) used in frigate 0.12.0 and see what changed there for MSE ?
Is there any debug mode which can be turned on which would be useful ?

**Comment by AlexxIT** [comment]
Almost whole code base was rewritten since 1.2.0

**Comment by atv2016** [comment]
But it still must be limited to MSE. What changes were made there?
________________________________

**Comment by AlphaNumericPencil** [comment]
> Please let me know if the problem is relevant

Still an issue AFAIK. My Reolink E1 Zoom shows a black screen in preview and live mode, but streams fine in debug. Seems to be caused by this issue.

**Comment by AlexxIT** [comment]
Same advice https://github.com/AlexxIT/go2rtc/issues/671#issuecomment-1748846171
