### ISSUE TITLE
Aqara G2H not being discovered by go2rtc

### ISSUE THREAD

**Issue by bgoncal** [AlexxIT/go2rtc#672]
When I look for the list of HomeKit cameras available to pair, my Aqara G2H is not shown there, even though I just reseted it and it shows in Apple Home to pair again.

**Comment by AlexxIT** [comment]
Looks like you using go2rtc inside Frigate https://github.com/AlexxIT/go2rtc/issues/668
You SHOULD have network host for your Frigate container for HomeKit protocol

**Comment by bgoncal** [comment]
Gonna try, thanks!
