### ISSUE TITLE
RTSP Camera not loading

### ISSUE THREAD

**Issue by ivantse08** [AlexxIT/go2rtc#674]
Hey I'm having some issue just loading my BambuLab X1C Camera, the built in stream works great after I restart my printer but eventually the stream breaks and is stuck loading every time I try to reload the page at the built in page on 1984 it is stuck on loading. I am currently running go2rtc as a docker container and this is my config. There are no errors in the docker logs at the info or debug level and everything else is default. I am just trying to load the built in stream at stream.html
```
streams:
  camera1: 
   rtsps://${USERNAME}:${ACCESS_PASSWORD}@${CAMERA_IP}:322/streaming/live/1
```

**Comment by AlexxIT** [comment]
Can you explain in more detail when it works and when it doesn't work

**Comment by ivantse08** [comment]
It works when I reboot the printer and then I leave the stream running and I'm not exactly sure when it breaks maybe I refresh the page or something and then the stream just never loads again, I have home assistant with the generic camera integration that I set up with this link https://www.wolfwithsword.com/bambulabs-x1c-camera-in-home-assistant/ and it shows up there but is also sometimes quite buggy and needs a printer reboot to see the camera

**Comment by ivantse08** [comment]
I think I found out that whenever I reboot the pi without restarting the container it doesnt display and it just keeps being stuck on loading and only works on printer reboot

**Comment by AlexxIT** [comment]
What is pi? Your server with docker?

**Comment by MohammadAG** [comment]
I think this is an X1C firmware issue. I stumbled upon this issue while googling it and I'm not using go2rtc. Rebooting the printer fixes it until the next print starts and then it breaks again. It would be also be broken in anything else (VLC, Home Assistant, etc), except Bambu's slicer and the Bambu Handy app. I guess they pull the feed from somewhere else and not RTSP.

**Comment by ivantse08** [comment]
> What is pi? Your server with docker?

Yeah my raspberry pi that runs the go2rtc docker container, but it seems like it may be an X1C firmware issue as Mohammad stated that every time a print is added it breaks the RTSP feed however there are times the Bambu Camera where it'll show in Home Assistant but not on the go2rtc api.

**Comment by AlexxIT** [comment]
Maybe your camera just can't handle two simultaneous connection
