### ISSUE TITLE
Fix memory overflow on bad RTSP sources

### ISSUE THREAD

**Issue by fearlings123** [AlexxIT/go2rtc#675]
Hi,

I'm running the 1.7.1 Windows binary as a service (installed via NSSM). I average about 30 concurrent clients, with ~50 streams available.
Memory usage appears to slowly climb, until it peaks at 100% usage (in my case, 10GB). It takes about a week to reach this amount. 
Restarting the service resolves the issue. Usage goes back down to about 150MB.

There's nothing conspicuous in stdout. It could possibly be my custom client code, which has extensive reconnection logic, but the amount of clients remains constant (confirming via localhost:1984) so I don't think that is leaking.

What can I do track down the memory usage?

**Comment by AlexxIT** [comment]
Can you show output for `http://localhost:1984/api/streams`? You can do it in PM. It may contain some private data.

**Comment by fearlings123** [comment]
Here it is - i've removed IP addresses. Memory usage is currently stable, but over the past two days it has been at 100% usage. 
`
{"x.x.x.x/020/hd":{"producers":[{"url":"x.x.x.x/020/hd"}],"consumers":null},"x.x.x.x/025/hd":{"producers":[{"url":"x.x.x.x/025/hd"}],"consumers":null},"x.x.x.x/030/hd":{"producers":[{"url":"x.x.x.x/030/hd"}],"consumers":null},"x.x.x.x/035/hd":{"producers":[{"url":"x.x.x.x/035/hd"}],"consumers":null},"x.x.x.x/040/hd":{"producers":[{"url":"x.x.x.x/040/hd"}],"consumers":null},"x.x.x.x/045/hd":{"producers":[{"url":"x.x.x.x/045/hd"}],"consumers":null},"x.x.x.x/050/hd":{"producers":[{"url":"x.x.x.x/050/hd"}],"consumers":null},"x.x.x.x/055/hd":{"producers":[{"url":"x.x.x.x/055/hd"}],"consumers":null},"x.x.x.x/060/hd":{"producers":[{"url":"x.x.x.x/060/hd"}],"consumers":null},"x.x.x.x/065/hd":{"producers":[{"url":"x.x.x.x/065/hd"}],"consumers":null},"x.x.x.x/070/hd":{"producers":[{"url":"x.x.x.x/070/hd"}],"consumers":null},"x.x.x.x/075/hd":{"producers":[{"url":"x.x.x.x/075/hd"}],"consumers":null},"x.x.x.x/080/hd":{"producers":[{"url":"x.x.x.x/080/hd"}],"consumers":null},"x.x.x.x/085/hd":{"producers":[{"url":"x.x.x.x/085/hd"}],"consumers":null},"x.x.x.x/090/hd":{"producers":[{"url":"x.x.x.x/090/hd"}],"consumers":null},"x.x.x.x/095/hd":{"producers":[{"url":"x.x.x.x/095/hd"}],"consumers":null},"x.x.x.x/100/hd":{"producers":[{"url":"x.x.x.x/100/hd"}],"consumers":null},"x.x.x.x/105/hd":{"producers":[{"url":"x.x.x.x/105/hd"}],"consumers":null},"x.x.x.x/110/hd":{"producers":[{"url":"x.x.x.x/110/hd"}],"consumers":null},"x.x.x.x/115/hd":{"producers":[{"url":"x.x.x.x/115/hd"}],"consumers":null},"x.x.x.x/120/hd":{"producers":[{"url":"x.x.x.x/120/hd"}],"consumers":null},"x.x.x.x/125/hd":{"producers":[{"url":"x.x.x.x/125/hd"}],"consumers":null},"x.x.x.x/130/hd":{"producers":[{"url":"x.x.x.x/130/hd"}],"consumers":null},"x.x.x.x/135/hd":{"producers":[{"url":"x.x.x.x/135/hd"}],"consumers":null},"x.x.x.x/140/hd":{"producers":[{"url":"x.x.x.x/140/hd"}],"consumers":null},"x.x.x.x/145/hd":{"producers":[{"url":"x.x.x.x/145/hd"}],"consumers":null},"x.x.x.x/150/hd":{"producers":[{"url":"x.x.x.x/150/hd"}],"consumers":null},"x.x.x.x/155/hd":{"producers":[{"url":"x.x.x.x/155/hd"}],"consumers":null},"x.x.x.x/160/hd":{"producers":[{"url":"x.x.x.x/160/hd"}],"consumers":null},"x.x.x.x/165/hd":{"producers":[{"url":"x.x.x.x/165/hd"}],"consumers":null},"x.x.x.x/170/hd":{"producers":[{"url":"x.x.x.x/170/hd"}],"consumers":null},"x.x.x.x/175/hd":{"producers":[{"url":"x.x.x.x/175/hd"}],"consumers":null},"x.x.x.x/180/hd":{"producers":[{"url":"x.x.x.x/180/hd"}],"consumers":null},"x.x.x.x/183/hd":{"producers":[{"url":"x.x.x.x/183/hd"}],"consumers":null},"rtsp://x.x.x.x/001/hd":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/001/hd","remote_addr":"x.x.x.x:11011","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=- 1234 1234 IN IP4 localhost\r\ns=Streamserver\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 profile-level-id=42002a; packetization-mode=1; sprop-parameter-sets=Z0IAKpY1QPAET8s3AQEBQAAAAwBAAAAMIQ==,aM4xsg==\r\na=framerate:25\r\n\r\n","medias":["video, recvonly, H.264 Baseline 4.2"],"receivers":["96 H264, bytes=489620722, senders=2"],"recv":495610858}],"consumers":[{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:61589 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=489620722, receivers=1"],"send":496417013},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:63442 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=489282515, receivers=1"],"send":496074865}]},"rtsp://x.x.x.x/004/hd":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/004/hd","remote_addr":"x.x.x.x:11011","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=- 1234 1234 IN IP4 localhost\r\ns=Streamserver\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 profile-level-id=42002a; packetization-mode=1; sprop-parameter-sets=Z0IAKpY1QPAET8s3AQEBQAAAAwBAAAAKIQ==,aM4xsg==\r\na=framerate:25\r\n\r\n","medias":["video, recvonly, H.264 Baseline 4.2"],"receivers":["96 H264, bytes=517392947, senders=2"],"recv":523345787}],"consumers":[{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:61585 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=517392947, receivers=1"],"send":524202108},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:57959 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=516779218, receivers=1"],"send":523581402}]},"rtsp://x.x.x.x/010/hd":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/010/hd","remote_addr":"x.x.x.x:11011","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=- 1234 1234 IN IP4 localhost\r\ns=Streamserver\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 profile-level-id=42002a; packetization-mode=1; sprop-parameter-sets=Z0IAKpY1QPAET8s3AQEBQAAAAwBAAAAMIQ==,aM4xsg==\r\na=framerate:25\r\n\r\n","medias":["video, recvonly, H.264 Baseline 4.2"],"receivers":["96 H264, bytes=627102533, senders=4"],"recv":634009049}],"consumers":[{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:61577 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=627102533, receivers=1"],"send":635055032},{"type":"RTSP passive consumer","url":"rtsp://aisaqumpirtsp01:8554/rtsp://x.x.x.x/010/hd","remote_addr":"x.x.x.x:50475","user_agent":"CmRtspClient 11.1a.427","sdp":"v=0\r\no=- 1 1 IN IP4 x.x.x.x\r\ns=go2rtc/1.7.1\r\nc=IN IP4 x.x.x.x\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=42002a; packetization-mode=1; sprop-parameter-sets=Z0IAKpY1QPAET8s3AQEBQAAAAwBAAAAMIQ==,aM4xsg==\r\na=control:trackID=0\r\n","medias":["video, sendonly, ANY","audio, sendonly, ANY"],"senders":["96 H264, bytes=626987440, receivers=1"],"send":636194752},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:52303 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=588960307, receivers=1"],"send":596476086},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:58446 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=583738934, receivers=1"],"send":591194274}]},"rtsp://x.x.x.x/015/hd":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/015/hd","remote_addr":"x.x.x.x:11011","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=- 1234 1234 IN IP4 localhost\r\ns=Streamserver\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 profile-level-id=420032; packetization-mode=1; sprop-parameter-sets=Z0IAMpY1QFEB6/LNwEBAUAAAAwAQAAADAehA,aM4xsg==\r\na=framerate:25\r\n\r\n","medias":["video, recvonly, H.264 Baseline 5.0"],"receivers":["96 H264, bytes=130664549, senders=3"],"recv":131952449}],"consumers":[{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:58947 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=887647431, receivers=1"],"send":897724656},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:61581 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=887647431, receivers=1"],"send":897724656},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:54692 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=887168727, receivers=1"],"send":897240748}]},"rtsp://x.x.x.x/020/hd":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/020/hd","remote_addr":"x.x.x.x:11011","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=- 1234 1234 IN IP4 localhost\r\ns=Streamserver\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 profile-level-id=420032; packetization-mode=1; sprop-parameter-sets=Z0IAMpY1QFEB6/LNwEBAUAAAAwAQAAADAYhA,aM4xsg==\r\na=framerate:25\r\n\r\n","medias":["video, recvonly, H.264 Baseline 5.0"],"receivers":["96 H264, bytes=130788207, senders=2"],"recv":132097287}],"consumers":[{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:59687 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=914523963, receivers=1"],"send":924532801},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:57999 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=914042938, receivers=1"],"send":924046631}]},"rtsp://x.x.x.x/025/hd":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/025/hd","remote_addr":"x.x.x.x:11011","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=- 1234 1234 IN IP4 localhost\r\ns=Streamserver\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 profile-level-id=420032; packetization-mode=1; sprop-parameter-sets=Z0IAMpY1QFEB6/LNwEBAUAAAAwAQAAADAehA,aM4xsg==\r\na=framerate:25\r\n\r\n","medias":["video, recvonly, H.264 Baseline 5.0"],"receivers":["96 H264, bytes=1357622, senders=1"],"recv":1370606}],"consumers":[{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:50990 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=860305368, receivers=1"],"send":869960234}]},"rtsp://x.x.x.x/030/hd":{"producers":[{"url":"rtsp://x.x.x.x/030/hd"}],"consumers":null},"rtsp://x.x.x.x/035/hd":{"producers":[{"url":"rtsp://x.x.x.x/035/hd"}],"consumers":null},"rtsp://x.x.x.x/040/hd":{"producers":[{"url":"rtsp://x.x.x.x/040/hd"}],"consumers":null},"rtsp://x.x.x.x/045/hd":{"producers":[{"url":"rtsp://x.x.x.x/045/hd"}],"consumers":null},"rtsp://x.x.x.x/050/hd":{"producers":[{"url":"rtsp://x.x.x.x/050/hd"}],"consumers":null},"rtsp://x.x.x.x/055/hd":{"producers":[{"url":"rtsp://x.x.x.x/055/hd"}],"consumers":null},"rtsp://x.x.x.x/060/hd":{"producers":[{"url":"rtsp://x.x.x.x/060/hd"}],"consumers":null},"rtsp://x.x.x.x/065/hd":{"producers":[{"url":"rtsp://x.x.x.x/065/hd"}],"consumers":null},"rtsp://x.x.x.x/070/hd":{"producers":[{"url":"rtsp://x.x.x.x/070/hd"}],"consumers":null},"rtsp://x.x.x.x/075/hd":{"producers":[{"url":"rtsp://x.x.x.x/075/hd"}],"consumers":null},"rtsp://x.x.x.x/080/hd":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/080/hd","remote_addr":"x.x.x.x:11011","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=- 1234 1234 IN IP4 localhost\r\ns=Streamserver\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=range:npt=0-\r\na=framerate:0S\r\na=fmtp:96 profile-level-id=42002a; packetization-mode=1; sprop-parameter-sets=Z0IAKpY1QPAET8s3AQEBQAAAAwBAAAAKIQ==,aM4xsg==\r\na=framerate:25\r\n\r\n","medias":["video, recvonly, H.264 Baseline 4.2"],"receivers":["96 H264, bytes=467832928, senders=2"],"recv":473129128}],"consumers":[{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:62789 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=467832928, receivers=1"],"send":473845653},{"type":"WebRTC/WebSocket async passive consumer","remote_addr":"udp4 prflx x.x.x.x:58086 related :0","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=467558556, receivers=1"],"send":473568160}]},"rtsp://x.x.x.x/085/hd":{"producers":[{"url":"rtsp://x.x.x.x/085/hd"}],"consumers":null},"rtsp://x.x.x.x/090/hd":{"producers":[{"url":"rtsp://x.x.x.x/090/hd"}],"consumers":[]},"rtsp://x.x.x.x/095/hd":{"producers":[{"url":"rtsp://x.x.x.x/095/hd"}],"consumers":null},"rtsp://x.x.x.x/100/hd":{"producers":[{"url":"rtsp://x.x.x.x/100/hd"}],"consumers":null},"rtsp://x.x.x.x/105/hd":{"producers":[{"url":"rtsp://x.x.x.x/105/hd"}],"consumers":null},"rtsp://x.x.x.x/110/hd":{"producers":[{"url":"rtsp://x.x.x.x/110/hd"}],"consumers":null},"rtsp://x.x.x.x/115/hd":{"producers":[{"url":"rtsp://x.x.x.x/115/hd"}],"consumers":null},"rtsp://x.x.x.x/120/hd":{"producers":[{"url":"rtsp://x.x.x.x/120/hd"}],"consumers":null},"rtsp://x.x.x.x/125/hd":{"producers":[{"url":"rtsp://x.x.x.x/125/hd"}],"consumers":null},"rtsp://x.x.x.x/130/hd":{"producers":[{"url":"rtsp://x.x.x.x/130/hd"}],"consumers":null},"rtsp://x.x.x.x/135/hd":{"producers":[{"url":"rtsp://x.x.x.x/135/hd"}],"consumers":null},"rtsp://x.x.x.x/140/hd":{"producers":[{"url":"rtsp://x.x.x.x/140/hd"}],"consumers":null},"rtsp://x.x.x.x/145/hd":{"producers":[{"url":"rtsp://x.x.x.x/145/hd"}],"consumers":null},"rtsp://x.x.x.x/150/hd":{"producers":[{"url":"rtsp://x.x.x.x/150/hd"}],"consumers":null},"rtsp://x.x.x.x/155/hd":{"producers":[{"url":"rtsp://x.x.x.x/155/hd"}],"consumers":null},"rtsp://x.x.x.x/160/hd":{"producers":[{"url":"rtsp://x.x.x.x/160/hd"}],"consumers":null},"rtsp://x.x.x.x/164/hd":{"producers":[{"url":"rtsp://x.x.x.x/164/hd"}],"consumers":null},"rtsp://x.x.x.x/0":{"producers":[{"url":"rtsp://x.x.x.x/0"}],"consumers":null},"rtsp://x.x.x.x/0":{"producers":[{"type":"RTSP active producer","url":"rtsp://x.x.x.x/0","remote_addr":"x.x.x.x:554","user_agent":"go2rtc/1.7.1","sdp":"v=0\r\no=StreamingServer 3433055887 1686246298345535 IN IP4 x.x.x.x\r\ns=0\r\ne=NONE\r\nc=IN IP4 x.x.x.x\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\nb=AS:70\r\na=control:trackID=1\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=64002a;packetization-mode=1;sprop-parameter-sets=Z2QAKq2EAQwgCGEAQwgCGEAQwgCEK1A8ARPyzcBAQECA,aO48sA==\r\nm=audio 0 RTP/AVP 8\r\nb=AS:48\r\na=control:trackID=2\r\na=rtpmap:8 PCMA/8000/1\r\na=framerate:25\r\na=Media_header:MEDIAINFO=494D4B48010100000400010000000000000000000000000000000000000000000000000000000000\r\n","medias":["video, recvonly, H.264 High 4.2","audio, recvonly, PCMA/8000"],"receivers":["96 H264, bytes=253731336, senders=4","8 PCMA/8000, bytes=4884800, senders=4"],"recv":261014228}],"consumers":[{"type":"MSE/WebSocket active consumer","remote_addr":"x.x.x.x:65344","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"],"senders":["96 H264, bytes=0, receivers=1","8 FLAC/8000, bytes=0, receivers=1"]},{"type":"WebRTC/WebSocket async passive consumer","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=0, receivers=1","8 PCMA/8000, bytes=0, receivers=1"]},{"type":"MSE/WebSocket active consumer","remote_addr":"x.x.x.x:64165","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, H264, H265","audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"],"senders":["96 H264, bytes=0, receivers=1","8 FLAC/8000, bytes=0, receivers=1"]},{"type":"WebRTC/WebSocket async passive consumer","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/x.x.x.x Safari/537.36","medias":["video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03","audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"],"senders":["102 H264, bytes=0, receivers=1","8 PCMA/8000, bytes=0, receivers=1"]}]},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null},"rtsp://x.x.x.x:554/1":{"producers":[{"url":"rtsp://x.x.x.x:554/1"}],"consumers":null},"rtsp://x.x.x.x:554":{"producers":[{"url":"rtsp://x.x.x.x:554"}],"consumers":null},"rtsp://x.x.x.x:554/0":{"producers":[{"url":"rtsp://x.x.x.x:554/0"}],"consumers":null}}`

**Comment by AlexxIT** [comment]
Well. I need this file when memory is high. Also you can provide `http://localhost:1984/api/stack` (when memory high).

**Comment by fearlings123** [comment]
Apologies for delay, it has taken approximately a week to get back to high memory usage.

Usage is just below 10GB. Stack and Streams are attached, with IP addresses removed.

![image](https://github.com/AlexxIT/go2rtc/assets/82689809/d055861d-6501-430d-8735-928b8e03ec82)

[stack.txt](https://github.com/AlexxIT/go2rtc/files/12923161/stack.txt)
[streams.json](https://github.com/AlexxIT/go2rtc/files/12923162/streams.json)

**Comment by AlexxIT** [comment]
Can check it on next week

**Comment by fearlings123** [comment]
pprof heap with high usage
![image](https://github.com/AlexxIT/go2rtc/assets/82689809/d689f0c2-a645-481d-beb3-7755e71de5c6)

**Comment by fearlings123** [comment]
![16gbdump](https://github.com/AlexxIT/go2rtc/assets/82689809/a8bc5a48-d581-45b3-a0ab-7fadad10695e)
Websockets not getting disposed? I currently have 21 clients watching 5 different streams.

**Comment by AlexxIT** [comment]
Thanks. Your research is very helpful. I'll look deep to it

**Comment by AlexxIT** [comment]
I think this can happen with bad RTSP sources on very hi packets miss.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.2

You can reopen issue if problem still exists
