### ISSUE TITLE
Feature REQ: Point to SSL files instead of copy/pasting the content

### ISSUE THREAD

**Issue by pergolafabio** [AlexxIT/go2rtc#680]
Hi, would it b possible to point to a file/path instead of copy/pasting the content like below?

```
  tls_cert: |        # default "", PEM-encoded fullchain certificate for HTTPS
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  tls_key: |         # default "", PEM-encoded private key for HTTPS
    -----BEGIN PRIVATE KEY-----
    ...
    -----END PRIVATE KEY-----
```

When using SSL with lets encrypt, the certficates need to be renewed every 90 days

thnx!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.0

**Comment by pergolafabio** [comment]
Wow, that's great, thnx!

**Comment by pergolafabio** [comment]
Hi @AlexxIT , i tried new version  but always receive error on opening file?
The files are stored in SSL dir:

![image](https://github.com/AlexxIT/go2rtc/assets/43251136/ef4df11d-840b-4c83-8d11-5f10c535ba61)

`17:38:29.757 ERR github.com/AlexxIT/go2rtc/internal/api/api.go:97 > error="open fullchain.pem: no such file or directory"`

tried like:

```
  tls_cert: fullchain.pem
  tls_key: privkey.pem
```

and

```
  tls_cert: /ssl/fullchain.pem
  tls_key: /ssl/privkey.pem
```

any idea?

**Comment by AlexxIT** [comment]
go2rtc addon doesn't have access to this folder. Don't knot about Frigate

**Comment by pergolafabio** [comment]
ah, but that ssl share is used by HA to store the centificalte files created, is has nothing todo with Frigate?

**Comment by pergolafabio** [comment]
can you added access to the ssl share in the addon?

**Comment by pergolafabio** [comment]
this line?

https://github.com/AlexxIT/hassio-addons/blob/master/go2rtc/config.yaml#L20

**Comment by pergolafabio** [comment]
Ok I forked your repo, and adding SSL to the mapping works... Can you also add it to yours? So I can stay uptodate with your addon?

The ask share is a default share used but HA to drop the SSL files, created by add-ons like , let's encrypt

Thnx, much appreciated!!

**Comment by AlexxIT** [comment]
ssl directory added to go2rtc addon

**Comment by markuslosco** [comment]
hey folk.. thanks for that builder.sh but i am using go2rtc with windows.. does someone have a idea?
