### ISSUE TITLE
Aqara G4 working fine in HomeKit (via go2rtc) and WebRTC but not RTSP

### ISSUE THREAD

**Issue by bgoncal** [AlexxIT/go2rtc#683]
I just spent an hour trying to use Aqara G4 doorbell in HomeKit and also in Frigate, but for some reason RTSP is not working at all, the stream can't be opened (not in VLC/frigate/scrypted), I was reading the documentation and I couldn't find any special configuration I needed to do, I should just be able to use RTSP after pairing the doorbell through HomeKit right?

Im running go2rtc in a docker container on a intel I7 mini PC
go2rtc version: 1.7.1

Edit:
Via webrtc and apple home It works properly

**Comment by bgoncal** [comment]
Ok... there is something to do with my docker setup, in home assistant add-on it works fine, any idea what it could be @AlexxIT ?

**Comment by NickM-27** [comment]
is your docker container running with host networking mode?

**Comment by bgoncal** [comment]
@NickM-27 Yes

**Comment by bgoncal** [comment]
My bad, I should have closed it. done.

**Comment by AlexxIT** [comment]
What about G2H? Same problem with RTSP and all ok with WebRTC?

**Comment by AlexxIT** [comment]
Have your checked logs. Maybe RTSP port taken by some other app. Or even some other go2rtc...

**Comment by bgoncal** [comment]
<img width="758" alt="Screenshot 2023-10-12 at 15 30 13" src="https://github.com/AlexxIT/go2rtc/assets/5808343/2d42f9b7-7b93-44fb-91a5-a304467ba5ae">

That was it, thank you!

**Comment by almirus** [comment]
[bgoncal](https://github.com/bgoncal) hi! Can you tell me if the image quality through HomeKit (HA) is normal? My picture is heavily compressed and doesn’t always display in live mode. I have a G2H camera, and its picture quality is better, with smooth video.

**Comment by bgoncal** [comment]
> [bgoncal](https://github.com/bgoncal) hi! Can you tell me if the image quality through HomeKit (HA) is normal? My picture is heavily compressed and doesn’t always display in live mode. I have a G2H camera, and its picture quality is better, with smooth video.

Sorry I don't own this doorbell anymore, moved to UniFi G4

**Comment by almirus** [comment]
![image](https://github.com/AlexxIT/go2rtc/assets/16898685/e1a6564c-2509-425c-af2d-27e6b00ada1b)

And when you had a doorbell, did the picture suit you?
