### ISSUE TITLE
please is there a demo on how to use it outside NAT ?

### ISSUE THREAD

**Issue by Abdeladim101Basraoui** [AlexxIT/go2rtc#69]
I'm trying to use the solution to get RTSP camera to webrtc to get displayed in the browser but each time don't work properly ,would you please create or maybe refer me to a demo ,I've seen the NAT hole punching mechanism but no clue

**Comment by AlexxIT** [comment]
All config examples in the docs:
https://github.com/AlexxIT/go2rtc#module-webrtc
