### ISSUE TITLE
Frigate lovelac card + go2rtc stream ? 

### ISSUE THREAD

**Issue by Sygnus83** [AlexxIT/go2rtc#692]
Hi !

Do I understand correctly that if I have a go2rtc stream, I can display it with the frigate card without installing frigate?

 "PS. There is also another nice card with go2rtc support - [Frigate Lovelace Card](https://github.com/dermotduffy/frigate-hass-card)."

My problem....

The stream from the camera is available in go2rtc, and showing good.
But I can’t configure the frigate card.

Could you describe a sample of the configuration?

Thanks

**Comment by AlexxIT** [comment]
Maybe it's better to ask in the card's repo. I never used this card.

**Comment by Sygnus83** [comment]
> Maybe it's better to ask in the card's repo. I never used this card.


Okay, thank you. It was in your description, so I thought I might get a solution here.
