### ISSUE TITLE
help configure WHIP obs stream

### ISSUE THREAD

**Issue by name-snrl** [AlexxIT/go2rtc#693]
I apologize for such a simple question. I've read readme 3 times, but I still don't understand how to do what I want to do.

I have a static IP, I know how to forward port through my router. `OBS` and `go2rtc` running on same Windows 10 LTSC pc. I want to publish the stream on my IP, on a specific port where only the stream will be, and hide everything else.

My config for now:

- `go2rtc`:
  ```yaml
  stream:
    stream: {}

  webrtc:
    candidates:
      - <my IP>:80
  ```
- `OBS`:
  Service `WHIP`
  Server `http://localhost:1984/api/webrtc?dst=stream`
- And I forward 80 external port to 8555 internal port in my router.

---

`OBS` connected to `go2rtc` and I can watch the stream, but it goes to the 1984 port. Is there any way I can change my configurations to safely publish my stream to the outside, or is this only possible with a reverse proxy?

**Comment by AlexxIT** [comment]
You need to use reverse proxy like nginx. Or use webtorrent sharing, check go2rtc docs

**Comment by name-snrl** [comment]
> check go2rtc

I've already read this, but I don't know anything about webRTC or webtorrent, to really understand the doc. I'm a simple guy who wants to share my screen in good quality and low latency with a friend.

**Comment by AlexxIT** [comment]
Well. Open WebUI, select your stream, goto links page, click to share link, click to copy link, send link to your friend.
