### ISSUE TITLE
Update from version v1.2.0 to v1.8.1 for Frigate running in container on TrueNAS Scale

### ISSUE THREAD

**Issue by MrMewCakes** [AlexxIT/go2rtc#700]
Hi noob here,

I'm trying to update my go2rtc to a later version. I've been trying to follow along with notes from this [ticket ](https://github.com/AlexxIT/go2rtc/issues/430) but have been unsuccessful so far.

I've downloaded go2rtc_linux_amd64, renamed it to go2rtc and placed it in frigate/config/
Then went to the shell in TrueNAS and ran the following:
![image](https://github.com/AlexxIT/go2rtc/assets/12710776/f6a59478-3caa-4fd3-afe6-ac50b3f74943)

I've restarted the container a few times but go2rtc is still showing as v1.2.0

Would appreciate some direction on how to update this in TrueNAS scale :)

**Comment by AlexxIT** [comment]
Maybe better to ask in the fridge repo

**Comment by MrMewCakes** [comment]
> Maybe better to ask in the fridge repo

fair enough, will do :)
