### ISSUE TITLE
ONVIF invalid port

### ISSUE THREAD

**Issue by Alexandros89** [AlexxIT/go2rtc#703]
hi,
i'm trying to add a onvif camera, that with the home assistant integration works fine, when i try to add the stream on go2rtc i receive this error:
parse   "onvif://admin:*****@192.168.1.174:8000": invalid port   ":Tcr23" after host

**Comment by AlexxIT** [comment]
Maybe it's your password

**Comment by Alexandros89** [comment]
Only online i put the *.
The url i take directly from the go2rtc on homeassistant

**Comment by AlexxIT** [comment]
Probably you have problem symbols in your password

**Comment by Alexandros89** [comment]
have i to put it easier ?

**Comment by Alexandros89** [comment]
I have resolved removing the "?" from the password
