### ISSUE TITLE
Fix wrong SDP for MERCURY camera

### ISSUE THREAD

**Issue by wiz-anzhen** [AlexxIT/go2rtc#708]
```
0:40:04.302 TRC [rtsp] client response:
RTSP/1.0 200 OK
Content-Base: rtsp://10.0.0.94:554/stream2/
Content-Type: application/sdp
Content-Length: 478
Cseq: 2
Date: Fri, Oct 20 2023 02:40:02 GMT

v=0
o=- 14665860 31787219 1 IN IP4 10.0.0.94
s=Session streamed by "MERCURY RTSP Server"
t=0 0
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:4096
a=range:npt=0-
a=control:track1
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; profile-level-id=640016; sprop-parameter-sets=Z2QAFqzGoCgPaEAAAAMAQAAAB6E=,aOqPLA==
m=audio 0 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=control:track2
m=application/MERCURY 0 RTP/AVP smart/1/90000
a=rtpmap:95 MERCURY/90000
a=control:track3

10:40:04.303 TRC [streams] skip prod=rtsp://admin:play4u88A@10.0.0.94:554/stream2 error="sdp: invalid value `application/MERCURY`"
2
10:40:09.583 DBG [streams] can't stop none producer
10:40:09.583 ERR internal/mjpeg/init.go:166 > error="streams: sdp: invalid value `application/MERCURY`"
```

**Comment by wiz-anzhen** [comment]
10:33:17.064 TRC [streams] skip prod=rtsp://admin:play4u88A@10.0.0.94:554/stream2 error=EOF
10:34:04.000 DBG [mp4] add consumer error="streams: sdp: invalid value `application/MERCURY`, EOF"
10:34:04.000 TRC [streams] skip prod=rtsp://admin:play4u88A@10.0.0.94:554/stream2 error="dial tcp 10.0.0.94:554: i/o timeout"
10:40:01.200 TRC [api.ws] msg type=mjpeg
10:40:01.200 DBG [streams] can't stop none producer
10:40:03.324 TRC [streams] check cons=0 media=video, sendonly, JPEG
10:40:03.324 DBG [webrtc] add consumer error="streams: EOF, dial tcp 10.0.0.94:554: i/o timeout"
10:40:03.676 TRC [rtsp] client request:
DESCRIBE rtsp://10.0.0.94:554/stream2 RTSP/1.0
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.8.1
CSeq: 1

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.2
