### ISSUE TITLE
Consider participating of Hacktoberfest

### ISSUE THREAD

**Issue by felipecrs** [AlexxIT/go2rtc#71]
Perhaps we can attract some external contributors, or at least this would help PRs against this repo to count towards the prize. It's as simple as adding the `hacktoberfest` to the GitHub topics/tags of the repo.

**Comment by AlexxIT** [comment]
Just need to add `hacktoberfest` to the tags? No problem.

**Comment by felipecrs** [comment]
Thanks a lot!
