### ISSUE TITLE
Fix panic for HomeKit source without SRTP module

### ISSUE THREAD

**Issue by wiz-anzhen** [AlexxIT/go2rtc#712]
```
api:
  listen: ':33223'
rtsp:
  listen: '127.0.0.1:38554'
srtp:
  listen: ''
streams:
  g3: 
    - homekit://10.0.0.169:32797?device_id=6F:7A:29:67:8B:E3&client_id=c91223d3-58bb-42c5-b987-38838495e37a&device_public=55221fa9f1afaafa725a5bf45a9229faf27ac9dd88a208589dc012990d04f188&client_private=9cd48d3b2d8c898ae288f21d8ad062ad51cd83c0112b24cf57fe7670bf757046eb535ec7e29c13b57bfdb41a827fb0dae23551fbea454741c25a9781cd30dbf5
    - ffmpeg:g3#audio=aac#audio=opus

log:
  format: ''
  level: trace
```

```
14:45:46.064 TRC [streams] check cons=0 media=audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS
14:45:46.068 TRC [streams] check prod=0 media=video, recvonly, H264
14:45:46.068 TRC [streams] check prod=0 media=audio, recvonly, ELD/16000/1
14:45:46.068 TRC [streams] check prod=0 media=video, recvonly, JPEG
14:45:46.189 TRC [rtsp] server request:
OPTIONS rtsp://127.0.0.1:38554/g3?audio RTSP/1.0
Cseq: 1
User-Agent: go2rtc/ffmpeg


14:45:46.189 TRC [rtsp] server response:
RTSP/1.0 200 OK
Cseq: 1
Public: OPTIONS, SETUP, TEARDOWN, DESCRIBE, PLAY, PAUSE, ANNOUNCE, RECORD


14:45:46.190 TRC [rtsp] server request:
DESCRIBE rtsp://127.0.0.1:38554/g3?audio RTSP/1.0
User-Agent: go2rtc/ffmpeg
Accept: application/sdp
Cseq: 2


14:45:46.190 DBG [rtsp] new consumer stream=g3
14:45:46.190 TRC [streams] check cons=2 media=audio, sendonly, ANY
14:45:46.190 TRC [streams] check prod=0 media=video, recvonly, H264
14:45:46.190 TRC [streams] check prod=0 media=audio, recvonly, ELD/16000/1
14:45:46.190 TRC [streams] match prod=0 => cons=2
14:45:46.190 DBG [streams] start producer url=homekit://10.0.0.169:32797?device_id=6F:7A:29:67:8B:E3&client_id=c91223d3-58bb-42c5-b987-38838495e37a&device_public=55221fa9f1afaafa725a5bf45a9229faf27ac9dd88a208589dc012990d04f188&client_private=9cd48d3b2d8c898ae288f21d8ad062ad51cd83c0112b24cf57fe7670bf757046eb535ec7e29c13b57bfdb41a827fb0dae23551fbea454741c25a9781cd30dbf5
14:45:46.190 TRC [rtsp] server response:
RTSP/1.0 200 OK
Content-Length: 267
Content-Type: application/sdp
Cseq: 2

v=0
o=- 1 1 IN IP4 0.0.0.0
s=go2rtc/1.8.1
c=IN IP4 0.0.0.0
t=0 0
m=audio 0 RTP/AVP 96
a=rtpmap:96 MPEG4-GENERIC/16000/1
a=fmtp:96 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=f8ec3000
a=control:trackID=0

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c9f164]

goroutine 56 [running]:
github.com/AlexxIT/go2rtc/pkg/srtp.(*Server).Port(0x0)
	/Users/anzhen/bnwGit/go2rtc/pkg/srtp/server.go:25 +0x24
github.com/AlexxIT/go2rtc/pkg/homekit.(*Client).srtpEndpoint(0x140001760d0)
	/Users/anzhen/bnwGit/go2rtc/pkg/homekit/client.go:219 +0x54
github.com/AlexxIT/go2rtc/pkg/homekit.(*Client).Start(0x140001760d0)
	/Users/anzhen/bnwGit/go2rtc/pkg/homekit/client.go:131 +0x268
github.com/AlexxIT/go2rtc/internal/streams.(*Producer).worker(0x14000150a20, {0x104f0dad8, 0x140001760d0}, 0x1)
	/Users/anzhen/bnwGit/go2rtc/internal/streams/producer.go:162 +0x40
created by github.com/AlexxIT/go2rtc/internal/streams.(*Producer).start in goroutine 54
	/Users/anzhen/bnwGit/go2rtc/internal/streams/producer.go:158 +0x264
rtsp://127.0.0.1:38554/g3?audio: Invalid data found when processing input
Process 13100 has exited with status 2
Detaching
```

**Comment by AlexxIT** [comment]
You can't use homekit source without SRTP.

**Comment by wiz-anzhen** [comment]
api:
  listen: ':33223'
rtsp:
  listen: '127.0.0.1:38554'
srtp:
  listen: ':38556'
streams:
  HK_54ef445955cf_webcam:
    - >-
      homekit://10.0.0.119:34465?device_id=B9:67:3D:CB:41:A5&client_id=ad245822-2e01-4e36-b419-629e52662419&device_public=f44cfbb49bad8fb9bba7b75598853b7ba2a5a8b4d8bd31b2b69ed30a00ec8ac0&client_private=455d831404be8e73fceb589bade644bbec5ed50e96781a8f56fdc6a0d8e83eed7e90904421fd790cc1b4019796445269962936966c1bf1147454d5063fb32526
    - 'ffmpeg:HK_54ef445955cf_webcam#audio=aac#audio=opus'
log:
  format: ''
  level: trace




12:26:53.004 TRC [streams] skip prod=homekit://10.0.0.119:34465?device_id=B9:67:3D:CB:41:A5&client_id=ad245822-2e01-4e36-b419-629e52662419&device_public=f44cfbb49bad8fb9bba7b75598853b7ba2a5a8b4d8bd31b2b69ed30a00ec8ac0&client_private=455d831404be8e73fceb589bade644bbec5ed50e96781a8f56fdc6a0d8e83eed7e90904421fd790cc1b4019796445269962936966c1bf1147454d5063fb32526 error="dial tcp 10.0.0.119:34465: i/o timeout"
12:26:53.004 DBG [exec] run url="exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:38554/HK_54ef445955cf_webcam?audio -map 0:a:0? -c:a:0 aac -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
Unrecognized option 'application:a:1'.
Error splitting the argument list: Option not found
12:26:53.013 TRC [streams] skip prod=ffmpeg:HK_54ef445955cf_webcam#audio=aac#audio=opus error="exec: exit status 1"

**Comment by wiz-anzhen** [comment]
http://10.0.0.21:33223/webrtc.html?src=HK_54ef442db40d_webcam&media=video+audio

can not  listen anything

**Comment by wiz-anzhen** [comment]
can play video

**Comment by wiz-anzhen** [comment]
delete #opus  params

[rtsp @ 0x437d5c0] Unable to open RTSP for listening
rtsp://127.0.0.1:38554/HK_54ef444c9a71_webcam?audio: Address already in use
15:31:22.915 TRC [streams] skip prod=ffmpeg:HK_54ef444c9a71_webcam#audio=aac error="exec: exit status 1"
15:31:22.915 DBG [streams] start producer url=homekit://10.0.0.93:33013?device_id=DE:78:55:56:F0:CF&client_id=9fccf012-46df-4871-8357-6e3624493495&device_public=da6df260b5ef4178cfd70435fa3fa1383b7749ed4450cfa42fff6fa3206faedd&client_private=4edcff9d5a20ac3df20142be22b7ecaf62a9d2b9dd193f728f462c4d4718512d5eecc6d12c247b15f79f55e737d1d2406e4c680755aeef25b0e49b39d1f3b918
15:31:22.915 DBG [exec] run url="exec:ffmpeg -hide_banner -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_flags prefer_tcp -i rtsp://127.0.0.1:38554/HK_54ef444c9a71_webcam?audio -c:a aac -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
[rtsp @ 0x32095c0] Unable to open RTSP for listening
rtsp://127.0.0.1:38554/HK_54ef444c9a71_webcam?audio: Address already in use

**Comment by AlexxIT** [comment]
I don't know how you install go2rtc. Probably you just using some outdated ffmpeg version

**Comment by wiz-anzhen** [comment]
root@OpenWrt-GXNAS:/# ffmpeg -version
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
configuration: --extra-cflags=-static --extra-ldflags=-static --pkg-config-flags=--static --enable-static --disable-shared --enable-libfdk-aac --enable-nonfree --enable-gpl --enable-libx264
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

**Comment by wiz-anzhen** [comment]
download https://github.com/AlexxIT/go2rtc/releases/download/v1.8.1/go2rtc_linux_amd64

**Comment by wiz-anzhen** [comment]
ffmpeg compile by myself

**Comment by wiz-anzhen** [comment]
I want to know this answer


[rtsp @ 0x32095c0] Unable to open RTSP for listening
rtsp://127.0.0.1:38554/HK_54ef444c9a71_webcam?audio: Address already in use

**Comment by AlexxIT** [comment]
4 version unsupported. Docker image uses 6 version! But it should also work with 5 version.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.2
