### ISSUE TITLE
Issue Aqara g3 - No Entity ID

### ISSUE THREAD

**Issue by julioarruda** [AlexxIT/go2rtc#713]
I`m trying to configure go2rtc with my HASS in a docker container, but i`m receiving this error:
![image](https://github.com/AlexxIT/go2rtc/assets/5204009/6c10369c-3a24-44d8-a649-e30cdb5fb97e)

My actual config
![image](https://github.com/AlexxIT/go2rtc/assets/5204009/525ad985-8ce7-46d8-9ad4-cdb677b1b904)

The strams list
![image](https://github.com/AlexxIT/go2rtc/assets/5204009/eb1b079a-282b-485c-887e-01ba44753751)

The device name on HASS
![image](https://github.com/AlexxIT/go2rtc/assets/5204009/ddb6ddf7-8429-4d4e-b8fb-9ebddb44eca0)

**Comment by AlexxIT** [comment]
#710
