### ISSUE TITLE
Best way to set up HTTPS?

### ISSUE THREAD

**Issue by privatesam** [AlexxIT/go2rtc#714]
I know there are plenty of reverse proxy options for funneling go2rtc through HTTPS but I've seen hints on some posts that go2rtc has something built in to serve on https?  Is this true?  Would make microphone access so much easier for testing internally etc.

**Comment by AlexxIT** [comment]
It's outside the scope of this project. I like Caddy because it's very simple. Other people like Nginx because it's popular.
