### ISSUE TITLE
No connection to camera

### ISSUE THREAD

**Issue by Lasta2007** [AlexxIT/go2rtc#715]
HA - 2023.10.3
go2rtc - Version: 1.8.1

The HomeAssistant`s add-on go2rtc does not connect to the camera. I use wireshark for diagnostics. By launching VLC and opening the URL of the RTCP from the camera, I see network activity. When opening the URL of the add-on stream (rtsp://192.168.1.2:8554/go2CH1), there is no network activity. It seems that the plugin cannot connect to the camera.

192.168.1.2 - HA
192.168.1.19 - NVR Uniview
go2rtc log:
```
22:31:51.561 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.2:56430->192.168.1.19:554: i/o timeout" url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
22:31:56.714 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.2:39204->192.168.1.19:554: i/o timeout" url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
23:27:06.549 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.2:56662->192.168.1.19:554: i/o timeout" url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
23:27:11.695 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.2:56664->192.168.1.19:554: i/o timeout" url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
23:27:26.162 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.2:33218->192.168.1.19:554: i/o timeout" url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
23:27:31.318 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.2:33230->192.168.1.19:554: i/o timeout" url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
00:17:32.968 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 192.168.1.2:35928->192.168.1.19:554: i/o timeout" url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
```
go2rtc config:
```
webrtc:
  candidates:
    - stun:8555

streams:
  go2CH1: rtsp://admin:pass$@192.168.1.19/unicast/c1/s0/live

log:
  format: ""
  level: "info"
```

**Comment by Lasta2007** [comment]
The problem is with go2rtc and WebRTC (after version 3.0). If the camera stream is entered through HA into the Camera domain and outputted through the Picture Glance card, then the video is output.
HA Server - 192.168.1.2/24
NVR - 192.168.1.19/24
They are physically plugged into the router.

**Comment by AlexxIT** [comment]
You can increase log level to trace for RTSP module

**Comment by Lasta2007** [comment]
`
12:58:58.921 DBG [streams] start producer url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
12:58:58.922 TRC [rtsp] client request:
PLAY rtsp://192.168.1.19/unicast/c1/s0/live RTSP/1.0
CSeq: 4
Authorization: Digest username="admin", realm="6cf17e4d97ba", nonce="421290802", uri="rtsp://192.168.1.19/unicast/c1/s0/live", response="c09d77aeec6f0aa7f05d1fbe8a290337"
Session: 285


12:58:58.921 TRC [streams] check prod=0 media=audio, recvonly, PCMU/8000
12:58:58.924 TRC [streams] check prod=0 media=audio, sendonly, PCMU/8000
12:58:58.924 TRC [rtsp] client response:
RTSP/1.0 200 OK
Cseq: 4
Session: 285


12:58:58.924 TRC [streams] check cons=1 media=audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML
12:58:58.924 TRC [streams] check prod=0 media=audio, recvonly, PCMU/8000
12:58:58.925 TRC [streams] match prod=0 => cons=1
12:58:58.966 TRC [webrtc] answer
v=0
o=- 3465002765726882056 1698141538 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 BF:F4:0B:D1:BE:1B:3D:5E:17:4F:DB:9D:63:53:AF:36:42:F6:33:E7:C5:B8:EA:16:B2:99:7D:E6:68:21:10:EC
a=extmap-allow-mixed
a=group:BUNDLE 0 1
m=video 9 UDP/TLS/RTP/SAVPF 102 106
c=IN IP4 0.0.0.0
a=setup:active
a=mid:0
a=ice-ufrag:tlsWxqEulpupmljO
a=ice-pwd:OqkKhPqLXWjtBYEWWFDFfpPmTrhqSTPp
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb 
a=rtcp-fb:102 transport-cc 
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack 
a=rtcp-fb:102 nack pli
a=rtpmap:106 H264/90000
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:106 goog-remb 
a=rtcp-fb:106 transport-cc 
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack 
a=rtcp-fb:106 nack pli
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:3375758420 cname:go2rtc
a=ssrc:3375758420 msid:go2rtc go2rtc-video
a=ssrc:3375758420 mslabel:go2rtc
a=ssrc:3375758420 label:go2rtc-video
a=msid:go2rtc go2rtc-video
a=inactive
m=audio 9 UDP/TLS/RTP/SAVPF 111 0 8
c=IN IP4 0.0.0.0
a=setup:active
a=mid:1
a=ice-ufrag:tlsWxqEulpupmljO
a=ice-pwd:OqkKhPqLXWjtBYEWWFDFfpPmTrhqSTPp
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc 
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:3211223824 cname:go2rtc
a=ssrc:3211223824 msid:go2rtc go2rtc-audio
a=ssrc:3211223824 mslabel:go2rtc
a=ssrc:3211223824 label:go2rtc-audio
a=msid:go2rtc go2rtc-audio
a=sendonly

12:58:58.978 TRC [webrtc] local candidate="candidate:1944728210 1 udp 2130706431 192.168.1.2 35218 typ host"
12:58:58.981 TRC [webrtc] local candidate="candidate:3457762162 1 tcp 1671430143 192.168.1.2 8555 typ host tcptype passive"
12:58:58.984 TRC [webrtc] local candidate="candidate:1786724586 1 udp 2130706431 10.147.19.198 53238 typ host"
12:58:58.988 TRC [webrtc] local candidate="candidate:3616289034 1 tcp 1671430143 10.147.19.198 8555 typ host tcptype passive"
12:58:58.994 TRC [webrtc] local candidate="candidate:3281593121 1 udp 1694498815 176.62.183.116 33802 typ srflx raddr 0.0.0.0 rport 33802"
12:58:58.999 TRC [webrtc] config candidate="candidate:2448750614 1 udp 2030043135 176.62.183.116 8555 typ host"
12:58:59.000 TRC [webrtc] config candidate="candidate:738691574 1 tcp 2023751679 176.62.183.116 8555 typ host tcptype passive"
12:58:59.234 TRC [api.ws] msg type=webrtc/candidate
12:58:59.236 TRC [webrtc] remote candidate=
12:59:07.164 TRC github.com/AlexxIT/go2rtc/internal/api/ws/ws.go:120 > error="websocket: close 1000 (normal)"
12:59:07.237 TRC [api] GET /api/streams 172.30.32.2:36134
12:59:07.245 TRC [api] GET /api 172.30.32.2:36138
12:59:13.438 DBG [streams] stop producer url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live
12:59:13.439 TRC [rtsp] client request:
TEARDOWN rtsp://192.168.1.19/unicast/c1/s0/live RTSP/1.0
CSeq: 5
Authorization: Digest username="admin", realm="6cf17e4d97ba", nonce="421290802", uri="rtsp://192.168.1.19/unicast/c1/s0/live", response="a79be92c7d630dd20e3e3ad7413a2aad"
Session: 285


12:59:13.441 TRC [streams] stop reconnect url=rtsp://admin:pas$@192.168.1.19/unicast/c1/s0/live`

**Comment by AlexxIT** [comment]
There is no timeout in your logs

**Comment by AlexxIT** [comment]
Please let me know if the problem is relevant
