### ISSUE TITLE
RTSP: Packet loss or Packet delay is not handled properly

### ISSUE THREAD

**Issue by rajesindia** [AlexxIT/go2rtc#717]
Hi,

We have several rtsp based devices which significantly introducing packet delay or loss of packets. Please see the screenshots in the attachment (the same rtsp when we try with ffplay)

![image](https://github.com/AlexxIT/go2rtc/assets/23351731/9ad38828-9c05-4a12-bac0-ec54a4539163)

![image](https://github.com/AlexxIT/go2rtc/assets/23351731/10fdeaeb-f1fb-4a8b-b42f-50cbc0c1ea1a)

for these kind of rtsps, go2rtc is not handling properly and lead to empty video. 

**Could you please handle the packet delay/packet loss?**

When we use ffmpeg option with a #video=copy setting, it loads the video properly, but with significant delay. Is there a way to improve the startup delay?

**Comment by AlexxIT** [comment]
Don't plan to spent my time on so buggy cameras. You should use ffmpeg source for them.
