### ISSUE TITLE
Nest camera stops working after 5 minutes

### ISSUE THREAD

**Issue by Inrego** [AlexxIT/go2rtc#723]
After 5 minutes, the nest stream stops working. I've set it up manually with the parameters (not through HA).
So something about the reconnection seems to not be working correctly.

Nothing seems to be logged around the time when the stream stops working, so I'm not sure what else I can provide.

**Comment by heroash88** [comment]
I think this is a limit Google enforced in their API unless you stream it on the Google Home App.

**Comment by Inrego** [comment]
Another fun thing I experienced recently, was that when the stream stops working, then Frigate suddenly used all remaining 20 GB RAM on my machine within seconds, rendering the machine unresponsive due to lack of RAM.

**Comment by AlexxIT** [comment]
go2rtc not using extend API. There are no such plans in the near future.
The fact that the stream is not reconnecting is a bug. It shouldn't be.

**Comment by Inrego** [comment]
I'm sorry, but I'm having a hard time understanding what you mean by your second line

> The fact that the stream is not reconnecting is a bug. It shouldn't be.

Should it be reconnecting automatically, or not?

**Comment by AlexxIT** [comment]
It should be reconnecting. But I haven't this source for testing.

**Comment by Inrego** [comment]
> Hello how exactly do I get the 'device_id=' and the 'refresh_token' ?

It's kind of off topic, but you can use this site:
https://device-access-sample.web.app/

**Comment by Inrego** [comment]
> It should be reconnecting. But I haven't this source for testing.

I might have a go at making a PR for it at some point when I have the time.
Would you accept if I implement calling the stream extension api, rather than reconnecting (while still having reconnect as a fallback if connection is lost)?

**Comment by AlexxIT** [comment]
If the code will be correct and logical - I will accept it :)

**Comment by Inrego** [comment]
I'll do my best. I've no experience in Go, but I've many years of professional experience in C#

**Comment by Inrego** [comment]
I'm afraid I won't have the time to get the proper understanding of the workings, to fix the issue. But I'll share my sparse findings here:
When the stream expires, the webrtc state changes to disconnected, and then closed.

When I manually close the stream by closing VLC, then the disconnected even is absent, and it only closes.

I believe the first step should be to fix the issue of reconnection. Because even if the extend stream is implemented, there could be edge cases where it's not fired in time, or for other reasons fail.

**Comment by Inrego** [comment]
After the stream expires, frigate shows the stream as full of flickering artifacts, and it uses up all my RAM (~30 GB) in seconds.

If I change this small thing, it successfully reconnects without issue:
File: `pkg\webrtc\conn.go`
Function: `pc.OnConnectionStateChange`

Change from: `case webrtc.PeerConnectionStateDisconnected, webrtc.PeerConnectionStateFailed, webrtc.PeerConnectionStateClosed:`
Change to: `case webrtc.PeerConnectionStateFailed, webrtc.PeerConnectionStateClosed:`

So basically no longer closing the connection on Disconnect.

However, I'm hesitant to make such a change in webrtc module since it could cause unintented consequences in other areas than Nest.

But maybe you can use this information to implement a proper fix, @AlexxIT ?

**Comment by AlexxIT** [comment]
Just removing `PeerConnectionStateDisconnected` is very strange. Maybe problem with double `Close` call. Maybe there is some block there. You need to investigate problem more deeper.

**Comment by Inrego** [comment]
Investigating is a bit hard, because whenever it happens my server more or less crash due to frigate consuming all the ram.

**Comment by AlexxIT** [comment]
So this is a very rare problem?

**Comment by Inrego** [comment]
No it's very reproducible. The stream expires after the 5 minute mark, and then everything goes south

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0

**Comment by jackhibbz** [comment]
> After the stream expires, frigate shows the stream as full of flickering artifacts, and it uses up all my RAM (~30 GB) in seconds.
> 
> If I change this small thing, it successfully reconnects without issue: File: `pkg\webrtc\conn.go` Function: `pc.OnConnectionStateChange`
> 
> Change from: `case webrtc.PeerConnectionStateDisconnected, webrtc.PeerConnectionStateFailed, webrtc.PeerConnectionStateClosed:` Change to: `case webrtc.PeerConnectionStateFailed, webrtc.PeerConnectionStateClosed:`
> 
> So basically no longer closing the connection on Disconnect.
> 
> However, I'm hesitant to make such a change in webrtc module since it could cause unintented consequences in other areas than Nest.
> 
> But maybe you can use this information to implement a proper fix, [@AlexxIT](https://github.com/AlexxIT) ?

Only started with HA a couple weeks ago so all this is new to me, I’ve got a Google nest doorbell gen 2 wired

I’ve used go2rtc and generated a url using the Google nest ( inputting my refresh token, cloud id etc) and got the camera streaming in frigate. Having the issue with the stream cutting out after 5 minutes though.

I’ve got frigate and go2rtc both on homeassistant and I’ve attempted to find the pkg/webrtc/conn.go files, to change the part you’ve mentioned. Wonder if you’d be able to point me in the right direction as I’m not able to find the file to edit it.

Appreciate any help you can provid
