### ISSUE TITLE
2 ways audio with Imou REX 3D 

### ISSUE THREAD

**Issue by PaulBiod** [AlexxIT/go2rtc#727]
Hi,
I have 2 cams imou ranger pro which work perfectly with 2 way audio (after enabling H264 and G711 via DAhua config tool).
My go2rtc yaml is : 
```
streams:
  salon:
    - rtsp://admin:xxxxxx@192.168.1.112/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - "ffmpeg:salon#audio=aac"
```
I bought a new one, the REX 3D which looks like the ranger pro. I also changed the video encoding to H264 and audio to G711 ( frequency 8000). No matter what I try (AAC, G711mu) it doesn't play 2 ways audio.
Here is the device settings : 
<img width="573" alt="image" src="https://github.com/AlexxIT/go2rtc/assets/28720176/95ba5094-7f03-43ca-a7cf-44d2c17bdd2e">
 and here is the VLC  codecs info : 
![Capture d’écran 2023-11-03 004815](https://github.com/AlexxIT/go2rtc/assets/28720176/5be45f95-773a-4cd2-ac16-2a46bf4f156c)

Is there something I am doing wrong ?

**Comment by AlexxIT** [comment]
Your screens not shows backchannel codec. You can check it in stream info (WebUI) while stream is active.

**Comment by PaulBiod** [comment]
Hi @AlexxIT 
What you mean by Webui ? cause the imou cams won't connect via their ip, exemple : http://192.168.1.89:37777 won't work

**Comment by AlexxIT** [comment]
Go2rtc WebUI

**Comment by PaulBiod** [comment]
I used it integrated in webrtc, so no webui

**Comment by AlexxIT** [comment]
All versions has WebUI

**Comment by PaulBiod** [comment]
Thanks @AlexxIT 
Got it, here is my logs while streaming : 

`{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.1.89/cam/realmonitor?channel=1\u0026subtype=0\u0026unicast=true\u0026proto=Onvif/",
      "remote_addr": "192.168.1.89:554",
      "user_agent": "go2rtc/1.8.1",
      "sdp": "v=0\r\no=- 2229913047 2229913047 IN IP4 0.0.0.0\r\ns=Media Server\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=control:*\r\na=packetization-supported:DH\r\na=rtppayload-supported:DH\r\na=range:npt=now-\r\nm=video 0 RTP/AVP 96\r\na=control:trackID=0\r\na=framerate:25.000000\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0032;sprop-parameter-sets=Z00AMukASAFHQgAAB9IAAYcECAA=,aOqMbIAA\r\na=recvonly\r\nm=audio 0 RTP/AVP 8\r\na=control:trackID=1\r\na=rtpmap:8 PCMA/8000\r\na=recvonly\r\nm=application 0 RTP/AVP 107\r\na=control:trackID=4\r\na=rtpmap:107 vnd.onvif.metadata/90000\r\na=recvonly\r\n",
      "medias": [
        "video, recvonly, H.264 Main 5.0",
        "audio, recvonly, PCMA/8000",
        "application, recvonly, VND.ONVIF.METADATA"
      ],
      "receivers": [
        "96 H264, bytes=75263917, senders=2",
        "8 PCMA/8000, bytes=1145920, senders=2"
      ],
      "recv": 77074481
    },
    {
      "url": "ffmpeg:rtsp://admin:PWD@192.168.124.89/cam/realmonitor?channel=1\u0026subtype=0\u0026unicast=true\u0026proto=Onvif#audio=opus"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.1.100:59407 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=71784263, receivers=1",
        "8 PCMA/8000, bytes=1094720, receivers=1"
      ],
      "send": 73657211
    },
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.1.100:50935 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "102 H264, bytes=25784615, receivers=1",
        "8 PCMA/8000, bytes=393280, receivers=1"
      ],
      "send": 26456779
    }
  ]
}`

![1](https://github.com/AlexxIT/go2rtc/assets/28720176/8effc87a-392e-4fd9-8c5a-c56ba84c6e54)
![2](https://github.com/AlexxIT/go2rtc/assets/28720176/f9d6bb08-41f1-4775-b707-76b31631a9cd)

Thanks, hope it helps

**Comment by AlexxIT** [comment]
Your camera doesn't support open two way proro (producer > medias > no sendonly media)

**Comment by PaulBiod** [comment]
Thanks @AlexxIT

**Comment by borgqueenx** [comment]
@PaulBiod well, i just got myself a few of these ranger camera's you spoke of in your first post and i can't get even two-way audio working on these.
Tried switching to h264 and G711A and G711U audio, no luck. microphone is open in go2rtc, but speaker in the camera does not output anything.
