### ISSUE TITLE
wrong response on DESCRIBE - Axis Camera

### ISSUE THREAD

**Issue by justinmiller62** [AlexxIT/go2rtc#728]
I am able to setup a camera and view the stream normally. However I find that if I view the camera feed through the software platform Immix for video monitoring I cannot view the stream through go2rtc at the same time. This is pretty much normal as I think the camera stream can only handle one view at a time, it is the same with say VLC and is an issue in reverse as well. 

However I found that if I close down the Immix viewer, it takes about 5 or 10 minutes before I can view the stream in go2rtc and if I try to view it before that i get the error "wrong response on DESCRIBE" if I wait 5 to 10 minutes it will start working again, I have tried this with both a straight rtsp stream and the websocket setup described in the documents. 

what does that error message mean, whats the best way to troubleshoot the issue?

**Comment by AlexxIT** [comment]
You can increase the log level for the rtsp module. And check the camera response there.
