### ISSUE TITLE
Camera stops working with wrong request

### ISSUE THREAD

**Issue by mhoogenbosch** [AlexxIT/go2rtc#73]
I have 5 cameras working with Go2RTC. 4 of them connected through Ring-mqtt are Amazon Ring camera's. They work just fine. One of the cameras is a Foscam camera. Which is working fine with the Foscam software and is working most of the time with Go2RTC.

Sometimes the lovance card doesn't show anymore. Ive tried using the iframe approach and the normal picture approach. Doesn't make any difference. 

`13:43:18.691 WRN [streams] start error="wrong request: г�]\x1a��\x00\x13���UN%ʜ��H�8wè\bt�<!b�)�nw��D����\x1ba�Ȅ�W}\x1d/�+w����;;�ݷ\x11o��$m�恵\r����#��2��\x12\x16��`\x14n\x1f�ԩ��q\x01�>!�\a[��>����2W�P3i\x05\x18�߲5�F\a%|�/�G��6�%�X��*zo�Z�!�V9��+��\x01\x11\x0e)G����\x10C~\"$5����|��\x18x�?W�Y\x1f��1��@���\x15S�)��\f������6\x0f�qUV���`9Q;���ճȩ�*i�c\x1eP�/t��\x18\aX1[��C�\x1d�\f�\x17��/��\x17�\bib\b�h���\x1e�JCר$7=̍����X\x13���8�w��H�\x13�/_Q{��{Dj&�Xn����&��6\x11�'<W��\b�\x1f�X��i��`W#}]��\x02��:z�*�T�捣���\x12hѿ\x13\x1c͚-K�?���E�pq���\x0f$�&�6�\x13��\v�fl�\"hV�\x1a��;��,N��\x1bm3�}s\x05C�;�L8�\x00\x05��ls\x02�->�{.:\x12=z��\x1b=MS|��<\x18�K2\x15R�}�qP���" url=rtsp://user:pass@192.168.20.231:88/videoMain`

I have added :

```
log:
  level: info  # default level
  api: debug
  rtsp: debug
  streams: debug
  webrtc: debug
```
To the go2rtc.yaml file, but can't really do anything with this error. 

If I could get some pointers of where to look for fixing this, that would be great. Restarting the go2rtc container btw fixes things. The feed comes back alive.

**Comment by AlexxIT** [comment]
This is known problem. Multiple simultaneous start commands for the same RTSP stream. You probably open same stream from different places in one time.

#60

**Comment by mhoogenbosch** [comment]
Yes that's true. I'm using the same camera on 2 lovance pages. And the pages are being shared across more users. Like for instance i'm using a dashboard with the camera for viewing my sleeping son but I'm opening it on my mobile phone too as goes for my wife. 

Should this be configured in a different way?

**Comment by AlexxIT** [comment]
The problem with instant simultaneous access. Usual there is no problem if you open stream second time after few seconds.
