### ISSUE TITLE
Didn't support Aqara G2h anymore from 1.7.0

### ISSUE THREAD

**Issue by mikeinblue** [AlexxIT/go2rtc#744]
I was using 1.6.2 working very well with my Aqara g2h.When I update to 1.7.0 and above it didn't stream any more.
logs:
![IMG_5609](https://github.com/AlexxIT/go2rtc/assets/62834868/51093fca-402f-4357-ad88-aa2af2a56323)

**Comment by AlexxIT** [comment]
The current go2rtc version is v1.8.2

**Comment by mikeinblue** [comment]
> The current go2rtc version is v1.8.2

Yes,1.8.2doesn't support g2h ,too.

**Comment by mikeinblue** [comment]
fixed in 1.8.5. Thx
