### ISSUE TITLE
Add support incoming H264 bitstream

### ISSUE THREAD

**Issue by fuatakgun** [AlexxIT/go2rtc#745]
Hi again,

This is a follow up of old discussion: https://github.com/AlexxIT/go2rtc/issues/134

Setting up the scene first;
- A node app (eufy-security-ws) is communication with physical devices and getting bytes of streams for a live view and publishing them over a websocket to connected client (https://github.com/bropat/eufy-security-ws)
- My home assistant integration (eufy_security) is connecting to respective WS (wrapped in home assistant add-on) and reading bytes from physical cameras (https://github.com/fuatakgun/eufy_security/)
- Same integration in HA is creating a TCP port and setting an ffmpeg process to connect to respective TCP port and publish a stream to another node app (RTSP Simple Server)
- Same integration publishes the RTSP address to home assistant so users can start watching their streams.

The issue is arising with not reliable/weak points. Most of the time I am receiving broken pipe issues and running ffmpeg process does not feel me safe inside python environment. 

Keeping aside all my feelings :) I want to handover all streaming specific stuff to go2rtc and just focus on integration itself.

Requirements;
- Chunks of bytes are incoming whenever user calls a service in home assistant, I need to send them to go2rtc and go2rtc should start to generate the stream ,even there is no consumer yet
- I can send them via tcp or websocket connection
- Stream should not be deconstructed as some users are preferring live stream (just to generate fresh thumbnails) without watching them in person
- My main focus is around generating the video but I will come up with audio after initial round

Please guide me through if go2rtc is right place to do so and if I can pick up some work or you can implement this?

my current exec use case;
```"exec:ffmpeg -analyzeduration {duration} -f {codec} -i tcp://localhost:{port} -vcodec copy -f rtsp -rtsp_transport tcp {output}"```

**Comment by AlexxIT** [comment]
Maybe go2rtc will be connecting directly to `eufy-security-ws` addon. So video traffic won't have to go through python integration. Does this addon support multiple connections? The usual features will remain in the integration, and the video will go directly to go2rtc.

**Comment by fuatakgun** [comment]
I had proposed this add-on owner and he does not want to miss the responsibilities of stuff and I respect.

He is also streaming to go2rtc on iobroker system if users have it already.

https://github.com/bropat/ioBroker.eusec/blob/1bffc607d127b22d59b79702bc2dfaa7fd1f3dbd/src/lib/video.ts#L196C20-L196C20

But as of now, every consumer of the client library (https://github.com/bropat/eufy-security-client) has to manage its own video generation layer.

**Comment by AlexxIT** [comment]
Well. You asking about [incoming source](https://github.com/AlexxIT/go2rtc#incoming-sources). You can use formats:
- RTSP - looks like this one used by [ioBroker.eusec](https://github.com/bropat/ioBroker.eusec)
- MPEG-TS
- HTTP-FLV
- ADTS (AAC audio only)

You can look for python libraries for generating MPEG-TS or HTTP-FLV. So you not need to use FFmpeg in this case. This will work in current go2rtc release.

The simplest option would be to implement AnnexB Bitstream (H264 frames with 000001 prefix). I can add it to next release, no problem. But it will support only video track and don't support audio in the same stream.

But go2rtc also support ADTS in the current release. And you can try to use AnnexB + ADTS as two incoming sources for one stream.

**Comment by fuatakgun** [comment]
So if we go with annex b-stream, i do not need to manage ffmpeg and go2rtc will handle everything?

**Comment by AlexxIT** [comment]
Do you know the format in which the video from eufy-security-ws comes in? I think this can be Bitstream or MPEG-TS.
Maybe you have some dump?

**Comment by fuatakgun** [comment]
Let me get the dump.

Depending on the camera, codec differs such as h264 and h265.

Data is coming in an array and i am converting it to a byte array.

I will get the dump and write it on a file and share with you.

**Comment by fuatakgun** [comment]
[dump.txt](https://github.com/AlexxIT/go2rtc/files/13327550/dump.txt)

**Comment by fuatakgun** [comment]
By the way, integration is currently using ffmpeg and RTSP Simple Server based streaming over here.
https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/eufy_security_api/p2p_stream_handler.py#L12C9-L12C9

I just want to ditch ffmpeg part and write data into a remote listener without managing a server too

**Comment by AlexxIT** [comment]
This is simple bitstream. I will add support to next release. And what about audio? Can you send dump?

**Comment by fuatakgun** [comment]
to be honest, I have always omitted sound so far :) but looking at other implementations of the same library, it has similar mechanism to post bits using `aac` codec

**Comment by AlexxIT** [comment]
Can you send dump for audio? So I'll check it.

**Comment by fuatakgun** [comment]
I can do it tomorrow, I need to change my local setup a bit, I will come back to yu

**Comment by AlexxIT** [comment]
You can try latest master version https://github.com/AlexxIT/go2rtc#incoming-sources

```
ffmpeg -re -i BigBuckBunny.mp4 -c copy -f h264 http://localhost:1984/api/stream?dst=camera1
```

**Comment by fuatakgun** [comment]
Wow, thanks for the quick update.

I might be a bit slow to grasp but how am i supposed to send the bytes to g2rtc?

**Comment by AlexxIT** [comment]
It's just POST connection with stream data. Single direction. Every language should support it.

**Comment by fuatakgun** [comment]
Expected events in order;
1. HA integration sends a ws request to add-on initiate livestream by user calling a service
2. HA integration will wait for livestream started event to validate if the first command is successfully run.
3. HA integration will wait for incoming bytes of live stream, this is contioues until user or device initiates an stop livestream request.
4. HA integration will call go2rtc to create stream record on the fly with stream name a and exec (or ffmpeg command).
5. Go2rtc will start listening incoming bytes through a medium (tcp/web socket/post request)
6. HA integration will forward incoming chunk of bytes to go2rtc in a loop as long as it continues to receive.

Before asking my question here, i was able to reach a solution with go2rtc, running of my own ffmpeg to create a stream onto go2rtc and writing all incoming bytes into local ffmpeg process.

My ask here is about having a less fragile mechanism than local ffmpeg process so Integration would not break with closed connection over closed process.

Please help me about step 4,5 and 6. What am i supposed to here now after your change?

**Comment by AlexxIT** [comment]
1. HA integration sends a ws request to add-on initiate livestream by user calling a service
2. HA integration will wait for livestream started event to validate if the first command is successfully run.
3. HA integration will wait for incoming bytes of live stream, this is contioues until user or device initiates an stop livestream request.
4. HA integration will forward incoming chunk of bytes to go2rtc in a loop as long as it continues to receive (empty stream should exist in the go2rtc config).

In the 4th step you should use POST to `/api/stream?dst={existing stream name}`

**Comment by fuatakgun** [comment]
I will of course use the API to create the stream before posting the chunks.

So, I will post chunk of bytes as form data to this endpoint (/api/stream?dst={existing stream name), wow, great. let me try as soon as possible.

**Comment by AlexxIT** [comment]
I'm not sure about "form data". It should be just bytes in stream mode. Not an exact example, but something close:
https://github.com/AlexxIT/YandexStation/blob/52f6316b59ec4d96debc602c6eeaae8b099bc5bd/custom_components/yandex_station/core/utils.py#L462-L469

**Comment by fuatakgun** [comment]
understood, crystal clear

**Comment by fuatakgun** [comment]
how will go2rtc resolve the incoming stream codec, frame rate and any other information given the below scenario given that data only includes information about the frames (or bitstream in better technical terms)?
configuration.yaml
```
streams:
  test:
```
Busines logic
```
while queue.isEmpty() is False:
  data = queue.get()
  response.write(data)
```

**Comment by AlexxIT** [comment]
go2rtc can autodetect on this endpoint:
- H264 bitstream
- H265 bitstream
- MJPEG stream
- Multipart stream
- FLV
- MPEG-TS

**Comment by AlexxIT** [comment]
go2rtc don't using framerate because frames coming in real time. Bitstream codec can be detected from first bytes of data.

**Comment by fuatakgun** [comment]
some failures :)

Try 1
```
async with aiohttp.ClientSession() as session:
    item = await asyncio.wait_for(self.camera.video_queue.get(), timeout=2.5)
    resp = await session.post(url, data = bytearray(item))
  _LOGGER.debug(f"Post response {x} - {resp.status} - {await resp.text()}")
```

Result 1
```
[custom_components.eufy_security.eufy_security_api] Post data 0 - 1502
[custom_components.eufy_security.eufy_security_api] Post response 0 - 500 - EOF
[custom_components.eufy_security.eufy_security_api] Post data 1 - 69
[custom_components.eufy_security.eufy_security_api] Post response 1 - 500 - unexpected EOF
[custom_components.eufy_security.eufy_security_api] Post data 2 - 69
[custom_components.eufy_security.eufy_security_api] Post response 2 - 500 - unexpected EOF
```

**Comment by AlexxIT** [comment]
It's not a stream in your code. It's multiple separated post requests

**Comment by fuatakgun** [comment]
my bad, my bad, here it is;

```
    async def chunk_generator(self):
        for x in range(0,10000):
            try:
                item = await asyncio.wait_for(self.camera.video_queue.get(), timeout=2.5)
                _LOGGER.debug(f"Yield data {x} - {len(item)}")
                yield bytearray(item)
            except TimeoutError as te:
                _LOGGER.debug(f"Timeout Exception %s - traceback: %s", te, traceback.format_exc())
                break
```

```
            async with aiohttp.ClientSession() as session:
                resp = await session.post(url, data = self.chunk_generator(), headers = headers)
                _LOGGER.debug(f"Post response - {resp.status} - {await resp.text()}")
```

this is working great now :)
confirmed, I believe we can close this as of now and I can change my integration accordingly

**Comment by fuatakgun** [comment]
and I will come back for audio support later on or you have already something in your mind?

**Comment by AlexxIT** [comment]
I still needs audio dump to check

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.3

**Comment by bropat** [comment]
> I still needs audio dump to check

@AlexxIT here is an audio dump:

[audio-stream.dump.txt](https://github.com/AlexxIT/go2rtc/files/13394179/audio-stream.dump.txt)

**Comment by fuatakgun** [comment]
Thanks @bropat

**Comment by AlexxIT** [comment]
OK. You can send this to same endpoint in latest master version. Will be in next release
```
ffmpeg -re -i BigBuckBunny.mp4 -c copy -f adts http://localhost:1984/api/stream?dst=camera1
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.4

**Comment by fuatakgun** [comment]
just to be sure that I understand right, in the same HTTP POST data stream, I can send both video and audio chunk of bytes?
