### ISSUE TITLE
Fix support raw username/password for tapo source

### ISSUE THREAD

**Issue by ladyisatis** [AlexxIT/go2rtc#748]
So some TP-Link Tapo cameras will run 1.3.x versions (1.3.9?) but some TP-Link Tapo cameras only have, at max, 1.2.13 running, which don't have the authorization changes. The [5d3953a](https://github.com/AlexxIT/go2rtc/commit/5d3953a9487e1ff528eed25467c59a83a8986cb5) commit breaks support for the Tapo TC85 camera, and possibly others, because of it:

```
go2rtc      | 18:47:55.872 WRN [rtsp] error="streams: 401 Unauthorized" stream=camera1
go2rtc      | 18:47:56.979 WRN [rtsp] error="streams: 401 Unauthorized" stream=camera3
```

**Comment by AlexxIT** [comment]
If you can share your stream (8800 port from camera), it would be helpful.
https://github.com/AlexxIT/go2rtc/wiki/Tunnel-RTSP-camera-to-Intenet

I have TC60. And it works fine with latest version

**Comment by AlexxIT** [comment]
If sharing stream is problem for you - I need response on this request (all headers)
https://github.com/AlexxIT/go2rtc/blob/28830a697d3c18d9c51a56d142029e8586311e3e/pkg/tapo/client.go#L261

You can try to do it with curl - POST to `http://ip:8800/stream` with this header `Content-Type: multipart/mixed; boundary=--client-stream-boundary--`.

**Comment by AlexxIT** [comment]
Thanks for test this before release

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.3

**Comment by ppfeister** [comment]
Hey @ladyisatis, how are things going for you nowadays? Running some tc85s with 1.2.18 and experiencing issues with the same error message. I'm wondering if there was a regression or if you're still seeing success on this version.
