### ISSUE TITLE
Cameras are not always loaded RTC streams after updating to 1.8.2

### ISSUE THREAD

**Issue by DieMetRik** [AlexxIT/go2rtc#750]
After updating go2rtc to 1.8.2 
When open lovelace in browser chrome 
1 of 4 cameras loaded RTC stream, the rest are MSE
Sometime 2 cameras load RTC
lovelace uses WebRTC 3.5.0
But in frigate are not load webrtc in UI

Frigate 13 beta-5 installed in proxmox LXC
bin file of go2rtc passthrough to frigate docker container
Rolling back to version 1.8.1 did not solve the problem.
Rolling back to version 1.8.0 and now all streams are RTC

**Comment by AlexxIT** [comment]
What was latest version when it works fine?
