### ISSUE TITLE
HomeKit proxy mode does not work 1.8.3

### ISSUE THREAD

**Issue by Minims** [AlexxIT/go2rtc#756]
HomeKit proxy mode does not work 1.8.3

I can’t see any logs in debug mode while accessing the camera 
I revert to 1.8.2 and all is working again

```
homekit:
  somfy_indoor_camera:
    name: Indoor Camera
    pin: 99999999
    pairings:
      - client_id=***
      - client_id=***

**Comment by IliasEagle** [comment]
Same for me.

**Comment by taioner** [comment]
Same for me.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.4
