### ISSUE TITLE
Sercomm Two Way Audio

### ISSUE THREAD

**Issue by Blueion76** [AlexxIT/go2rtc#760]
I have a Sercomm (ADT) DBC835 Doorbell that I reset and configured to my WiFi. I have RTSP and audio working with go2rtc, but I’m trying to get two-way audio working. 

From what I can tell in the web UI; it uses NetSurveillance ActiveX for viewing. I can get audio files to the camera using a curl command such as the one below. 

curl -vv --data-binary @sample.wav http://username:password@10.0.1.42/img/g711u.cgi

but the DVRIP go2rtc integration will not work as the camera only has 80, 443 and 6789 ports open. Is there any debugging I can do to try and get the two-way audio working?

Image attached with the docs on how two-way audio works. 
![image](https://github.com/AlexxIT/go2rtc/assets/128919662/43d1eb0a-6ea4-452a-a600-fbc7125c92fb)

**Comment by Blueion76** [comment]
Meant to say I can get .wav audio files to the camera using the curl command *not two way audio

**Comment by AlexxIT** [comment]
Theoretically this could be implemented. But I don't have this device and time.

**Comment by xromansx** [comment]
Do you know the default password for this doorbell ?

**Comment by Blueion76** [comment]
> Do you know the default password for this doorbell ?

I have since replaced it with a Reolink doorbell. I wanna say it's either administrator, password or admin. 

Sorry I can't be of more help.

**Comment by xromansx** [comment]
This cameras don't use the default password, that's why I was interested how did you get it.

**Comment by Blueion76** [comment]
> This cameras don't use the default password, that's why I was interested how did you get it.

Did you reset your camera and connect it to your own wifi network? You can't use it while connected to ADT. I also had to block internet access to mine.

**Comment by xromansx** [comment]
This is interesting maybe when it connects to their server it changes the password. I'll try to block internet access and verify, did your camera had sort of setup page ?
