### ISSUE TITLE
Add presets for hardware acceleration on Rockchip devices

### ISSUE THREAD

**Issue by MarcA711** [AlexxIT/go2rtc#768]
I guess there is a considerable number of users that use Rockchip hardware. The rk3588 seems to be widely used and the new [Home Assistant Green](https://www.home-assistant.io/green/) uses a rk3566.

There is a [FFmpeg fork](https://github.com/hbiyik/FFmpeg) that supports hardware de- and encoding on Rockchip devices. A static binary is available from [my repo](https://github.com/MarcA711/Rockchip-FFmpeg-Builds/releases/tag/6.0-1).

Using this FFmpeg version, the presets for hardware encoding are:
```
"h264/rk": "-c:v h264_rkmpp_encoder -g 50 -bf 0",
"h265/rk": "-c:v hevc_rkmpp_encoder -g 50 -bf 0",
```

Is there any chance that go2rtc includes support for the Rockchip platform?

In any case, great project. Many thanks!

**Comment by AlexxIT** [comment]
Do you know if Hass developers uses forked ffmpeg version? These presets are useless, until most users will have forked ffmpeg version.

**Comment by MarcA711** [comment]
No, I don't know what ffmpeg version is used by hass.
Yes, these presets will only work with the forked FFmpeg version.

Maybe the user can provide a static binary himself if he wants to use hw accel on rockchip. Or go2rtc can download a binary, if it detects rockchip hardware.

**Comment by AlexxIT** [comment]
Is this chip support only arm64 arch?

**Comment by MarcA711** [comment]
The bigger, modern Rockchip SoCs (RK3588/s and RK356X) support arm64. These are the most widespread SoCs as far as I know.

But there are also older SoCs that support armhf.

But I don't know for sure, if you need this information, I will do some research.

**Comment by AlexxIT** [comment]
I wander if this ffmpeg version can automatically use hardware decoder without choosing it manually.

**Comment by MarcA711** [comment]
Yes, it does

**Comment by AlexxIT** [comment]
Don't know about including this binary to go2rtc docker, because this project was closed due to license issues
https://github.com/JeffyCN/FFmpeg

And there is some another project with rkmpp support:
https://github.com/jjm2473/ffmpeg-rk

**Comment by StuartIanNaylor** [comment]
> Don't know about including this binary to go2rtc docker, because this project was closed due to license issues

Its not that project its FFmpeg & Hevc and why Youtube is moving to AV1 a lot of current developement is dodging ffmpeg and focusing on gstreamer AV1.
There will not be any official rockchip Fmpeg H264/H265 or any mainline inclusions unless the argument about licensing that I don't fully understand is resolved.

Its a bit of a problem as Rockchip historically is heavily based on ffmpeg, but all work is with gstreamer and av1 hence the only submission was a AV1 stateless codecs for rk3588 & Mediatec SoCs.
To be honest I am as confused as anyone but the above was the proposed Rockchip ffmpeg and a few others have forked as the only work being done is those backporting to solve the obvious problems no ffmpeg causes but the above is [jeffy.chen@rock-chips.com](mailto:jeffy.chen@rock-chips.com)

**Comment by MarcA711** [comment]
Yes, I added support for Object Detection using the NPU.

**Comment by MarcA711** [comment]
You either need sudo or you need to add our user to some group (that I don't remember at the moment) in order to get access to the hardware.

Try it with `sudo ./ffmpeg -i ...`

**Comment by AlexxIT** [comment]
Leave it here

```
alexxit@orangepi5b:/tmp$ sudo ./ffmpeg -hide_banner -decoders | grep rkmpp
 V..... av1_rkmpp_decoder    av1 (rkmpp decoder ) (codec av1)
 V..... h263_rkmpp_decoder   h263 (rkmpp decoder ) (codec h263)
 V..... h264_rkmpp_decoder   h264 (rkmpp decoder ) (codec h264)
 V..... hevc_rkmpp_decoder   hevc (rkmpp decoder ) (codec hevc)
 V..... mpeg1_rkmpp_decoder  mpeg1 (rkmpp decoder ) (codec mpeg1video)
 V..... mpeg2_rkmpp_decoder  mpeg2 (rkmpp decoder ) (codec mpeg2video)
 V..... mpeg4_rkmpp_decoder  mpeg4 (rkmpp decoder ) (codec mpeg4)
 V..... vp8_rkmpp_decoder    vp8 (rkmpp decoder ) (codec vp8)
 V..... vp9_rkmpp_decoder    vp9 (rkmpp decoder ) (codec vp9)
```

```
alexxit@orangepi5b:/tmp$ sudo ./ffmpeg -hide_banner -encoders | grep rkmpp
 V..... h264_rkmpp_encoder   h264 (rkmpp encoder ) (codec h264)
 V..... hevc_rkmpp_encoder   hevc (rkmpp encoder ) (codec hevc)
 V..... vp8_rkmpp_encoder    vp8 (rkmpp encoder ) (codec vp8)
```

**Comment by AlexxIT** [comment]
@MarcA711 you can try latest master version

**Comment by AlexxIT** [comment]
I have tested width/height param. Looks like it works fine via filters:
https://github.com/AlexxIT/go2rtc/blob/eceb4a476f86dc979352f9af4a4deaab478d5279/internal/ffmpeg/ffmpeg_test.go#L154-L164

**Comment by MarcA711** [comment]
Yes, filters work, but it is worse this way. Using `-vf "scale=-1:320"` the scaling part is done in software and results in a higher CPU load.
Using `-width` and `-height` scaling will be done in hardware (in the Raster Graphics Accelerator - RGA) and results in a lower CPU load.

**Comment by AlexxIT** [comment]
Are you sure? Have you compare result? I saw something about new size in logs. And it was from rkmpp encoder.

**Comment by MarcA711** [comment]
Yes, the difference is big:
```
$ time sudo ./ffmpeg -i test.mp4 -c:v h264_rkmpp_encoder -vf "scale=1920:1080" out.mp4
[... FFmpeg output...]

real    0m12.228s
user    0m0.000s
sys     0m0.023s

$ time sudo ./ffmpeg -i test.mp4 -c:v h264_rkmpp_encoder -width 1920 -height 1080 out1.mp4
[...]

real    0m2.538s
user    0m0.015s
sys     0m0.007s
```

So, transcoding and rescaling took 12.3s vs 2.5 seconds.

**Comment by MarcA711** [comment]
> I saw something about new size in logs. And it was from rkmpp encoder.

Where did you see this? hbiyik/FFmpeg has two branches:
- **encoder** is kind of the stable branch
- in **exp_refactor_all** he reimplements everything including new features

Maybe what you read is true for the newer **exp_refactor_all** branch. My ffmpeg was built from **encoder**. I plan to build a binary from the **exp_refactor_all** branch within the next couple of days, then I can test.

**Comment by AlexxIT** [comment]
I don't have access to OrangePi any more. Will this work?

```
sudo ./ffmpeg -i test.mp4 -c:v h264_rkmpp_encoder -width:v 1920 -height:v 1080 out1.mp4
```

**Comment by MarcA711** [comment]
yes, this works fine.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.5
