### ISSUE TITLE
Sound but no image

### ISSUE THREAD

**Issue by frawau** [AlexxIT/go2rtc#769]
I got one el cheapo camera from China (Model 4K-SW7 branded "Home-Mall"). It works with both ICSee and XMEye applications on Android

I spun up a Windows 7 VM with IE, and after a bit of work I got to login into the Web Interface, but there is apparently nothing of interest there.

After reading a number of articles, I tried to integrate the camera into my HomeAssistant setup.

I installed the go2rtc Add on and configured it with

 ```
streams:
  garage_dvrip:
    - dvrip://admin:password@192.168.77.17:34567
  garage_dvrip_mini:
    - dvrip://admin:password@192.168.77.17:34567?channel=0&subtype=1
```
When I go to the WebUI, after waking up the camera (i.e. moving in front of it), thinks seem to work, there is an "MSE" at the top right but the screen is black and the sound works. 

Also tried with the first stream as `dvrip://admin:7Lvb1F0D@192.168.77.17:34567?channel=0&subtype=0` but it is the same.

Any idea why that is?

**Comment by frawau** [comment]
Forgot to mention,  my HA is running on a RPi4 with latest version
  - go2rtc 1.8.4
  - core 2023.11.2
  - supervisor 2023.11.3
  - OS 11.1
  - Frontend 20231030.2

**Comment by AlexxIT** [comment]
Open stream info from go2rtc WebUI. And compare it to go2rtc docs, codecs section.

**Comment by frawau** [comment]
Thanks for your answer. I wonder if I am not victim of the H265 issue. Here is what I got :

For 
    dvrip://admin:password@192.168.77.17:34567?backchannel=1?channel=0&subtype=0

Sound OK, dark screen

Stream info is 
```json
{
  "producers": [
    {
      "type": "DVRIP active producer",
      "medias": [
        "video, recvonly, H265",
        "audio, recvonly, PCMA/8000"
      ],
      "receivers": [
        "255 H265, bytes=1276730, senders=0",
        "0 PCMA/8000, bytes=95680, senders=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp6 srflx [2001:470:1f1d:393:517:9b2c:a8db:4b8e]:34379 related 0.0.0.0:0",
      "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "8 PCMA/8000, bytes=95680, receivers=1"
      ],
      "send": 96348
    }
  ]
}
```

For
 dvrip://admin:password@192.168.77.17:34567?channel=0&subtype=1
Sound OK, dark screen

Stream info is  
```json
{
  "producers": [
    {
      "type": "DVRIP active producer",
      "medias": [
        "video, recvonly, H265",
        "audio, recvonly, PCMA/8000"
      ],
      "receivers": [
        "255 H265, bytes=75264, senders=0",
        "0 PCMA/8000, bytes=66880, senders=1"
      ]
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 prflx 192.168.77.1:37535 related :0",
      "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264",
        "audio, sendonly, OPUS/48000/2, G722/8000, PCMU/8000, PCMA/8000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "senders": [
        "8 PCMA/8000, bytes=66880, receivers=1"
      ],
      "send": 67340
    }
  ]
}
```

For 
  dvrip://admin:password@192.168.77.17:34567?backchannel=1

Error message
  MSE Stream: codec not matched => H264, AAC, PCMA, PCMU, S16B, S16L, OPUS

Stream info is 

```json

{
  "producers": [
    {
      "url": "dvrip://admin:password@192.168.77.17:34567?backchannel=1"
    }
  ],
  "consumers": null
}
```

Note that remote_addr point to the same device with both IPv4 and IPv6.

Lastly, not sure it can be of any use to you, but the camera regularly broadcast on UDP port 34569 some blob containing

```json
{ "NetWork.NetCommon" : 
     { 
         "ChannelNum" : 1, 
         "DeviceType" : 285409282, 
         "GateWay" : "0x010AA8C0", 
         "HostIP" : "0x114DA8C0", 
         "HostName" : "camera_297d", 
         "HttpPort" : 80, 
         "MAC" : "00:12:33:52:29:7d", 
         "MonMode" : "TCP", 
         "SN" : "f541e7e864708c99", 
         "SSLPort" : 8443, 
         "Submask" : "0x00FFFFFF", 
         "TCPPort" : 34567, 
         "UDPPort" : 34568 
     }, 
     "Ret" : 100, 
     "SessionID" : "0x00000000" 
}
```
GateWay is a bit weird.

Thanks again, and sorry for the longish reply

**Comment by frawau** [comment]
Indeed, it is an H265 issue. The streams work when using HA apps on Android

**Comment by frawau** [comment]
In the event someone is stumbling on this thread. Here is how I got things to work on HA with transcoding to h264.

```yaml
# go2rtc.yaml
streams:
  garage_cam:
    - dvrip://admin:password@192.168.77.17:34567?backchannel=1?channel=0&subtype=0
    - ffmpeg:garage_cam#video=h264
  garage_cam_mini:
    - dvrip://admin:password@192.168.77.17:34567?channel=0&subtype=1
    - ffmpeg:garage_cam_mini#video=h264
```
