### ISSUE TITLE
[Question] How to use / play webRTC stream in another application?

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#77]
We are looking to build go2rtc in to frigate and webRTC would be an ideal choice to be used with the frigate live view. I am referencing https://github.com/AlexxIT/go2rtc/blob/master/www/webrtc.html to try to support webrtc in frigate however the websocket fails to connect with an undefined error / reason.

I am wondering is this the way that other clients should use this webRTC connection or is there a better way? What recommendations do you have for trying to accomplish integrating the webRTC stream in another application?

Thank you in advance!

**Comment by NickM-27** [comment]
If I go into the browser console on another site and try to create a websocket `const ws = new WebSocket('ws://<host>:1984/api/ws?src=front_doorbell_cam');` then it will fail. However, when I do it from the go2rtc frontend and open a console, it works as expected.

Not sure where exactly the error falls, happy to help provide more info or debug if it is useful.

**Comment by NickM-27** [comment]
Saw in the go2rtc logs `ERR [api.ws] upgrade error="websocket: request origin not allowed by Upgrader.CheckOrigin"` so I believe this is by design and the behavior makes sense. I did a manual build of go2rtc with the origin check disabled and webRTC works perfectly 🎉 

I believe if I use our nginx proxy to proxy to the go2rtc websocket then that should satisfy the origin check? Will close this if I am able to figure it out.

**Comment by NickM-27** [comment]
Another idea is that using go2rtc inside of frigate, we are only using it internally and not exposing port 1984. If there was an ENV variable or configuration to disable the origin check for this case that could be another way to go about it?

**Comment by NickM-27** [comment]
Going to close this as I believe I have it working with nginx. Once #76 is included in a release build I will be able to test for sure.

**Comment by AlexxIT** [comment]
I can disable origin check. Don't know cons. Check enabled by default in websocket library

**Comment by NickM-27** [comment]
> I can disable origin check. Don't know cons. Check enabled by default in websocket library

Understood. I think having a config option to disable it would be ideal if you're good with that.
