### ISSUE TITLE
How to fetch the stream in Javascript to resend via custom P2P connection

### ISSUE THREAD

**Issue by kirianguiller** [AlexxIT/go2rtc#770]
Hi, thank you a lot to for this awesome library. This issue is more a question than a real issue.

I would like to know what is the recommended way to get the stream of a camera locally in a Nodejs script so it could then be resent via custom P2P connection (I am personnaly using [node-datachannel](https://github.com/murat-dogan/node-datachannel) for communication between my iot edges and their multiple clients outside of the network).

I don't understand how I could get from go2rtc such a stream that would be pipeable. I imagine that the stream would need to be on a unix UDP socket where the information about the port number of this socket would be fetchable via the API (1984) ?

Thank you for your help!. I tried to search in current wiki, issues and documentation but couldn't find anything.

**Comment by AlexxIT** [comment]
Start from this
https://github.com/AlexxIT/go2rtc/tree/master/api

**Comment by kirianguiller** [comment]
Hi @AlexxIT , thank you a lot for the link !
Here is what I will do from now :
- try to just use my existing signaling pipeline to communicate the SDP fetched from the go2rtc api/ws
- understand more how go2rtc "pipe" the video stream to webrtc 
- study the video-stream.js that has all the client logic for the video stream.

I close the issue as I think I now have all in hand to answer it ! Thanks again

**Comment by AlexxIT** [comment]
go2rtc "pipe" the video stream to webrtc according to webrtc standards. Like any other webrtc app.
And I don't recommend using webrtc to stream between local applications. Too much overhead.

**Comment by kirianguiller** [comment]
I see!

I want to send the stream from IoT edges (raspberry's) to external clients (mobile phones). I succeeded today to do the signaling and the connection between them. But it seems that I have to use a TURN server (coturn in my case) to have the solution working. 

But what trickle me is that I don't need the TURN server for my own webrtc connection (between the same edges and the clients). The difference is that I use datachannel (through UDP) whereas go2rtc are streaming over TCP ? And that would explain why one works without TURN and the other don't.

I'm checking other issues

**Comment by hassanalikhan87** [comment]
did you have any luck with it?
