### ISSUE TITLE
Audio support for incoming bitstream

### ISSUE THREAD

**Issue by fuatakgun** [AlexxIT/go2rtc#772]
just to be sure that I understand right, in the same HTTP POST data stream, I can send both video and audio chunk of bytes?

_Originally posted by @fuatakgun in https://github.com/AlexxIT/go2rtc/issues/745#issuecomment-1824865878_

**Comment by AlexxIT** [comment]
You should do this in two different post requests to same endpoint.

**Comment by fuatakgun** [comment]
but without any difference between endpoints or ordering does not matter?

**Comment by fuatakgun** [comment]
ok, understood, two different POST with the same endpoint ,working fine. Of course, AAC is causing issues on webrtc but it is another problem

**Comment by fuatakgun** [comment]
resolving this as of now, thanks.

On the other hand, would it be hard for the consumer (me) to keep alive two parallel HTTP streams at once given that any of these streams can fail independently for some random reasons.

Do you think, we can merge these into one?

**Comment by AlexxIT** [comment]
You can merge them only into supported format for video/audio. Example FLV or MPEG-TS.
