### ISSUE TITLE
Is there an option to disable the RTC overlay text in the top right hand corner?

### ISSUE THREAD

**Issue by simondsmason** [AlexxIT/go2rtc#776]
I am using go2rtc through Frigate.  When I stream my cameras I get an "RTC" in the top right hand corner.  Is there a switch to disable this?  Thanks.

<img width="92" alt="image" src="https://github.com/AlexxIT/go2rtc/assets/6063262/0e904029-4b60-4795-bfe8-9e464b3dc218">

**Comment by AlexxIT** [comment]
I think this question not to this project. Go2rtc writes this label only in the own WebUI. You can write custom WebUI if you want: https://github.com/AlexxIT/go2rtc#module-api

**Comment by Marcwa19197** [comment]
Hi, im using go2rtc with the HomeAssistant Integration. On my HA UI i also see the annoying "RTC" Text - how can i disable / hide it? Where is it coming from? Thanks!

**Comment by simondsmason** [comment]
> I think this question not to this project. Go2rtc writes this label only in the own WebUI. You can write custom WebUI if you want: https://github.com/AlexxIT/go2rtc#module-api

I see that someone else has asked the same question.  I didn't fully understand your response but seek to clarify here.  You state that "Go2rtc writes this label only in the own WebUI".  Not sure what this means.  Go2rtc writes this label in MY own WebUI, or in Go2rtc's WebUI?  

Since Go2rtc was installed with Frigate and I made only Frigate specific configuration - I am not clear where I would start to discuss this to see if it is possible to remove it?  The link is to commands for writing a custom UI - a custom UI for what - go2rtc?  I am not using any WebUI - all I am getting is a simple camera feed and want to get rid of the RTC.

If there is a place that is better to discuss this then please suggest where that might be.  Thanks.

**Comment by AlexxIT** [comment]
You both need to figure out what project is being used to display this overlay. And write in the repository of that project

**Comment by Marcwa19197** [comment]
HI @AlexxIT : Im using HomeAssistant and the default Card from your Project: https://github.com/AlexxIT/WebRTC#configuration

**Comment by simondsmason** [comment]
So it is not Frigate - already confirmed there?  It is not Go2rtc - confirmed here?  So no ideas where it might be coming from?  Seems like a mystery?

**Comment by AlexxIT** [comment]
@Marcwa19197 how to remove mode label for WebRTC Camera project described in the readme

**Comment by Marcwa19197** [comment]
Worked - thanks! So @simondsmason: In your case it must be on the frigate side (?) 
Adding style: '.mode {display: none}' to the card-config fixed it for my side, thank you!

**Comment by simondsmason** [comment]
Where exactly in the configuration did you make this change?  I will have to look for that in my Frigate setup as I didn't configure anything specific for go2rtc - it was all done with the frigate docker install.  Currently I am only configuring go2rtc in the frigate config file so don't have anywhere at present to add in this command.  Thanks for helping.

**Comment by Marcwa19197** [comment]
On the UI Settings which displays the camera feed - im not using frigate (but nice tip - will look into this). Is there a way to change the settings how the UI is displaying the camera feed? (Or adding some custom CSS-Commands?)

**Comment by simondsmason** [comment]
Thanks - don't know about settings on the go2rtc feed - will check in the Frigate docker files.  Frigate is great.  I used to use Blue Iris - very powerful but a nightmare to setup and maintain and in my situation was very unstable.  Frigate has a steep learning curve but truly set and forget once it is running.
