### ISSUE TITLE
[Question] mDNS in Docker, Avahi on the host

### ISSUE THREAD

**Issue by juliekoubova** [AlexxIT/go2rtc#777]
Hey, I would like to use go2rtc in Docker (podman) and expose my streams to HomeKit, but I already have Avahi running on the host. Is there any way to make this work?

**Comment by AlexxIT** [comment]
Do you have some problems with HomeKit module? I don't know if Avahi on host affects on go2rtc.

**Comment by juliekoubova** [comment]
I haven't tried it yet, but I don't think go2rtc container in host mode would be able to listen on UDP 5353 if Avahi already listens on that port (or vice versa, depending on what starts first)

**Comment by juliekoubova** [comment]
I currently use Scrypted, which talks to Avahi daemon on the host via mounted `/dev/dbus` to register its services. But I would like to switch to go2rtc for that sweet low-latency Home Assistant WebRTC card :)

**Comment by AlexxIT** [comment]
You should try. Go2rtc opens mDNS port with special mode. There is no problem via Hass and go2rtc ok same host. And Hass also listening mDNS port.

**Comment by juliekoubova** [comment]
Cool, it works! Thank you ❤️
