### ISSUE TITLE
2-Way Audio In Home Assistant Using Frigate for Doorbird

### ISSUE THREAD

**Issue by yvonneh7** [AlexxIT/go2rtc#778]
Hi, 

I looked at your tutorial (https://www.youtube.com/watch?v=upXyBVMR4RM) and would like to use this for Doorbird. I have replaced "**rtsp://admin:YourPassword@192.168.1.1:554/h264Preview_01_sub**" with "**rtsp://admin:YourPassword@IP_adress/mpeg/media.amp**" 

It works except for the audio. What is the configuration to enable audio for a Doorbird door station?

**Comment by AlexxIT** [comment]
I don't know what is Doorbird door station.

**Comment by yvonneh7** [comment]
Doorbird is just another manufacturer like Reolink. So it has also a doorbell camera with 2 way talk. The Doorbird documentation gives the following URLS:

LIVE AUDIO RECEIVE: http://<device-ip>/bha-api/audio-receive.cgi
LIVE AUDIO TRANSMIT: http://<device-ip>/bha-api/audio-transmit.cgi
LIVE VIDEO REQUEST: rtsp://<device-ip>:<device-rtsp-port>/mpeg/media.amp

I have tested a lot. But so far audio does not work. I would be very grateful for any help or ideas

**Comment by AlexxIT** [comment]
Most cameras on market don't support two way audio with some open protocols like RTSP

**Comment by nisnu** [comment]
@yvonneh7 did you get this working? I would be interested about this approach as well.

**Comment by yvonneh7** [comment]
Unfortunately not. If you find a solution, please share it here.

**Comment by AlexxIT** [comment]
It's better to continue all discussion about this camera model in single place https://github.com/AlexxIT/go2rtc/issues/1060

**Comment by oeiber** [comment]
@nisnu @yvonneh7 
Please see #1060
Maybe you can also help improving backchannel audio for doorbird devices?
