### ISSUE TITLE
Cameras don't show without internet

### ISSUE THREAD

**Issue by DaN66O** [AlexxIT/go2rtc#78]
The Internet turned off and all the cameras stopped showing.
The picture shows 2 seconds and disappears.
Cameras and Go2rtc on the local network.
![2022-10-18_00-36-05](https://user-images.githubusercontent.com/113509164/196412111-283b749f-1f26-4c9e-aaba-688b0bfa7b91.png)

**Comment by rogerquake** [comment]
What browser? I’ve seen this issue in Firefox. Works fine in Chrome without internet on my side.

**Comment by AlexxIT** [comment]
I think the problem is when the go2rtc server does not have Internet access and cannot get a public IP address. I'll fix it.

**Comment by AlexxIT** [comment]
Should be fixed in https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.1
