### ISSUE TITLE
Impossible to register dynamic exec stream

### ISSUE THREAD

**Issue by diver-ua** [AlexxIT/go2rtc#784]
It is impossible to register dynamic "**exec**" stream, because you have to provide parameters (at least {output}), and spaces in dynamic sources are not allowed.

Is there a way to dynamically add an "exec" stream with parameters (space-separated)?

**Comment by AlexxIT** [comment]
This is some protection for adding dangerous sources from API. I don't have better design for using them yet. You can change them only via yaml.

**Comment by diver-ua** [comment]
Ok, thanks, solved by patch&recompile (no external access to the api endpoint, so not so big concern).
