### ISSUE TITLE
Timeout with P2P > WebRTC

### ISSUE THREAD

**Issue by V4ler1an** [AlexxIT/go2rtc#786]
When I live stream my Eufy cameras through either the Lovelace WebRTC card or the GotoRTC http page (http://<local HASS IP>:1984) I find the stream stops after what seems to be about 10 minutes. If I live view the camera in the Eufy mobile app I get no such limitation. These are AC powered cameras btw.

Is there a timeout I can change? How can I ensure the live stream keeps running?

Also, I notice if I switch focus away from any WebRTC card that is live streaming, that too will disconnect the stream within a few seconds. Is there a way to ensure lovelace webrtc card live streams keep running when not displayed in the active browser tab? (Firefox).

**Comment by AlexxIT** [comment]
You haven't provide info about source. Eufy doesn't tell me anything. I don't have these cameras.

**Comment by V4ler1an** [comment]
Sorry the Eufy cameras are S100.

**Comment by AlexxIT** [comment]
Didn't help much. What kind of stream format is used there? How did you get it?

**Comment by V4ler1an** [comment]
The codec is h264, provider is P2P, resolution is 2K (2048×1536).

**Comment by AlexxIT** [comment]
go2rtc haven't support P2P out of box.

**Comment by V4ler1an** [comment]
Ok maybe it relates to the RTSP Simple Server HASS add-on that's needed to handle the P2P. I'll raise an issue there: https://github.com/fuatakgun/eufy_security.
