### ISSUE TITLE
Add support OPUS codec for MPEG-TS source

### ISSUE THREAD

**Issue by diver-ua** [AlexxIT/go2rtc#788]
When used "pipe" transport - there is no audio, and in logs media=video

```
18:57:33.357 TRC [streams] check prod=0 media=video, recvonly, H.264 Main 4.0
18:57:33.357 DBG [streams] start producer url=exec:/scripts/nvrs 2 4 1
```

_Using mpegts format, thet contains audio and video:_
```
root@7a174ab66f12:/app# /scripts/nvrs 2 4 1 | ffprobe -hide_banner -
Input #0, mpegts, from 'pipe:':
  Duration: N/A, start: 1.400000, bitrate: N/A
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 12 fps, 25 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp
```

Maybe, I'm doing something wrong?

I tried to add `#media=video+audio` param, but is used with ffmpeg and rtsp producers and has no effect with exec.

Have to pipe to ffmpeg for rtsp output...

**Comment by AlexxIT** [comment]
Never heard about OPUS inside MPEG-TS. Probably it's non standard situation. Will check if it is described by any spec

**Comment by diver-ua** [comment]
AAC with mpegts does not work also
mpegts is a container format, so there can be virtually any audio/video codecs embedded.

Is there any recommended audio codec for the mpegts?

**Comment by AlexxIT** [comment]
I know only one well supported codec for MPEG-TS. It is AAC.
You can use any codecs inside. But the popular players on the market won't be able to open them :)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.5
