### ISSUE TITLE
Add support subtype for Tapo source

### ISSUE THREAD

**Issue by jkay90** [AlexxIT/go2rtc#792]
Is there substream available for the [source Tapo.](https://github.com/AlexxIT/go2rtc#source-tapo)
i.e. 
What's available now through tapo://admin:HASHED_PASS@0.0.0.0 is rtsp://user:pass@0.0.0.0:8554/stream1 
Is it possible to get the low-res stream which is available on rtsp://user:pass@0.0.0.0:8554/stream2 somehow?

**Comment by AlexxIT** [comment]
`tapo://cloud-password@192.168.1.123?subtype=1`

https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.5
