### ISSUE TITLE
Onvif does not work with docker swarm

### ISSUE THREAD

**Issue by kalmastenitin** [AlexxIT/go2rtc#799]
I copied docker compose file from docker hub : [go2rtc](https://hub.docker.com/r/alexxit/go2rtc)
i am trying to run it with docker swarm mode. It runs RTSP streams successfully there is trouble rtsp links using onvif discovery.

@AlexxIT Help required to run go2rtc in docker swarm mode.

**Comment by AlexxIT** [comment]
`network_mode: host       # important for WebRTC, HomeKit, UDP cameras`

and also important for some types of discovery, including ONVIF/DVRIP/etc. I don't know if multicast request may work well in the docker swarm mode.
