### ISSUE TITLE
Error TAPO protocol with Frigate

### ISSUE THREAD

**Issue by Mikescotland** [AlexxIT/go2rtc#804]
Hi Alex
Cannot get tapo protocol to work with Dockered Frigate 0.13 and go2rtc 1.8.4.
I removed (just in case all references to rtsp protocol in config) and added tapo:// trying all 3 versions one by one.
When trying to access the stream I get 
mse: streams: parse "tapo://admin:XXXXXXXXXX/192.168.1.8": invalid port ":***********************" after host.
This is a message in the viewer, no message in the logs for frigate or go2rtc or nginx.

**Comment by AlexxIT** [comment]
You shouldn't have / between password and IP

**Comment by Mikescotland** [comment]
> You shouldn't have / between password and IP

Omg, how did I miss it... Terribly sorry Alex

**Comment by Mikescotland** [comment]
All works now. Thank you
