### ISSUE TITLE
"wrong adaptation size" error

### ISSUE THREAD

**Issue by almazikv** [AlexxIT/go2rtc#807]
Get "mpegts: wrong adaptation size" error for the stream added to go2rtc.
Stream works ok in vlc

**Comment by AlexxIT** [comment]
You should provide stream dump if you want this fixed.

**Comment by AlexxIT** [comment]
First, it needs to understand what kind of stream source you have. You haven't provide any info.

**Comment by almazikv** [comment]
@AlexxIT, this is an output from ffmpeg -i:
Input #0, mpegts, from 'https://streamer126.tattelecom.ru/intercom_8102/mpegts?token=XXX
  Duration: N/A, start: 58366.001667, bitrate: N/A
  Program 1
  Stream #0:0[0xd3]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 1920x1080, 25 tbr, 90k tbn, 180k tbc
  Stream #0:1[0xdd]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 8000 Hz, mono, fltp, 37 kb/s

**Comment by AlexxIT** [comment]
OK. You can try curl or wget for this url with some timeout. Can you handle it?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#source-ffmpeg

**Comment by almazikv** [comment]
thanks

**Comment by AlexxIT** [comment]
But if you send me a dump from curl or wget, I can try to fix this for http source

**Comment by almazikv** [comment]
It seems that problem was on my side. I tried again and no it works
