### ISSUE TITLE
Fix hardware profiles for H265 templates

### ISSUE THREAD

**Issue by MPTres** [AlexxIT/go2rtc#809]
Streaming fails when using the default h265/videtoolbox  template  (in a mac). It shows this error:	

```
[hevc_videotoolbox @ 0x7fb602b08300] [Eval @ 0x7ff7b834a380] Undefined constant or missing '(' in 'high'
[hevc_videotoolbox @ 0x7fb602b08300] Unable to parse option value "high"
[hevc_videotoolbox @ 0x7fb602b08300] Error setting option profile to value high.
[vost#0:0/hevc_videotoolbox @ 0x7fb602b07b80] Error initializing output stream: 
Error while opening encoder for output stream #0:0 - maybe incorrect parameters
 such as bit_rate, rate, width or height
```
Current template:
`h265/videotoolbox": "-c:v hevc_videotoolbox -g 50 -bf 0 -profile:v high -level:v 5.1`

The problem is  the `-profile:v` parameter, because `high` is not a valid option.
The valid options for that value in ffmpeg are: 
```
 -profile           <int64>      E..V....... Profile (from 0 to 3) (default 0)
     main                         E..V....... Main Profile
     main10                       E..V....... Main10 Profile
```

That should be an integer from 0 to 3, or the literals `main` or `main10`.   Did not send a PR because i have no idea which profile is the equivalent to h264's `high` :)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.5
