### ISSUE TITLE
Is it possible to add/remove cameras without restarting go2rtc?

### ISSUE THREAD

**Issue by nonibytes** [AlexxIT/go2rtc#813]
Adding hot reloading will be helpful. Adding a http endpoint to go2rtc which when called, causes gortc to look for changes in the camera settings and to add new cameras or remove old ones.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/tree/master/api

**Comment by nonibytes** [comment]
> https://github.com/AlexxIT/go2rtc/tree/master/api

From the docs, it seem a restart is needed. Is there a way to do this without restart? For example, in a situation where cameras are being updated programmatically and frequently.

**Comment by pgswow** [comment]
> Adding hot reloading will be helpful. Adding a http endpoint to go2rtc which when called, causes gortc to look for changes in the camera settings and to add new cameras or remove old ones.

Hello! did you manage to solve the problem of reloading the application without a full restart?

**Comment by nonibytes** [comment]
No, I ended up looking for other solutions besides go2rtc.

For example this:
https://github.com/panjjo/gosip

It's based on ZLMediaKit library.

**Comment by NickM-27** [comment]
no restart is needed, you can even add and remove cameras using the web ui without restarting go2rtc

**Comment by NickM-27** [comment]
and the webUI just uses the apis that were linked to

**Comment by nonibytes** [comment]
Is there a documented API?
