### ISSUE TITLE
Problem discovering RTSP from ONVIF

### ISSUE THREAD

**Issue by RichyT** [AlexxIT/go2rtc#817]
go2rtc detects my onvif camera fine. It shows

10.0.0.XXX:80 | onvif://user:pass@10.0.0.XXX:80/onvif/devices

If I paste that into the box with the correct user and password, it gives

IPCAM IPC stream0	onvif://myuser:mypass@10.0.0.XXX:80/onvif/devices?subtype=MainProfileToken
IPCAM IPC stream1	onvif://myuser:mypass@10.0.0.XXX:80/onvif/devices?subtype=SubProfileToken

At this point, I have verified that the username and pass are correct because I get authentication failed if I change either.

If I further paste either of these into the test box, I get the same URL back but with another query appended e.g.

IPCAM IPC stream0	onvif://myuser:mypass@10.0.0.XXX:80/onvif/devices?subtype=MainProfileToken?subtype=MainProfileToken
IPCAM IPC stream1	onvif://myuser:mypass@10.0.0.XXX:80/onvif/devices?subtype=MainProfileToken?subtype=SubProfileToken

At no point to I see a link for RTSP. It's possible I'm using this wrong. If so, I would appreciate being corrected in my usage. It's also possible the camera is not correctly implementing the onvif protocol. Any ideas?

**Comment by RichyT** [comment]
OK, I kinda got it working. By copying the onvif URL into "temporary streams", I was able to view the stream. Is there any way to get the RTSP stream from that now it's working?

**Comment by RichyT** [comment]
Well... I ran a tcpdump while go2rtc was working and while I was able to find an rtsp link, it looks like it uses some kind of one-time token. That's disappointing. I'm going to close this issue now since there's no further point in me pursuing this direction.

**Comment by AlexxIT** [comment]
You don't need tcpdump. You could have just increasee the log level.

**Comment by RichyT** [comment]
Thanks. That would doubtless have been the easier option but tcpdump wasn't too bad.
