### ISSUE TITLE
Aqara g2h pro ->No audio or Error

### ISSUE THREAD

**Issue by Monratis** [AlexxIT/go2rtc#824]
Hey so i have an issue with g2h pro from aqara i can get the video to work  but the audio isn't cooperating with me 
Im using the build in go2rtc in frigate beta 13 thats Version: 1.8.4 
If i add the ffmpeg:[camera name]#audio=aac#audio=opus camera dosen't work at all no audio or video ffmpeg errors 

Can anyone point me in the right direction ? thanks sorry if is obvious im fairly new to frigate and go2rtc 
Frigate config
![frigatess](https://github.com/AlexxIT/go2rtc/assets/69222411/6ff430fa-24fa-4624-8ee7-7d05216b5fcf)

Go2rtc config
![go2rtcss](https://github.com/AlexxIT/go2rtc/assets/69222411/ffeb65e7-d096-4158-9e15-568d7b652b38)

Camera informations (took this without the audio params as with audio params it dosen't show)
![CameraData](https://github.com/AlexxIT/go2rtc/assets/69222411/d4fa026d-8356-403b-b09f-576514952e86)

[logsGo2rtc.txt](https://github.com/AlexxIT/go2rtc/files/13647086/logsGo2rtc.txt)
[logsfrigate.txt](https://github.com/AlexxIT/go2rtc/files/13647084/logsfrigate.txt)

**Comment by AlexxIT** [comment]
Your go2rtc is not valid yaml.

**Comment by Monratis** [comment]
the go2rtc config that i attached was from frigate  
that's how the full go2rtc config looks with one more camera but please don't mind that the issue is only with g2hpro
how should i fix it sorry yaml is pretty new to me and if editor dosen't say something is not okay i have no way of knowing that 
Cheers
![fullconfig](https://github.com/AlexxIT/go2rtc/assets/69222411/745648e9-49dd-4306-91b3-8d0eba4e2e41)

**Comment by AlexxIT** [comment]
Have you tried looking for your error in this repository?

**Comment by Monratis** [comment]
Im retarded. you were right thats how it should look for anyone else that could be as retarded as i am 
![image](https://github.com/AlexxIT/go2rtc/assets/69222411/5d406fec-a3f2-42fe-9a9d-ac1eb8293635)
