### ISSUE TITLE
Scaling with Hardware Acceleration

### ISSUE THREAD

**Issue by tdashmike** [AlexxIT/go2rtc#831]
Hello,

#hardware=vaapi works on my setup but if I try to scale it does not, the video stream is still accessible but is not scaled.

Does not work:
`ffmpeg:T-DOORBELL_90#video=h264#raw=-vf "scale_vaapi=-1:864"#audio=copy#hardware=vaapi`

Works:
`ffmpeg:T-DOORBELL_90#video=h264#raw=-vf "scale=-1:864"#audio=copy`

I cannot seem to generate any errors with:
```
log:
  level: debug
```

**Comment by AlexxIT** [comment]
1. https://github.com/AlexxIT/go2rtc#source-ffmpeg
2. `level: trace`

**Comment by tdashmike** [comment]
Thanks!

`#video=h264#width=1280` was the solution.
