### ISSUE TITLE
Nest Hello Doorbell

### ISSUE THREAD

**Issue by tr1ckz** [AlexxIT/go2rtc#834]
Hi,

I was able to add the normal Next camera via the go2rtc nest integration, but it didn't see my gen 1 doorbell. 
Tried to add the device-id manually as a nest? integration, I got the device-id from the command:
`curl -X GET 'https://smartdevicemanagement.googleapis.com/v1/enterprises/xxxxx/devices' \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer xxxxxxxxx'`

But when I check the streams on go2rtc dashboard it just says "mse: streams: nest: wrong status: 404 Not Found"
The main difference that I noticed in the GET api call was that the camera is type `"sdm.devices.types.CAMERA"` while the doorbell is type `"sdm.devices.types.DOORBELL"`.

Is this not intended to work yet? Just trying to figure out if I should continue to bang my head against the wall. 
Thanks for all your work.

**Comment by AlexxIT** [comment]
Are you sure your device model works over WebRTC proto?
