### ISSUE TITLE
Aqara G4 not working in Motioneye (RTSP)

### ISSUE THREAD

**Issue by edelhauer** [AlexxIT/go2rtc#836]
Hi everyone,

I've successfully added my Aqara G4 to go2rtc via Homekit, and I can access the stream through webstream links. However, I'm encountering issues with opening the RTSP streams in MotionEye or VLC. 
My go2rtc is running on Portainer on an Intel NUC. Here's my current configuration:

```
streams:
  Doorbell Repeater-4729: homekit://someaddress

rtsp:
  listen: ":8554"
  username: "someone"
  password: "1234"

webrtc:
  listen: ":9555"
```

Thanks in advance for your help!

**Comment by AlexxIT** [comment]
Try to change stream name to something simpler. Maybe space is a problem

**Comment by edelhauer** [comment]
> Try to change stream name to something simpler. Maybe space is a problem

Thats it! Problem solved. Thanks a lot!
