### ISSUE TITLE
Webrtc stream restart on apple devices

### ISSUE THREAD

**Issue by luzik** [AlexxIT/go2rtc#840]
After update I got RTC stream restart every ~40seconds. This is happing with all my streams. MSE is working fine. Found bug while using HA integration, but it also is visible on frigate got2rtc dashboard:
http://IP/live/webrtc/stream.html?src=wejscie&mode=webrtc

using both - macOS safari and IOS

Do not know if this is related, but also webrtc integration with poster: <streamname> is making stream long time to load on apple devices - on linux/firefox it is working fine.

**Comment by AlexxIT** [comment]
You should use network host for docker container.

**Comment by luzik** [comment]
It was working perfectly fine with:
[docker]
privileged: true
ports:
 - 5000:5000
 - 8554:8554  # RTMP feeds
 - "8555:8555/tcp" # WebRTC over tcp
 - "8555:8555/udp" # WebRTC over udp
[go2rtc]
  webrtc:
    candidates:
      - LOCAL_IP:8555
      - PUBLIC_IP:8555

And I do forward traffic on my public IP to go2rtc

So while fixing something, something else was broke. If so, please consider giving configuration option/switch for old behavior.

Frigate do not support auth, I do not understand how "network: host" can work with my firewall from internet, and it is generally bad idea for "network: host", maybe there is a way to avoid this?

**Comment by AlexxIT** [comment]
1. Most users don't have a firewall at home. And no one can access to their devices because of NAT.
2. Probably you have static TCP and dynamic UDP (it's better for performance) for WebRTC. And iOS can't handle TCP connection for some reason.

It's not recommended not to use network host for many reasons. But you can set static UDP via `listen: ":8555"` option for webrtc module.

**Comment by luzik** [comment]
`listen: ":8555"` fixed my issue!

I believe that some of [WebRTC documentation](https://github.com/AlexxIT/go2rtc#module-webrtc) have to be fixed As it suggest that `listen: ":8555"` is default option set

**Comment by luzik** [comment]
btw - poster issue is still there, should I put other ticket on https://github.com/AlexxIT/WebRTC ?

**Comment by AlexxIT** [comment]
It was changes some versions ago. But docs not. My bad. TCP - static, UDP - dynamic by default.

**Comment by nalin29** [comment]
Is there a reason listen: ":8555" is not default? I ran into this as well on frigate. Seems this would break functionality of webrtc on ios devices

**Comment by AlexxIT** [comment]
Latest default `:8555/tcp`.
https://github.com/AlexxIT/go2rtc/blob/9c534b1df5f5ad6ca5603e5d152419de3df6b4a0/internal/webrtc/webrtc.go#L26

TCP port - static, UDP port - dynamic. For performance reason. I still don't know if it is good idea or not. Needs more tests.
