### ISSUE TITLE
[Feature Request] Add motion sensor support to HomeKit module

### ISSUE THREAD

**Issue by johndi3** [AlexxIT/go2rtc#842]
Hi, thanks for this great project

I'm using go2rtc to integrate my OpenIPC camera's RTSP streaming source into HomeKit system, everything works well except that there's no motion sensor integrated into the camera in HomeKit

I'm wondering if it's possible to add the feature to publish a motion sensor together with HomeKit camera, and be able to trigger the sensor via MQTT/HTTP API/ONVIF Event?

Thanks again

**Comment by vitva** [comment]
Oh yes, that would be awesome! And a binary doorbell switch 👍

**Comment by twocolors** [comment]
wow, is good idea make **doorbell switch** and call him from api/mqtt ...

**Comment by vitva** [comment]
This will be the best New Year's gift for Home kit users 😊

**Comment by AlexxIT** [comment]
Duplicate #812
Big issue because no trigger/automation engine yet.
