### ISSUE TITLE
log:exec:error does not log error

### ISSUE THREAD

**Issue by wrohdewald** [AlexxIT/go2rtc#846]
in my case I made a syntax error calling rpicam-vid. stderr from rpicam-vid is only logged by go2rtc with level **trace**. 

Could you please consider logging stderr output with loglevel error? 

Otherwise - I know this is not a go2rtc error - but if you explicitly do not want to log stderr as errors, could you please mention that in the documentation?

**Comment by AlexxIT** [comment]
For now exec stderr goto go2rtc stderr (works only for debug log level for exec module)
https://github.com/AlexxIT/go2rtc/blob/853e98879b0a17c5c0b6cff9e920f5d759513039/internal/exec/exec.go#L66

I understand what you want. Maybe someday

**Comment by AlexxIT** [comment]
Changes in next version:
- Viewer will receive stderr from exec module (first 512 bytes)
- Exec module will log stderr messages on debug log level (because ffmpeg very spamming)
- FFmpeg module will have personal log level (error by defaul)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.3
