### ISSUE TITLE
reolink 811a stream not compatible

### ISSUE THREAD

**Issue by mabed-fr** [AlexxIT/go2rtc#848]
Hello,

reolink 811a stream is not compatible ?

I use go2rtc with frigate + chrome Version 120.0.6099.129 (Build officiel) (64 bits) on Linux Debian 12

go2rtc:
  streams:
    clim:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.146:554/h265Preview_01_main
      
  
M

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#source-rtsp

**Comment by mabed-fr** [comment]
I have only sound

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc#codecs-madness

**Comment by mabed-fr** [comment]
thank
