### ISSUE TITLE
Increase max bitrate for HomeKit cameras

### ISSUE THREAD

**Issue by duncanleo** [AlexxIT/go2rtc#851]
May I know if it's possible to increase the video and audio max bitrate for HomeKit cameras? 

I'm able to see a noticeable increase in video quality after increasing from 299 to 1024/2048 or more.

https://github.com/AlexxIT/go2rtc/blob/ccec41a10f2636676befea50aa4cee2aa9d1d75a/pkg/hap/camera/stream.go#L37

https://github.com/AlexxIT/go2rtc/blob/ccec41a10f2636676befea50aa4cee2aa9d1d75a/pkg/hap/camera/stream.go#L46

**Comment by AlexxIT** [comment]
I don't think this make sense for audio, but make sense for video.

**Comment by AlexxIT** [comment]
New version has increased default bitrate for HomeKit source up to 4096 kbit/s.
This is 5 times better than default bitrate for Apple Home app!
Also new version has custom `#bitrate=6M` param for HomeKit source
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.3

**Comment by duncanleo** [comment]
@AlexxIT thank you so much! I've tried out the new version and it's working well!
