### ISSUE TITLE
How to keep streams alive?

### ISSUE THREAD

**Issue by wwww-wwww** [AlexxIT/go2rtc#854]
> By default, go2rtc establishes a connection to the source when any client requests it. Go2rtc drops the connection to the source when it has no clients left.

How can I change this so it always stays connected?

**Comment by leonw1112** [comment]
with an service file, so the daemon runs it always

**Comment by wwww-wwww** [comment]
🙄

**Comment by kalmastenitin** [comment]
Go2rtc streams work as similar to on-demand services it will drop the connection as soon as client/browser closes. Myself Running same stream on browser without closing stream is working nicely since last 7 days. Thanks @AlexxIT

**Comment by AlexxIT** [comment]
This works by default.
v1.8.5 has a bug with reconnect functionality.
