### ISSUE TITLE
Unifi camera BW showing - no speedup?

### ISSUE THREAD

**Issue by fribse** [AlexxIT/go2rtc#86]
Firefox browser 105.0.3 (64-bit)
Home Assistant 2022.10.5 Supervisor 2022.10.0 Operating System 9.2 Brugerfladeversion: 20221010.0 - latest 
go2rtc: 0.1-beta.9

I don't understand, shouldn't the latency be shorter on the webrtc camera made under 'generic'?
I made a card with both the unifi integration view and the go2rtc camera, and I don't see any latency difference?
The only difference I see is that the generic camera is in B/W where the integration is in color?

![billede](https://user-images.githubusercontent.com/13660621/197382823-cfd31f19-d479-4d27-a8b2-06ad95217387.png)

**Comment by AlexxIT** [comment]
Have you setup RTSPtoWebRTC integration?

**Comment by AlexxIT** [comment]
Closed without response
