### ISSUE TITLE
dahua doorbell 2-way audio confirmed to work specific models?

### ISSUE THREAD

**Issue by BienRyne** [AlexxIT/go2rtc#861]
I noticed that Dahua Doorbells are recommended, and I was wondering if someone could kindly provide information on specific models that are confirmed to support 2-way audio with go2rtc. I apologize if this inquiry is not in the correct place, as I am relatively new to using GitHub. Thank you for your time and assistance.

**Comment by AlexxIT** [comment]
There is no recommendations section in the project. Only the experience section.
And there's no Dahua doorbells. With some Dahua dorrbels there are problems with setting up two way audio.
