### ISSUE TITLE
Backchannel audio for ffmpeg sources

### ISSUE THREAD

**Issue by oeiber** [AlexxIT/go2rtc#868]
Hi,
is there a plan to support backchannel audio for ffmpeg sources?

**Comment by AlexxIT** [comment]
What ffmpeg source can support backchannel audio?

**Comment by oeiber** [comment]
my doorbird doorbell. It has seperate api endpoints for audio receive and transmit. both endpoints uses ulaw and 8000khz

**Comment by AlexxIT** [comment]
And why ffmpeg should be involved in this?

**Comment by oeiber** [comment]
i thaugt i can use two ffmpeg sources one for audio and one for backchannel?

**Comment by AlexxIT** [comment]
Is this duplicate for your other issue? #841

**Comment by oeiber** [comment]
yes it is ;-)

**Comment by AlexxIT** [comment]
So one issue will be enough
