### ISSUE TITLE
Auto Restart without Playback Interruption if Problems

### ISSUE THREAD

**Issue by darethehair** [AlexxIT/go2rtc#87]
Love this project!

Doing testing at home with my own (Tapo) RTSP cams in preparation for using in real-world non-profit environment with (Swann) RTSP cams.  Noticed that occasional glitches (e.g. error="wrong request") can occur, resulting in current view being frozen.  Easy to workaround by re-entering the view -- but wondering if it is possible to:

- Detect this type of problem and restart go2rtc automatically (the entire app, or somehow just the stream that was affected)
     or
- Restart go2rtc on a regular schedule (e.g. every 5 minutes?) 

...all without interruption of any cameras being viewed, so as not to require intervention for those viewing the streams in a web browser far from the actual server running go2rtc?

**Comment by NickM-27** [comment]
See #34

**Comment by NickM-27** [comment]
See #39

**Comment by felipecrs** [comment]
I proposed a short-term solution at:

- https://github.com/AlexxIT/go2rtc/pull/88

**Comment by AlexxIT** [comment]
Same as #39
