### ISSUE TITLE
Feature-Request: Make kill method of process configurable

### ISSUE THREAD

**Issue by dadav** [AlexxIT/go2rtc#870]
I'm trying to stream my canon eos 600d feed with this config:

```yaml
streams:
  canon: exec:gphoto2 --capture-movie --stdout
```

This works exactly one time. But the process is killed immediately (calling `os.Process.Kill`) by go2rtc after closing the stream without giving gphoto2 enough time for a proper cleanup.

gphoto2 is waiting for the SIGINT signal, therefore my request is to make that configurable.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0
