### ISSUE TITLE
windows desktop stream

### ISSUE THREAD

**Issue by alfredit** [AlexxIT/go2rtc#873]
hi,

I am trying to stream 2 things : a webcam and a windows desktop. 

The webcam works well, for the windows desktop i used ffmpeg exec with a working ffmpeg cmd : "ffmpeg -f dshow -i video="screen-capture-recorder""

so my go2rtc.yaml is : 

```
streams:
  windows_webcam: ffmpeg:device?video=0&video_size=1280x720#video=h264
  desk: exec:ffmpeg -f dshow -i video="screen-capture-recorder"

```

And i get this error : 
```
PS C:\Program Files\ffmpeg> .\go2rtc.exe
18:27:04.491 INF go2rtc version 1.8.5 windows/amd64
18:27:04.524 INF [rtsp] listen addr=:8554
18:27:04.524 INF [api] listen addr=:1984
18:27:04.526 INF [webrtc] listen addr=:8555
18:27:20.924 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: EOF"
18:33:40.882 ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166 > error="streams: EOF"
```

Can you help me to share my desktop? I think i need an output somewhere on the exec but not shure..

thanks,

Edgar

**Comment by skrashevich** [comment]
Is go2rtc installed in the docker container or run directly?

**Comment by AlexxIT** [comment]
Wrong output for exec source. It should has supported format and codec

**Comment by alfredit** [comment]
Exec from windows, no container.

**Comment by alfredit** [comment]
> Wrong output for exec source. It should has supported format and codec

Shoud i use exec or directly ffmped: for this?

**Comment by AlexxIT** [comment]
I have never saw screen capture recorder and never test it via ffmpeg source

**Comment by alfredit** [comment]
I finally did it with vlc cmd line, it was  not a good  usage of your app 

Thanks for the help.
