### ISSUE TITLE
Aqara G4 Doorbell Homekit Integrations in HA fails. please help

### ISSUE THREAD

**Issue by Elcapone86** [AlexxIT/go2rtc#877]
I have been trying to pair my G4 with HA via go2rtc since yesterday. Unfortunately I always get this error message when I try. (See picture)

The integration on Apple Homekit on my iPhone works without any problems. However, I would also like to use the camera in HA as an entity for automations.

![IMG_0855](https://github.com/AlexxIT/go2rtc/assets/40920098/1cb18a1f-81b2-4c0a-8eb6-76a671df192b)

Here my Go2Rtc Config

![IMG_0856](https://github.com/AlexxIT/go2rtc/assets/40920098/c54fbff5-fb9d-406e-ad50-f1aea61eb4c5)

whats wrong???

**Comment by skrashevich** [comment]
Add G4 first to home-assistant through the "HomeKit Controller" integration, then to go2rtc using the keys from the HA.

**Comment by AlexxIT** [comment]
I don't really understand what you're doing. If you are trying to add go2rtc to Home Assistant via HomeKit protocol, it is not supported on the Home Assistant side
