### ISSUE TITLE
Security related question

### ISSUE THREAD

**Issue by oeiber** [AlexxIT/go2rtc#880]
Hi,
before exposing 8555 tcp and udp to the internet I would ask if there's any authentication mechanism included. 
Is there any token, which is transmitted to the client using websockets, which is later used to authenticate against port 8555?

**Comment by NickM-27** [comment]
You can read https://webrtc-security.github.io/ which explains the built in security of webrtc

**Comment by oeiber** [comment]
Thank you! 
So for my understanding it should not be possible to stream any cameras without establishing a websocket connection before. Furthermore decoding a stream should also be impossible, because the encryption key is also being exchanged via ws protocol, right?

I asume all security considerations, described in the document, are implemented in go2rtc ;-)

**Comment by AlexxIT** [comment]
I hope so too
