### ISSUE TITLE
symmetric nat in other system

### ISSUE THREAD

**Issue by freedom1810** [AlexxIT/go2rtc#882]
as I see in this doc https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-webrtc
your app can work normally with webRTC  without use TURN server even the network is behind a symmetric nat. In my understanding, only solution to deal with symmetric nat is TURN server, am I right ? how do you deal with this ?

P/S: sr,  This issue is not related to this repo

**Comment by AlexxIT** [comment]
I don't understand your question. All the answers are in the link you provided
