### ISSUE TITLE
`BUG` - Consumers do not close properly for iPhone

### ISSUE THREAD

**Issue by illuzn** [AlexxIT/go2rtc#896]
I don't know the precise reproduction steps to produce this but it seems that iPhone (at least through Home Assistant) somehow causes go2rtc to hold open a stream even if the consumer has closed it.

Here is the JSON from go2rtc:
```json
"consumers": [
  {
    "type": "WebRTC/WebSocket async passive consumer",
    "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.12.1 (io.robbie.HomeAssistant; build:2023.508; iOS 16.3.1) Mobile/HomeAssistant, like Safari",
    "medias": [
      "video, sendonly, H264, RTX, VP8, VP9, RED, ULPFEC, FLEXFEC-03",
      "audio, sendonly, OPUS/48000/2, RED/48000/2, ISAC/16000, G722/8000, PCMU/8000, PCMA/8000, CN/16000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/16000, TELEPHONE-EVENT/8000, L16, PCML"
    ],
    "senders": [
      "96 H264, bytes=12895228627, receivers=1"
    ],
    "send": 13040515453
  }
]
```

I assure you that no one is sitting around watching 13GB of footage of my courtyard. I've checked the device in question and the Home Assistant companion app is completely closed. I encountered this previously using webRTC (with go2rtc built in) where the go2rtc process was consuming 90% CPU (presumably because of the same issue).

**Comment by AlexxIT** [comment]
WebRTC library will automatically close connection without answer from viewer during 30 sec.
I'm 99% sure some client keep open connection.

**Comment by illuzn** [comment]
Logically, it doesn't make sense:

* all my cameras use WebRTC 
* all my cameras appear on a single lovelace card which shows all the cameras at once
* I have intersection set to 0
* In any event, the courtyard camera is in the middle of the screen, so it would be least likely for a dodgy intersection setting to be tripping it.

If this was the case, I should be seeing lingering camera connections for all my cameras. I'll monitor and try to get back to you if I see it again. Is there any other information which would be helpful for me to provide to diagnose this issue?

**Comment by illuzn** [comment]
This issue hasn't been replicated for the last 2 months.

Closing issue and will open a new issue if I discover more.
