### ISSUE TITLE
RTMP from Frigate sometimes without a video track

### ISSUE THREAD

**Issue by hagak** [AlexxIT/go2rtc#90]
I have HA configured with RTSPtoWebRTC with go2rtc.  Frigate is my camera server using Frigate Cards

I can get the system to work well for a short bit but after a little while I will start getting:
Failed to start WebRTC stream: WebRTC offer was not accepted by any providers

And at the same time the logs in go2RTC will report:
23:04:47.636 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
23:04:47.637 ERR [api.hass] exchange SDP error="couldn't find the matching tracks"

Frigate/HASS/go2RTC are all running in containers on the same docker host.  go2RTC is setup with a macvlan.  I have tested with go2RTC setup in host mode same result.

**Comment by AlexxIT** [comment]
You need to increase log level and provide more logs

**Comment by hagak** [comment]
Some additional info.  I noticed that when a stream fails that camera/stream in gortc always has a "client producer" hanging around without consumers.  Not sure if this has any relevance to the issue.

**Comment by AlexxIT** [comment]
You have too many simultaneous streams in the log. It's hard to understand. You need to leave only one.
Try to add one RTMP to go2rtc config and open it from go2rtc UI.

**Comment by hagak** [comment]
Yeah that might make it take a much longer time to reproduce.  Issue I think might be due to the number of streams I have.  ~16.  Of 16 after a few minutes I will start to have issues with 2-4 of them.  Once the issue starts though only a restart of gortc will resolve it.

**Comment by hagak** [comment]
ACtually I was able to get it to fail.  I could not get it to fail with open via the go2rtc UI though.  I then added a dashboard in HA so that just the one camera is there and since that camera was pre-config in the config file it did not need to auto create it.  Then after reloading that HA page with the Frigate card i got the error.

AGain when this error happened this is what is in the info for that camera:
``
[
  {
    "media:0": "audio, sendonly, 0 MPEG4-GENERIC/16000/1",
    "receive": 0,
    "remote_addr": "172.18.0.31:1935",
    "track:0": "0 MPEG4-GENERIC/16000/1, sinks=0",
    "type": "RTMP client producer",
    "url": "rtmp://frigate:1935/live/office"
  }
]
``
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
exit OK
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
16:58:27.959 DBG [app] arch=amd64 conf_size=218 cwd=/config os=linux
16:58:27.960 TRC [api] register path path=/
16:58:27.960 TRC [api] register path path=/api/streams
16:58:27.960 TRC [api] register path path=/api/ws
16:58:27.960 INF [api] listen addr=:1984
16:58:27.960 TRC [api] register path path=/api/devices
16:58:27.961 TRC [api] register path path=/static
16:58:27.961 TRC [api] register path path=/streams
16:58:27.961 TRC [api] register path path=/stream/
16:58:27.961 TRC [api] register path path=/stream
16:58:27.961 INF [rtsp] listen addr=:8554
16:58:27.961 TRC [api] register path path=/api/frame.mp4
16:58:27.961 TRC [api] register path path=/api/stream.mp4
16:58:27.961 TRC [api] register path path=/api/stream.mjpeg
16:58:27.961 INF [srtp] listen addr=:8443
16:58:27.961 TRC [api] register path path=/api/homekit
16:58:27.961 TRC [api] register path path=/api/stack
16:58:27.961 TRC [api] register path path=/api/exit
16:58:57.125 TRC [api] GET url=/streams
16:58:57.127 TRC [api] POST url=/stream/camera.office/add
16:58:57.130 TRC [api] POST url=/stream/camera.office/channel/0/webrtc
16:58:57.138 TRC [streams] consumer:0:0 candidate media="audio, recvonly, 111 OPUS/48000/2, 63 RED/48000/2, 103 ISAC/16000, 9 G722/8000, 0 PCMU/8000, 8 PCMA/8000, 105 CN/16000, 13 CN/8000, 110 TELEPHONE-EVENT/48000, 113 TELEPHONE-EVENT/16000, 126 TELEPHONE-EVENT/8000"
16:58:57.138 DBG [streams] probe producer url=rtmp://frigate:1935/live/office
16:58:58.413 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:58:58.413 TRC [streams] consumer:0:1 candidate media="video, recvonly, 96 H264/90000, 97 RTX/90000, 98 H264/90000, 99 RTX/90000, 100 H264/90000, 101 RTX/90000, 102 H264/90000, 125 RTX/90000, 104 VP8/90000, 124 RTX/90000, 106 VP9/90000, 107 RTX/90000, 108 RED/90000, 109 RTX/90000, 127 ULPFEC/90000, 35 FLEXFEC-03/90000"
16:58:58.413 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:58:58.413 TRC [streams] consumer:0:2 candidate media="application, , 0 webrtc-datachannel/0"
16:58:58.413 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:58:58.413 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
16:58:58.413 ERR [api.hass] exchange SDP error="couldn't find the matching tracks"
16:58:58.543 TRC [api] GET url=/streams
16:58:58.544 TRC [api] POST url=/stream/camera.office/add
16:58:58.546 TRC [api] POST url=/stream/camera.office/channel/0/webrtc
16:58:58.552 TRC [streams] consumer:0:0 candidate media="audio, recvonly, 111 OPUS/48000/2, 63 RED/48000/2, 103 ISAC/16000, 9 G722/8000, 0 PCMU/8000, 8 PCMA/8000, 105 CN/16000, 13 CN/8000, 110 TELEPHONE-EVENT/48000, 113 TELEPHONE-EVENT/16000, 126 TELEPHONE-EVENT/8000"
16:58:58.552 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:58:58.552 TRC [streams] consumer:0:1 candidate media="video, recvonly, 96 H264/90000, 97 RTX/90000, 98 H264/90000, 99 RTX/90000, 100 H264/90000, 101 RTX/90000, 102 H264/90000, 125 RTX/90000, 104 VP8/90000, 124 RTX/90000, 106 VP9/90000, 107 RTX/90000, 108 RED/90000, 109 RTX/90000, 127 ULPFEC/90000, 35 FLEXFEC-03/90000"
16:58:58.552 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:58:58.552 TRC [streams] consumer:0:2 candidate media="application, , 0 webrtc-datachannel/0"
16:58:58.552 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:58:58.552 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
16:58:58.553 ERR [api.hass] exchange SDP error="couldn't find the matching tracks"
16:59:09.245 TRC [api] GET url=/
16:59:09.250 TRC [api] GET url=/main.js
16:59:09.251 TRC [api] GET url=/api/streams
16:59:22.187 TRC [api] GET url=/streams
16:59:22.189 TRC [api] POST url=/stream/camera.office/add
16:59:22.191 TRC [api] POST url=/stream/camera.office/channel/0/webrtc
16:59:22.196 TRC [streams] consumer:0:0 candidate media="audio, recvonly, 111 OPUS/48000/2, 63 RED/48000/2, 103 ISAC/16000, 9 G722/8000, 0 PCMU/8000, 8 PCMA/8000, 105 CN/16000, 13 CN/8000, 110 TELEPHONE-EVENT/48000, 113 TELEPHONE-EVENT/16000, 126 TELEPHONE-EVENT/8000"
16:59:22.196 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:22.196 TRC [streams] consumer:0:1 candidate media="video, recvonly, 96 H264/90000, 97 RTX/90000, 98 H264/90000, 99 RTX/90000, 100 H264/90000, 101 RTX/90000, 102 H264/90000, 125 RTX/90000, 104 VP8/90000, 124 RTX/90000, 106 VP9/90000, 107 RTX/90000, 108 RED/90000, 109 RTX/90000, 127 ULPFEC/90000, 35 FLEXFEC-03/90000"
16:59:22.196 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:22.196 TRC [streams] consumer:0:2 candidate media="application, , 0 webrtc-datachannel/0"
16:59:22.196 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:22.196 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
16:59:22.196 ERR [api.hass] exchange SDP error="couldn't find the matching tracks"
16:59:22.311 TRC [api] GET url=/streams
16:59:22.313 TRC [api] POST url=/stream/camera.office/add
16:59:22.315 TRC [api] POST url=/stream/camera.office/channel/0/webrtc
16:59:22.319 TRC [streams] consumer:0:0 candidate media="audio, recvonly, 111 OPUS/48000/2, 63 RED/48000/2, 103 ISAC/16000, 9 G722/8000, 0 PCMU/8000, 8 PCMA/8000, 105 CN/16000, 13 CN/8000, 110 TELEPHONE-EVENT/48000, 113 TELEPHONE-EVENT/16000, 126 TELEPHONE-EVENT/8000"
16:59:22.319 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:22.319 TRC [streams] consumer:0:1 candidate media="video, recvonly, 96 H264/90000, 97 RTX/90000, 98 H264/90000, 99 RTX/90000, 100 H264/90000, 101 RTX/90000, 102 H264/90000, 125 RTX/90000, 104 VP8/90000, 124 RTX/90000, 106 VP9/90000, 107 RTX/90000, 108 RED/90000, 109 RTX/90000, 127 ULPFEC/90000, 35 FLEXFEC-03/90000"
16:59:22.319 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:22.319 TRC [streams] consumer:0:2 candidate media="application, , 0 webrtc-datachannel/0"
16:59:22.319 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:22.319 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
16:59:22.320 ERR [api.hass] exchange SDP error="couldn't find the matching tracks"
16:59:41.007 TRC [api] GET url=/webrtc.html?src=camera.office
16:59:41.026 TRC [api] GET url=/api/ws?src=camera.office
16:59:41.031 DBG [webrtc] new consumer url=camera.office
16:59:41.037 TRC [streams] consumer:0:0 candidate media="video, recvonly, 96 H264/90000, 97 RTX/90000, 98 H264/90000, 99 RTX/90000, 100 H264/90000, 101 RTX/90000, 102 H264/90000, 125 RTX/90000, 104 VP8/90000, 124 RTX/90000, 106 VP9/90000, 107 RTX/90000, 108 RED/90000, 109 RTX/90000, 127 ULPFEC/90000, 35 FLEXFEC-03/90000"
16:59:41.037 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:41.037 TRC [streams] consumer:0:1 candidate media="audio, recvonly, 111 OPUS/48000/2, 63 RED/48000/2, 103 ISAC/16000, 9 G722/8000, 0 PCMU/8000, 8 PCMA/8000, 105 CN/16000, 13 CN/8000, 110 TELEPHONE-EVENT/48000, 113 TELEPHONE-EVENT/16000, 126 TELEPHONE-EVENT/8000"
16:59:41.037 TRC [streams] producer:0:0 candidate media="audio, sendonly, 0 MPEG4-GENERIC/16000/1"
16:59:41.037 WRN [api.webrtc] add consumer error="couldn't find the matching tracks"
16:59:45.028 TRC [api] GET url=/
16:59:45.035 TRC [api] GET url=/main.js
16:59:45.038 TRC [api] GET url=/api/streams
``

**Comment by AlexxIT** [comment]
Well. There is no video in your RTMP stream. Only audio.

**Comment by hagak** [comment]
Ideas on as to the cause of that?  Cause the stream HAD video and then didn;t.

**Comment by hagak** [comment]
tried to reproduce it again and now i can't.  So the stream not having video only happens on occasion and it can happen even AFTER it was working fine.  Once it happens it does not correct itself.  The other part that seems to stand out is if I remove ALL consumers under normal conditions all the producers are cleaned up EXCEPT when the failure occurs the audio channel sticks around with no consumers.

**Comment by AlexxIT** [comment]
Reopen issue if it still relevant

**Comment by skynet01** [comment]
I've been getting the same errors as you "Failed to start WebRTC stream: WebRTC offer was not accepted by any providers
" 
and 
```
23:19:27.127 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:51 > error=EOF url=rtsp://172.16.3.161:38599/69f4b72cd9d9654e
23:19:27.127 WRN github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:198 > stream.AddConsumer error="source 0 error: EOF"
23:19:27.128 ERR [api.hass] exchange SDP error="source 0 error: EOF" 
```
This seems to happen when I use the rebroadcast URL from Scrypted. The weird part is that I have 10 cameras and only 2 of them have this issue with the rebroadcast URL. Would love to help troubleshoot this as this was not the issue on the v2 releases.

**Comment by AlexxIT** [comment]
@skynet01 maybe your problem related to #165 
Because you using RTSPtoWebRTC integration.
I recommend to use WebRTC Camera v3

**Comment by skynet01** [comment]
Ah ... I see you remember :) I am actually using both since I wanted to have built-in ha entity support as well.. or does the new v3 has that feature as well now?
