### ISSUE TITLE
Liveview in HomeAssistant with go2rtc under Frigate

### ISSUE THREAD

**Issue by UeT-Fire** [AlexxIT/go2rtc#900]
Hello everyone, 

I hope someone can help me.

I use go2rtc in conjunction with Frigate on Home Assistant. I would also like to include a camera stream as a live view in my dashboard. I have installed the WebRTC Camera integration and the Frigate Lovelace Card. This works very well on the PC browser using WebRTC. However, when I am on the go with my iPhone, it automatically switches to the MSE stream, which does not work on iOS devices. Is there any other way to achieve a live view in the HomeAssistant iOS app?

**Comment by NickM-27** [comment]
it should use webrtc unless your iphone is unable to use webrtc for some reason. Also, on iOS 17.1+ MSE does work on iPhone

**Comment by UeT-Fire** [comment]
I don't know why MSE is not working on my iPhone. I have the latest iOS version installed. However, I managed to get the WebRTC stream running. I had to open the TCP and UDP ports on my router and expand my configuration. Since then, it works flawlessly.

webrtc:
  candidates:
    - stun:8555  # if you have dynamic public IP-address
