### ISSUE TITLE
Stream dies with EOF error every 10 minutes to the second

### ISSUE THREAD

**Issue by andonevris** [AlexxIT/go2rtc#908]
I have a stream that dies every 10 minutes exactly from when go2rtc launches.  It is a Tuya camera with its stream exposed using the "expose_camera_stream" hacs integration.

Refreshing the webpage brings the stream back up.  

As you can see from the logs it happens at precise 10 minute intervals

```
1/27/2024, 12:32:03 PM	info	go2rtc version 1.8.5 linux/amd64
1/27/2024, 12:32:03 PM	info	[rtsp] listen addr=:8554
1/27/2024, 12:32:03 PM	info	[api] listen addr=:1984
1/27/2024, 12:32:03 PM	info	[webrtc] listen addr=:8555
1/27/2024, 12:42:10 PM	warn	undefined error=EOF url=echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.xxxxxxx caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171
1/27/2024, 12:52:10 PM	warn	undefined error=EOF url=echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.xxxxxxx caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171
1/27/2024, 1:02:11 PM	warn	undefined error=EOF url=echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.xxxxxxx caller=github.com/AlexxIT/go2rtc/internal/streams/producer.go:171
```

I have other streams from different cameras that don't exhibit this issue.

Using the Tuya app I can watch the stream indefinitely so it's not Tuya cutting the stream off.

**Comment by AlexxIT** [comment]
Why do you think Tuya app uses same protocol?

**Comment by andonevris** [comment]
> Why do you think Tuya app uses same protocol?

I don't, I'm just putting the info there for you in case it helps with diagnosis. 

I considered it could well be Tuya but the stream restarts at 10 minute intervals from when go2rtc first launches so thought it could also be possible its go2rtc somehow.

**Comment by AlexxIT** [comment]
You do.

> Using the Tuya app I can watch the stream indefinitely so it's not Tuya cutting the stream off.

I think Tuya API from Hass integration, that you using, provide link only for 10 minutes. It's usual situation. Nest gives link only for 5 minutes

**Comment by andonevris** [comment]
> You do.
> 
> > Using the Tuya app I can watch the stream indefinitely so it's not Tuya cutting the stream off.
> 
> I think Tuya API from Hass integration, that you using, provide link only for 10 minutes. It's usual situation. Nest gives link only for 5 minutes

I see, OK useful info thanks. 

It only started happening this past week though, previously it would stay on indefinitely, anyway thanks for the clarification.

**Comment by oleg-d** [comment]
@andonevris i have the same EOF that freezes my feed on v1.8.5 but on 1.8.4 it's working absolutely fine all day.

**Comment by andonevris** [comment]
> @andonevris i have the same EOF that freezes my feed on v1.8.5 but on 1.8.4 it's working absolutely fine all day.

Thanks for that.  Yeah like I tried to explain this was a recent issue but it was obvious the dev had no interest in this issue and wanted to blame protocols.

In the end I threw the feed into frigate and used a frigate lovelace card, feed stays up all day now.

Useful to know which version broke this though, thank you

**Comment by AlexxIT** [comment]
@andonevris and now you're blaming the developer for something he didn't do.
I said "I think...". And didn't close this issue or the issue from @oleg-d 

I think Tuya breaks connection after 10 minutes all the time. But v1.8.4 can handle auto reconnect, and v1.8.5 don't.
