### ISSUE TITLE
FFMPEG On-The-Fly Conversion of RTSP H.265 to H.264: Problems

### ISSUE THREAD

**Issue by darethehair** [AlexxIT/go2rtc#91]
I get a hint that the RTSP Swann camera feeds that our non-profit is using are H.265 format, and therefore incompatible with various WebRTC projects, but when I took note that Go2RTC had a way of dealing with this i.e. on-the-fly conversion using FFMPEG:

ffmpeg:rtsp://user:pass@ipaddr:554/ip06/0#video=h264

For my home (Tapo) cameras, which are also RTSP, but not using H.265, this works fine (no errors), but when I try it on the Swann H.265 cameras, I get no feed but instead get this strange diagnostic:

`TODO: webrtc ontrack &{mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} id:4dffc49b-20cc-481f-bc21-a605ee5a761e streamID:s2IkZMQRejMOasBuCUunhbaFrVfnyyIXcf5e payloadType:111 kind:1 ssrc:2037322378 codec:{RTPCodecCapability:{MimeType:audio/opus ClockRate:48000 Channels:2 SDPFmtpLine:minptime=10;useinbandfec=1 RTCPFeedback:[{Type:transport-cc Parameter:}]} PayloadType:111 statsID:} params:{HeaderExtensions:[{URI:http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01 ID:4}] Codecs:[{RTPCodecCapability:{MimeType:audio/opus ClockRate:48000 Channels:2 SDPFmtpLine:minptime=10;useinbandfec=1 RTCPFeedback:[{Type:transport-cc Parameter:}]} PayloadType:111 statsID:}]} rid: receiver:0xc0004f8540 peeked:[144 239 116 20 60 187 230 247 121 111 18 138 190 222 0 1 65 0 1 0 120 3 216 98 15 167 107 107 178 0 123 27 27 119 90 81 33 77 80 209 81 175 44 125 93 40 141 238 29 29 205 240 222 213 87 5 246 132 198 74 32 126 118 94 205 109 159 24 239 35 143 42 201 92 195 33 154 35 195 49 197 41 0 101 49 121 174 211 180 222 56 55 68 73] peekedAttributes:map[0:0xc0000b9e50]}`

Is there something that I can do about this?  I have been trying both the 'RTSPtoWebRTC' project and this 'Go2RTC' one, and neither are able to get me to the success point that I am hoping for.  Thanks for any help!

**Comment by AlexxIT** [comment]
This message not related to issue.
You need to increase log level and search something useful there.

**Comment by darethehair** [comment]
Followup: The 'debug' option doesn't seem to provide more info, so here is a 'trace' instead:

https://www.dropbox.com/s/pwr6coiir47yli3/go2rtc.trace?dl=0

I don't see anything 'bad', but I have no idea what I should really be looking for.

Thanks

**Comment by AlexxIT** [comment]
Important log parts:

```
Input #0, rtsp, from 'rtsp://admin:mypassword@192.168.100.250:554/ip06/0':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuvj420p(pc, bt709), 3840x2160, 90k tbr, 90k tbn, 90k tbc
Please use -profile:a or -profile:v, -profile is ambiguous
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[swscaler @ 0x5b3a518da800] deprecated pixel format used, make sure you did set range correctly
[rtsp @ 0x5b3a518a6b00] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2
```

```
Output #0, rtsp, to 'rtsp://localhost:8554/45ec2907f785d2823e3fbf8a57c9f8f1':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 3840x2160, q=-1--1, 90k fps, 90k tbn, 90k tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
```

FFmpeg can start transcoding, but can't produce frames.

You can try to find right encoding options for your stream (without go2rtc). Start with this:

```
ffmpeg -i rtsp://admin:mypassword@192.168.100.250:554/ip06/0 -codec:v libx264 -g 30 -preset superfast -tune zerolatency -profile main -level 4.1 -pix_fmt yuv420p -an -t 10 out.mp4
```
