### ISSUE TITLE
docker application crashing

### ISSUE THREAD

**Issue by kalmastenitin** [AlexxIT/go2rtc#911]
I am running application in docker with provided docker image without modifying anything. I have added 10 rtsp cameras for live streaming.
After running for more than 3 days I saw log. attached screenshot.
I don't know the reason.
@AlexxIT Help me out

![image](https://github.com/AlexxIT/go2rtc/assets/17327672/20d2b256-4d42-4518-add9-dba49b0f5dfb)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/718
