### ISSUE TITLE
Help wanted: working with usb cam

### ISSUE THREAD

**Issue by n1ght-hunter** [AlexxIT/go2rtc#912]
im trying to figure out if there is a better way to do this i have been messing around for a few hours and finally got my webcam working with the exec below
`printer: exec:ffmpeg -f v4l2 -framerate 30 -c:v mjpeg -i /dev/video0 -c copy -rtsp_transport tcp -f rtsp {output}`
was wondering if there is a better way to do this.
i need the `-f v4l2 -framerate 30 -c:v mjpeg` part or i dont get any frames from the camera.
Thanks in advance

**Comment by AlexxIT** [comment]
```streams:
  printer: ffmpeg:device?video=/dev/video0&input_format=mjpeg&framerate=30
```

**Comment by n1ght-hunter** [comment]
ive tried that and it doesnt seems to add the input format
i jsut get
`url="exec:ffmpeg -hide_banner -f v4l2 -framerate 30 -i /dev/video0 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://localhost:8554/6e815ea4ebb80a8671ea2a483352872b"`

**Comment by AlexxIT** [comment]
Are you using latest go2rtc?

**Comment by n1ght-hunter** [comment]
im on v1.8.4

**Comment by AlexxIT** [comment]
I don't know how it can add `framerate` and not add `input_format`

https://github.com/AlexxIT/go2rtc/blob/a87dafbbecdc64e4dae78fbbf99688f14301c583/internal/ffmpeg/device/device_linux.go#L14-L29

**Comment by AlexxIT** [comment]
Double check your config

```go
func TestParseArgsDevice(t *testing.T) {
	args := parseArgs("device?video=/dev/video0&input_format=mjpeg&framerate=30")
	require.Equal(t, `ffmpeg -hide_banner -f v4l2 -input_format mjpeg -framerate 30 -i /dev/video0 -c copy -f mjpeg -`, args.String())
}
```

**Comment by n1ght-hunter** [comment]
reply i coudln't figure it out either was very confused. i will keep messing around and get back to you
