### ISSUE TITLE
Two way audio using webRTC is lost when changing resolution or fps

### ISSUE THREAD

**Issue by jjorosa** [AlexxIT/go2rtc#915]
Hi everyone,

I have my stream defined as:

`rtsp://xxxxx:xxxxxx@192.168.86.64:554/Streaming/Channels/102`

With a Hikvision camera with two way audio. It works like a charm using the webRTC example:

`#share=xxxxxxx&pwd=xxxxxx&media=video+audio+microphone`

If I want to reduce the resolution or the fps, I tried defining the stream as:

`rtsp://xxxxx:xxxxxx@192.168.86.64:554/Streaming/Channels/102#width=640`

And indeed, the resolution is changed, but I'm losing the audio from the browser to the camera. The audio from the camera is not lost.

I tried using ffmpeg as a source:

`ffmpeg:rtsp://xxxxx:xxxxx@192.168.86.64:554/Streaming/Channels/102#video=h264#witdh=640#fps=6#audio=pcmu`

But with the same results.

Any idea if this is possible? 

Thanks!

**Comment by NickM-27** [comment]
you need to set separate streams, so it would be

```
streams:
  hikvision:
    - "ffmpeg:rtsp://xxxxx:xxxxx@192.168.86.64:554/Streaming/Channels/102#video=h264#witdh=640#fps=6#audio=pcmu"
    - rtsp://xxxxx:xxxxx@192.168.86.64:554/Streaming/Channels/102
```

**Comment by jjorosa** [comment]
Thanks a lot, @NickM-27. That did the trick!

Beware readers, because I mispelled "width".
