### ISSUE TITLE
Different timestamp in HD and SD stream on Reolink RLC-822A

### ISSUE THREAD

**Issue by muzzy124** [AlexxIT/go2rtc#917]
Hi there,
I see a strange bug. go2rtc 1.8.5 is in docker, alexxit/go2rtc image. My camera is reolink RLC-822A.
HD stream in go2rtc shows correct timestamp (maybe about 1 sec delay with actual time), but SD (sub) stream shows some past timestamp (about 12-14 secs delay with actual time).
If I open this camera in reolink app, it shows correct timestamps in both high and low mode.
It's a kind of cached stream that I see in SD? How to clear it? Docker container restart doesn't help.

Config:
```
  reolink_garage_outdoor_stream: 
    - rtsp://*:*@10.10.*.*:554/h265Preview_01_main
  reolink_garage_outdoor_stream_sub:
    - rtsp://*:*@10.10.*.*:554/h264Preview_01_sub
```
(the only difference I see in h264 in SD and h265 in HD stream)

Stream links are:
http://go2rtc.local:1984/stream.html?src=reolink_garage_outdoor_stream
http://go2rtc.local:1984/stream.html?src=reolink_garage_outdoor_stream_sub

**Comment by muzzy124** [comment]
Forgot to mention, it worked correctly for some time but I noticed this bug recently.
If I revert back to old SD config string like:
  reolink_garage_outdoor_stream_sub:
    - ffmpeg:http://10.10.*.*/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=*
 it show correct actual timestamp

**Comment by AlexxIT** [comment]
Have you read this? https://github.com/AlexxIT/go2rtc#source-rtsp

**Comment by muzzy124** [comment]
I have. But it worked before flawlessly. Anyway I've switched to ffmpeg link for SD stream because of this problem.

**Comment by AlexxIT** [comment]
You can restart your camera and delay will be fixed for free days. You can never trust RTSP from Reolink.
