### ISSUE TITLE
Add new Temporary stream fails when using ffmpeg or exec source

### ISSUE THREAD

**Issue by rajesindia** [AlexxIT/go2rtc#918]
Hi,

We try to add the stream via api

PUT http://localhost:1984/api/streams?src=exec:ffmpeg -ss 3600 -rtsp_transport tcp -i  rtsp://username:password@192.168.0.102/axis-media/media.amp?recordingid=xxxxx -c copy -rtsp_transport tcp -f rtsp {output}&name=stream1

it gives 400 bad request always. Could you help us in adding such streams via API?

**Comment by AlexxIT** [comment]
API don't work with spaces for security reason
