### ISSUE TITLE
Possibility to have video not muted by default

### ISSUE THREAD

**Issue by pmarki** [AlexxIT/go2rtc#92]
Hi, first of all great work, I've been using your WebRTC in home assistant, now my needs shifted a bit and here it is go2rtc.
Do you think it would make sense to you to make videos not muted by default? I mean changing html files to 
`<video id="video" autoplay controls playsinline></video>`
I use it as a baby monitor app (which is much better then provided by TP-link), having sound always on is very important in this usecase. I'm happy to create pull request if you're ok with this change (maybe you're planning making this part configurable? I'd really would like to help but go is totally out of my skill set). Anyway thank you for your work!

**Comment by AlexxIT** [comment]
This is very complicated feature. Browsers don't like when page run video with audio by default. This feature requires a great deal of research.

**Comment by AlexxIT** [comment]
I found one problem - autoplay without muted doesn't work in Safari.

**Comment by calisro** [comment]
Frigate card has auto_unmute options.  So if its in lovelace, it's possible with that card for now.

**Comment by AlexxIT** [comment]
More info about autoplay and muted https://developer.chrome.com/blog/autoplay/

**Comment by AlexxIT** [comment]
Latest version tries to play video with audio by default. If browser not block it.

**Comment by felipecrs** [comment]
@AlexxIT, that's true, but not in the two-way audio page:

https://user-images.githubusercontent.com/29582865/212432972-23b938c5-7f30-4ee7-89d5-097fb160f56f.mp4

**Comment by quizzical86** [comment]
@AlexxIT is there a solution to the two-way-audio stream being muted by default as shown in the video above?

**Comment by AlexxIT** [comment]
Default go2rtc stream page don't have mute setting. You can write your own player for your needs.

**Comment by quizzical86** [comment]
I'm afraid I don't have the skills to code a DIY player, but I appreciate your answer. Now I know I'm not simply overlooking some configuration that changes the default to unmuted.
Guess I'll have to live with unmuting it every time.
Thanks a lot for all your efforts on go2rtc!
