### ISSUE TITLE
webrtc/go2rtc stopped working in Home Assistant for Tuya cameras

### ISSUE THREAD

**Issue by GaryAW** [AlexxIT/go2rtc#924]
I have 8 cameras with two being Tuya .. Have all been working fine for months ..

Now the two Tuya ones don't stream

Message in video box says ..

**_webrtc/offer: streams: exit status 22_**

Any help appreciated .. did try reboot bu other 6 working and 2 tuya not working

**Comment by AlexxIT** [comment]
You need to provide more useful info about your setup

**Comment by GaryAW** [comment]
Thanks oleg-d .. Yes!!!

After many minutes of trying to get it sorted .. I reset everything starting with the Tuya Integration (Which as you say showed no cameras!!)

After re-installing and configuring .. my two Tuya cameras came back ..
Cheers
Gary

**Comment by GaryAW** [comment]
AlexxIT .. all fixed
