### ISSUE TITLE
no audio in the stream when using 2 way audio communication with frigate lovelace card

### ISSUE THREAD

**Issue by automjordan** [AlexxIT/go2rtc#925]

**Comment by automjordan** [comment]
i'm so sorry, the text disappared :
Hi there, i don't know if the right place to ask is here or in the repository of the lovelace frigate card but , the issue is that when i press the microphone button in the lovelace card, the audio stops and i'm not able to hear the audio from the camera.

Everything is set up according to documentation, i did the following test :

addedd " ?video&audio " after " rtsp://admin:*****@192.168.1.129:554/h264Preview_01_sub " this allowed me to hear the sound while the mic button was active, but unfortunately disabled 2 way audio config .
I'm using :

go2rtc version 1.7.1 linux/amd64
SYSTEM 0.13.1-34FB1C2
VM with proxmox on nuc with coral
reolink doorbell wifi with last firmware v3.0.0.2555_23080700
config as mentioned in the documentation
Thanks for your help!

**Comment by AlexxIT** [comment]
I'm not developer of frigate card. I't better to ask there.
