### ISSUE TITLE
Stream stays online, al lot of CPU usage 

### ISSUE THREAD

**Issue by Beer17HWAM** [AlexxIT/go2rtc#926]
HA docker 2024.1.6
WebRTC hacs v3.5.1

After viewing streams in Home Assistant with a WebRTC dashboard streams stays online and are using a lot of CPU usage. I can't stop the online streams, visible in go2rtc streams web view with a non zero. Not even with switching off Wi-Fi on the device which I viewed with. The online connections only disappear if I reload the WebRTC integration.

**Comment by ned-kelly** [comment]
This also sometimes happens directly when loading go2rtc in the browser and then cloading the webrtc stream - ffmpeg stays running in the background
