### ISSUE TITLE
webRTC stream stops playing after 35 seconds

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#93]
Watching streams back they play perfectly for 35 seconds and then immediately stop, this happens every time and exactly at 35 seconds. It happens in both safari and chrome. Refreshing the page lets the stream continue working for another 35 seconds.

Let me know what logs or other information would be helpful, thank you!

**Comment by AlexxIT** [comment]
Trace logs can be useful. It is better to make them on a separate installation of go2rtc, so that there are no unnecessary cameras. You can send them to me on Discord, so you don't have to publish something private.

**Comment by NickM-27** [comment]
ended up being an issue with 8555 on my host. Switching to a different port there fixed the issue.
