### ISSUE TITLE
FFmpeg Device / USB-camera: Power Saving / Turn Camera Off / Nginx exec_pull

### ISSUE THREAD

**Issue by TCB13** [AlexxIT/go2rtc#931]
Hello,

Many thanks for this great project. I'm not sure if this is somehow supported but here's my question / feature request.

I'm used to use Nginx to publish a rtmp stream from a USB camera and I wanted to move to this project as it supports more camera types and seems to have less latency than what I get with Nginx. Here's my typical Nginx config for refence.

```
rtmp {
        server {
                listen 1935;
                chunk_size 4096;
                allow publish 127.0.0.1;
                deny publish all;

                application live {
                        live on;
                        exec_pull /usr/bin/ffmpeg -f v4l2 -input_format h264 -video_size 1920x1080 -i /dev/video4 -copyinkf -codec copy -f flv rtmp://127.0.0.1/live/stream;
                        record off;
                }
        }
}
```

The important part here is the `exec_pull` option. **It starts external process when first subscriber connects to the stream and kills it when the last one disconnects**. It's extremely useful if you don't want the stream to be always pulled and transcoded but only do that when there's at least one client.

This means that whenever nobody is consuming the stream `ffmpeg` is killed and the camera is turned off / saving power. Is there a way to have the same behavior with go2rtc?

Thank you!

**Comment by AlexxIT** [comment]
This is the default behaviour. And users are now asking just the opposite - that the stream should run all the time, regardless of clients.

**Comment by TCB13** [comment]
> This is the default behaviour.

Great then! I'll to give it a try.

> And users are now asking just the opposite - that the stream should run all the time, regardless of clients.

Maybe include an option on the settings for those users? But I personally like it to only run whenever there's someone connected.

**Comment by AlexxIT** [comment]
This feature is not so easy to implement. The application architecture is not ready for it
