### ISSUE TITLE
Help needed to troubleshoot WebRTC via reverse proxy in HA.  Works through go2rtc:1984

### ISSUE THREAD

**Issue by kenjfox** [AlexxIT/go2rtc#94]
Trying to get this running outside of my network using a reverse proxy and wireguard (similar to an ngrok setup?).   Home Assistant and g2rtc running via docker compose on 192.168.8.10.  The proxy is running on 20.245.146.196.  I have port 8555 and 1984 open to the outside and mapped to the HA/go2rtc server.  I can see webrtc streams via the UI on :1984.  However, the same cameras don't work via Home Assistant.  

Questions:
1.  What do I need to change to get this running?  Does anything jump out in the attached logs?  Maybe "a=sctp-port:5000" is a clue?  5000 is not open to the outside.
2. There are multiple nats on each side, so ideally I'd want my streams to be sent through the wireguard tunnel.  I'm a bit rusty on reading sdp, but it appears to be a number of candidates offered that represent unroutable addresses within my internal network.  Is there a way to prevent them from being offered up?
3. Do I need to keep 1984 and 8555 open outside my tunnel on 20.245.146.196?

I'd appreciate any guidance you may have.

From HA:
[webrtc_fail.txt](https://github.com/AlexxIT/go2rtc/files/9914090/webrtc_fail.txt)
From go2rtc UI (works most of the time):
[webrtc_good.txt](https://github.com/AlexxIT/go2rtc/files/9914091/webrtc_good.txt)

**Comment by AlexxIT** [comment]
I think it work from addon UI and doesn't work from HA because addon UI can send public candidates for client (web browser).

Connection can be made in any direction (from client to server or from server to client). But in your case only client has public accessible address.

So you need tunnel 8555 to public address (proxy? in your case). And add it to YAML as one of candidates.

Also you can install TURN server on your public server and use it. But I haven't test this function in go2rtc project. Only in WebRTC Camera project
https://github.com/AlexxIT/WebRTC#webrtc-external-access

**Comment by kenjfox** [comment]
Thanks for your quick reply.  I did add my proxy address to the yaml as a candidate, and it appears to be offered... along with a bunch of others that are invalid. I guess I need to do some homework on routing.  
Cheers,

Ken

**Comment by AlexxIT** [comment]
No problem with wrong candidates. It is usual situation for webrtc. Browser will try to connect to all of them. It would be very quickly.

**Comment by spacebares** [comment]
Have you solved this? I believe i am having a similar issue with WebRTC working on external network _(192.168.1.x)_ threw HA External URL but not if im connected with internal network _(192.168.100.x)_.

**Comment by NickM-27** [comment]
> Have you solved this? I believe my similar issue shares the same solution, I have WebRTC working on external network _(192.168.1.x)_ threw HA External URL but not if im connected with internal network _(192.168.100.x)_. 

Is go2rtc running as host?

**Comment by spacebares** [comment]
> Is go2rtc running as host?

im not sure what you mean, It is the go2rtc embedded in the dev frigate.

**Comment by NickM-27** [comment]
> > Is go2rtc running as host?
> 
> im not sure what you mean, It is the go2rtc embedded in the dev frigate.
> 

Then is frigate running as host?

**Comment by spacebares** [comment]
> > > Is go2rtc running as host?
> > 
> > 
> > im not sure what you mean, It is the go2rtc embedded in the dev frigate.
> 
> Then is frigate running as network mode host?

Ya lost me there, i just have frigate repo cloned, and i run it with `docker compose up -d` on a machine that is hooked up to a router that is facing the internet. Another router connects to the first to form the other subnet, can view jsmpeg & MSE but not webRTC. If i use a device that is on the frigate subnet, things work just fine.

**Comment by NickM-27** [comment]
> Ya lost me there, i just have frigate repo cloned, and i run it with `docker compose up -d` on a machine that is hooked up to a router that is facing the internet. Another router connects to the first to form the other subnet, can view jsmpeg & MSE but not webRTC. If i use a device that is on the frigate subnet, webRTC work just fine.

First off this is incorrect, if you just want to run the frigate dev branch then you should use the packages https://github.com/blakeblackshear/frigate/pkgs/container/frigate as the repo itself is only meant to be run in a vscode dev container.

In any case, what you're experiencing is expected without additional config as it is covered in the dev docs https://github.com/blakeblackshear/frigate/blob/dev/docs/docs/configuration/live.md

**Comment by spacebares** [comment]
> 

Nice! That was it. I set docker host mode and frigate-go2rtc.yaml to docker-compose and webRTC works now. I will look into using the dev packages at some point. Thanks!

**Comment by AlexxIT** [comment]
Reopen issue if it still relevant
