### ISSUE TITLE
"Can't find consumer" trying to play an audio file with hikvision ISAPI

### ISSUE THREAD

**Issue by ProtoxiDe22** [AlexxIT/go2rtc#948]
Hi, i'm trying to play an audio file to an hikvision doorbell (DS-KV6113-WPE1(C)), that's configured in go2rtc as follows
```
  hikvision:
    - rtsp://admin:xxxx@192.168.1.x:554/Streaming/Channels/101
    - isapi://admin:xxxx@192.168.1.x:80/ 
``` 

the stream works great with the webrtc card and audio works both ways. 
however i can't seem to play an audio file manually via the api. this is the request i'm sending

`POST 'http://192.168.1.223:1984/api/streams?dst=hikvision&src=ffmpeg:https://file-examples.com/storage/fe34a88a9a65cf545955ccb/2017/11/file_example_MP3_700KB.mp3#audio=pcma#input=file'`

the response i'm getting is 500 with error message 'can't find consumer'
i can't in fact see any consumer active in the info page of the stream when trying this, but again, if i try to use the camera with the webrtc card everything works just fine, including the return channel via ISAPI

**Comment by AlexxIT** [comment]
You can increase log level to trace and check

**Comment by frstep** [comment]
@ProtoxiDe22 Did this get resolved for you? I'm having the same issue.

**Comment by AlexxIT** [comment]
Common problem with no encoding query params

**Comment by frstep** [comment]
Ok, so what is the call from the API to play a stream or file? http://localhost:1984/api/streams?dst=New_HV&src=ffmpeg:http://streams.radiomast.io/ref-32k-mp3-mono#audio=pcma

**Comment by frstep** [comment]
Increasing the log level was the answer: it looks like the links.html uses an api that I didn't know about (/api/ffmpeg) which works.

(the api call documented at https://github.com/AlexxIT/go2rtc#stream-to-camera still does not work for me)

**Comment by AlexxIT** [comment]
This is new easy to use API. Was introduced in some of v1.9.x.
Old API don't work for many users because they not encoding query parameters. For example `#` symbol

**Comment by frstep** [comment]
> This is new easy to use API. Was introduced in some of v1.9.x. 

I must have failed to fine the documentation :-(

> Old API don't work for many users because they not encoding query parameters. For example `#` symbol

I can't see how that explains why we've had problems, since we followed the documented api calls.

**Comment by AlexxIT** [comment]
https://en.wikipedia.org/wiki/URL

**Comment by benshabatnoam** [comment]
We're getting the same ''Can't find consumer" 500 error from the api call:
`http://my-ip-address:1984/api/streams?dst=speaker&src=ffmpeg:apex.mp3#audio=pcma#input=file`
![Snag_690710d](https://github.com/user-attachments/assets/27c2f3e6-5afb-4c50-ab3f-45a93455a4ef)

We added all possible logs and found that this is the ffmpeg request that was used by go2rtc:
`[exec] run url=exec:ffmpeg -hide_banner -v error -re -i apex.mp3 -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}`

Now when we're using the 'links' page with the same url request we're getting a 200 response with this log below that has some extra args in the ffmpeg command:
`[exec] run url=exec:ffmpeg -hide_banner -v error -re -i apex.mp3 -c:a pcm_alaw -ar:a 8000 -ac:a 1 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}`
As you can see the extra params are: `-c:a pcm_alaw -ar:a 8000 -ac:a 1 -vn`
![Snag_68eafa7](https://github.com/user-attachments/assets/eda8562d-0189-45bb-bb08-0dfc3121b736)

What can be the reason for that??

**Comment by benshabatnoam** [comment]
After 8 hours!! working on just to figure out what is the problem, I finally found that the `#` sign is the problem, it should be converted to `%23` instaed.

I use this url which didn't work:
`/streams?dst=speaker&src=ffmpeg:apex.mp3#audio=pcma`

And changed it to this url that worked:
`/streams?dst=speaker&src=ffmpeg:apex.mp3%23audio=pcma%23input=file`

😞

I hope this post will save your 8 hours.
Cheers

**Comment by AlexxIT** [comment]
Programs like Postman know this rule and convert query parameters using URL encoding.
But you need to enter query parameters through the “Params” tab.

**Comment by benshabatnoam** [comment]
> Programs like Postman know this rule and convert query parameters using URL encoding. But you need to enter query parameters through the “Params” tab.

That's accurate, that what I did and it worked, thanks
