### ISSUE TITLE
Disable two way audio from Home Assistant camera stream

### ISSUE THREAD

**Issue by mattbrad2** [AlexxIT/go2rtc#95]
Is there a way to disable audio completely from a camera stream? I'm having an issue with my Amcrest AD110 door bell where the chime gets disabled (and also the talk back function on the amcrest app) when go2rtc is streaming its video. It basically locks the mic channel so the doorbell itself doesn't even ring. This used to work flawlessly using WebRTC, but I'm not sure how to change this in go2rtc for it to not lock out the mic audio.

**Comment by NickM-27** [comment]
Just add `#backchannel=0` to the stream in go2rtc config

**Comment by AlexxIT** [comment]
Need to make this setting optional somehow

**Comment by mattbrad2** [comment]
Not sure where to put this in the config since there are no streams there. I'm having it automatically pick up the generic camera streams I've put into Home Assistant.

**Comment by mattbrad2** [comment]
That worked! Thank you

**Comment by calisro** [comment]
Just a thought but should the **default** be backchannel=1 rather than always enabled?

**Comment by aeozyalcin** [comment]
@mattbrad2 were you actually able to get 2-way audio working with your AD110 doorbell through go2rtc? I see that people have been getting it to work with their AD410's, but I haven't seen anyone else get it working on an AD110. 

If you got it working, I'd love some pointers!

**Comment by mattbrad2** [comment]
Sorry, no. Everything else works flawlessly though.

Matthew Bradley
President, Bradley Electronics
t: 770-408-0272 x2001 | a: 26 E Midland Ave, Winder, GA 30680
e: ***@***.*** | w: www.bradleyelectronics.com
________________________________
