### ISSUE TITLE
Can I serve a folder that contains subfolders and mp4 files?

### ISSUE THREAD

**Issue by jiekechoo** [AlexxIT/go2rtc#955]
Folder:
```
- media
  - 2024
    - 01
    - 02
      - 01.mp4
      - 02.mp4
```

**Comment by yeonzi** [comment]
I have the same problem.

My security camera will save the video to NFS server in 60s mp4 clips. And the folder looks like:

```
- camera
  - YYYYMMDD
    - hhmm.mp4
 ```

Is it possible to use this folder as a source?

Also, I tried to generate an m3u8 file by a script that refers those file, but it seems that these mp4 files does not have moov record before mdat block so it fails on VLS to play this source. so I think it maybe necessary to generate the m3u8 along with modify the mp4 file by ffmpeg, is it possible?

**Comment by AlexxIT** [comment]
Outside the scope of this project
