### ISSUE TITLE
pkg/isapi/client.go gets wrong URL to close session

### ISSUE THREAD

**Issue by f1d094** [AlexxIT/go2rtc#960]
in pkg/isapi/client.go, func Close is calling `/ISAPI/System/TwoWayAudio/channels/<channel id>/close/open` instead of `/ISAPI/System/TwoWayAudio/channels/<channel id>/close`

Submitted PR #959

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0
