### ISSUE TITLE
How to hide the plaintext password in the RTSP uri during packet capture?

### ISSUE THREAD

**Issue by tanpopoycz** [AlexxIT/go2rtc#968]
When using Wireshark to capture and camera RTSP negotiation messages...
![image](https://github.com/AlexxIT/go2rtc/assets/107358453/09cf1378-12a5-45ab-b9b9-18f420c05b8c)

**Comment by AlexxIT** [comment]
Add streams to config

**Comment by tanpopoycz** [comment]
I did it this way, but if the rtsp uri in the stream domain of the go2rtc.yaml file does not have a username and password, the actual situation fails with an error message indicating that the username and password were not provided

**Comment by AlexxIT** [comment]
So provide them in the config file

**Comment by tanpopoycz** [comment]
I don't quite understand what you mean.. I have provided the user and password in the stream uri of the configuration file, but the current issue is that the password during RTSP negotiation is transmitted in plaintext on the network. I want to hide the plaintext password on the network.. So I'm a bit confused about what you're saying, and there's no explanation in the github readme file, or is it that Go2RTC currently doesn't support it

**Comment by AlexxIT** [comment]
RTSP is plaintext protocol

**Comment by tanpopoycz** [comment]
But there is another authentication process (two DESCRIBE requests), instead of directly playing a uri with a user and password. Would you consider changing the format of the request uri, such as adding a configuration item in the configuration file stream, to solve this problem?

**Comment by AlexxIT** [comment]
I really don't understand what you talking about

**Comment by tanpopoycz** [comment]
sry sry sry, my mistake ,there's some things wrong...😱 let me make sure...
