### ISSUE TITLE
Streams fail to clear after view change causing lagging afterwards

### ISSUE THREAD

**Issue by neogenx** [AlexxIT/go2rtc#970]
Hello together.

Having issue with go2rtc (and WebRTC) while using my android tablet (Honor Tab X8).
I noticed that I can only stream video from my camera when opening the HA app and opening the view for the first time. Then, when I change to another view and coming back again, video becomes lagging or not loading at all. In go2rtc "Streams" overview I can see many opened streams which were not closed (log saying all of them are from this specific tablet). Not happening on my iPhone or PC.
Thank you

**Comment by AlexxIT** [comment]
1. Show webrtc card code
2. Check streams list after 1 minute

**Comment by neogenx** [comment]
Code:

type: custom:webrtc-camera
url: rtsp://xxxxxx:yyyyyy@192.168.2.xxx:8554/camera.Kamera_obyvak
title: Kamera obývák
intersection: 0.75
background: true
mode: webrtc,mse,mp4,mjpeg
ui: true

**Comment by AlexxIT** [comment]
So you enabling the mode when streams don't break. And you're complaining that it works?

**Comment by neogenx** [comment]
I don't get you. I complain about behaviour happening only on android tablet. My iPhone, Windows PC are working perfectly.

**Comment by AlexxIT** [comment]
This is not go2rtc issue https://github.com/AlexxIT/WebRTC/issues/463
