### ISSUE TITLE
Unable to open RTSP for specific cameras

### ISSUE THREAD

**Issue by DGAzr** [AlexxIT/go2rtc#971]
I'm experiencing a strange issue with two of my eight cameras in go2rtc. Most of my cameras are fine, but these two are of a different manufacturer and for some reason go2rtc cannot open their RTSP streams. The strange thing is that other RTSP clients have no trouble opening the same stream from these two cams, it's only go2rtc that fails. 

When go2rtc attempts to open the stream the only thing I see in the log is:

```
frigate    | 2024-02-26 13:33:48.031319333  13:33:48.030 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 10.11.101.15:46782->192.168.99.218:554: read: connection reset by peer" url=rtsp://frigate:********@192.168.99.218:554
frigate    | 2024-02-26 13:33:48.917906052  13:33:48.917 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 10.11.101.15:46788->192.168.99.218:554: read: connection reset by peer" url=rtsp://frigate:********@192.168.99.218:554
frigate    | 2024-02-26 13:33:49.794973678  13:33:49.794 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 10.11.101.15:46798->192.168.99.218:554: read: connection reset by peer" url=rtsp://frigate:********@192.168.99.218:554
frigate    | 2024-02-26 13:33:50.740905949  13:33:50.740 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 10.11.101.15:46808->192.168.99.218:554: read: connection reset by peer" url=rtsp://frigate:********@192.168.99.218:554
frigate    | 2024-02-26 13:33:51.634536458  13:33:51.634 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 10.11.101.15:46824->192.168.99.218:554: read: connection reset by peer" url=rtsp://frigate:********@192.168.99.218:554
```

go2rtc can open other camera streams on the same target network as these problem cams. VLC, HomeAssistant, and ffmpeg are able to open the streams from these problem cams without any issue at all which is very confusing. 

I've tried both the go2rtc included with frigate, and a dedicated go2rtc docker image and both experience the same problem. 

I am almost suspecting an encoding error from the camera stream that ffmpeg handles somewhat more gracefully than go2rtc, but this is purely speculation based on an occasional ffprobe output that looks like this:

```
$ ffprobe rtsp://frigate:*********@192.168.99.218:554
ffprobe version 5.1.4-0+deb12u1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55c4827cd700] max delay reached. need to consume packet
[rtsp @ 0x55c4827cd700] RTP: missed 156 packets
[h264 @ 0x55c4827d2400] cabac decode of qscale diff failed at 85 29
[h264 @ 0x55c4827d2400] error while decoding MB 85 29, bytestream 62785
[h264 @ 0x55c4827d2400] concealing 8540 DC, 8540 AC, 8540 MV errors in I frame
Input #0, rtsp, from 'rtsp://frigate:********@192.168.99.218:554':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.233422, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 2048x1536, 15 fps, 15 tbr, 90k tbn
```

That `cabac decode...` error does not appear every time, but most of the times I see it with ffprobe. 

Any advice on how might I go about debugging the cause of this?

**Comment by marsmaennchen** [comment]
I would like to join in here because this is closest to my problem.
I integrated go2rtc 1.8.5 in HomeAssistant Frontend with:
`type: custom:webrtc-camera
url: homeassistant`

The Camera is a HikVision
Now I can see the Stream via _Windows PC_ (logged into the HA Frontend) and Android Smartphone with HA App.
But
when i log into the HA Frontend via _Windows Laptop_ or _RaspberryPi_ with FullPageOS i only see a black Screen. But the SoundBar at the bottom is alive.

my current config is:
`streams:
        
    homeassistant: rtsp://User:password@192.xxx.x.xxx:554/Streaming/channels/101`

Any idea what else i could try?

**Comment by Soulflyzz** [comment]
I would also like to join in on this.
I have 3 different Hikvision Models cameras in my house and 2 of them work with go2rtc but one has the same issue as above.
There are 2 main differences with this camera it has Audio and it's on wifi. I have disabled the audio in the Config settings on the camera, besides that everything is the same on all three cameras.

**Comment by Genieplumb** [comment]
I would also like to add to the list : this time I have one of my Hikvision cameras that will only allow one stream to connect. sometimes after a restart it the main stream, then it will be the sub stream that won't connect "error="read tcp 172.18.0.2:50232->192.168.1.221:554: read: connection reset by peer" url=rtsp://XXXXX:XXXXX@192.168.1.221:554/Streaming/Channels/102

**Comment by marsmaennchen** [comment]
Have you Guys tried to configurate your cams to different Codecs? In my Case i need to configurate my Cam to H264

**Comment by Soulflyzz** [comment]
> Have you Guys tried to configurate your cams to different Codecs? In my Case i need to configurate my Cam to H264

Yes and no,
I have not tried a different codec because h.264 is the only available option.
Also, I have the same settings on the one camera as I have on the other 2.

**Comment by Genieplumb** [comment]
> Have you Guys tried to configurate your cams to different Codecs? In my Case i need to configurate my Cam to H264

Yes yes and yes.. tried and spend hours/days on this and still no luck, the fact it obits in a first come first sort or action seem like there's a "computer says no" action from a second feed to he same ip and only on multiple cameras of this type or codec..  

Also it connects to the sub feed then won't to the main feed  then after a restart of the container the opposite happens ?? connecting the the main feed and saying no the the sub feed..

**Comment by AlexxIT** [comment]
PS. All recommendations for problem RTSP source described here:
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-rtsp

Using ffmpeg source is one of solutions.

**Comment by DGAzr** [comment]
Understood. I will mark this one as closed then. I would rather not replace the camera because they're in really inconvenient locations. They're actually quite reliable with ffmpeg or other clients (like my Synology Surveillance Station, or ZoneMinder which I used in the past) so I will happily deal with ffmpeg rather than climb 30' up a ladder again.

Thanks so much for your reply here, love the software!
