### ISSUE TITLE
[docs update request] add instructions to the docs how to add SSL/HTTPS to go2rtc dashboard in home assistant?

### ISSUE THREAD

**Issue by borgqueenx** [AlexxIT/go2rtc#976]
The go2rtc dashboard supports using the microphone, but this is kinda useless if the browser is not using https.
It is possible to make home assistant itself use https, but the go2rtc dashboard(installed through frigate) is then still using http.

Could the documentation please add a section how to get this working for at least home assistant?
Thanks!

**Comment by AlexxIT** [comment]
Out of scope this project
