### ISSUE TITLE
time overlay not working - mapping not allowed in this context.

### ISSUE THREAD

**Issue by ddean6232** [AlexxIT/go2rtc#983]
This is valid ffmpeg but does not work in go2rtc.  Is there a fix for this in go2rtc?
```
ffmpeg -re -loop 1 -i puppy-snout-dog-1280x720.jpg -vf drawtext="fontfile=monofonto.ttf: fontsize=96: box=1: boxcolor=black@0.75: boxborderw=5: fontcolor=white: x=(w-text_w)/2: y=((h-text_h)/2)+((h-text_h)/4): text='%{gmtime\:%H\\\\\:%M\\\\\:%S}'" ... {output}
```

**Comment by AlexxIT** [comment]
You can enable trace logs for exec module and check error

**Comment by ddean6232** [comment]
it does not get into the exec module... the error is in configuration... see attached 

![Capture1](https://github.com/AlexxIT/go2rtc/assets/23565169/a53eddc9-dad8-448c-8791-f9e4fa7c7677)
![Capture](https://github.com/AlexxIT/go2rtc/assets/23565169/e0bfad45-05e3-4260-81cc-e406d88b780b)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#module-log

**Comment by ddean6232** [comment]
I don't think you are understanding.... This does not get saved and restarted ... Setting a log level does nothing
