### ISSUE TITLE
Two-way audio not working anymore with latest Reolink Doorbell Firmware

### ISSUE THREAD

**Issue by marcosimeone** [AlexxIT/go2rtc#987]
Hello,

Since the release of the latest firmware for Reolink Doorbell, two-way audio is not working anymore. Video and main audio channel are working as expected. From what i can see, it seems the active producer audio codec was changed from PCMA to PCMU.

I can paste some logs to help investigations in order to better understand if the issue comes from go2rtc or the doorbell itself.

`{
  "producers": [
    {
      "type": "RTSP passive producer",
      "url": "rtsp://127.0.0.1:8554/602e1a386e35963abdfdb361802a02cb",
      "remote_addr": "127.0.0.1:36754",
      "user_agent": "ffmpeg/go2rtc",
      "sdp": "v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=Session streamed by \"preview\"\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\na=tool:libavformat 60.16.100\r\nm=video 0 RTP/AVP 96\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033\r\na=control:streamid=0\r\nm=audio 0 RTP/AVP 0\r\nb=AS:64\r\na=control:streamid=1\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=4151888, senders=1",
        "0 PCMU/8000, bytes=66544, senders=1"
      ],
      "recv": 4255180
    },
    {
      "type": "RTSP active producer",
      "url": "rtsp://[camera_ip]/Preview_01_main/",
      "remote_addr": "[camera_ip]:554",
      "user_agent": "go2rtc/1.8.5",
      "sdp": "v=0\r\no=- 1709647899235247 1 IN IP4 [camera_ip]\r\ns=Session streamed by \"preview\"\r\nt=0 0\r\na=tool:BC Streaming Media v202210012022.10.01\r\na=type:broadcast\r\na=control:*\r\na=range:npt=now-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==\r\na=recvonly\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:8192\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=recvonly\r\na=control:track2\r\nm=audio 0 RTP/AVP 0\r\na=control:track3\r\na=rtpmap:0 PCMU/8000\r\na=sendonly",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000",
        "audio, sendonly, PCMU/8000"
      ],
      "senders": [
        "0 PCMU/8000, bytes=64000, receivers=1"
      ],
      "recv": 132,
      "send": 70400
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "udp4 host [client_ip]:46127",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16, PCML"
      ],
      "receivers": [
        "0 PCMU/8000, bytes=64000, senders=1"
      ],
      "senders": [
        "102 H264, bytes=4151888, receivers=1",
        "0 PCMU/8000, bytes=66544, receivers=1"
      ],
      "recv": 72210,
      "send": 4262438
    }
  ]
}`

`[webrtc] offer:
v=0
o=- 8059316927483008255 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:czGG
a=ice-pwd:JoTamRT+/nUE3WLr0kZOmP7A
a=ice-options:trickle
a=fingerprint:sha-256 C2:5B:4E:DE:67:67:3B:EF:92:71:02:89:BC:D2:7C:DD:30:6E:59:75:69:44:C1:11:6B:46:98:C8:05:68:D2:DD
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendonly
a=msid:- 30e9fab3-3311-44d5-bed8-75efc5867484
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:807325059 cname:imqglFdS1cEV0xQ8
a=ssrc:807325059 msid:- 30e9fab3-3311-44d5-bed8-75efc5867484
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 103 104 105 106 107 108 109 127 125 39 40 41 42 43 44 45 46 47 48 112 113 114 49
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:czGG
a=ice-pwd:JoTamRT+/nUE3WLr0kZOmP7A
a=ice-options:trickle
a=fingerprint:sha-256 C2:5B:4E:DE:67:67:3B:EF:92:71:02:89:BC:D2:7C:DD:30:6E:59:75:69:44:C1:11:6B:46:98:C8:05:68:D2:DD
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:35 VP9/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=fmtp:35 profile-id=1
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:37 VP9/90000
a=rtcp-fb:37 goog-remb
a=rtcp-fb:37 transport-cc
a=rtcp-fb:37 ccm fir
a=rtcp-fb:37 nack
a=rtcp-fb:37 nack pli
a=fmtp:37 profile-id=3
a=rtpmap:38 rtx/90000
a=fmtp:38 apt=37
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:104 H264/90000
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 transport-cc
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=127
a=rtpmap:39 H264/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
a=rtpmap:40 rtx/90000
a=fmtp:40 apt=39
a=rtpmap:41 H264/90000
a=rtcp-fb:41 goog-remb
a=rtcp-fb:41 transport-cc
a=rtcp-fb:41 ccm fir
a=rtcp-fb:41 nack
a=rtcp-fb:41 nack pli
a=fmtp:41 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=f4001f
a=rtpmap:42 rtx/90000
a=fmtp:42 apt=41
a=rtpmap:43 H264/90000
a=rtcp-fb:43 goog-remb
a=rtcp-fb:43 transport-cc
a=rtcp-fb:43 ccm fir
a=rtcp-fb:43 nack
a=rtcp-fb:43 nack pli
a=fmtp:43 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=f4001f
a=rtpmap:44 rtx/90000
a=fmtp:44 apt=43
a=rtpmap:45 AV1/90000
a=rtcp-fb:45 goog-remb
a=rtcp-fb:45 transport-cc
a=rtcp-fb:45 ccm fir
a=rtcp-fb:45 nack
a=rtcp-fb:45 nack pli
a=rtpmap:46 rtx/90000
a=fmtp:46 apt=45
a=rtpmap:47 AV1/90000
a=rtcp-fb:47 goog-remb
a=rtcp-fb:47 transport-cc
a=rtcp-fb:47 ccm fir
a=rtcp-fb:47 nack
a=rtcp-fb:47 nack pli
a=fmtp:47 profile=1
a=rtpmap:48 rtx/90000
a=fmtp:48 apt=47
a=rtpmap:112 red/90000
a=rtpmap:113 rtx/90000
a=fmtp:113 apt=112
a=rtpmap:114 ulpfec/90000
a=rtpmap:49 flexfec-03/90000
a=rtcp-fb:49 goog-remb
a=rtcp-fb:49 transport-cc
a=fmtp:49 repair-window=10000000
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:czGG
a=ice-pwd:JoTamRT+/nUE3WLr0kZOmP7A
a=ice-options:trickle
a=fingerprint:sha-256 C2:5B:4E:DE:67:67:3B:EF:92:71:02:89:BC:D2:7C:DD:30:6E:59:75:69:44:C1:11:6B:46:98:C8:05:68:D2:DD
a=setup:actpass
a=mid:2
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000

[rtsp] server request:
OPTIONS rtsp://127.0.0.1:8554/602e1a386e35963abdfdb361802a02cb RTSP/1.0
Cseq: 1
User-Agent: ffmpeg/go2rtc

[rtsp] server response:
RTSP/1.0 200 OK
Public: OPTIONS, SETUP, TEARDOWN, DESCRIBE, PLAY, PAUSE, ANNOUNCE, RECORD
Cseq: 1

[rtsp] server request:
ANNOUNCE rtsp://127.0.0.1:8554/602e1a386e35963abdfdb361802a02cb RTSP/1.0
Content-Type: application/sdp
Cseq: 2
User-Agent: ffmpeg/go2rtc
Content-Length: 346

v=0
o=- 0 0 IN IP4 127.0.0.1
s=Session streamed by "preview"
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 60.16.100
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==; profile-level-id=640033
a=control:streamid=0
m=audio 0 RTP/AVP 0
b=AS:64
a=control:streamid=1

[rtsp] server response:
RTSP/1.0 200 OK
Cseq: 2

[rtsp] server request:
SETUP rtsp://127.0.0.1:8554/602e1a386e35963abdfdb361802a02cb/streamid=0 RTSP/1.0
User-Agent: ffmpeg/go2rtc
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=record
Cseq: 3

[rtsp] server response:
RTSP/1.0 200 OK
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
Cseq: 3
Session: 70543537;timeout=60

[rtsp] server request:
SETUP rtsp://127.0.0.1:8554/602e1a386e35963abdfdb361802a02cb/streamid=1 RTSP/1.0
Cseq: 4
User-Agent: ffmpeg/go2rtc
Session: 70543537
Transport: RTP/AVP/TCP;unicast;interleaved=2-3;mode=record

[rtsp] server response:
RTSP/1.0 200 OK
Session: 82989202;timeout=60
Transport: RTP/AVP/TCP;unicast;interleaved=2-3
Cseq: 4

[rtsp] server request:
RECORD rtsp://127.0.0.1:8554/602e1a386e35963abdfdb361802a02cb RTSP/1.0
Cseq: 5
User-Agent: ffmpeg/go2rtc
Session: 70543537
Range: npt=0.000-

[rtsp] server response:
RTSP/1.0 200 OK
Cseq: 5
Session: 82989202

[rtsp] client request:
DESCRIBE rtsp://[camera_ip]:554/h264Preview_01_main RTSP/1.0
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.8.5
CSeq: 1
Accept: application/sdp

[rtsp] client response:
RTSP/1.0 401 Unauthorized
Cseq: 1
Date: Wed, Mar 06 2024 14:54:45 GMT
Www-Authenticate: Digest realm="BC Streaming Media", nonce="2a169ed8bc28465db5b2d726be106dde"

[rtsp] client request:
DESCRIBE rtsp://[camera_ip]:554/h264Preview_01_main RTSP/1.0
Authorization: Digest username="user", realm="BC Streaming Media", nonce="2a169ed8bc28465db5b2d726be106dde", uri="rtsp://[camera_ip]:554/h264Preview_01_main", response="578fcfd6c1c1a9caa678ce1bfe51562a"
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.8.5
CSeq: 2

[rtsp] client response:
RTSP/1.0 200 OK
Cseq: 2
Date: Wed, Mar 06 2024 14:54:45 GMT
Content-Base: rtsp://[camera_ip]/Preview_01_main/
Content-Type: application/sdp
Content-Length: 742

v=0
o=- 1709647899235247 1 IN IP4 [camera_ip]
s=Session streamed by "preview"
t=0 0
a=tool:BC Streaming Media v202210012022.10.01
a=type:broadcast
a=control:*
a=range:npt=now-
a=x-qt-text-nam:Session streamed by "preview"
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:8192
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGQ,aO48sA==
a=recvonly
a=control:track1
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
b=AS:8192
a=rtpmap:97 MPEG4-GENERIC/16000
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408
a=recvonly
a=control:track2
m=audio 0 RTP/AVP 0
a=control:track3
a=rtpmap:0 PCMU/8000
a=sendonly

[rtsp] client request:
SETUP rtsp://[camera_ip]/Preview_01_main/track3 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=4-5
CSeq: 3
Authorization: Digest username="user", realm="BC Streaming Media", nonce="2a169ed8bc28465db5b2d726be106dde", uri="rtsp://[camera_ip]/Preview_01_main/track3", response="2452d0bbec2a4e0e6d0978e90a8b5793"

[rtsp] client response:
RTSP/1.0 200 OK
Cseq: 3
Date: Wed, Mar 06 2024 14:54:45 GMT
Transport: RTP/AVP/TCP;unicast;destination=[server_ip];source=[camera_ip];interleaved=4-5
Session: FE631D5A;timeout=65

[rtsp] client request:
PLAY rtsp://[camera_ip]/Preview_01_main/ RTSP/1.0
CSeq: 4
Authorization: Digest username="user", realm="BC Streaming Media", nonce="2a169ed8bc28465db5b2d726be106dde", uri="rtsp://[camera_ip]/Preview_01_main/", response="efb929bd911cf0dd40d2e20f67d2921b"
Session: FE631D5A

[webrtc] answer
v=0
o=- 7492827502987364652 1709736885 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 3B:7C:C9:EB:C5:03:C3:80:23:A8:78:FE:60:A7:E2:DD:DC:9E:F3:7D:9F:DF:3C:E2:4B:B5:E5:E5:08:C5:A4:CD
a=extmap-allow-mixed
a=group:BUNDLE 0 1 2
m=audio 9 UDP/TLS/RTP/SAVPF 0
c=IN IP4 0.0.0.0
a=setup:active
a=mid:0
a=ice-ufrag:tQQbeIdFzGgntjXi
a=ice-pwd:oGdiziNLJMOMkkeJfvgExRvZGAarGLXs
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:0 PCMU/8000
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=recvonly
m=video 9 UDP/TLS/RTP/SAVPF 102 106
c=IN IP4 0.0.0.0
a=setup:active
a=mid:1
a=ice-ufrag:tQQbeIdFzGgntjXi
a=ice-pwd:oGdiziNLJMOMkkeJfvgExRvZGAarGLXs
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtpmap:106 H264/90000
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:3404690778 cname:go2rtc
a=ssrc:3404690778 msid:go2rtc go2rtc-video
a=ssrc:3404690778 mslabel:go2rtc
a=ssrc:3404690778 label:go2rtc-video
a=msid:go2rtc go2rtc-video
a=sendonly
m=audio 9 UDP/TLS/RTP/SAVPF 111 0 8
c=IN IP4 0.0.0.0
a=setup:active
a=mid:2
a=ice-ufrag:tQQbeIdFzGgntjXi
a=ice-pwd:oGdiziNLJMOMkkeJfvgExRvZGAarGLXs
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:1402251925 cname:go2rtc
a=ssrc:1402251925 msid:go2rtc go2rtc-audio
a=ssrc:1402251925 mslabel:go2rtc
a=ssrc:1402251925 label:go2rtc-audio
a=msid:go2rtc go2rtc-audio
a=sendonly`

**Comment by NickM-27** [comment]
what firmware version are you referring to

**Comment by marcosimeone** [comment]
This one:
[Reolink Video Doorbell WiFi](https://reolink.com/product/reolink-video-doorbell-wifi/)
DB_566128M5MP_W
v3.0.0.3215
Note & What's New
Download Firmware
Feb. 29, 2024 Updated

**Comment by damianrovira** [comment]
having the same issue using scrypted using reolink plugin or onvif plugin.
I didn't test any other firmware as i bought and updated directly.  Did you have this working before? what was the firmware?   Wifi version?

**Comment by marcosimeone** [comment]
Yes, previous stable firmware was working. Not sure about version as i don't have a backup, i think it was from April 2023. Hardware version Is the one i reported earlier: DB_566128M5MP_W

**Comment by damianrovira** [comment]
> Yes, previous stable firmware was working. Not sure about version as i don't have a backup, i think it was from April 2023. Hardware version Is the one i reported earlier: DB_566128M5MP_W

I opened a case with Reolink and they requested to test this older firmware, which fixed the issue. Now I hope that they fix this problem in the new version. This is for WiFi version 

https://support-d.reolink.com/attachments/token/ZUrpJdpOSwSKwTqq78ZdXNBJs/?name=DB_566128M5MP_W.2676_23090700.Reolink-Video-Doorbell-WiFi.OV05A10.5MP.WIFI8812.REOLINK.pak

**Comment by marcosimeone** [comment]
I did opened a ticket with Reolink and they asked me to test this version (different from you): [](https://support-d.reolink.com/attachments/token/T8PYqw4d1HuD9qFszdSh79ky8/?name=DB_566128M5MP_W.2602_23081801.Reolink-Video-Doorbell-WiFi.OV05A10.5MP.WIFI8812.REOLINK.pak)

So, i downgraded the firmware and confirmed that with this version, two way audio is working with go2rtc.
Here the relevant differences:

[rtsp] client request:
DESCRIBE rtsp://[camera_ip]:554/h264Preview_01_main RTSP/1.0
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.8.5
CSeq: 2
Authorization: Digest username="user", realm="BC Streaming Media", nonce="e7c0cbe45e1cf217dab16c9da98916de", uri="rtsp://[camera_ip]:554/h264Preview_01_main", response="4253836b8aad1d6379b2628379e91fda"

[rtsp] client response:
RTSP/1.0 200 OK
Content-Type: application/sdp
Content-Length: 776
Cseq: 2
Date: Fri, Mar 08 2024 07:24:18 GMT
Content-Base: rtsp://[camera_ip]/Preview_01_main/

v=0
o=- 1709882513947344 1 IN IP4 [camera_ip]
s=Session streamed by "preview"
t=0 0
a=tool:BC Streaming Media v202210012022.10.01
a=type:broadcast
a=control:*
a=range:npt=now-
a=x-qt-text-nam:Session streamed by "preview"
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:8192
a=rtpmap:96 H264/90000
**a=range:npt=now-**
a=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKAoAPGhAAAE9gAAxnAEAA==,aO48sA==
a=recvonly
a=control:track1
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
b=AS:8192
a=rtpmap:97 MPEG4-GENERIC/16000
a=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408
a=recvonly
a=control:track2
m=audio 0 RTP/AVP 8
a=control:track3
**a=rtpmap:8 PCMA/8000**
a=sendonly

[webrtc] answer
v=0
o=- 8295298220240623374 1709882660 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 77:46:6A:A6:A8:B8:F4:C3:2C:C1:59:11:A0:C4:1A:A8:60:05:11:81:ED:2F:44:B2:21:91:40:A9:5E:E4:38:D7
a=extmap-allow-mixed
a=group:BUNDLE 0 1 2
m=audio 9 UDP/TLS/RTP/SAVPF **8**
c=IN IP4 0.0.0.0
a=setup:active
a=mid:0
a=ice-ufrag:axeDWgWdXhtwiHqp
a=ice-pwd:KDfFMoIoPEUffYCglXUhMqzEiYppyEsZ
a=rtcp-mux
a=rtcp-rsize
**a=rtpmap:8 PCMA/8000**
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=recvonly
m=video 9 UDP/TLS/RTP/SAVPF 102 108 112
c=IN IP4 0.0.0.0
a=setup:active
a=mid:1
a=ice-ufrag:axeDWgWdXhtwiHqp
a=ice-pwd:KDfFMoIoPEUffYCglXUhMqzEiYppyEsZ
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtpmap:108 H264/90000
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=rtpmap:112 H264/90000
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 transport-cc
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:2412822279 cname:go2rtc
a=ssrc:2412822279 msid:go2rtc go2rtc-video
a=ssrc:2412822279 mslabel:go2rtc
a=ssrc:2412822279 label:go2rtc-video
a=msid:go2rtc go2rtc-video
a=sendonly
m=audio 9 UDP/TLS/RTP/SAVPF 111 0 8
c=IN IP4 0.0.0.0
a=setup:active
a=mid:2
a=ice-ufrag:axeDWgWdXhtwiHqp
a=ice-pwd:KDfFMoIoPEUffYCglXUhMqzEiYppyEsZ
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp-fb:111 transport-cc
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=ssrc:678808888 cname:go2rtc
a=ssrc:678808888 msid:go2rtc go2rtc-audio
a=ssrc:678808888 mslabel:go2rtc
a=ssrc:678808888 label:go2rtc-audio
a=msid:go2rtc go2rtc-audio
a=sendonly

I may be wrong, but other than the audio codec that changed from PCMA to PCMU, the newer firmware version doesn't reply with this **a=range:npt=now-** to the onvif backchannel request.

**Comment by tabnul** [comment]
Same issue here with POE version. Asked reolink support for a solution.

**Comment by mutasim** [comment]
I had same issue with POE version and contacted support. They shared with me an interim/older firmware to use until they get the bug fixed:

[Link here if that helps.](https://support-d.reolink.com/attachments/token/yTrwkB8wDJo82ZrJJGo4IIBzY/?name=DB_566128M5MP_P.2676_23090702.Reolink-Video-Doorbell-PoE.OV05A10.5MP.REOLINK.pak)

**Comment by tabnul** [comment]
> I had same issue with POE version and contacted support. They shared with me an interim/older firmware to use until they get the bug fixed:
> 
> [Link here if that helps.](https://support-d.reolink.com/attachments/token/yTrwkB8wDJo82ZrJJGo4IIBzY/?name=DB_566128M5MP_P.2676_23090702.Reolink-Video-Doorbell-PoE.OV05A10.5MP.REOLINK.pak)

Thank you very much! Will try!

**Comment by fabiobrolo** [comment]
I downgraded the firmware and the 2 way is working again, however the use of the ONVIF images of this older version has a lot of lags.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/issues/331
