### ISSUE TITLE
Enforce H264 for output stream?

### ISSUE THREAD

**Issue by Horgul123** [AlexxIT/go2rtc#997]
Hi,

I can show the stream of my cams in Edge, but not in Chrome. I guess it uses the wrong codec.
Tried to find out how to enforce the H264 codec, but nothing worked.

How  can I configue it the right way?

**Comment by AlexxIT** [comment]
1. Check stream info while it active in the WebUI.
2. Use transcoding via ffmpeg source.

**Comment by Horgul123** [comment]
Stream Info:
`{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.0.179/mpeg/720p/media.amp/",
      "remote_addr": "192.168.0.179:554",
      "user_agent": "go2rtc/1.8.5",
      "sdp": "v=0\r\no=- 1707377912557582 1 IN IP4 192.168.0.179\r\ns=RTSP/RTP stream from DoorBird\r\ni=mpeg/720p/media.amp\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2020.11.05\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:RTSP/RTP stream from DoorBird\r\na=x-qt-text-inf:mpeg/720p/media.amp\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:2\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=4D0028;sprop-parameter-sets=Z00AKNoBQBbpUgAAAwDwAAA4QMCAAehIAAiVRe98LwiEag==,aO48gA==\r\na=control:track1\r\n",
      "medias": [
        "video, recvonly, H.264 Main 4.0"
      ],
      "receivers": [
        "96 H264, bytes=105569, senders=1"
      ],
      "recv": 107069
    }
  ],
  "consumers": [
    {
      "type": "MSE/WebSocket active consumer",
      "remote_addr": "192.168.1.13:50652",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
      ],
      "senders": [
        "96 H264, bytes=105569, receivers=1"
      ],
      "send": 98247
    }
  ]
}`

So it's using H264? But why is the stream not visible?

![Screenshot 2024-03-12 182220](https://github.com/AlexxIT/go2rtc/assets/45976162/d370ac57-ce56-403c-890b-b63b8bcc27bd)

**Comment by Horgul123** [comment]
For a stream from a Reolink cam it looks like this:

`{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://192.168.1.30/h264Preview_01_sub/",
      "remote_addr": "192.168.1.30:554",
      "user_agent": "go2rtc/1.8.5",
      "sdp": "v=0\r\no=- 1710032423562982 1 IN IP4 192.168.1.30\r\ns=Session streamed by \"preview\"\r\ni=h264Preview_01_sub\r\nt=0 0\r\na=tool:LIVE555 Streaming Media v2020.08.12\r\na=type:broadcast\r\na=control:*\r\na=range:npt=0-\r\na=x-qt-text-nam:Session streamed by \"preview\"\r\na=x-qt-text-inf:h264Preview_01_sub\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:500\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6wVFKCgPZA=,aO48sA==\r\na=control:track1\r\nm=audio 0 RTP/AVP 97\r\nc=IN IP4 0.0.0.0\r\nb=AS:256\r\na=rtpmap:97 MPEG4-GENERIC/16000\r\na=fmtp:97 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408\r\na=control:track2\r\n",
      "medias": [
        "video, recvonly, H.264 High 5.1",
        "audio, recvonly, MPEG4-GENERIC/16000"
      ],
      "receivers": [
        "96 H264, bytes=401278, senders=1",
        "97 MPEG4-GENERIC/16000, bytes=68513, senders=1"
      ],
      "recv": 476139
    }
  ],
  "consumers": [
    {
      "type": "MSE/WebSocket active consumer",
      "remote_addr": "192.168.1.13:50957",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, H264, H265",
        "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
      ],
      "senders": [
        "96 H264, bytes=401278, receivers=1",
        "97 MPEG4-GENERIC/16000, bytes=68513, receivers=1"
      ],
      "send": 495717
    }
  ]
}`
