### ISSUE TITLE
Can't stream RTSP

### ISSUE THREAD

**Issue by groyee** [AlexxIT/go2rtc#999]
I get an error that my username or password are wrong. This is the exact error:

`undefined error=streams: wrong user/pass
`
But they are correct. I can connect with VLC.

Camera: Tplink Tapo C110

Here are the trace logs:

3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0CSeq: 1Accept: application/sdpRequire: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5
-- | -- | --
3/13/2024, 11:24:18 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:18 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpRequire: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==
3/13/2024, 11:24:18 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:18 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:18 PM | trace | [rtsp] describe (backchannel=true) err: wrong user/pass
3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpUser-Agent: go2rtc/1.8.5CSeq: 1
3/13/2024, 11:24:18 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:18 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpUser-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==
3/13/2024, 11:24:18 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:18 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Require: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5CSeq: 1Accept: application/sdp
3/13/2024, 11:24:18 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:18 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0User-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==Accept: application/sdpRequire: www.onvif.org/ver20/backchannel
3/13/2024, 11:24:18 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:18 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:18 PM | trace | [rtsp] describe (backchannel=true) err: wrong user/pass
3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0CSeq: 1Accept: application/sdpUser-Agent: go2rtc/1.8.5
3/13/2024, 11:24:18 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedWww-Authenticate: Basic realm="TP-Link IP-Camera"Cseq: 1Date: Wed, Mar 13 2024 16:24:18 GMT
3/13/2024, 11:24:18 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpUser-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedWww-Authenticate: Basic realm="TP-Link IP-Camera"Cseq: 2Date: Wed, Mar 13 2024 16:24:19 GMT
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpRequire: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5CSeq: 1
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpRequire: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] describe (backchannel=true) err: wrong user/pass
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0User-Agent: go2rtc/1.8.5CSeq: 1Accept: application/sdp
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpUser-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedDate: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"Cseq: 2
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:OPTIONS rtsp://192.168.1.43/live0 RTSP/1.0CSeq: 18Authorization: Basic SWc2MFRPOGdMSnJQOlRnNGo2Q1NnQjd1Qg==Session: 123463104
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpRequire: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5CSeq: 1
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 200 OKPublic: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, GET_PARAMETERCseq: 18
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0User-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==Accept: application/sdpRequire: www.onvif.org/ver20/backchannel
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] describe (backchannel=true) err: wrong user/pass
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0User-Agent: go2rtc/1.8.5CSeq: 1Accept: application/sdp
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==Accept: application/sdpUser-Agent: go2rtc/1.8.5CSeq: 2
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Require: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5CSeq: 1Accept: application/sdp
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Require: www.onvif.org/ver20/backchannelUser-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==Accept: application/sdp
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] describe (backchannel=true) err: wrong user/pass
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpUser-Agent: go2rtc/1.8.5CSeq: 1
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 1Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | trace | [rtsp] client request:DESCRIBE rtsp://192.168.1.84:554/stream1 RTSP/1.0Accept: application/sdpUser-Agent: go2rtc/1.8.5CSeq: 2Authorization: Basic SWc2MFRPOGdMSnJQOkpwMmY2MnN0MjJheg==
3/13/2024, 11:24:19 PM | trace | [rtsp] client response:RTSP/1.0 401 UnauthorizedCseq: 2Date: Wed, Mar 13 2024 16:24:19 GMTWww-Authenticate: Basic realm="TP-Link IP-Camera"
3/13/2024, 11:24:19 PM | error | undefined error=streams: wrong user/pass caller=github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:166
3/13/2024, 11:24:32 PM | trace | [rtsp] server request:OPTIONS rtsp://homeassistant.local:8554/camera.living_room_cam RTSP/1.0User-Agent: Lavf58.76.100Session: 72701007Cseq: 17Require: implicit-play
3/13/2024, 11:24:32 PM | trace | [rtsp] server response:RTSP/1.0 200 OKCseq: 17Session: 72701007
3/13/2024, 11:24:32 PM | trace | [rtsp] server request:OPTIONS rtsp://homeassistant.local:8554/camera.living_room_cam RTSP/1.0Cseq: 17Require: implicit-playUser-Agent: Lavf58.76.100Session: 88620260
3/13/2024, 11:24:32 PM | trace | [rtsp] server response:RTSP/1.0 200 OKCseq: 17Session: 88620260
3/13/2024, 11:24:32 PM | trace | [rtsp] server request:OPTIONS rtsp://homeassistant.local:8554/camera.living_room_cam RTSP/1.0Cseq: 17Require: implicit-playUser-Agent: Lavf58.76.100Session: 57580535
3/13/2024, 11:24:32 PM | trace | [rtsp] server response:RTSP/1.0 200 OKCseq: 17Session: 57580535
3/13/2024, 11:24:44 PM | trace | [rtsp] client request:OPTIONS rtsp://192.168.1.43/live0 RTSP/1.0CSeq: 19Authorization: Basic SWc2MFRPOGdMSnJQOlRnNGo2Q1NnQjd1Qg==Session: 123463104
3/13/2024, 11:24:44 PM | trace | [rtsp] client response:RTSP/1.0 200 OKCseq: 19Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, GET_PARAMETER

**Comment by AlexxIT** [comment]
There can be no mistake here. Your login/password is incorrect. If you have special characters in your password, you need to escape them
